### ISSUE TITLE
Move OpenShift cost summary calculation out of cloud summary updater

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1004]
## Objective
The OpenShift cost summary needs to be run regardless of whether OpenShift is running on a cloud provider. We should move this calculation back to the ocp_report_summary_updater as a separate update method that can be called again after every other OpenShift related summary method. Needs to be called after derived cost calculations. 

## Investigation
See if we are missing derived cost with how this is being run today. If so, this needs to be called after the charge (derived cost) calculation tasks

## Additional Information
- See https://github.com/project-koku/koku/blob/master/koku/masu/processor/ocp/ocp_cloud_summary_updater.py#L155-L161
-

## Acceptance Criteria

- [ ] Cost Summary is always populated for any OpenShift provider

**Comment by maskarb** [comment]
reopen for QA

**Comment by dchorvat1** [comment]
verified
