### ISSUE TITLE
Update summary SQL handling of tags

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1005]
## Objective
Right now we do some complicated SQL to roll up tags from hourly to daily. This tag SQL in particular has been bogging down some of our larger AWS accounts. In the end we really just need an extra `GROUP BY` for tags. 

## Assumptions and Additional Information
- See https://github.com/project-koku/koku/blob/master/koku/masu/database/sql/reporting_awscostentrylineitem_daily.sql#L2-L66
- Add a tag GROUP BY here https://github.com/project-koku/koku/blob/master/koku/masu/database/sql/reporting_awscostentrylineitem_daily.sql#L106

## Acceptance Criteria

- [ ] API results are exactly the same with and without this change
- [ ] Current tests pass

**Comment by adberglund** [comment]
@lcouzens There shouldn't be any new tests for this, just verifying that everything still passes. I know Doug checked that while doing the work. Effectively we made some SQL more efficient with the same exact end result.

**Comment by lcouzens** [comment]
Verified
