### ISSUE TITLE
Remove a Provider (AWS Account) for a Customer

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#101]
## User Story
As a customer owner, I want to be able to remove an AWS account associated with my customer so that service will no longer try to gather cost visualization data.

## Impacts
API, UI, Docs

## Role
Customer Owner and/or User responsible for provider creation

## Assumptions
- An AWS account can only be associated with a single customer.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | DELETE | 
 | **Path** | /api/v1/providers/(provider uuid)/ | 
 | **Body** |  | 
 | **Response** |  | 

## UI Details
A view exist to remove an existing AWS account.

## Acceptance Criteria

- [x] Verify that any customer owner can remove an existing AWS accounts for a customer.
- [x] Verify that the user (doesn't have to be owner) can remove the AWS account that it added.
- [x] Verify that a non-customer owner cannot remove an existing AWS account that they did not create.
- [x] Verify that upon customer delete that all associated provider data has been removed

**Comment by nachandr** [comment]
I have verified all the acceptance criteria. I also ran into this issue while testing this user story.

https://github.com/project-koku/koku/issues/206

**Comment by dccurtis** [comment]
Thanks @nachandr.  I have a PR out to address #206 now.  To me it would be ok to close this story since it meets acceptance criteria and the other issue has been opened.  But if you prefer to keep it open until #206 is merged, I'm ok with that too.  Your call.

**Comment by nachandr** [comment]
@dcurtis, I am closing this issue.
