### ISSUE TITLE
Migrate AWS and OCP providers to using non-deprecated model fields

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#1017]
## User Story
When the Azure provider was implemented, there were new JSONFields created in our models to store authentication and data source information.

The AWS and OCP providers are still using the AWS-specific model fields and should be migrated to using the new JSONFields and the old fields should be removed from the DB.

## Impacts
API, UI

## Assumptions
-
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/PATCH/DELETE |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## UI Details
UI calls to the API will need to be updated to use the updated parameters for AWS and OCP provider calls.

## Acceptance Criteria

- [x] AWS Provider uses JSONField for credentials and data_source
- [x] OCP Provider uses JSONField for credentials and data_source
- [ ] Deprecated fields are removed from the Provider models.
- [ ] References to deprecated fields are removed from the code

**Comment by adberglund** [comment]
We are waiting for additional information around the sources UI. We should see a demo and get some of that info next week (8/26) to decide how we are proceeding with sources or if we should greenlight this immediately.

**Comment by adberglund** [comment]
Let's keep the priority on this lower until we are fully integrated with sources and we need our cost specific config wizard stuff needs our fields to be consistent.

**Comment by blentz** [comment]
Moved: https://issues.redhat.com/browse/COST-116
