### ISSUE TITLE
copy normalized data to our S3 bucket for archiving

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1024]
## User Story
As a Koku user, I want to get Koku's normalized version of the raw values that were used in generating my reported data.

One of the prerequisites to achieving that goal is to save the normalized version to our S3 bucket for long-time storage. Then when the user requests an export, we can reference those archived copies in our S3 bucket.

## Assumptions and Questions
- Files should be stored hierarchically with the account ID, provider type, year, month, and (optionally) day in the S3 bucket using a pattern like:
  - /data_archive/acct_12345/aws/2019/08/01/tablename.csv
- If the data is not specifically relevant to individual days, it may be stored at the month directory level.
- Question: since this job runs every minute, should the hierarchy include hour and minute?
  - Probably not. We anticipate overwriting files that represent updates.
- If a file with the same name already exists at the path, we will overwrite it.
- All new normalized rows that are written by `ReportProcessor` (or classes that extend `ReportProcessorBase`) are dumped as CSV and saved to S3.
  - consider adapting `_save_to_db` or `bulk_insert_rows`
- See also: https://redhatmbu.aha.io/epics/COST-E-97

## Acceptance Criteria

- [ ] When the periodic task `masu.processor.tasks.get_report_files` runs, all new normalized database table rows are saved in CSV files to S3.
- [ ] Files for different accounts, provider types, and dates are stored in different directories following the described pattern.
- [ ] The S3 bucket is configurable with values set in appropriate places for qa, ci, stage, and prod.
- [ ] The root of the path is configurable with a default value of "/data_archive/".

**Comment by lcouzens** [comment]
Verified.
Commit: 96a12fc0e55ee08d444f5919b549ec575683a988
