### ISSUE TITLE
set an S3 lifecycle policy to age out old files

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1025]
## User Story
As a Koku sysop, I want archived customer data files in S3 to automatically move to infrequent access and glacier over time so I don't have to pay to keep them in standard access forever.

## Assumptions
- Maybe borrow ideas from cloudigrade?
  - See also: https://gitlab.com/cloudigrade/cloudigrade/blob/master/cloudigrade/util/management/commands/syncbucketlifecycle.py
- See also: https://redhatmbu.aha.io/epics/COST-E-97
- See also: #1023 #1024
  - configuration variables should be shared with those issues
- Default numbers of days for transition may change as we further discuss this issue.

## Acceptance Criteria

- [ ] Lifecycle policy is automatically applied only to our S3 bucket's data archive directory.
- [ ] S3 bucket name is configurable.
- [ ] The root of the path is configurable with a default value of "/data_archive/".
- [ ] Number of days to transition to "infrequent access" is configurable with a default value of 180 days.
- [ ] Number of days to transition to "glacier" is configurable with a default value of 365 days.

**Comment by lcouzens** [comment]
Verified
commit: b9f284fed61bd68465dccf35f3b1c02467361598
