### ISSUE TITLE
Azure tags API

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1031]
## Objective
An endpoint is available to deliver the current list of valid Azure tags. 

## Assumptions
- This should be a near duplicate of the AWS tags endpoint, but using the Azure tags summary table

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/tags/azure/ |

## Acceptance Criteria

- [ ] Azure tags are returned as key/values
- [ ] Just the list of tags can be returned using the `key_only` boolean param

**Comment by msager27** [comment]
Verified
Commit: a8a00c585888596881fc7f4e9d18c4c8042ec764
Automation: test_api_azure_tagging_limit_order_by
