### ISSUE TITLE
Cost Model History

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1034]
## User Story
As a user I want my cost calculations to reflect the state of my cost model (price list and markup) at the time of the billing period being calculated. 

## Assumptions
- We will make a cost model history table that mirrors the cost model model/table
- We can use a Postgres trigger function to populate the history table. We can add the trigger using a manually generated Django migration. 
- See https://www.postgresql.org/docs/10/plpgsql-trigger.html for info on triggers, specifically the example for an audit

## Acceptance Criteria

- [ ] For every update to the cost model table, we store the `OLD` record in the history table before updating the cost model table

**Comment by adberglund** [comment]
@lcouzens I would say there isn't anything _yet_ to test on this. It's a purely backend feature until we tackle cost model history and finalization with a corresponding UI next milestone.

**Comment by lcouzens** [comment]
Closing in wait for UI work
