### ISSUE TITLE
Investigate GraphQL

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1050]
## Objective
See if something like GraphQL would make sense for reducing the number of API calls we make

https://www.freecodecamp.org/news/how-to-get-instant-graphql-apis-on-your-existing-django-application-c8fcfdb945aa/

**Comment by blentz** [comment]
I spent some time reviewing the above-linked article as well as doing a survey of OSS projects that enable GraphQL support in Python-based applications. Here's my findings.


## Hasura

The above-linked blog talks about Hasura, which is a standalone GraphQL engine. ( https://github.com/hasura/graphql-engine/tree/master/server/src-lib/Hasura ) This is a Haskell application that's aimed at being an "appliance" of sorts for any application that wants to provide a GraphQL API endpoint.

### Pros:
- Isolated / Standalone (there is no connection or embedding to the application codebase)
- Seems like a straightforward "appliance" setup (low initial complexity)
- Is already containerized (there's a docker-compose file, among other things.)

### Cons:
- It's Haskell, not Python (limiting our ability to change it to suit our needs)
- It's disconnected from our code, so it needs to introspect our DB schema to generate the GraphQL schema. The docs do note that there are cases where the schema generation process isn't perfect and may need occasional manual intervention. So, this could be reviving some of the same problems we were having when Koku & Masu were separate.

### Recommendation: 

Not recommended. I think the Hasura architecture doesn't align with ours well enough. In solving one problem, I think it will bring with it a non-zero number of new problems.

## Graphene (graphene-django)

Graphene-django is a Django integration for Graphene. Graphene is a library for building GraphQL APIs in Python.

Project links:
* graphene-django: https://github.com/graphql-python/graphene-django
* graphene-python: https://graphene-python

Example links:
* https://stackabuse.com/building-a-graphql-api-with-django/
* https://gearheart.io/blog/how-to-use-graphql-with-django-with-example/

### Pros:
- It's Python and it's Django (matches our application, no extra technology required)
- Initial implementation looks medium-low effort. We mainly mirror our DB schema and define a set of query objects that are the API.
- Much tighter coupling to our application means the API will be purpose-built to suit our needs.

### Cons:
- Requires development time to implement.
- It will be our code, so we'll own the maintenance.

### Recommendation:

Recommended. I think this is the best solution for implementing a GraphQL endpoint. Initial development shouldn't require more than one sprint (probably only a couple days).

I like the "plug and play" aspect of already having a native Django library to consume. The class structures appear to somewhat mirror the DB schema classes, which should make it relatively easy to do an initial implementation.

## Other Options

I found a few other options for GraphQL. They do not seem like they offer any significant differences from the above two options.

- Apollo ( https://www.apollographql.com/docs/apollo-server/ ) - This looks like a similar appliance-type application as Hasua.

- Ariadne ( https://github.com/mirumee/ariadne ) - Similar to Graphene, but newer (smaller userbase) and its Django support appears to be an early implementation. 

- Strawberry ( https://github.com/strawberry-graphql/strawberry ) - Similar to Graphene and Ariadne, but even newer and no native Django support.
