### ISSUE TITLE
Set up a customer schema for AWS Cost Usage Report

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#107]
## User Story
As developer, I want to create a unique customer schema with appropriate tables when onboarding/creating a customer so that we will be prepared to ingest and store AWS Cost Usage Report data.

## Assumptions
We are using PostgresSQL that supports [PostgresSQL schemas](https://www.postgresql.org/docs/9.1/static/ddl-schemas.html), such that we can segregate cost entry data by customer.

### Data Model
**Cost Entry**
- _id_: UUIDField; Primary key; read-only
- _interval_start_: DateTimeField; read-only
- _interval_end_: DateTimeField; read-only
- _bill_: ForeignKey (Cost Entry Bill)
- _line_item_: ForeignKey (Cost Entry Line Item)
- _product_: ForeignKey (Cost Entry Product)
- _reservation_: ForeignKey (Cost Entry Reservation)
- _tag_: ForeignKey (Cost Entry Tag)

**Cost Entry Bill**
- _id_: UUIDField; Primary key; read-only
- _billing_resource_: CharField; max_length=50; default=aws; required
- _billing_type_: CharField; max_length=50; required  (i.e. “Anniversary”)
- _payer_id_: CharField; max_length=50; required
- _billing_period_start_: DateTimeField; required
- _billing_period_end_: DateTimeField; required

**Cost Entry Line Item**
- _id_: UUIDField; Primary key; read-only
- _line_item_id_: CharField; max_length=63; required
- _line_item_type_: CharField; max_length=50; required  (i.e. “Usage”)
- _usage_id_: CharField; max_length=50; required
- _usage_start_: DateTimeField; required
- _usage_end_: DateTimeField; required
- _product_code_: CharField; max_length=50; required  (i.e. “AWSCloudTrail”)
- _usage_type_: CharField; max_length=50; required  (i.e. “EU-FreeEventsRecorded”)
- _operation_: CharField; max_length=50
- _availability_zone_: CharField; max_length=50
- _resource_id_: CharField; max_length=50
- _usage_amount_: PositiveIntegerField
- _normalization_factor_: PositiveIntegerField
- _normalized_usage_amount_: PositivieIntegerField
- _currency_code_: CharField; max_length=10
- _unblended_rate_: FloatField
- _unblended_cost_: FloatField
- _blended_rate_: FloatField
- _blended_cost_: FloatField
- _tax_type_: TextField

**Cost Entry Product**
- _id_: UUIDField; Primary key; read-only
- _product_name_: CharField; max_length=50
- _location_: CharField; max_length=50 (i.e. “EU (Ireland)”)
- _location_type_: CharField; max_length=50 (i.e. “AWS Region”)
- _product_family_: CharField; max_length=150 (i.e. “Management Tools - AWS CloudTrail Free Events Recorded”)
- _service_code_: CharField; max_length=50 (i.e. “AWSCloudTrail”)

**Cost Entry Reservation**
- _id_: UUIDField; Primary key; read-only
- _number_of_reservations_: PositiveIntegerField
- _reservation_crn_: TextField
- _total_reserved_normalized_units_: PositiveIntegerField
- _total_reserved_units_: PositiveIntegerField
- _units_per_reservation_: FloatField

**Cost Entry Tag**
- _id_: UUIDField; Primary key; read-only
- _name_: CharField; max_length=256; required
- _cost_entry_: ForeignKey (Cost Entry); required

Potential use of [Django Tenant Schemas](https://github.com/bernardopires/django-tenant-schemas); may only need the `TenantMixin` portions of code since we won't be operating with url based tenant sites.

## Acceptance Criteria

- [ ] Verify that a `public` schema tenant is created or validated when first launching the app
- [ ] Verify that customer schemas are identified by schema_name field on the customer object
- [ ] Verify that creating a new customer creates a new tenant
- [ ] Verify that the creation of a new tenant creates a new schema for the customer
- [ ] Verify that the new schema has all required cost entry / reporting tables that are distinct to the customer

**Comment by adberglund** [comment]
Demo: https://asciinema.org/a/LHXH1wiljnDfHYsMehCdLF96z
