### ISSUE TITLE
Use safe templating for templated raw SQL

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1079]
## Objective
We don't want SQL Injection, and despite our current variables being controlled by us, it would still be safer to rely on paramaterization for the strings getting inserted into our SQL. 

Let's look at using https://github.com/hashedin/jinjasql for our SQL which will swap out or variables and return a list of parameters for the SQL. 

## Additional Information

* We need to modify our variables in our SQL to be Jinja variables (effectively switching from single brackets `{variable}` to double `{{variable}}`
  * SQL files are located here: https://github.com/project-koku/koku/tree/master/koku/masu/database/sql

* We need to switch our db_accessors that run this SQL from using string `.format()` calls to running JinjaSQL and getting the modified SQL string and bind_params.

* Update https://github.com/project-koku/koku/blob/master/koku/masu/database/report_db_accessor_base.py#L415 commit_and_vacuum to pass the sql and bind params to the `cursor.execute()` call

## Acceptance Criteria

- [ ] SQL produces identical results

**Comment by nbon12** [comment]
@adberglund where is the unsafe SQL?

**Comment by adberglund** [comment]
@nbon12 just a reminded to put a comment on the issue to help with QA. 

QA: There should be no functional difference here. This was just tackling technical debt and the goal is for all processed and summarized data to be exactly the same as it was before.

**Comment by lcouzens** [comment]
Verified.
Commit: 96a12fc0e55ee08d444f5919b549ec575683a988
