### ISSUE TITLE
Track Customer Cost Usage Report Consumption

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#108]
## User Story
As user, I want to know how up-to-date my cost data is so that I can understand how current and reliable it is.

## Assumptions
We will initially be polling for updates, but may later move to SNS for Cost Usage Report availability.

## Implementation details

For each customer we need to capture the following data:

- Current _cost usage report_ being read
- Read Cursor (files are appended to; we don't need to start at the beginning)
- Last processing completed time
- Last processing started time

## Acceptance Criteria

- [ ] Verify that we can capture the processing complete time to show the "freshness" of the data.
- [ ] Verify the current cost usage report that was read

**Comment by dccurtis** [comment]
This is now complete now all stats are updated in the Masu download/processing pipeline.
