### ISSUE TITLE
gzip files before uploading to s3 archive

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1083]
## User Story
As a koku sysop, I want to minimize the long-term storage costs for the many large CSVs we will be archiving in S3.

As a koku developer, I want to minimize time spent uploading and downloading files to S3.

Since the CSVs we are uploading are all text with highly repetitive content, gzipping them before upload should significantly reduce their sizes, and that should reduce our S3 storage costs and time spent uploading and downloading in S3.

## Assumptions

- This is a followup to https://github.com/project-koku/koku/issues/1024 and https://github.com/project-koku/koku/issues/1067

## Acceptance Criteria

- [ ] Instead of plaintext CSV files, the data archival process uploads gzipped files to S3.

**Comment by infinitewarp** [comment]
A rough test using the default command-line gzip reduced some of my S3 archived test files for AWS and OCP spanning two months from 51M to 14M.

**Comment by infinitewarp** [comment]
@adberglund @chargio  What are your thoughts on this? Is this too much of a micro-optimization? Should we even be concerned about S3 storage costs at this scale?

**Comment by lcouzens** [comment]
Verified.
Commit: 96a12fc0e55ee08d444f5919b549ec575683a988
