### ISSUE TITLE
Api returns 400 when using limit/offset query parameters in cost model api

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1091]
**Describe the bug**
Using `limit` or `offset` query parameters in `/api/cost-management/v1/costmodels/` results in 400 response and 

**To Reproduce**
1. Go to `https://ci.cloud.redhat.com/api/cost-management/v1/costmodels/?offset=0&limit=10`
2. See error

**Expected behavior**
200 response with a list of cost models

**Response**
```
{
    "errors": [
        {
            "detail": "Cannot resolve keyword 'limit' into field. Choices are: costmodelmap, created_timestamp, description, name, rates, source_type, updated_timestamp, uuid",
            "source": "detail",
            "status": 400
        }
    ]
}
```

**Additional context**
commit afbc1ac47dc809a704e082d3415b8e4eb8811500
tested on CI

**Comment by boaz0** [comment]
:rofl: I also just filed a bug for that thing. :smile: 
I will close mine.
