### ISSUE TITLE
Download GCP exported billing data

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1096]
## User Story
As the koku backend, I need to access locally the GCP customer's exported billing data so I can import its contents, but to get it locally, I must download it first.

## Assumptions and Questions
- Depends on https://github.com/project-koku/koku/issues/1095 (Support GCP Provider/Source creation)
- Refer to the recent implementation for Azure to find areas of the system that may need changes.
- See also: https://cloud.google.com/billing/docs/how-to/export-data-file
- Does the manifest need to be created here? Or in the later "load into the DB" step?
  - Probably here is where we need to create the manifest.
- The logic here probably all lives in the `masu` module in `koku`.

## Acceptance Criteria

- [ ] Backend process downloads GCP customer's exported billing data to the local filesystem.
  - Same process that is used by AWS, Azure, etc. to initiate downloading.
- [ ] Manifest information for the GCP billing data file is stored like it is for AWS, Azure, etc.
  - See also:
    - `reporting_common_costusagereportmanifest`
    - `reporting_common_costusagereportstatus`

**Comment by infinitewarp** [comment]
This is/was blocked on the e2e configuration being updated to include the GCP credentials json.

@werwty has just merged a fix. So, I'm un-blocking this issue now.

**Comment by lcouzens** [comment]
Verified as best we can. CI logs show some GCP ingestion happening but I really want to verify this when we have proper GCP report endpoints. That said I will close this and when we get full GCP report endpoints then I will make sure we have proper test coverage.
