### ISSUE TITLE
Load downloaded GCP billing data file into DB

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1097]
## User Story
As a GCP user, I want koku to retain my recent GCP billing data so I can run reports against it.

This issue includes the loading of the GCP exported billing data file contents into the database but not yet the daily/monthly summarization of that data.

## Assumptions and Questions
- Depends on https://github.com/project-koku/koku/issues/1096 (Download GCP exported billing data)
- Does the manifest need to be created here? Or in the earlier "download" step?
  - Probably the manifest should be created in the *previous* step at time of download.
- This probably lives in the `masu` module within `koku`.
- The current process uses some combination of reading the file, temp tables, and inserts. We may follow that pattern or if we feel there is a better or more optimal route, we may diverge from the existing pattern.

## Acceptance Criteria

- [ ] New table (or multiple tables if applicable) exists (created using django migration) for storing the billing data file's lines.
  - For example, some similar existing tables:
    - `reporting_awscostentrylineitem`
    - `reporting_ocpstoragelineitem`
    - `reporting_ocpusagelineitem`
- [ ] New table is populated after downloading the GCP billing data file using the same process as AWS, Azure, etc.
- [ ] Manifest information for the GCP billing data file is stored like it is for AWS, Azure, etc.
  - See also:
    - `reporting_common_costusagereportmanifest`
    - `reporting_common_costusagereportstatus`
- [ ] Any new tables defined here are also included in the customer-driven data export process. (see `DataExportRequest` and the operations that follow it)

**Comment by infinitewarp** [comment]
This is/was blocked on the e2e configuration being updated to include the GCP credentials json.

@werwty has just merged a fix. So, I'm un-blocking this issue now.

**Comment by lcouzens** [comment]
Verified as best we can. CI logs show some GCP ingestion happening but I really want to verify this when we have proper GCP report endpoints. That said I will close this and when we get full GCP report endpoints then I will make sure we have proper test coverage.
