### ISSUE TITLE
Change this project's name?

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#11]
Just a thought: Since we're big fans of Ansible here and this project's name _looks_ an awful lot like it's related to [SaltStack](https://github.com/saltstack/), maybe you should consider a different name that is a bit more unique.

**Comment by chargio** [comment]
We voted, but we could always vote again. We are still quite early in the process.

**Comment by blentz** [comment]
It's unclear what the final public view of this project is going to be, or whether the product folks will rebrand it regardless of what project name we pick. 

Given that this is likely a microservice, this project's outputs may not even be distinguishable as a separate entity when looking at a dashboard.

So, I'm not really married to the name but I'm also uncertain how much it'll matter what we call it.

**Comment by chambridge** [comment]
Organization name changed to **project-koku**.
Project name changed to **koku**.
