### ISSUE TITLE
Support "GCP-local" provider/source

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1104]
## User Story
As a koku developer, I want to simulate interacting with GCP but by only using the local filesystem.

Extend the work done by https://github.com/project-koku/koku/issues/1095 to implement a `GCP-local`-type provider in the style of `AWS-local` and `AZURE-local`.

## Assumptions
- Whoever picks this up, please share with the kokugrade team your findings on
  - how `-local` things differ from their main counterparts.
  - how `DEVELOPMENT=True` affects things related to `-local` providers.

## Acceptance Criteria

- [ ] User can register their GCP-local account with koku via the provider API with provider type `GCP-local`.
- [ ] `GCP-local`-type provider only references the local filesystem with no real GCP account information.
- [ ] When the `DEVELOPMENT=True` environment variable is set, koku should follow the behavior established by `AWS-local` and default to some special override things for `GCP-local`. TBD what those specific things are.

**Comment by lcouzens** [comment]
Verified!
