### ISSUE TITLE
Trigger workers to process via SNS

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#111]
## User Story

As a developer, I want workers to be triggered to process cost usage reports as quickly as possible by utilizing Amazon's SNS notifications on S3 bucket changes so that data is available to customers in a timely fashion and as a better strategy than polling alone.

## Assumptions
The IAM policy that the customer enables on their AWS account provides the capability to setup SNS notifications of changes to the S3 bucket.

## Implementation details
We will have listeners for SNS events on customer S3 buckets. Similar to the polling procedure this will cause a worker to process the CUR and note its completion

## Acceptance Criteria

- [ ] Verify that an SNS event for a new customer usage report triggers a worker to process the new data.

**Comment by adberglund** [comment]
Link for boto3 API to add event listener to S3 bucket. http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.put_bucket_notification_configuration

**Comment by chambridge** [comment]
@chargio Issue #110 will use a polling strategy to handle workers that die or dropped messages.

**Comment by chambridge** [comment]
Closing a duplicate of https://github.com/project-koku/masu/issues/7

Since this work will be done in masu
