### ISSUE TITLE
Azure tags API to return array

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1140]
**Describe the bug**
Encountered a slight issue with the Azure tags API. The Koku UI is expecting an array of tag values, similar to the tag API for AWS.

We could write special code to handle this in the UI, but would be good to normalize.

**To Reproduce**
1. Go to `v1/tags/azure/?filter[subscription_guid]=2639de71-ca37-4a17-a104-17665a50e7fc`
2. See value returned

**Expected behavior**
Expecting an array to be returned regardless if there is only one value available, similar to the AWS API.

**Screenshots**
Azure:
![Screen Shot 2019-09-19 at 3 36 56 PM](https://user-images.githubusercontent.com/17481322/65275295-5a653100-daf3-11e9-9ca6-65f7e671d3a1.png)

AWS:
![Screen Shot 2019-09-19 at 3 37 32 PM](https://user-images.githubusercontent.com/17481322/65275323-6bae3d80-daf3-11e9-8887-9e8c0c2d7d60.png)

**Comment by dchorvat1** [comment]
verified
