### ISSUE TITLE
Cost model markup can't be negative

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku#1148]
**Describe the bug**
Trying to set a negative markup fails. This is supposed to be a valid value in case the provider gives a discount.

**To Reproduce**
1. Run the following:
```
curl -XPOST localhost:8000/api/v1/costmodels -d'{
    "name": "bla",
    "description": "",
    "source_type": "OCP",
    "provider_uuids": [],
    "rates": [],
    "markup": {
        "value": "-20",
        "unit": "percent"
    }
}'
```

**Expected behavior**
A success response

related to https://github.com/project-koku/koku-ui/pull/1009

//cc @chargio @maskarb

**Comment by dchorvat1** [comment]
verified, commit 79f377f80fcf80f6f8c4802d3644cb58bbd11be7
