### ISSUE TITLE
pgAdmin in OpenShift development environment

### ISSUE THREAD

**Issue by nbon12** [project-koku/koku#1158]
## User Story
Often times and for many reasons, users want to interact with a database directly.
Using pgAdmin, developers can inspect the contents of the database with an easy to use UI.
This will allow for faster development.
It may also aid in testing, debugging, and system administration.

This is a follow up of https://github.com/project-koku/koku/pull/1156

"adding OpenShift templates, and testing them is going to require some knowledge and experience building with OpenShift. In this case, pgAdmin is a dev tool, not critical work. " - aberglun

## Impacts
OpenShift templates

## Assumptions
- Adding pgAdmin to OpenShift templates will only be available in the development environment.

**Comment by adberglund** [comment]
Let's get a local template but also consider how this plays into e2e, where we will likely not want non app deployment templates. Perhaps once we switch entirely to using e2e templates for local dev, we could have a dev tools repo or something like that???
