### ISSUE TITLE
Markup cost for OCP on Cloud not always formatting properly in reporting APIs

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1161]
**Describe the bug**
For the OpenShift `group_by[project]` views we are calling markup_cost `project_markup_cost` and the `PACK_DEFINITIONS` in the provider_map does not know what to do with that. 

Also cases when no markup cost is present we have null values in the DB instead of `0` which causes markup_cost and cost calculations to return `null`  and not be formatted properly. 

**To Reproduce**
1. Look at OCP on AWS API calls in CI 

**Expected behavior**
1) What we report to the API should always be `markup_cost` regardless of whether it came form project_markup_cost. 
2) We should report `0` instead of null when no cost is there.

**Comment by adberglund** [comment]
We were seeing `null` returned for the various cost components in the reporting APIs. 

e.g. `"markup_cost": null` instead of `"markup_cost": {"value": "1.0", "unit": "USD"}` . All cost fields in the API should now always come back as JSON with value and unit.

**Comment by dchorvat1** [comment]
verified
