### ISSUE TITLE
Address OpenShift database table sprawl

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1169]
## Objective
We should, as much as possible, conform OpenShift's database design to be in-line with other data sources. 

* Move storage and cpu to a single usage table with some form of “type” column to distinguish the data source
* Remove cost summary table and move its content backward to the ocp_daily_summary table 
* Update infra costs in ocp_daily_summary table after OCP on AWS (or OCP on any cloud) table is summarized

## Assumptions
- This would alleviate some of the issues of where to put certain information for OpenShift
- Having everything in one summary table means the APIs don't have to use different tables

## Acceptance Criteria

- [x] All cost columns are populated in the daily_summary table, infrastructure, derived, and markup
- [x] APIs use the new common summary table

**Comment by adberglund** [comment]
Merged in commit 7d8ad0765f5828e462e56e2c2553f53ae0cefc91. 

This switches handling of OpenShift data to a single table instead of 3 different tables. Ideally we should see no change in the APIs and calculated numbers after this test, but there is no new functionality to test.

**Comment by lcouzens** [comment]
Verified.
Commit: 96a12fc0e55ee08d444f5919b549ec575683a988
