### ISSUE TITLE
Convert provider table to use uuid as primary key

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1170]
## Objective
Currently throughout our code base we use either provider_id or the uuid column for references to the `api_providers` table. We should consolidate to using the uuid as a primary key and only column used to reference the table.

## Assumptions
- This will require a custom and multi-step database migration to update every table currently using the provider id column to use the uuid, then remove the id column.
- References to provider uuid on all tables can now become foreign key relationships. When masu was SQLAlchemy based, this was not possible between schemas, but with everything in Django now, we should be able to cross schema boundaries with foreign keys. 

## Acceptance Criteria

- [ ] All tables referencing api_providers do so by the uuid column and with a foreign key relationship.

**Comment by adberglund** [comment]
There should be no functional change here. Just making our references to the provider table consistent across the app.

**Comment by lcouzens** [comment]
Verifed
