### ISSUE TITLE
Resolve request caching issues

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1174]
**Update** 
This was being caused by our default caching. 

- Potential header/key issue where we were geting back data in CI that did not appear to be from out user
- Cache invalidation on data delete/update for reports.
- Cost models calculations invalidate the reports cache as well

**Describe the bug**
After removing the provider (it was the only one in the environment), the api returned the same cost report populated with data. (perhaps a caching issue) This happened with AWS provider only. 

**To Reproduce**
1. Add an aws provider and ingest some data
2. Get a cost report
3. Remove the provider
4. Get a second cost report, see that it's the same as the first one and the data is still there

**Expected behavior**
The provider's data shouldn't show up after removing the provider.

**API output after removing the provider**
**`/reports/aws/costs/?group_by[account]=*`**
```
"meta": {
        "count": 10,
        "group_by": {
            "account": [
                "*"
            ]
        },
        "filter": {
            "time_scope_value": "-10",
            "time_scope_units": "day",
            "resolution": "daily"
        },
        "total": {
            "cost": {
                "value": 242.55,
                "units": "USD"
            },
            "infrastructure_cost": {
                "value": 242.55,
                "units": "USD"
            },
            "derived_cost": {
                "value": 0.0,
                "units": "USD"
            },
            "markup_cost": {
                "value": 0.0,
                "units": "USD"
            }
        }
    },
...
```
**`/providers/`**
```
{
    "meta": {
        "count": 0
    },
    "links": {
        "first": "/api/cost-management/v1/providers/?limit=10&offset=0",
        "next": null,
        "previous": null,
        "last": "/api/cost-management/v1/providers/?limit=10&offset=0"
    },
    "data": []
}
```

**Additional context**
Tested on CI

**Comment by dchorvat1** [comment]
I found another caching issue, I logged out from one account and logged into another, the UI was still showing data from the first one, this is probably related.

**Comment by adberglund** [comment]
@dchorvat1 I've been seeing caching issues as well. For now I'm going to flag caching as optional, and disable it in CI/QA environments until this can be sorted out.

**Comment by lcouzens** [comment]
@adberglund Whats the plan for this going forward? Do we need to have a discussion around caching or is it just going to be disabled from now one and this can just be closed?

**Comment by chambridge** [comment]
Is this still a problem?

**Comment by adberglund** [comment]
@lcouzens @chambridge Yes it is still a problem. It has just been disabled for a while. So we need some healthy cache invalidation logic for the reports APIs, but I also seem to recall that it was still showing incorrect data (like from other tenants) even after that was supposed to be fixed.

**Comment by adberglund** [comment]
https://django-tenant-schemas.readthedocs.io/en/latest/install.html#caching

**Comment by adberglund** [comment]
Opened as https://issues.redhat.com/browse/COST-87
