### ISSUE TITLE
Azure costs reporting 10x higher than actual

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1180]
**Describe the bug**
We are reporting 10x the cost for Azure than our actual bill right now. The problem appears to be in report processing. I believe we are duplicating data as the `_daily` table we load data into should match what Azure claims is our current cost.

```
select sum(pretax_cost) from reporting_azurecostentrylineitem_daily where usage_date_time >= '2019-09-01';
      sum
---------------
 155.882472574
```

Looking a little further, I believe we want to take either the AWS approach or the OCP approach for Azure processing.

**AWS Approach)** Wipe the table for the billing period prior to processing a file. 
**OCP approach)** Write the entire file to a temporary table, and then merge that temp table into the main table with an `ON CONFLICT... DO UPDATE` clause.

**Expected behavior**
We need a proper check to avoid duplicating data when running the Azure processor.

**Comment by lcouzens** [comment]
Verified
Commit: "1dc0c990bdde6af21a1c4930c21d7216da6dde1b"
Automation: Raw calc tests coming soon
