### ISSUE TITLE
Provider update API operation

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1181]
## User Story
As a user of platform sources I would like source edits to echo to cost management so that my source is up to date in this application. 

## Impacts
API

## Assumptions
- The Provider API needs an update operation using PUT

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | PUT
 | **Path** | /api/v1/providers/ |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ] A PUT call to our provider API causes the provider to update successfully. 
- [ ] Editing a source in platform sources causes an PUT to our provider and our provider is updated

**Comment by dccurtis** [comment]
Dup of #864.  Can close one of these issues
