### ISSUE TITLE
Sentry integration

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1189]
## User Story
As a Koku sysop, I want to be alerted when unhandled exceptions occur so that I can be aware of problems and react accordingly.

The [cloudigrade](https://gitlab.com/cloudigrade/cloudigrade/) project uses [Sentry.io](https://sentry.io/) to solve this problem, and koku may be able to lean on that for inspiration. In cloudigrade's case, we installed, configured, and initialized the [`sentry_sdk`](https://pypi.org/project/sentry-sdk/) middleware. That required only minor settings changes in the app. See for reference:

- django settings:
  - https://gitlab.com/cloudigrade/cloudigrade/blob/master/cloudigrade%2Fconfig%2Fsettings%2Fbase.py#L287
  - https://gitlab.com/cloudigrade/cloudigrade/blob/master/cloudigrade%2Fconfig%2Fsettings%2Fprod.py#L29
- celery settings:
  - https://gitlab.com/cloudigrade/cloudigrade/blob/master/cloudigrade%2Fconfig%2Fcelery.py#L27

## Assumptions and Questions

- Sentry is not free, and we need to arrange someone to handle billing.
- Is there a benefit to _developers_ (not SREs) to implementing this?
  - We have missed and had to deal with several failures over the last month. If the integration is cheap+easy, then this could save us time and catch issues sooner.
  - This would provide a "one-stop shop" for logs and state when an error occurs so devs don't have to go hunting through logs.
- Are there other solutions we want to entertain besides Sentry?
  - Chris H. says OpenShift team is maybe already using Sentry. :)
- Do we want to enable for all environments? Or just prod and stage?
  - All environments!
- Should Sentry send alerts to #koku_dev? Should we add a #koku_alerts channel? Or #cost-mgmt-alerts?
  - Send to #cost-mgmt-alerts.
- This will augment/add to the existing prometheus alerting. Maybe in the future we alter the way those alerts are generated, but that is not included in the scope of this issue.

## Acceptance Criteria

- [x] koku organization exists in Sentry with access granted to appropriate team members (all of the devs + qe!)
- [x] koku organization exists in Sentry has projects:
  - [x] koku-api
  - [x] koku-celery
  - [ ] maybe more, TBD by whoever picks this up. Doug thinks we may want more; talk with him!
- [x] koku is configured to send to Sentry in all environments
- [x] Slack integration is enabled in Sentry for the koku organization
- [x] Alert rules are added in Sentry to notify the #cost-mgmt-alerts channel
- [x] Whoever implements this has run a meeting with at least one or some of the Koku Prime team for knowledge sharing about all things Sentry!

**Comment by lcouzens** [comment]
Nothing specific to verify but looks to be implemented.

**Comment by nbon12** [comment]
https://github.com/project-koku/koku/pull/1442

**Comment by nbon12** [comment]
Testing requested as per: #1485
