### ISSUE TITLE
Remove unused/dead AWS SNS code

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1204]
## User Story
As a developer, I don't want to see unused/dead code because it is distracting and confusing.

Based on recent conversations, the current AWS SNS code seems to have been developed but never actually used. We should delete it and any helpers and tests around it.

## Assumptions and Questions

- See these and maybe more:
  - notification_handler
  - sns_helpers
  - test_notification
  - test_aws_notification_handler

## Acceptance Criteria

- [ ] Dead code is gone, and tests continue passing.

**Comment by infinitewarp** [comment]
Thanks for linking your PR, @maskarb! 👍 Also, please remember in the future to self-assign issues if you are working on them so nobody else unwittingly starts working on them too.

**Comment by maskarb** [comment]
commit hash: d22172d13438b7d7acf171cd6803e8d8b85d6fad

**Comment by dchorvat1** [comment]
verified, 1fc823b5bd5610de48bd9450c3ff7cb34e545c16
