### ISSUE TITLE
Research IQE container to simplify developer QE test execution

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#1216]
The IQE framework now has a supported container that is designed to simplify the setup and execution of QE tests.  The test setup has always been complicated and unreliable for users that are not familiar with the IQE environment.  This issue is to research and develop helper scripts to simplify the test setup for Koku developers.

**Comment by adberglund** [comment]
We can make use of iqe's container and now #1243 has been created to track doing the work for docker-compose and OpenShift for iqe use locally.
