### ISSUE TITLE
Creating a provider with incorrect type returns 500

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1221]
**Describe the bug**
API returns 500 when posting a provider with incorrect provider type

**To Reproduce**
1. Go to `/providers/`
2. POST 
```
{
    "name": "somename",
    "type": "FOO",
    "authentication": {
        "provider_resource_name": "someauth"
    }
}
```
3. See error

**Expected behavior**
400, with error message that "FOO" is not a valid choice

**Additional context**
Tested on CI, commit b043912d8cf2d0d8d3ac74559c80f83834c18508

**Comment by lcouzens** [comment]
Verified
