### ISSUE TITLE
Openshift-on-Azure tag matching

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1230]
## User Story
As a koku customer, I want to see my Openshift usage in Azure associated with my other Azure data so that I understand their relationship.

What this means in this smaller context is we need to write the SQL to do our tag matching for Openshift-on-Azure in Koku, and we need to make the results available in the API.

## Assumptions and Questions
- This will eventually result in new APIs, but those are being held until we understand the UX.
  - This type of data appears as "openshift on cloud" in the UI today.
  - Q. Does this merge into that tab? Or add another tab?
  - Irrespective of where it shows in the UI, we will be adding a new API.
- See also: https://redhatmbu.aha.io/epics/COST-E-160
- We're going to make some assumptions about what may be useful in the API, but we accept that this will likely iterate and need changes in the future once we know the UX. No UI integration here yet.
- An initial API will likely live at `api/v1/reports/openshift/infrastructures/azure`.
  - First pass implementation will likely look similar in output to `api/v1/reports/openshift/infrastructures/aws`.
- We do _not_ need to complete _all_ APIs for this issue; we just need some API that can show that the SQL has been executed and there is _some kind_ of internal association of Openshift-on-Azure.
- TODO track an issue for the rest of the APIs and/or to follow up when the UX is ready for review.

## Acceptance Criteria

- [ ] An API exists where an end user can see that their Openshift provider is associated with an Azure provider
- [ ] Developer-centric notes/documentation exists or has been updated to explain what is means to associate OpenShift with Azure. Are there tags? Where do they live? How can I verify this on my sandbox?

**Comment by lcouzens** [comment]
Verified
Commit: 776278675649b0f439bc4afce28482564df825cf
