### ISSUE TITLE
Free space in OCP reports

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1232]
## User Story
As a Koku customer, I want to know how much available resources I have in OCP so that I can effectively compare the projects usage with the overall cluster.

Normally you might fill a cluster to, for example, 60%, and knowing at a given time that you have hit 35 or 40% is a key indicator for your trends.

## Assumptions and Questions
- See also: https://redhatmbu.aha.io/epics/COST-E-116
- **...but let's focus on considering doing two specific things here:**
  - 1. In the UI, if you go to the details page and group by cluster and look at a cluster, we can put in numbers (or charts?) to indicate the overall capacity for that cluster. We need to UX design this solution.
    - Natalie says "We want a number, not a chart. If you make a chart, I'm gonna cry" and we don't want Natalie to cry. 
  - 2. If you group by project we allow that "order by usage" so you can see the biggest projects.
    - Some additional thoughts… we already allow "order by cost", and we're not sure how technically feasible the "order by usage" will actually be here. Maybe this part of these requirements is _effectively_ redundant since cost and usage are likely proportional? Maybe we need some UI toggle to flip visibility of usage? (Natalie will think about this and try to mock up something...)
- "For me, that makes sense!" - Sergio :)
- As last discussed on Nov 7, Natalie will mock up some examples of this, and the next time we will review if we agree it makes sense to "answer the why" of helping our customers.
- As last discussed on Nov 21, we want to hold a separate discussion to specifically resolve this issue's definition. @nlcwong to organize this discussion. Try to include Sergio, Dan, Jen, Doug, Chris, Brett… and anyone else who volunteers to join! 

## Acceptance Criteria

- [ ]
- [ ]

**Comment by adberglund** [comment]
[Uploading... Screen Shot 2019-10-10 at 11.50.20 AM.png ]

**Comment by chargio** [comment]
@nlcwong This is still being shown with needs UI/UX

**Comment by infinitewarp** [comment]
Earlier discussion points that we have removed from the original description above:

- This requires some UX decision to show where it goes.
  - Maybe look at how Openshift 4 currently displays similar data.
  - We accept that we may make assumptions about API implementation details here and that we may need to revisit/refactor them if UX demands do not match.
- Internally, we have total capacity and used capacity for OCP. We should just be able to subtract them and return up the API!
- Q: Capacity of what exactly? CPU? Memory?
  - A: All of the above. CPU, memory, and storage.
- Q: We have "usage vs requests" today as a way of looking at usage. "usage" is legit usage; "request" is "blocked off" (it is not schedulable by another usage). Which of these do we use for subtracting from capacity?
  - A: Sum of both of those because they both deduct from the overall available capacity.
- Q: At what level do we do arithmetic? SQL queries? API serialization? UI display?
  - A: API serializer (python code, not SQL) is where this calculation will live, not the UI. 
- Q: Are there analogous capacity metrics for AWS and Azure without OpenShift?
  - A: No, this is a problem specific to OpenShift _on_ a cloud.
- Q: Natalie wants to answer: Where do we live? Are there areas in other UIs where this would make more sense?
- **Since the conversations are trending to this being under OpenShift, let's defer this work or just link to some other UI somewhere.** We are leaving this issue open for now until we get feedback from Sergio.
  - Sergio: We don't currently give the _context_ of the usage we currently show. So, perhaps the end user doesn't know how exactly he/she needs to optimize. The lack of context is hurting things here. Sergio suggests another unused/undefined/empty "project" with the remaining unused part(s).
  - Natalie: This unused/undefined/empty "project" may confused customers. We have a cluster list; maybe we rethink the UI around that to show available usage.
  - Andrew: Also, that weird unused project is something the customer will have to know to look for.
  - We should use an overall top-level cluster view for this kind of information.
  - Maybe "this project is using x% of your capacity" at each project level. Show the number, not the graph, because visually 1% is difficult to comprehend.
  - Can I sort my projects by % usage so I can know what projects are my biggest users in the cluster? Yes, we should have this sorting option as well.
- Q: What can we do quickly here?
  - Do we want this visible from overview? Or does it have to be in details page? Sergio says: This has to be in details page. It would be great (but not as helpful) to have it in the overview page.
- Even if we don't add capacity to the UI, sorting could be a helpful first step.
- If we add this information to the cluster definition so when you expand the cluster, that should be enough to cover the initial use case needs.

**Comment by chargio** [comment]
It seems that this provides a good view that can be added to the cluster view, and the historical view of the cluster too.

We tried to show this in the project level, but we were told that in many situations one project is basically too small to be compared with the clusters (i.e. you have 1000 projects and each one of them is less than 1% of the view, you are not going to be able to take decisions based on that info). That is the reason we don't compare any more the project with the cluster capacity.

So we need to find a way of showing this information at the cluster level (where it matters, this is an item of cluster optimization), while perhaps showing a number at the project level (i.e. this is 0.2% of total cluster capacity).

We then should be able to show (add an additional line) the comparison of usage and reserved against capacity in the historical view for that specific cluster.

**Comment by nlcwong** [comment]
Slide 4: https://marvelapp.com/1jj511j6

**Comment by adberglund** [comment]
This should be taken care of on the details page when grouping by cluster, if you expand a cluster we should see capacity info.

**Comment by lcouzens** [comment]
Verified
