### ISSUE TITLE
Investigate Prod 5xx Alerts

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1239]
**Summary**
We get 5xx alerts from alert manager each day at approximately the same time. I believe it's QE testing that overloads gunicorn and it bounces requests. 

Possibly related: #1082 

See channel in Ansible Slack: #cost-mgmt-alerts

**Expected behavior**
We should hopefully have the ability to handle the requests from our tests. 

**Additional context**
- Worth checking kibana for 500 logs.

**Comment by lcouzens** [comment]
@katherine-black I guess you didnt find anything? and assume you moved it here so I can investigate the QE test runs instead.

**Comment by katherine-black** [comment]
Hey @lcouzens, I'm sorry I'm getting back to you so late, this notification slipped through the cracks. This is the only issue I managed to track down: https://github.com/project-koku/koku/pull/1300

**Comment by lcouzens** [comment]
Not seen any PROD alerts since this fix so closing it for now.
