### ISSUE TITLE
OpenShift and OpenShift on AWS Returning Slightly Different Costs

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1241]
**Describe the bug**
After merging the change to use a single reporting daily summary table for OpenShift (bypassing the need for the costs summary table) our OpenShift and OpenShift on AWS APIs are returning slightly different costs. 

**To Reproduce**
1. Hit api/cost-management/v1/reports/openshift/costs/?filter[time_scope_value]=-1
2. Hit api/cost-management/v1/reports/openshift/infrastructures/aws/costs/?filter[time_scope_value]=-1
  - this one is probably the accurate view of the data
3. Observe infrastructure cost!

**Expected behavior**
We should have the same infrastructure cost on both APIs.

@adberglund has volunteered to walk through and explain the SQL behind these results if you have any questions.

In the even that this is an API issue, here are a few links to places to look. 

- OCP execute query method: https://github.com/project-koku/koku/blob/master/koku/api/report/ocp/query_handler.py#L115
- OCP provider map where aspects of the query are defined: https://github.com/project-koku/koku/blob/master/koku/api/report/ocp/provider_map.py
- OCP AWS execute query: https://github.com/project-koku/koku/blob/master/koku/api/report/ocp_aws/query_handler.py#L57
- OCP AWS provider map: https://github.com/project-koku/koku/blob/master/koku/api/report/ocp_aws/provider_map.py

In the even that this is a SQL bug

- The data in this table to be the source of truth for cost since it is, per the group by aws_id, it should not have any duplicates of AWS line item costs: https://github.com/project-koku/koku/blob/master/koku/masu/database/sql/reporting_ocpawscostlineitem_daily_summary.sql#L1129
- Check the data in this table to make sure the costs are the same: https://github.com/project-koku/koku/blob/master/koku/masu/database/sql/reporting_ocpawscostlineitem_daily_summary.sql#L1197
- Finally check this block to see if the cost discrepancy is occurring at this step: https://github.com/project-koku/koku/blob/master/koku/masu/database/sql/reporting_ocpcosts_summary.sql#L1-L55

**Comment by lcouzens** [comment]
Verified
