### ISSUE TITLE
Make it easier to run iqe tests locally

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1243]
## User Story
As a developer I want a simple and reliable way to run our full test suite locally so that I can identify regressions earlier. 

## Assumptions
- docker-compose and OpenShift development will be covered
-

## Acceptance Criteria

- [ ]
- [ ]

**Comment by blentz** [comment]
I wrote up some additional documentation, but it looks like the existing scripting that Luke wrote works well and is easy to navigate.

There is still complexity in the workflow, but this pass has improved on it a fair bit.
