### ISSUE TITLE
Celery not configured properly

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1261]
**Describe the bug**
Our celery workers are not respecting the settings we have set. 

**To Reproduce**
1. Log into a machine running a worker
2. `DJANGO_READ_DOT_ENV_FILE=True python koku/manage.py shell`
3. 
```
from celery.task.control import inspect
inspect().stats()
```
4. See `max-concurrency` and `prefetch_count` are the defaults

**Expected behavior**
Workers should only be pulling 1 task at a time, and we should only have 2 worker processes per pod.

**Comment by adberglund** [comment]
This was a mis-configuration that was causing a) too many celery workers to spawn and b) a celery worker to fetch too many tasks, starving other workers. Confirmed that the settings are properly set in CI.

**Comment by lcouzens** [comment]
Verified.
Commit: 96a12fc0e55ee08d444f5919b549ec575683a988
