### ISSUE TITLE
Process only data needed in AWS Report Processor

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1263]
## Objective
Currently we process all files in a cost and usage report start to finish every time we receive a new manifest, but we really only need to process the same 3 day window we run summarization on as older data is not going to change. We re-process the entire month when the AWS bill is finalized anyway so any estimates that change will be updated then.

## Assumptions
- We want to run a 3 day window to get any missing data from prior days
- This will greatly reduce processing time for large manifests

## Acceptance Criteria

- [ ] All data is still loaded and APIs reflect accurate usage and cost

**Comment by dchorvat1** [comment]
verified, 5f65d324af3f801b7f2ee6f20f7a6da5ba6162d7
