### ISSUE TITLE
Document Azure Source Creating

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1266]
## Objective
We want to document the entire workflow for adding an Azure source for our read the docs pages. Everything required from creating the service principal, IAM, et cetera in Azure to creating the source in cost management should be covered. 

See https://docs.google.com/document/d/1oF_avuqraCulQUE9Q55Pj2aBAbPsPXzFBAj-WEC-wJs/edit

**Comment by lcouzens** [comment]
Verified
