### ISSUE TITLE
Replace _PROVIDER_TYPES with PROVIDER_CHOICE_LIST

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1277]
## User Story
As a Koku developer, I want to reduce code duplication so that I reduce risk of regression.

We recently added [`_PROVIDER_TYPES`](https://github.com/project-koku/koku/blob/master/koku/api/dataexport/syncer/__init__.py#L14) because we did not find an obvious existing list of provider type identifier strings, but there is also the recently introduced [`PROVIDER_CHOICE_LIST`](https://github.com/project-koku/koku/blob/master/koku/api/provider/serializers.py#L33).

`PROVIDER_CHOICE_LIST` should be used instead of `_PROVIDER_TYPES`, but `PROVIDER_CHOICE_LIST` also should be moved to a more common module than `serializers`.

## Assumptions and Questions
- Maybe talk with @adberglund since he recently added `PROVIDER_CHOICE_LIST`.

## Acceptance Criteria

- [x] `_PROVIDER_TYPES` no longer exists, and its uses have been replaced with `PROVIDER_CHOICE_LIST` or an even more appropriate equivalent.
- [ ] ~If we decide to use `PROVIDER_CHOICE_LIST`, it now exists in a different module that makes more sense for commonplace imports than from `api.provider.serializers`.~

**Comment by werwty** [comment]
LGTM.
Since we did not continue using `PROVIDER_CHOICE_LIST` there's no need to refactor it as of this moment. I've updated the AC to reflect this.
