### ISSUE TITLE
API to return our cloud account ID for use in sources

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1284]
## User Story
As a sources UI engineer I would like to have an API to call to get the AWS account ID for cost management so that I do not have to hard code an account ID I do not own.

## Assumptions
- Our sources flow has a user setting up an IAM role in *their* AWS account and allowing *our* AWS access to that role via the boto3 assume_role command.
- We currently just hard code our AWS account ID in the cost management sources wizard, but with that workflow now moving to platform sources, we should really be giving that account ID via an API. 

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/cloudaccounts/?type=AWS |
 | **Body** | N/A |
 | **Response** | `{"account_id": "9999999999"}` |

## Acceptance Criteria

- [ ] The API returns the correct account ID for our cost management AWS account
- [ ] The API is filterable by source type (although we only need AWS today)

**Comment by nbon12** [comment]
@adberglund a new table will be created called Attributes, with the following columns

- Name
- Value
- Description

The first row entry would be the tuple <"aws_account_id", "XXXXXXXXX", "Cost Management's AWS Account ID">

A user can make a GET request to /api/v1/attributes/?name=aws_account_id and receive the following response in the payload: {"aws_account_id", "XXXXXXXXX", "Cost Management's AWS Account ID"}

**Comment by lcouzens** [comment]
@nbon12 I am goner move this back for a minor tweak. Me being really picky, but all our current endpoints use `-` over `_` so we should probably keep consistent here too.

For example:
`cost-management`
`instance-types`

**Comment by nbon12** [comment]
@lcouzens I merged the PR to rename the endpoint and moved the issue to QA.

**Comment by lcouzens** [comment]
Verified
commit: 9418759f4f87a6e7b87ff2b356cb32ca583a9478
