### ISSUE TITLE
OpenShift on AWS group by project is incorrect.

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#1303]
The OCP on AWS query handler is grabbing the wrong ProviderMap, which gives the query handler the database annotations to query by.  Bug was introduced with https://github.com/project-koku/koku/pull/1234

This has been seen on CI and production on the OCP on Cloud Details pages.  Problem was reproduced with Nise and I've attached a document showing the difference in API response between commits `1ebdbc7de5ddfa3cc631313b1ea4b6318ddd6f37` and `efd0007ababb346b486a722d503a2ee6258dedab`

[api_refactor_regression.txt](https://github.com/project-koku/koku/files/3768679/api_refactor_regression.txt)

**Comment by lcouzens** [comment]
Verified
Commit: 5ab2bd6248462c96c73eb727fc1c0b5720764447
