### ISSUE TITLE
Create API to return provider status to Platform Sources

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#1309]
## User Story
As cost management user, I need my cost management account's status to be available to the insights platform so I can be informed when my account is not healthy.

## Impacts
API, UI, Docs

## Assumptions and Questions
- Platform Sources will be calling this API periodically.  Exact frequency is not yet known but it will be most likely hourly or daily.
- The exact calling convention and expected response is not yet known.  Platform Sources design work is forthcoming.  I know that it will be requesting status for Source ID: X and expecting a simple boolean type response.
- In order to start this work I propose that we make an API such as `/source-status/X` to return the source status for ID X.  The response can be a simple json such as `{'source_id: X', 'status': true}`. Before beginning this work we should reach out to Platform Sources and see if they have an API definition.  If they do use that, if they don't maybe propose something or try to get a heads up on what it will be so we can minimize changes for integration.
- `ProviderAccessor().cost_usage_source_ready()` can be used as the business logic behind the source status.  The `sources` database table has the `source_id`, `authentication`, and `billing_source` arguments needed for `ProviderAccessor`.
- TODO for whoever implements this: Figure out how `ProviderStatus` fits into this, and consider the flows @blentz describes in which we may set an "error" status if things fail during processing.
- Q: Are there any specific RBAC concerns for this? Should this be a special internal API that only the platform can access? Should this be available to customers (thus RBAC)?
  - A: We probably want this to be an internal API. Sources client is currently internal... there may be something we can reuse there if we want this to be internal.
  - Also please have a discussion with the platform sources team about how this may affect the standard interface for other services that implement this.

## API Details

Anything that takes a source ID and returns a boolean status for the source.  Ultimately this will need to conform with what Platform Sources defines.  We will be their first customer so we should reach out to them before starting this work to get the latest status.

| API  | Detail|
 | --- | --- |
 | **Method** | GET/ |
 | **Path** | /api/v1/source-status/?source_id=X |
 | **Body** |  |
 | **Response** | `{True}` |
|**Response Code ** | 200_OK |

## UI Details
TBD.  UX mocks are underway.

## Acceptance Criteria

- [ ] API returns successful for an AWS, and Azure source that is configured correctly.
- [ ] API returns failure for an AWS, and Azure source that becomes misconfigured on the cloud backend.  This would mean setting it up correctly initially than changing something on the AWS or Azure side such that our checks fail.
- [ ] API returns successful for an OCP source since we have no checks in place at this point in time.
- [ ] API returns a 404 if  the Source ID is not found

**Comment by nbon12** [comment]
@lcouzens

**Comment by lcouzens** [comment]
Something I just noticed. I know this is an internal api but still wondering whether we should keep consistency between api paths.. for example `cost-management` vs `source_status`

Should we change `source_status` to `source-status` to match all our current paths?

@nbon12 @adberglund thoughts??

**Comment by nbon12** [comment]
@lcouzens 
In the source app, the other URLs, for example`billing_source`, use an underscore.
In this case, `source_status` matches `billing_source`
https://github.com/project-koku/koku/blob/master/koku/sources/api/urls.py#L26

**Comment by lcouzens** [comment]
So it does! I missed that, Now I am wondering if we should change that tooo :laughing:  The query params are fine that matches everything we have today. It was just the path I was looking at. Maybe @adberglund has a comment on what to do, I'm not that bothered either way just want to make sure we are consistent where it makes sense :+1:

**Comment by nbon12** [comment]
@lcouzens I've renamed /source_status/ to /source-status/
Merged the PR https://github.com/project-koku/koku/pull/1399/files

**Comment by dchorvat1** [comment]
verified, 6bac6962d08f693740f8147c966bfdb5ce39a7c3
