### ISSUE TITLE
Modify Sources Client integration service to use a provided cluster-id instead of sources uuid

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#1310]
## User Story
As a user, I want my OCP cluster to be added when on boarding a new OCP cluster through Platform Sources.

The Sources Client integration service is currently coded to use the Sources UUID as the cluster ID.  After discussions with members from UX and Platform Sources, we decided to keep the OCP on boarding flow the same as it is today where a cluster ID from Korekuta is provided to Platform Sources UI to onboard the cluster into Cost Management.

## Impacts
API, UI, Docs

## Assumptions and Questions
- Same Korekuta flow as today (however, a new issue will be opened to replace the UUID generated today with a cluster uuid returned from the OCP cluster resource object)
- The Koku-Sources client flow will match that of AWS and Azure, where the frontend will have to supply the cluster id directly to the koku micro service instead of going to the platform sources service.
- Sources Client service API endpoints need to be enhanced to allow for an API call to supply the cluster_id for OCP source types.  Most obvious candidate for this is the existing endpoint `<koku-sources-client>/authentication` with the JSON data`{"source_id": 3, "credentials": {"cluster_id": "2639de71-ca37-4a17-a104-17665a50e7fc"}}`

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** POST |
 | **Path** | <koku-sources-client>/api/v1/authentication/ |
 | **Body** |  {"source_id": 3, "credentials": {"cluster_id": "2639de71-ca37-4a17-a104-17665a50e7fc"}} |
 | **Response** | {"source_id": 3, "credentials": {"cluster_id": "2639de71-ca37-4a17-a104-17665a50e7fc"}} |

## UI Details
Platform Sources UI will enhance the Cost Management specific wizard pages for OCP type to send the cluster-id value to the Koku micro service.  Same as what is being done for AWS

## Acceptance Criteria

- [ ] An OCP cluster can be onboard to cost management via Platform Sources + Koku Sources Client /authentication endpoint
- [ ] All standard cost management Source CRUD works.

**Comment by dccurtis** [comment]
After thinking this over some and discussing with Platform Sources this morning, I think we will be storing the cluster ID on the Platform Sources side since Platform Sources will ultimately integrate with OCM.

If we decide to go this direction, there will be no `/authentication` work but instead be only Sources Client updates to fetch the "OCM" (korekuta provided) cluster_id from platform sources.

**Comment by lcouzens** [comment]
Verified
Commit: "c6ca9c8134ff24ef80ab9ce65a8d5449476f847e"
