### ISSUE TITLE
split archive data on provider id, not just type

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#1315]
## User Story
As a Koku customer, I want my exported data archive to be split on provider id so I can analyze data at the provider level.

We currently save all of the data at the provider _type_ level (e.g. `aws`). We will need to change the way we query the data, the path where the data is stored, and the path where the data is fetched+copied to the customer's S3 bucket.

S3 file paths should look like `acct10001/aws/{provider_id}/2019/10/12/foo.csv`.

## Assumptions and Questions
- Maybe a future enhancement: Allow the customer to ask for only a specific provider ID, not "give me everything within this time".

## Acceptance Criteria

- [ ] When the scheduled job runs to archive data daily, the files we write to Koku's S3 bucket include the relevant provider ID in the path.
- [ ] When the customer requests their data export and we copy files to the requested bucket, we include the appropriate provider IDs in the paths of the copied files.
  - This means we probably need to iterate in code the provider IDs so we can define appropriate S3 path prefixes.

**Comment by lcouzens** [comment]
Verified
