### ISSUE TITLE
Remove Azure meter data upon provider removal leading to smoke test failures

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#1322]
**Describe the bug**
Azure meter data is not being removed from table `reporting_azuremeter`.  This is impacting smoke tests when the same meter-id is being used and Nise generates a new meter name on subsequent azure provider test runs.

**To Reproduce**
1. Add an Azure-local provider with nise data
2. Ingest/process data.  Verify meter id table is populated
3. Remove Azure-local provider
4. See meter data remains
5. Re-generate Nise data with the same nise yaml (hard-coded meter-id, let meter-name get randomly generated)
6. Add Azure-local provider back and ingest and you will see a processing failure like this, if it generated a different meter name:

```
koku_worker       | [2019-10-29 15:24:48,753] INFO: File <_io.TextIOWrapper name='/testing/pvc_dir/processing/acct10001/azure//costreport_5de48ec0-ee24-46ff-badc-18df1ad4c5a4.csv' mode='r' encoding='utf-8-sig'> opened for processing
koku_worker       | [2019-10-29 15:24:48,935] ERROR: Row in <class 'reporting.provider.azure.models.AzureMeter'> does not exist in database.
koku_worker       | [2019-10-29 15:24:48,937] ERROR: Failed row data: {'meter_category': 'Storage', 'meter_subcategory': 'Tables', 'meter_id': '55555555-4444-3333-2222-111111111116', 'meter_name': 'Write Operations', 'meter_region': None, 'currency': 'USD', 'unit_of_measure': None}
koku_worker       | [2019-10-29 15:24:48,939: ERROR/ForkPoolWorker-2] masu.processor.tasks.get_report_files[2e65780a-bd23-4e60-b293-9f1edb209b30]: 'NoneType' object has no attribute 'id'
```

**Expected behavior**
Subsequent Azure providers with the same meter-id should not fail processing since meter data would be removed whenever the provider is deleted

FYI: @lcouzens @maskarb

**Comment by lcouzens** [comment]
Verified
