### ISSUE TITLE
Suspend provider activities when a provider becomes misconfigured.

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#1326]
## User Story
As a user, I want Cost Management to not attempt to ingest/process my account and alerts me when my account is misconfigured.

More Context:
Platform Sources will be tracking the status of all Cost Management accounts through a status checker that will be periodically asking us for status.  Additionally, cost management will have the capability to push status to the platform when we determine that the provider is no longer configured correctly.

This issue is to make enhancements to the cost management backend to facilitate pausing and resuming providers as well as give the frontend a way to know why a particular account has not ingested data.

## Impacts
API, UI, Docs

## Assumptions and Questions
- Work is ongoing for the Platform Source team to define app-specific status schematics.  This will include a boolean-type flag indicating the health of the source and most likely some sort of error id for the frontend to look up a localized string for an error message.
- I think we could begin the work to suspend Koku-providers when the cloud on boarding checks fail i.e. `ProviderAccessor().cost_usage_source_ready()`
- Issue https://github.com/project-koku/koku/issues/1309 is adding the provider status hook for the platform to call.  One this is in place this could be the re-activation mechanism for the source.  As long as we are living on the Insights platform; I do not think we should have any internal retries and simply let the platform drive this flow.
- `ProviderStatus` should be considered here since it is backing off downloads on failure.  The Platform will also be having a back off logic when it comes to poll for status on a source.  We do not want to have two back off mechanisms at odds with each other which would cause the provider to be stuck unnecessarily in a disabled state.
- `AccountsAccessor()` could be enhanced to return the status of the provider.  Maybe put a boolean on `provider` table for `active: true/false` and then the Masu `Orchestrator` would know whether or not it should attempt to ingest from the account.  This flag could also be surfaced on the `/providers` response for the UI to know if the provider is active or not. 
- Brett reminds us that there are lots of checks scattered through the downloader code (maybe elsewhere too), and this would be a good opportunity to review and possibly consolidate. Maybe ask him if you want a tour of where those downloader checks are!

## API Details
Just an idea... Could use the same status endpoint to attempt to re-engage a source being implemented here https://github.com/project-koku/koku/issues/1309.

That API could be enhanced to also take a provider-uuid in the event that the provider hasn't been added to Platform Sources.

## UI Details
- Need UX to weigh in, but we could use the `active` status on the provider response to update the Cost Management UI
- We will enter another issue to update the UI to show some representation of this data.

## Acceptance Criteria
- [ ] Another issue has been entered for working on the UI.
- [ ] Misconfigure a provider (rename AWS bucket for example), hit the source status endpoint to simulate the platform polling for status, verify that it fails.  Force a re-ingest with the `/download` endpoint and verify that ingest/processing is skipped. 
- [ ] Continuing from the previous point, fix the provider, and call the source status endpoint again, verify that it's successful.  Force a re-ingest with `/download` and verify that ingest/processing occurs.

**Comment by dccurtis** [comment]
Going to make a PR which focuses on suspending a provider while it's misconfigured via the PUT /provider method.  Further integration with https://github.com/project-koku/koku/issues/1309  will be done on that PR or in a subsequent PR.

**Comment by lcouzens** [comment]
Verified
Commit: 5f65d324af3f801b7f2ee6f20f7a6da5ba6162d7
