### ISSUE TITLE
Sometimes hit 500 error on deleting provider

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#1328]
**Describe the bug**
Sometimes hit 500 error on deleting provider

**To Reproduce**
1. Add provider (possible aws only, not confirmed)
2. Delete provider
3. See error

**Expected behavior**
Provider should be deleted without errors

**Context (please complete the following information):**
 - Commit Hash from status endpoint: e95da551ea6ae2af24e6f6842be2dc16448322d2

**Additional context**
CI logs
```
[2019-10-29 23:19:58,215] ERROR: User object (114) failed to remove provider uuid: f06c4c39-d8a5-4466-8fa7-7335e8256376. Error: deadlock detected
DETAIL:  Process 12106 waits for ShareLock on transaction 1477614; blocked by process 12108.
Process 12108 waits for ShareLock on transaction 1477612; blocked by process 12106.
HINT:  See server log for query details.
CONTEXT:  while deleting tuple (662,14) in relation "reporting_awscostentrylineitem"
```

I hit this while running automation against CI/QA and once locally
Automation throws up this `HTTP response body: {"errors":[{"detail":"Error removing provider","source":"detail","status":500}]}`

You can probably reproduce it using something like this `ENV_FOR_DYNACONF=local iqe tests plugin hccm -k test_providers`

**Comment by lcouzens** [comment]
So looking at this again, it looks like its getting hit when deleting a provider while its trying to ingest data. That being said its a little more of an edge case but @adberglund and I agree we could probably handle it better.

**Comment by infinitewarp** [comment]
@adberglund thinks this may be a recent regression from when we added new FKEYs with integrity enforcement.

**Comment by infinitewarp** [comment]
@lcouzens was deleting providers while masu was doing its hourly ingestion, and that seemed to be a likely case for reproducing.

Maybe unrelated, but @lcouzens and @adberglund were seeing some "leftover" data in the database after deleting a provider recently, and that _shouldn't_ happen... @dccurtis may have more information about what data was left behind. This may or may not be related to this particular issues.

**Comment by dccurtis** [comment]
I'm no longer hitting the issue that I mentioned in the meeting.  The issue was two stray providers remaining in the database after running provider tests.  There must have been a recent test change that addressed this

**Comment by lcouzens** [comment]
Verified
Commit: d543f89bdcaf572a36413aa8c7002a7162274d77
