### ISSUE TITLE
Convert Images to Being RHEL Based

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1335]
## User Story
As an application in the platform, we must have RHEL based images so that we can go to production.

## Assumptions and Information
- This is a **requirement** for going to production on the Insights platform.
- CentOS does not count as RHEL based
- Whoever takes this issue should sync with the quipicords team who recently converted their images to using Universal Base Image 8 (UBI8) 

## Acceptance Criteria

- [x] All OpenShift images in the e2e-deploy repository are RHEL based (UBI8)
- [x] All of our applications and dependent services deploy successfully in OpenShift
- [x] local development continues to work, and developer docs are updated to explain how to set up registry access locally

**Comment by blentz** [comment]
Note: An offline conversation reveals that we probably can't go all the way to UBI8. So, we're going with UBI7/RHEL7 until the platform migrates over to OpenShift 4.x on EL8.

**Comment by lcouzens** [comment]
Verified
