### ISSUE TITLE
All cost columns should be populated on the OCP Daily Summary Table

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1336]
**Describe the bug**
A recent change was made to try to bring OpenShift in line with other sources by using the same database table schema. This meant that `reporting_ocpstoragelineitem_daily_summary` `reporting_ocpusagelineitem_daily_summary` and `reporting_ocpcosts_summary` were supposed to be consolidated to the `reporting_ocpusagelineitem_daily_summary` table.  Not all cost values are making it into that table. As an immediate fix we reverted to using the `reporting_ocpcosts_summary` table for now. 

**To Reproduce**
1. Create an OpenShift source
2. Create a cost model with a price list and markup and associate with the OpenShift source
3. Load OpenShift data (nise should be fine)
4. Check APIs for OpenShift and check `infrastructure_cost`, `markup_cost`, `derived_cost` and `cost` values

**Expected behavior**
All cost columns should be populated on `reporting_ocpusagelineitem_daily_summary`

**Additional context**
- The SQL in question is most likely here: https://github.com/project-koku/koku/blob/master/koku/masu/database/sql/reporting_ocpcosts_summary.sql#L1-L55
- Check that the `GROUP BY` statement is accurate
- Check that `WHERE` clause is not excluding rows (the fix here would be including null columns)
- When we fix this issue, we should be able to revert the aforementioned revert and go back to using the `reporting_ocpusagelineitem_daily_summary` table. Let's do that as part of this fix!

**Comment by lcouzens** [comment]
Verified
Commit: "6bac6962d08f693740f8147c966bfdb5ce39a7c3"
