### ISSUE TITLE
Add cloud-accounts to OpenAPI spec

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1337]
## User Story
As a user of the koku API I would like the cloud-accounts API to be represented in the OpenAPI spec so that I can know how to use the API. 

## Assumptions
- The API exists already, this is just a miss from the acceptance criteria and code review of the original issue

## Acceptance Criteria

- [x] OpenAPI spec has this API and has no errors (can generate a client)

**Comment by dchorvat1** [comment]
verified, 73391d32b0a76f05295f219d9f5c2b6542b96a60
