### ISSUE TITLE
Investigate API Timeouts

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1338]
## User Story
As a user of cost-management I'd like my dashboard to load without timeout so that I can see my data!

## Assumptions and Information
- We make 3 API calls per card on the dashboard -- This part probably isn't going to change in the near term, and we have a UI redesign in the pipe so although we should look at making fewer calls if possible, we should wait to make drastic changes until we know how that will shake down. Never-the-less, this is a spike, so API redesign ideas are welcome.
- All of these API calls for a source are hitting the same summary table which for larger customers can still be millions of rows. 

```
select count(*) from reporting_awscostentrylineitem_daily_summary;
  count
---------
 2,713,211
```

- Consider materialized views to split our summary table into smaller tables by date range, group by? 
- @dlabrecq has some ideas about reducing the number of API calls because some calls may be redundant. Be sure to talk with him as you investigate this spike!! Currently may be getting two months of data twice?
- Let's start by treating _this_ issue as a "back-end only" research item, but do talk with @dlabrecq and consider opening a second issue as a "front-end only" research item.

## Acceptance Criteria or Desired Research Output

- [ ] proposal for changes to share with the team that we can then discuss and scope into stories
- [ ] another issue has been opened or conversation is ongoing with @dlabrecq to review and optimize front-end calls to the API

**Comment by lcouzens** [comment]
In terms of getting two months of data in a single call. That was possible with time_scope changes previously but those changes were reverted because of other issues that came up.

Based on the backlog discussion I think we were assuming that this call returned both months of data but it only returns previous month datas.

```/api/cost-management/v1/reports/openshift/infrastructures/aws/instance-types/?filter[time_scope_units]=month&filter[time_scope_value]=-2&filter[resolution]=daily```

**Comment by lcouzens** [comment]
Verified
Commit: 88f941102c430aa69dd11fda69962b88ef27782a
