### ISSUE TITLE
Cost models API - sorting cost models

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku#1339]
## User Story
As user, I want to sort cost models by name, number of sources assigned or last modified so that cost models that most recent or have the most sources will be shown first.

## Impacts
API & UI

## Assumptions
- Should just reuse our existing ordering code for DRF.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/cost-models/ |
 | **Body** |  |
 | **Response** | sorted cost model list by name/last-modified/sources |

## Acceptance Criteria

- [ ] passing sort-by (name, sources, updated) and sort-direction (asc/desc) parameters
- [ ] sorting information (by and direction) have to be shown in the response body.

**Comment by boaz0** [comment]
@adberglund @maskarb - feel free to update the ticket in case I missed something.
Thanks.

**Comment by lcouzens** [comment]
Verified
Commit: 558ce56cb6a82cfd22bd8a51965e788b47427eb9
