### ISSUE TITLE
Cost models - filter cost model by description too

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku#1340]
## User Story
As user, I want to filter cost models by description so that cost models that contains specific information in the description will be shown.

## Impacts
API, UI

## Assumptions and Questions
- Do we just treat the filter as a _literal_ string?
  - Yes, literal string only.
- Do we normalize anything?
  - No, literal string only.
- Do we just SQL `ILIKE` with `%` globs around each side of the literal string?
  - Yes, do that. :)
- Anywhere we currently filter, there is a dropdown of options. We will need to add the "description" field as an option to those lists.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/costmodels/ |
 | **Body** |  |
 | **Response** | cost models filtered by sub string |

## Acceptance Criteria

- [ ] passing a description parameter that will filter cost models that contains it (case insensitively) in their descriptions. I guess that the description may contain spaces, quotes, double quotes and etc.
- [ ] User can apply a "description" filter in the UI anywhere they can apply other filters for the cost models.

**Comment by lcouzens** [comment]
Verified
Commit: 88f941102c430aa69dd11fda69962b88ef27782a
