### ISSUE TITLE
FakeQueryParameters does not act like QueryParams

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1342]
**Describe the bug**
When calling our APIs specifying `?filter[time_scope_value]=-1` will default the query handler to use a `time_scope_units` of `month`. The `FakeQueryParameters` does not follow this behavior whereas the `QueryParams` object does.

Causes this failure on the 31st day of a month (when defaulting to 30 days is not the same as a full month)

```
======================================================================
FAIL: test_execute_query_w_delta_no_previous_data (api.report.test.tests_queries.ReportQueryTest)
Test deltas with no previous data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/project-koku/koku/koku/api/report/test/tests_queries.py", line 1074, in test_execute_query_w_delta_no_previous_data
    self.assertAlmostEqual(delta.get('value'), expected_delta_value, 6)
AssertionError: Decimal('0') != Decimal('640.3514654031000032315133668') within 6 places
```

**To Reproduce**
1. Be on a month with 31 days
2. Run `test_execute_query_w_delta_no_previous_data`

**Expected behavior**
Tests should pass regardless of the run date.

**Additional context**
Although one solution would be to fix the `FakeQueryParameters` object, I would like further understanding of why we need a mocked class here at all, we don't need specific control over the returned results and no external service is involved. I think a better approach would be to to have `QueryParams` be usable in a test situation.

**Comment by dccurtis** [comment]
https://github.com/project-koku/koku/pull/1341 has the temporary fix
