### ISSUE TITLE
Add Platform Sources AWS CRUD tests

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#1346]
## User Story
As user of cost management, I want to ensure that my AWS account added to Platform Sources works with Cost Management.

Basic CRUD tests to ensure the integrity of the integration logic between Cost Management and Platform Sources is needed.  These tests need to only focus on the account creation, updating, and deleting.  The Koku `/provider` API is where the tests would validate they are handling the appropriate Platform Source operation.

Ideally these tests would be UI driven and ran in Vortex.

## Impacts
Tests

## Assumptions
- Test environment has Platform Sources and RBAC running.
- All UI and backend work is complete, no blockers!

## Acceptance Criteria

- [ ] Tests are ran in automation where we are exercising all of the integration points between cost management, RBAC, UI, and Platform Sources

**Comment by lcouzens** [comment]
Complete
https://gitlab.cee.redhat.com/insights-qe/hccm-plugin/merge_requests/423
https://gitlab.cee.redhat.com/insights-qe/hccm-plugin/merge_requests/419
