### ISSUE TITLE
Add Platform Sources OCP CRUD tests

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#1347]
## User Story
As user of cost management, I want to ensure that my OCP account added to Platform Sources works with Cost Management.

Basic CRUD tests to ensure the integrity of the integration logic between Cost Management and Platform Sources is needed.  These tests need to only focus on the account creation, updating, and deleting.  The Koku `/provider` API is where the tests would validate they are handling the appropriate Platform Source operation.

Ideally these tests would be UI driven and ran in Vortex.

## Impacts
Tests

## Assumptions
- Test environment has Platform Sources and RBAC running.
- UI tests are blocked by https://github.com/ManageIQ/sources-ui/issues/127
- Backend is complete with PRs: https://github.com/ManageIQ/sources-api/pull/117 and https://github.com/project-koku/koku/pull/1319

## Acceptance Criteria

- [ ] Tests are ran in automation where we are exercising all of the integration points between cost management, RBAC, UI, and Platform Sources

**Comment by lcouzens** [comment]
https://gitlab.cee.redhat.com/insights-qe/hccm-plugin/merge_requests/423
https://gitlab.cee.redhat.com/insights-qe/hccm-plugin/merge_requests/419
