### ISSUE TITLE
OCP on AWS infrastructure_cost dependency problem for OCP costs endpoint

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#1362]
**Describe the bug**
There is a dependency problem in the ordering of ingesting OCP and AWS providers resulting in the `reports/openshift/costs` not having an updated `infrastructure_cost` value when OCP is ingested before AWS

**To Reproduce**
1. Create an OCP provider and generate/ingest data from Nise (example_ocp_static_data.yml)
2. Create an AWS-local provider and generate/ingest data from Nise (example_aws_static_data.yml)
3. Visit the Koku api `reports/openshift/costs`
4. See that `infrastructure_cost` is $0

Note if you followed these steps in the reverse order (AWS then OCP) the `infrastructure_cost` is not $0

**Expected behavior**
The `infrastructure_cost` value for `reports/openshift/costs` should be updated correctly regardless of the OCP and AWS ingestion order.

**Comment by adberglund** [comment]
Let's do https://github.com/project-koku/koku/issues/1336 first and make sure that doesn't solve this.

**Comment by lcouzens** [comment]
Verified
Commit: 0049e4c4c8d72eecbc6f662b05b23ad33d64024a
