### ISSUE TITLE
Worker is trying to access csv file after it's deleted

### ISSUE THREAD

**Issue by msager27** [project-koku/koku#1365]
**Describe the bug**
My test is ingesting data that was generated by Nise.  Most of the time it passes.  When it fails, I've noticed an error in the koku_worker log in which it's trying to access a csv file that no longer exists.  The file was deleted slightly before access by a different worker.

**To Reproduce**
This isn't 100% reproducible, but the test steps are:
1. Create 4 Azure-local providers
2. Generate Nise data
3. Ingest the data.
4. Wait for ingest to complete using data fields in the /providers api to detect this (this step eventually times out).
5. Retrieve cost data via the /reports/azure/costs api and validate total cost equals the sum of daily costs

**Expected behavior**
At the user level, the /providers api data fields should reflect all files have been processed

**Context (please complete the following information):**
- OS: Fedora 30

**Additional context**
I'll attach the log, but a couple entries of relevance from the log:

```
File '/testing/pvc_dir/processing/acct10001/azure/costreport_9510368f-2fc3-492e-a96f-2660c2b7f5f7.csv' gets removed by ForkPoolWorker-1 at 20:58:45,418:

[2019-11-06 20:58:45,418: INFO/ForkPoolWorker-1] masu.processor.tasks.get_report_files[ea378154-cfd0-4868-a1e6-6e490b895eab]: Temporary files removed: ['/testing/pvc_dir/processing/acct10001/azure/costreport_b4d0bec6-f83e-4751-806d-033d553a0b12.csv', '/testing/pvc_dir/processing/acct10001/azure/costreport_9510368f-2fc3-492e-a96f-2660c2b7f5f7.csv']
```

But ForkPoolWorker-2 tries to access it at 20:58:45,461:

```
[2019-11-06 20:58:45,461: ERROR/ForkPoolWorker-2] masu.processor.tasks.get_report_files[4820106d-9188-413f-af83-ad100075d8ee]: [Errno 2] No such file or directory: '/testing/pvc_dir/processing/acct10001/azure//costreport_9510368f-2fc3-492e-a96f-2660c2b7f5f7.csv'
```

This is with Azure.  I haven't seen it with AWS, but I've mostly been using Azure.  It's not 100% reproducible, but I seem to encounter it pretty often (~20-30% of the time?).  Perhaps a synchronization issue?

I'll attach the log, which has 2 instances of this error.  Please let me know what else I can provide.

[koku_worker_log.txt](https://github.com/project-koku/koku/files/3816934/koku_worker_log.txt)

**Comment by adberglund** [comment]
This is happening in production now too. We're deleting files before all files in a manifest are processed and we fail out.

**Comment by msager27** [comment]
Verified
