### ISSUE TITLE
Use OpenShift ReportPeriod instead of cluster ID

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1367]
## User Story
As a developer I want interactions with each data source to be consistent so I know what to expect. 

This would improve consistency in how we treat the data.

## Assumptions and Background
- Currently we look at AWS and Azure using their bill IDs which is a foreign key relationship. For OpenShift we have used a cluster id which is a string. Recently we added foreign key relationships for the OpenShift equivalent of a bill table `OCPUsageReportPeriod` throughout the reporting OpenShift tables, so it can now be used.
- There are several helper functions in use in masu, particularly in the OCPCloudSummaryUpdater  (https://github.com/project-koku/koku/blob/master/koku/masu/processor/ocp/ocp_cloud_summary_updater.py) to get the cluster ID that would have to be updated. 

## Acceptance Criteria

- [ ] `_get_ocp_cluster_id_for_provider` in the OCPCloudSummaryUpdater references the `report_period_id`
- [ ] `reporting_ocpinfrastructure_provider_map.sql` references the `report_period_id` instead of `cluster_id`

**Comment by jlalbertson** [comment]
Created Jira issue: https://issues.redhat.com/browse/COST-101, closing this issue.
