### ISSUE TITLE
No longer implicitly group by cluster on OpenShift APIs

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1368]
## User Story
As a user of cost management I want to see a single entry for a project, even if that project exists in multiple clusters, so that I can see a single cost for that project name.

At tech exchange, @chargio observed that it was confusing for customers to see the same project multiple times. If you have one project in three clusters, you want to see it as one single project in the UI.

## Assumptions
- Currently when grouping by node or project we implicitly group by cluster to give a breakdown by cluster. We want to stop doing this. 
- This is the method that adds the group by cluster: https://github.com/project-koku/koku/blob/master/koku/api/query_handler.py#L303
- This is a "quick fix" to improve the user experience, not necessarily a part of re-imagining the UX/UI.

## Acceptance Criteria

- [ ] The OpenShift APIs returns a single result for a project, even when the project exists in two or more clusters
- [ ] The previous implied group by can still be achieved with an explicit `group_by[cluster]` param

**Comment by lcouzens** [comment]
Verified
Commit: "c6ca9c8134ff24ef80ab9ce65a8d5449476f847e"
