### ISSUE TITLE
Move OpenShift on AWS special tag handling to occur first

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1370]
**Describe the bug**
When matching OpenShift on AWS we match to three special case tags `openshift_cluster`, `openshift_node` and `openshift_project`. Currently we're doing this matching after the broader tag matching. Because these special tags are more specific we should match them first. 

**To Reproduce**
1. Create nise data that has multiple OpenShift clusters associated with a single AWS account
2. Associate resources in both clusters and AWS using a specific tag (e.g. `environment: dev`)
3. Tag the associated AWS resource with `openshift_cluster` using and associated with only 1 of the clusters
4. Observe AWS cost get double counted

**Expected behavior**
Because the AWS resource has specified a specific cluster to associate to, the cost should only associate to that cluster. 

**Additional context**
We just need to switch the order of a few blocks of SQL to ensure the more specific matching happens first.

**Comment by maskarb** [comment]
On hold pending discussion around #1468.

**Comment by jlalbertson** [comment]
Moved to Jira: https://issues.redhat.com/browse/COST-101, closing issue.
