### ISSUE TITLE
Log an UUID in async tasks

### ISSUE THREAD

**Issue by werwty** [project-koku/koku#1373]
## User Story
As a developer I want to see the same uuid in the Celery task logs so I can trace the effect of a request all the way through the system.

Currently logged uuids are either generated in a task and have to be manually put into log statements:
https://github.com/project-koku/koku/blob/master/koku/masu/celery/tasks.py#L215
Or logs do not have an associated UUID. This makes keeping track of task logs difficult.

Celery supports signals that we could use to set a UUID when a task is kicked off and have it be included in every log statement in the task by default. 

Example of how Cloudigrade does it:
https://gitlab.com/cloudigrade/cloudigrade/blob/master/cloudigrade/config/celery.py#L38
https://gitlab.com/cloudigrade/cloudigrade/blob/master/cloudigrade/config/settings/base.py#L47

See: https://github.com/project-koku/koku/issues/1032 as a related issue

## Questions and Answers
- Q: Which original UUID do we want to start with? Cloudigrade starts with the request's UUID and creates a new UUID if it didn't start from a request.
- A: Instead of tracking the request UUID through the logs (although independently that would be good to see logged as well), we should try to track the `Async Task ID` through the logs from whatever Celery task likely spawned the current process.
- If some operation did not originate as a Celery task with an ID, then the initial UUID is generated and used consistently throughout.
- Possibly see also: https://docs.celeryproject.org/en/latest/userguide/tasks.html#bound-tasks

## Acceptance Criteria

- [ ] Verify that an UUID is generated when a task is kicked off and is included by default in task logs.
- [ ] Verify that this UUID is the same for any tasks kicked off by the original task.
- [ ] Verify that `log_uuid` (and any known manual logging of UUIDs) is removed from tasks, since it is no longer needed.
  - Best effort here. Do some grep/pattern matching searches, but we don't have to exhaustively prune the code.

**Comment by lcouzens** [comment]
Verified
Commit: e92a2ed6473fc26e13b932a0c0ab4c59a82215a1
