### ISSUE TITLE
Missing openapi spec entries

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1385]
**Describe the bug**
There is no spec for `/cloud-accounts/` [1] in the openapi.json file, and there's also missing PUT method specification for `/providers/<uuid>/` endpoint [2]

[1] https://github.com/project-koku/koku/issues/1284
[2] https://github.com/project-koku/koku/issues/864

**To Reproduce**
1. Go to `/v1/openapi.json`
2. See error

**Expected behavior**
Complete openapi spec

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox 70
 - Commit Hash from status endpoint: ef93a2b2a1d46e6badb3c1919555c8a4b633cb22

**Comment by chambridge** [comment]
Related to: https://github.com/project-koku/koku/issues/1337

**Comment by dchorvat1** [comment]
verified, 73391d32b0a76f05295f219d9f5c2b6542b96a60
