### ISSUE TITLE
Azure instance-types API: usage format

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1387]
Currently, the Azure instance-types API returns a single property for meta total `usage` Vs a property containing `value` and `units`.

This is effectively a duplicate or more specific use case of: https://github.com/project-koku/koku/issues/1360

![Screen Shot 2019-11-11 at 1 20 34 PM](https://user-images.githubusercontent.com/17481322/68610595-1dc80d00-0486-11ea-8bb9-9808e2350b76.png)

**Comment by infinitewarp** [comment]
Closing this in favor or https://github.com/project-koku/koku/issues/1360
