### ISSUE TITLE
OpenAPI spec for sources_status

### ISSUE THREAD

**Issue by nbon12** [project-koku/koku#1390]
## User Story
As a QA person, I want the sources_status to have an openapi spec to make it easier to generate the testing client. 
Related to Issue #1309
Related PRs: #1356 #1375 
Luke: "We have internal endpoint on koku-masu which we create a openapi spec for to make it easier to generate our client so we may want to do the same for this"
Doug: "yeah we probably should have one, even though it’s called internally
we could do it now or once we finalize the request/response conventions with the platform"

## Impacts
Sources client

## Assumptions
- This spec may change when request/response conventions are finalized with the platform

## API Details

http://localhost:4000/api/cost-management/v1/source_status/?source_id=1

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/PATCH/DELETE |
 | **Path** | /api/cost-management/v1/source_status/?source_id=X |

![Screen Shot 2019-11-11 at 5 00 52 PM](https://user-images.githubusercontent.com/17408265/68624463-e3219d00-04a4-11ea-927f-727c1a8355aa.png)

## UI Details
- None

## Acceptance Criteria

- [ ] An openapi spec is created for sources_status
- [ ]

**Comment by lcouzens** [comment]
Verified
Commit: "6bac6962d08f693740f8147c966bfdb5ce39a7c3"
