### ISSUE TITLE
Azure storage API: usage format

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1391]
Currently, the Azure storage API returns individual properties for meta total `count` and `count_units` Vs a single property containing `value` and `units`.

Note that the Azure instance-types API returns a single property containing `value` and `units`.

![Screen Shot 2019-11-12 at 9 37 26 AM](https://user-images.githubusercontent.com/17481322/68680793-4a386380-0530-11ea-98d0-5ab6543c996c.png)

**Comment by infinitewarp** [comment]
Closing in favor of https://github.com/project-koku/koku/issues/1360
