### ISSUE TITLE
Change delta to previous cost

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1395]
Note: This is a place holder for a "backlog review" discussion

As a user, I want to see the change in cost instead of a delta. We want to see the amount of money it was historically rather than show the difference.

![Screen Shot 2019-11-12 at 4 42 03 PM](https://user-images.githubusercontent.com/17481322/68713231-60174a00-056b-11ea-8c16-3b973f1868ce.png)

Month over month change: 
- If the cost had increase, show the amount it was previous month, plus percentage.
- If the cost had decrease, show the amount it was previous month, plus percentage
- If the previous month was nothing $0.00, so have a “- -” for the percentage and the line below say “$0.00 from Oct. 1st thru Oct. 5th”
- If the previous month was nothing $0.00, so have a “- -” for the percentage and the line below say “$0.00 from Oct. 1st thru Oct. 5th”
- If the previous month was null, then we would not show it at all and just show the previous month’s amount — API change needed!
- If we can show last month’s cost rather than the difference, that would be preferable. “Cost to date from previous month"
- On march 30th, is it OK that the previous month is from feb 1 - feb 28

**Comment by dlabrecq** [comment]
//cc @nlcwong @chargio

**Comment by chambridge** [comment]
Can't this just be calculated in the UI with the existing API?

**Comment by nlcwong** [comment]
Format: <dollar amount> for <date range>
e.g. "$1,445.96 for 1-20 Oct"

**Comment by chargio** [comment]
We can calculate it, but we want customers to use the API. We could do this in two phases, phase one we calculate it in the UI, phase II we add this to the response (and we keep the delta for compatibility).

**Comment by chambridge** [comment]
I disagree. If the user is already using the API subtracting one number from another seems like a simple step for them to take and I wouldn't think we would return the format above in the API because it is more like a translated string.

**Comment by dlabrecq** [comment]
When I created the issue, I didn't realize that the delta was cumulative for a specific date. That is, if the current date is Dec 4th, the delta represents Nov 1-4.

As a user of the API, the delta is all that is necessary. With that, we can choose how to display the information either way. If the delta changed, users no longer have the option.

That said, I believe the only thing we need from the API is:

- If the previous month was null, then we would not show it at all and just show the previous month’s amount.

The wording seems a little bit off? However, is there a distinction between $0.00 and null?

**Comment by dlabrecq** [comment]
When there is a provider, but no data has been collected, a null value may help the UI clarify what's shown below. In this case, the UI indicates no change over the previous month, but it's not clear why. Perhaps if the UI received null, we could potentially show something different?

![Screen Shot 2020-01-06 at 10 29 56 AM](https://user-images.githubusercontent.com/17481322/71856003-90cdb880-30b0-11ea-89a5-adfc974178e9.png)

**Comment by dlabrecq** [comment]
Noticed that the delta percentage returns null, when there is no data, but the delta value does not. Ideally, the delta value would be null as well.

![Screen Shot 2020-01-20 at 11 05 05 AM](https://user-images.githubusercontent.com/17481322/72744259-36862a80-3b7b-11ea-91b5-f43db0553502.png)

**Comment by chargio** [comment]
I agree. If the % is null the data should be null too

**Comment by adberglund** [comment]
A `null` delta percent indicates that no data is present in the prior time period the delta calculation is using.
