### ISSUE TITLE
Missing instance-type data for some dates in Azure api report

### ISSUE THREAD

**Issue by msager27** [project-koku/koku#1398]
**Describe the bug**
I'm querying the Azure instance-type report for 10 days of data with daily resolution and grouping by instance-type.  I'm using Nise to generate data.  The instance types generated are Standard_A0 and Standard_B2s.  In my report, I'm seeing both instance types for every date except one.  I've run this multiple times and have consistently seen this behavior, although not always for the same date.  The CSV files seem to have the proper data.

I'll provide what I have.  I've also discussed this with Doug and I think he's been able to recreate this behavior in his environment.

Note to devs: try loading the data here and check the database to ensure that each day actually has the expected data. If the files have that data, then it's likely a processing bug.

**To Reproduce**
1. Create 4 Azure-local providers
2. Generate Nise data
3. Ingest the data
4. Query the report, e.g. http://localhost:8000/api/cost-management/v1/reports/azure/instance-types/?filter[resolution]=daily&filter[time_scope_value]=-10&filter[time_scope_units]=day&group_by[instance_type]=*

**Expected behavior**
I'm expecting to see both instance types for every date based on what I'm seeing in the CSV files.  However, I'm not seeing one for Standard_A0 on 2019-11-06 (in a prior run, it was missing Standard_B2s for 2019-11-03).  I'll attach the CSV files.

**Screenshots**
![11-06-entry](https://user-images.githubusercontent.com/53917070/68720361-f2741980-057c-11ea-8aed-e6239b954be7.png)
![11-07-entry](https://user-images.githubusercontent.com/53917070/68720332-d96b6880-057c-11ea-8f6c-4d3cb99fe347.png)
![CSV-Standard_A0-grep-11-06](https://user-images.githubusercontent.com/53917070/68720341-e12b0d00-057c-11ea-827c-7ee5c28bd6e0.png)

**Context (please complete the following information):**
 - OS: Fedora 30

**Additional context**
[csv_files.tar.gz](https://github.com/project-koku/koku/files/3838753/csv_files.tar.gz)

**Comment by lcouzens** [comment]
Verified
Commit: e92a2ed6473fc26e13b932a0c0ab4c59a82215a1
