### ISSUE TITLE
504 error when deleting providers

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#1404]
**Describe the bug**
504 error when deleting providers

**To Reproduce**
1. Go to '/api/cost-management/v1/providers/'
2. Add provider
3. Go to `api/cost-management/v1/providers/uuid/`
4. Delete provider
5. See error

**Expected behavior**
Provider deletes with no errors

**Screenshots**
![Screenshot from 2019-11-14 13-52-54](https://user-images.githubusercontent.com/18352403/68862856-1b63ee00-06e6-11ea-9541-4e6252f5c044.png)

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: f5b85daf076592c6c98143bb9b6f18e6ed88c58e

**Additional context**
testing on CI

After a brief discussion with @adberglund we suspect it might have something to do with the new archive clean up on provider delete.

This is causing all automation to fall over on provider clean up

**Comment by infinitewarp** [comment]
I believe this is fixed by https://github.com/RedHatInsights/e2e-deploy/pull/837

After that PR merged and I waited for e2e to redeploy the new OpenShift deployment configs, I poked the API in CI, and things seem to be working normally again.

The requests I made (with some details truncated) to verify:
```
$ http https://ci.cloud.redhat.com/api/cost-management/v1/providers/ <<< '{
>     "name": "my great OCP potato",
>     "type": "OCP",
>     "authentication": {
>         "provider_resource_name": "my-great-ocp-potato-1"
>     },
>     "billing_source": {
>         "bucket": ""
>     }
> }'
HTTP/1.1 201 Created
...
x-rh-insights-request-id: 096255940f5d40de87fcf3aeb6cf87fd
...
    "name": "my great OCP potato",
    "type": "OCP",
    "uuid": "d5810962-d709-42f8-91b0-11bc77d71eff"
}
```
```
$ http delete https://ci.cloud.redhat.com/api/cost-management/v1/providers/d5810962-d709-42f8-91b0-11bc77d71eff/
HTTP/1.1 204 No Content
...
x-rh-insights-request-id: f0a17006041d431daddd96f8cfe009c5
```

**Comment by lcouzens** [comment]
Verified
Commit: a8a00c585888596881fc7f4e9d18c4c8042ec764
