### ISSUE TITLE
Create product manifest for product security consumption.

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1407]
## User Story
As a service developer, I want to be able to provide a manifest of the run-time dependencies in a machine readable fashion so that product security can review dependencies for any needed vulnerability remedeation.

## Impacts
Backend

## Implementation Details
Another application (python 3.6) has created a manifest  in the following fashion:
[Drift app - manifest creation](https://github.com/RedHatInsights/drift-backend/search?q=manifest&unscoped_q=manifest)

We can review and iterate as necessary. We would like perform this update as part of our `make requirements` target.

## Acceptance Criteria

- [ ] We produce a manifest file of dependencies that is consumable by product security.
- [ ] We fail travis builds if dependencies are changed but the manifest is not updated.

**Comment by lcouzens** [comment]
Verified.
