### ISSUE TITLE
Track access to Cost Managment AWS account S3 with Cloud Watch

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1414]
## User Story
As service developer, I want an audit trail of access to S3 data used to provide exports for customers use with BI tools so that tracking of any malicious actions can be logged and monitored.

This is required per our recent security evaluation checklist.

## Impacts
Account setup

## Implementation Details
Enable cloud watch (Free tier) to capture access to s3 buckets

## Acceptance Criteria

- [ ] Cloud watch is enabled and access (read, update, deletes) are logged for s3 buckets

**Comment by nbon12** [comment]
@chambridge which AWS account is cloudwatch to be enabled on? Could you link the security checklist that requires this? Is this for when the customer sets up their own AWS account, or for the Red Hat AWS account itself?

**Comment by nbon12** [comment]
Planning and Estimation:

- For this story, I plan to read the AWS CloudTrail Documentation to get the information required to enable CloudTrail.
- I plan to read the SQL Reference documentation to determine if that's needed, and then to implement it if so.
- The log format will be the default setting of CloudTrail, see https://docs.aws.amazon.com/AmazonS3/latest/dev/LogFormat.html
- I plan to enable Logging for one Amazon S3
- I plan to configure Metrics for the S3 bucket in the hccm-alias account to capture read,update, and delete operations that are performed on the S3 bucket. The logs should information about the actor, using out-of-the-box CloudWatch tooling.
- Logs are to be retained for X days (to be determined by @chambridge 
- I estimate at least a 5 day completion time window, any change to the scope of this project after this post will cause delays, any feedback and review comments will cause additional delays, up to 2 days per feedback comment.
- Logging will be enabled at all times, logs will be stored indefinitely; however if we want Logs to be deleted after a specified lifecycle, I estimate adding that feature will take 1 day.
- No CloudWatch alarms are to be set up during this story.
- Sharing log files between accounts is not 

CC: @jlalbertson , @kholdaway 
(the @mention should send an automated email to the above parties)

**Comment by nbon12** [comment]
@chambridge CloudTrail has been created: https://console.aws.amazon.com/s3/buckets/cost-management-cloudtrail-s3-audit/AWSLogs/589173575009/CloudTrail/?region=us-east-1

**Comment by nbon12** [comment]
Ready for QA @lcouzens 
Testing instructions:

1. Go to the AWS Management Console
2. Log in as hccm-alias, using your corporate AWS credentials.
3. Go to S3
4. Go to the bucket cost-management-cloudtrail-s3-audit
5. Observe the log files are present.

**Comment by nbon12** [comment]
Reviewed by @chambridge "looks fine. Feel free to put the issue in the QA column"

**Comment by lcouzens** [comment]
Verified
