### ISSUE TITLE
Use Server-Side Encryption with AWS KMS-Managed Keys for archiving S3 buckets

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1419]
## User Story
As a service developer, I want the service to encrypt the S3 buckets used for archiving data with KMS-Managed Keys so that our service is Information Security compliant.

## Impacts
Backend

## Details
Information Security compliance requires the use of our own encryption keys:
> Specifically, in case of AWS S3, the requirement is to use KMS managed encryption with keys

https://docs.aws.amazon.com/kms/latest/developerguide/services-s3.html

Our current AWS S3 buckets being used for customer data archival *do* have encryption enabled; however, they use AWS-managed keys. The crucial difference here is **who owns the keys**.

## Acceptance Criteria

- [ ] KMS encryption keys are setup
  - [ ] different keys exist for different environments (CI, QA, stage, prod)
  - [ ] if necessary, IDs/secrets/etc. needed for the keys have been shared with Andrew and Chris.
- [ ] S3 buckets are encrypted using KMS encryption keys
  - [ ] the default settings for new files are set to use the new keys
  - [ ] all existing files have been migrated to use the new keys
- [ ] Archived data is retrievable & readable by the customer
  - [ ] Verify by requesting a data export as a customer and retrieving and reading the files from the customer's bucket

**Comment by werwty** [comment]
-  KMS keys have been set up
![image](https://user-images.githubusercontent.com/6206134/70470409-f2dad400-1a98-11ea-8e4d-7729fe3831a0.png)

- S3 buckets are encrypted using KMS encryption keys
![image](https://user-images.githubusercontent.com/6206134/70470467-13a32980-1a99-11ea-8689-e7c559d9dcaa.png)

- Demo for 
> Verify by requesting a data export as a customer and retrieving and reading the files from the customer's bucket

https://asciinema.org/a/A5e5jFIyCdlIrrvZ4pbxV0Eci

**Comment by infinitewarp** [comment]
Looks good to me! @chambridge would you like to review before we close this issue?

**Comment by chambridge** [comment]
LGTM! I moved it to the QA pipeline.

Nice Job! 🏆

**Comment by lcouzens** [comment]
Verified
Commit: 8aaee11d1b0e33711660f0202f333440079a3acc
