### ISSUE TITLE
New billing source endpoint does not meet current path standards

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#1424]
**Describe the bug**
New billing source endpoint does not meet current path standards

**To Reproduce**
1. Go to `api/cost-management/v1/sources/billing_source/`

**Expected behavior**
`billing_source` should change to `billing-source` to be consistent with all our api paths

**Context (please complete the following information):**
 - Commit Hash from status endpoint: "1fc823b5bd5610de48bd9450c3ff7cb34e545c16"

**Additional context**
- This isn't actively breaking anything; we just want to be internally consistent.
- This might be resolved by other work that's currently also in-progress.
- Make sure any UI API calls are updated with this change.
- Make sure the platform UI code has been updated alongside this change so nothing breaks there!!

**THIS ISSUE IS ON HOLD UNTIL… @dccurtis says so; he will come back with some information.**

**Comment by dccurtis** [comment]
https://github.com/project-koku/koku/issues/1439 is opened which would deprecate this API

**Comment by maskarb** [comment]
#1548 removed the old sources endpoints.

**Comment by lcouzens** [comment]
Verified
