### ISSUE TITLE
Instance-type values display "tag": null rather than "tag": "no-tag" for no-tag grouping

### ISSUE THREAD

**Issue by msager27** [project-koku/koku#1429]
**Describe the bug**
I have an AWS tag "app".  My query is grouping by or:tag:app=*:

http://localhost:8000/api/cost-management/v1/reports/aws/instance-types/?group_by[or:tag:app]=*

Here's an excerpt from the output.  Under instance_types values, the report displays "app": null.  I expected to see "app": "no-app".

    "data": [
        {
            "date": "2019-11-11",
            "apps": [
                {
                    "app": "no-app",
                    "instance_types": [
                        {
                            "instance_type": "db.t3.medium",
                            "values": [
                                {
                                    "app": null,
                                    "instance_type": "db.t3.medium",
                                    "date": "2019-11-11",
                                    "cost": {
                                        "value": 3.456,
                                        "units": "USD"
                                    },

               .....
               .....
               .....                

                    "app": "b5",
                    "instance_types": [
                        {
                            "instance_type": "db.t3.large",
                            "values": [
                                {
                                    "app": "b5",
                                    "instance_type": "db.t3.large",
                                    "date": "2019-11-11",
                                    "cost": {
                                        "value": 3.48,
                                        "units": "USD"
                                    },

I see the same behavior for Azure instance types.

**To Reproduce**
1. Create static report files with a mix of tagged and untagged services.
2. Generate data with Nise
3. Ingest data
4. Query instance-types report.  Sample URL: http://localhost:8000/api/cost-management/v1/reports/aws/instance-types/?group_by[or:tag:app]=*

**Expected behavior**
I expected to see "app": "no-app" in the instance_types values list

**Screenshots**
![Screenshot from 2019-11-20 11-59-39](https://user-images.githubusercontent.com/53917070/69260109-573aff80-0b8d-11ea-8304-79fe7e667931.png)

**Context (please complete the following information):**
 - OS: Fedora 30

**Additional context**

**Comment by dchorvat1** [comment]
verified, 082381280223bd331d4a25f4e52a7489f9d24d35
