### ISSUE TITLE
Not seeing no-tag grouping for OpenShift reports

### ISSUE THREAD

**Issue by msager27** [project-koku/koku#1436]
**Describe the bug**
I have four OpenShift providers.  I'm using Nise to generate data.  I have the tag label_qe:rock in two of the four static files.  When I run this query:

http://localhost:8000/api/cost-management/v1/reports/openshift/costs/?group_by[or:tag:qe]=*&filter[resolution]=monthly&filter[time_scope_value]=-1&filter[time_scope_units]=month

I don't see a no-qe grouping in the output.

I ran this by Andrew to make sure my static files looked correct and he didn't see any issues with them, so raising this issue.  I'll attach the static files and a screenshot of the output.

**To Reproduce**
1. Create static report files with a mix of tagged and untagged services.
2. Generate data with Nise
3. Ingest data
4. Query OpenShift report.  Sample URL: http://localhost:8000/api/cost-management/v1/reports/openshift/costs/?group_by[or:tag:qe]=*&filter[resolution]=monthly&filter[time_scope_value]=-1&filter[time_scope_units]=month

**Expected behavior**
I expected to see a no-qe grouping in the output.

**Screenshots**
![Screenshot from 2019-11-21 10-55-19](https://user-images.githubusercontent.com/53917070/69354025-78632500-0c4d-11ea-8683-6aedf21f3192.png)

**Context (please complete the following information):**
 - OS: Fedora 30
 - Browser: Chrome

[static_files.tar.gz](https://github.com/project-koku/koku/files/3875530/static_files.tar.gz)

**Comment by lcouzens** [comment]
Verified
Commit: 6c7f0032ed1f85d12e83d1141f90482c4be82d33
