### ISSUE TITLE
Consolidate Sources API endpoints and enable PATCH

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#1439]
## User Story
As user I want to have a single API where I can and do limited editing on my cost management sources.  I want to be able to edit the cost management source `authentication` and `billing_source` values.  These values are not stored within the Platform Sources backend so they need to be editable via this API so they can be set by the UI.  The `sources-status` API should also be consolidated to the new API with an action method on a particular source instance.

## Impacts
API, UI, Docs

## Assumptions
- Existing `billing_source`, `authentication`, and `source-status` APIs continue to work until the frontend and test automation can be moved to the new API.  Once they are transitioned we can remove the old API endpoints.

## API Details
`GET` Example
```
GET /api/cost-management/v1/sources/
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Content-Type: application/json
Expires: Thu, 21 Nov 2019 21:28:08 GMT
Vary: Accept

{
    "meta": {
        "count": 1
    },
    "links": {
        "first": "/api/cost-management/v1/sources/?limit=10&offset=0",
        "next": null,
        "previous": null,
        "last": "/api/cost-management/v1/sources/?limit=10&offset=0"
    },
    "data": [
        {
            "source_id": 1,
            "name": "Test Azure Source",
            "source_type": "AZURE",
            "authentication": {
                "credentials": {
                    "client_id": "0f10dbdf-be25-452d-871b-4e32d19a4249",
                    "tenant_id": "3be09d48-9d77-468c-99ba-36be84238834",
                    "client_secret": "b6f61b57-bc7f-46be-a019-66dccd8b7dfe",
                    "subscription_id": "3b63027f-af79-4ddd-b6f2-e7b0ac6e7546"
                }
            },
            "billing_source": {
                "data_source": {
                    "resource_group": "TESTRG",
                    "storage_account": "mysa1"
                }
            },
            "koku_uuid": "fcb45f97-7d60-43e1-8574-596716570dcb",
            "source_uuid": "fcb45f97-7d60-43e1-8574-596716570dcb"
        }
    ]
}
```
`GET` specific source id
```
GET /api/cost-management/v1/sources/1/
HTTP 200 OK
Allow: GET, PATCH, HEAD, OPTIONS
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Content-Type: application/json
Expires: Thu, 21 Nov 2019 21:29:38 GMT
Vary: Accept

{
    "source_id": 1,
    "name": "Test Azure Source",
    "source_type": "AZURE",
    "authentication": {
        "credentials": {
            "client_id": "0f10dbdf-be25-452d-871b-4e32d19a4249",
            "tenant_id": "3be09d48-9d77-468c-99ba-36be84238834",
            "client_secret": "b6f61b57-bc7f-46be-a019-66dccd8b7dfe",
            "subscription_id": "3b63027f-af79-4ddd-b6f2-e7b0ac6e7546"
        }
    },
    "billing_source": {
        "data_source": {
            "resource_group": "TESTRG",
            "storage_account": "mysa1"
        }
    },
    "koku_uuid": "fcb45f97-7d60-43e1-8574-596716570dcb",
    "source_uuid": "fcb45f97-7d60-43e1-8574-596716570dcb"
}
```

`GET` status
```
GET /api/cost-management/v1/sources/1/status/
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "availability_status": "available",
    "availability_status_error": ""
}
```

`PATCH /api/cost-management/v1/sources/1/` with json data `{"authentication": {"credentials": {"subscription_id": "3b63027f-af79-4ddd-b6f2-e7b0ac6e7546"}}, "billing_source": {"data_source": {"resource_group": "TESTRG", "storage_account": "mysa1"}}}`

`PATCH` for AWS source json_data `{"billing_source": {"bucket": "cost-usage-bucket"}}`
## Acceptance Criteria

- [ ] All source-type checks continue to work with new combined API as they did with `billing_source` and `authentication`
- [ ] All provider types can be created with new combined API.
- [ ] `/status` action endpoint is only accessible on the sources-client, not the koku-api
- [ ] PATCH only works for the billing_source and authentication fields.  All other fields must be updated via Platform Sources

**Comment by lcouzens** [comment]
Verified
Commit: 88f941102c430aa69dd11fda69962b88ef27782a
