### ISSUE TITLE
Platform sources delete not passing into Cost Management

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1440]
**Describe the bug**
After deleting a source from platform sources, Cost Management still showed the provider and was failing to delete it, with 500 error.
@adberglund found out that there probably wasn't a proper response to a delete event from Sources and Cost Management never deleted the entry in `api_sources` table. After manually resolving this, I could remove the provider from Cost Management `/providers/` endpoint.

**To Reproduce**
1. Add a provider in platform sources
2. Delete the provider
3. See the provider in Cost Management

**Expected behavior**
Correct provider deletion

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox 
 - Commit Hash from status endpoint: 3e267cd4f05dedb3d5fd65b4fe20d4e6077146de

**Additional context**
This is probably not 100% reproducible, as I have encountered this only once. Raising this bug so we can track this if it happens again.

**Comment by dccurtis** [comment]
I noticed that the provider encountering 403 errors was being deleted with this authentication header.  

```
➜  ~ echo -n 'eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjYwODk3MTkifX0=' | base64 --decode
{"identity":{"account_number":"6089719"}}%                                                                                                                                                                                                                                                                                                ➜  ~ 
```

That explains the 403, but the next question is what is causing these malformed headers.  I've noticed a few sources that I created via the Platform Sources UI with similarly malformed headers (different account number).  Need to investigate this further.

**Comment by chambridge** [comment]
@dccurtis I don't get the percent:
```
$ echo -n 'eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjYwODk3MTkifX0=' | base64 --decode
{"identity":{"account_number":"6089719"}
```
strange

**Comment by infinitewarp** [comment]
Moving this to QA to verify that this _may_ have recently been fixed.

**Comment by dchorvat1** [comment]
verified, 082381280223bd331d4a25f4e52a7489f9d24d35
