### ISSUE TITLE
e2e-deploy.sh does not work on MacOS

### ISSUE THREAD

**Issue by nbon12** [project-koku/koku#1452]
## User Story
As a developer I want e2e-deploy.sh to work on MacOS.
The e2e-deploy.sh script requires `iqe` to be installed in the PATH
docker-compose users use `make docker-iqe-smokes-tests` for iqe, and it isn't in PATH.
Also `readlink -f` is different on Mac than Fedora.

- Update dev documentation for this script to specify requirements (oc, ocdeployer, iqe)
- Do a `which` check for dependencies
- Update script for Mac OR document requirement for Mac users to get `coreutils` and alias

## Impacts
Mac Developers

## Role
Developer

## Assumptions
- e2e-deploy.sh works on Fedora
- e2e-deploy.sh required IQE to be installed locally
- e2e-deploy.sh required oc to be installed locally
- e2e-deploy.sh required ocdeployer to be installed locally

## Acceptance Criteria
- [ ] e2e-deploy.sh works on Mac

**Comment by nbon12** [comment]
Example of changes https://github.com/project-koku/koku/tree/nbon12-patch-e2e-secrets.yml

**Comment by blentz** [comment]
As discussed in the retro for Sprint 36, this will require Mac users to `brew install coreutils` and set up their environment to align with the deployment target environment of OSD on RHEL.

In this case, the script uses the GNU `readlink` utility, which has a `-f` flag that the BSD version lacks.
