### ISSUE TITLE
provider update allows us to change provider type

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1458]
**Describe the bug**
PUT request to `/providers/` allows us to change provider types, for example, we can change OCP provider to an AWS one.
After briefly discussing this with @dccurtis and @lcouzens, it was said that this should be disabled.

**To Reproduce**
1. Go to `/providers/`, add an AWS provider
2. Update the provider to an OCP provider (the ocp provider input must be valid)
3. See that the provider changed to OCP

**Expected behavior**
400 bad request

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox 70
 - Commit Hash from status endpoint: 5f65d324af3f801b7f2ee6f20f7a6da5ba6162d7

**Additional context**
I tested this with AWS provider that had some Nise data in it, updated it to OCP, the data wasn't showing in the provider anymore, then I uploaded OCP data, which ingested/summarized correctly, so at first glance, this does not cause any errors or corrupt data.

**Comment by lcouzens** [comment]
Verified
Commit: cd2bf064b7ef440cd6f629d5d6654342e3468980
