### ISSUE TITLE
Update OpenAPI YAML to pass platform requirement check

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1463]
## User Story
As a citizen of the Insights Platform I would like to adhere to the API requirements so that all users have a consistent and reliable experience with APIs.

## Assumptions
- We are largely in compliance now, we just need to update our servers section to include c.rh.c
- The following snippet is from the approval app, showing that we can have multiple entries

```
"servers": [
        {
            "url": "https://cloud.redhat.com/{basePath}",
            "description": "Production Server",
            "variables": {
                "basePath": {
                    "default": "/api/approval/v1.0"
                }
            }
        },
        {
            "url": "http://localhost:{port}/{basePath}",
            "description": "Development Server",
            "variables": {
                "port": {
                    "default": "3000"
                },
                "basePath": {
                    "default": "/api/approval/v1.0"
                }
            }
        }
    ]
```

## Acceptance Criteria

- [ ] Our OpenAPI yaml servers section has a production, CI, QA, and localhost entry

**Comment by dchorvat1** [comment]
verified, 082381280223bd331d4a25f4e52a7489f9d24d35
