### ISSUE TITLE
Consolidate global variable references to provider types

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1464]
## User Story
As a developer I want a single source of truth for the value for provider type so that any change is automatically propagated through the codebase. 

## Assumptions
- The Provider model seems like a good place to host provider types (See https://github.com/project-koku/koku/blob/master/koku/api/provider/models.py#L107-L141)
- We need to convert masu global variables and any other provider type references not using those defined in the Provider model over to using the Provider model.

## Acceptance Criteria

- [ ] All other global variables referencing provider type are removed. 
- [ ] All provider type references use the provider model

**Comment by lcouzens** [comment]
Verified
Commit: 712a742a78b0c0593169c8a8266f4392603477be
