### ISSUE TITLE
ProviderManager should check the infrastructure id on the providers table

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1466]
## User Story
As a providers API user I want the API to return results as quickly and efficiently as possible so that I can make quick use of the information. 

## Assumptions
- Right now we check the OCP on AWS table (we query that table and get a group by; if that table is large, the operation may take a very long time) which is not compatible with OpenShift on Azure or future providers.
- We recently introduced the concept of infrastructure on the providers table which can be queried directly to show the infrastructure type independent of cloud provider
  - This value is pre-computed and should be much faster to query.
  - https://github.com/project-koku/koku/blob/master/koku/api/provider/models.py#L163 
  - https://github.com/project-koku/koku/blob/master/koku/api/provider/models.py#L274

## Acceptance Criteria

- [ ] ProviderManager now accesses the information in the infrastructure map to show infrastructure_type

**Comment by lcouzens** [comment]
Verified
