### ISSUE TITLE
group_by tag: 400 error

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1473]
**Describe the bug**
The UI encounters a 400 error when attempting to use group_by with multiple tags.

<img width="574" alt="Screen Shot 2019-12-03 at 9 52 00 AM" src="https://user-images.githubusercontent.com/17481322/70061940-23130600-15b3-11ea-880e-c5f4a5aec694.png">

**To Reproduce**

The following URLs all fail. Doesn't seem to matter if we use ":or" or not.

/v1/reports/aws/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&**group_by[or:tag:environment]=*&group_by[tag]=prod**&order_by[cost]=desc

/v1/reports/aws/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&**group_by[or:tag:environment]=*&group_by[or:tag]=prod**&order_by[cost]=desc

/v1/reports/aws/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&**group_by[tag:environment]=*&group_by[tag]=prod**&order_by[cost]=desc

**Expected behavior**
We should not receive an error when using group_by with multiple tags. 

**Screenshots**
<img width="1056" alt="Screen Shot 2019-12-03 at 9 58 42 AM" src="https://user-images.githubusercontent.com/17481322/70062170-89982400-15b3-11ea-98ca-d67725f02d62.png">

**Comment by lcouzens** [comment]
@dlabrecq Are you not missing the Tag key? For example: group_by[tag:environment]=prod

so you want this:

api/cost-management/v1/reports/aws/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[tag:environment]=*&group_by[tag:environment]=prod&order_by[cost]=desc

**Comment by dlabrecq** [comment]
Ah, I believe you're correct. This must have broke when the ":or" was introduced. We'll fix that in the UI then.
