### ISSUE TITLE
centos7 ModuleNotFoundError: No module named 'psycopg2'

### ISSUE THREAD

**Issue by ptrnull** [project-koku/koku#1477]
**Describe the bug**
An error rises when trying to: pipenv run make run-migrations

  File "/root/.local/share/virtualenvs/koku-MctNmxCl/lib/python3.6/site-packages/tenant_schemas/models.py", line 4, in <module>
    from tenant_schemas.postgresql_backend.base import _check_schema_name
  File "/root/.local/share/virtualenvs/koku-MctNmxCl/lib/python3.6/site-packages/tenant_schemas/postgresql_backend/base.py", line 3, in <module>
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'

**To Reproduce**
1. follow the step for installing koku and when running the migrations it crashes.

**Expected behavior**
Ends fine and the migrations are loaded.

**Screenshots**

**Context (please complete the following information):**
 - OS: CentOS Linux release 7.6.1810 (Core) 

**Additional context**
A possible solution is to add the following packages under the [dev-packages] section in the Pipfile:
psycopg2 = "==2.8.4"
psycopg2-binary = "==2.8.4"

**Comment by maskarb** [comment]
@ptrnull I am not able to reproduce this error.

It's a strange error because the Pipfile.lock does contain `psycopg2-binary`, so it should have been installed when `pipenv install` was called.

I suggest remove the pipenv environment,`git pull` the repo, and install again. Based on the error message, it seems that the `pipenv install` did not complete the installation successfully.

**Comment by ptrnull** [comment]
Hello @maskarb , I think it's not about the `psycopg2-binary`, in my case the error complains about the ` ModuleNotFoundError: No module named 'psycopg2'` here what is missing is the psycopg2 python package.

And about the Pipfile and Pipfile.lock, I didn't know exactly the meaning of each (get used to requirements.txt) so I did a little research ending in https://stackoverflow.com/questions/46330327/please-explain-the-usage-of-pipfile-and-pipfile-lock
The summary:
```
The Pipfile file is intended to specify packages requirements for your Python application or library, both to development and execution. 

The Pipfile.lock is intended to specify, based on the packages present in Pipfile, which specific version of those should be used, avoiding the risks of automatically upgrading packages that depend upon each other and breaking your project dependency tree.
```
I think the required dependencies should be added into the Pipfile, the Pipfile.lock should include the specific version for freeze of the required packages indicated in the Pipfile.

**Comment by adberglund** [comment]
@ptrnull The difference here is that pyscopg2 is a dependency of package we *do* list in our Pipfile (Django). We don't explicitly require psycopg2 in our code base. The Pipfile.lock will flatten your dependency tree for you and show you every single package you need. Also if you `pipenv install` psycopg2 should be installed as a depencency of Django. If that's not happening there's probably another error and without the full log of running `pipenv install` or `pipenv install --dev` I can't say what that is. That said, until recently we were deploying our application on Centos 7 so we do know it can work there.

**Comment by ptrnull** [comment]
Hey @adberglund thank you for answering, I have trying to replicate again the issue since it happened to me 2 times the same day and I couldn't replicate it. Looks like was something punctual, sorry to bother you and @maskarb with the issue.
