### ISSUE TITLE
Ocp on Azure tagging endpoint missing from openapi spec

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#1487]
**Describe the bug**
Ocp on Azure tagging endpoint missing from openapi spec

**To Reproduce**
1. Go to api/cost-management/v1/openapi.json
2. See Openshift-on-AZURE tags missing from spec

**Expected behavior**
Expect to have Openshift-on-AZURE tags implemented in the spec similar to that of Openshift-on-AWS tags

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: 776278675649b0f439bc4afce28482564df825cf

**Additional context**
QE use the spec to generate our testing client.

**Comment by dchorvat1** [comment]
verified, 082381280223bd331d4a25f4e52a7489f9d24d35
