### ISSUE TITLE
Remove old sources APIs once frontend and QE have moved to new API

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#1532]
https://github.com/project-koku/koku/pull/1481 introduced a new Sources API to allow for the user (UI wizard) to set the cost specific bits related to billing_source and authentication.

Once QE and the frontend moves to the new API we should remove the `/billing_source` and `/authentication` APIs (including Koku-api proxy and sources-client).

Koku API: openapi spec entries as well as all view code.
The APIs to remove are: 
https://github.com/project-koku/koku/blob/5f8881905ce93860f0016712434116db8a2753f3/docs/source/specs/openapi.json#L2178

https://github.com/project-koku/koku/blob/5f8881905ce93860f0016712434116db8a2753f3/docs/source/specs/openapi.json#L2225

Sources Client
https://github.com/project-koku/koku/blob/master/koku/sources/api/authentication.py

https://github.com/project-koku/koku/blob/master/koku/sources/api/billing_source.py

@rvsia @boaz0 @lcouzens can be consulted regarding the progress of the API migration.

**Comment by lcouzens** [comment]
Verified
Commit: 87f7d49b9ff4ebcc58f44ec21b4f12375303c8b1
