### ISSUE TITLE
Provide data output in CSV or JSON output

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#154]
## User Story
As a user, I want to be able to download the data used in a chart as a CSV or JSON file so that I can reuse it in external tools (Excel, Jasper Reports, etc).

## Impacts
API, UI, Docs

## Role
User

## Assumptions
The user will get the data in used to comprised the chart from the API in addition to any data they may have “hidden” based on any interactive selections in the UI.

## API Details

Add support for `media_type = 'text/csv'`
http://www.django-rest-framework.org/api-guide/renderers/#custom-renderers
https://github.com/mjumbewu/django-rest-framework-csv

## UI Details
https://github.com/project-koku/koku-ui/issues/21

## Acceptance Criteria

- [ ] Verify that a chart data can be downloaded from the user interface dashboard and reflects the same chart data seen in the dashboard.

**Comment by LandoCalrizzian** [comment]
VERIFIED. Passing the header 'Accept: text/csv' resulted in the report api returning csv data instead of json
