### ISSUE TITLE
Provider local migrations should be included, but only optionally available via API

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1544]
## User Story
As a developer,  we need local provider migrations available so that we can test without all cloud provider scaffolding but those provider types should be limited to only a development mode.

## Impacts
API

## Role
Developer

## Implementation Details
Serializers will be used to control whether local provider types are available using the *DEVELOPMENT=TRUE* environment variable

## Acceptance Criteria

- [ ] In DEVELOPMENT=True mode allow local provider types via the serializer
- [ ] In DEVELOPMENT=False mode local provider types will raise an error.
- [ ] The migrations for local providers should always be there and no longer controlled by the DEBUG variable.

**Comment by lcouzens** [comment]
Verified
Commit: 87f7d49b9ff4ebcc58f44ec21b4f12375303c8b1
