### ISSUE TITLE
Squash migrations to date

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1549]
## User Story
As developer, I want to squash migrations so that database migrations for the service across all tenants and locally for tests run faster.

The caveat is that we need to run through the result with a fine toothed comb to make sure we remove all the intermediate steps from older migrations that are time consuming but don't actually get us to the current state of the database.

## Impacts
Database

## Role
Developer

## Assumptions
- Its safe to squash the migrations

## Implementation Details
https://docs.djangoproject.com/en/3.0/topics/migrations/#migration-squashing

This should be done for all django apps.

## Acceptance Criteria

- [x] Unit test still run successfully
- [x] Database schemas are correct

## QA/QE Testing

- [ ] All unit tests run successfully in QA/QE
- [ ] Changes are safely applied to existing DB
- [ ] Changes are safely applied to new DB (new account)
- [ ] e2e testing passes

**Comment by nbon12** [comment]
Is it important to keep at least some of the more recent migrations in case of needing to roll back a more-recent change?

**Comment by Red-HAP** [comment]
As django migrations grow, it may be wise to discuss alternatives to setting up a development database for testing and development. There may be alternatives that will provide faster database init, but it comes with its own issues.

**Comment by Red-HAP** [comment]
I've been fighting with the django optimization optimizer for hours and the only conclusion I can come up with is to manually re-order and optimize the entire migration file for reporting migrations. The django optimizer was only combining 4 of the 300+ steps which is basically no optimization. I've singled out that file first as it is the one with the most steps and the most create/drop/create steps and I'm hoping I can get the most bang for the buck working on that one.

**Comment by Red-HAP** [comment]
Getting help from Andrew after 4th attempt is running, but there are errors.

**Comment by Red-HAP** [comment]
Made significant progress. Want to run one more test before submission

**Comment by Red-HAP** [comment]
Merged after 2 reviews.

**Comment by lcouzens** [comment]
Verified
