### ISSUE TITLE
Azure sources failed due to "Missing credentials key"

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku#1557]
**Describe the bug**
During the creation process of a new Azure source for cost management, patching the source with billing_source and authentication fails with the following response body:

```
{"errors":[{"detail":"Missing credentials key","source":"detail","status":400}]}
```

**To Reproduce**
1. Go to sources
2. Click on 'Add a source'
3. Create azure-cost management source

**Expected behavior**
A new source is created successfully.

**Screenshots**
![f1](https://user-images.githubusercontent.com/2453279/71008435-467c9b80-20f1-11ea-9f35-7963a8467d32.png)

![f2](https://user-images.githubusercontent.com/2453279/71008668-a96e3280-20f1-11ea-8233-ccab61e0aa05.png)

Looking into it more - it seems like the problem is coming from this part: https://github.com/project-koku/koku/pull/1481/files#diff-5ec5c4c35eb2bbb57833137a16bf1ab6R102

What is confusing is that the kafka listener does push those values here: https://github.com/project-koku/koku/blob/0d73db81a2940b942bbeaa4da02765e02cbf9e22/koku/sources/kafka_listener.py#L217

Am I missing something?

// @dccurtis can you look at this please?
//cc @rvsia

**Comment by boaz0** [comment]
So I think my guess was right. The Kafka listener is waiting on sources authentication creation event and these adds credentials under authentication.

The flow:

POST https://ci.foo.redhat.com:1337/api/sources/v1.0/sources
request
```
{"name":"boaz01","source_type_id":"8"}
```
```
{"created_at":"2019-12-17T16:48:21Z","id":"1261","name":"boaz01","source_type_id":"8","uid":"b7555865-055d-475e-9a42-4330c543d599","updated_at":"2019-12-17T16:48:21Z","tenant":"1460290"}
```

POST https://ci.foo.redhat.com:1337/api/sources/v1.0/endpoints
request
```
{"role":"azure","default":true,"source_id":"1261"}
```
response
```
{"created_at":"2019-12-17T16:48:23Z","default":true,"id":"835","role":"azure","source_id":"1261","updated_at":"2019-12-17T16:48:23Z","tenant":"1460290"}
```

POST https://ci.foo.redhat.com:1337/api/sources/v1.0/applications
request
```
{"application_type_id":"2","source_id":"1261"}
```
response
```
{"application_type_id":"2","created_at":"2019-12-17T16:48:24Z","id":"794","source_id":"1261","updated_at":"2019-12-17T16:48:24Z","tenant":"1460290"}
```

POST https://ci.foo.redhat.com:1337/api/sources/v1.0/authentications
request
```
{"authentication":{"credentials":{"subscription_id":"boaz01"}},"billing_source":{"data_source":{"resource_group":"boaz01","storage_account":"boaz01"}}}
```
response
```
{"authentication":{"credentials":{"subscription_id":"boaz01"}},"billing_source":{"data_source":{"resource_group":"boaz01","storage_account":"boaz01"}}}
```

(checking that source exists on the cost management side)
GET https://ci.foo.redhat.com:1337/api/cost-management/v1/sources/1261/ 
response
```
{"source_id":1261,"name":"boaz01","source_type":"AZURE","authentication":{"credentials":{"client_id":"boaz01","tenant_id":"boaz01","client_secret":"boaz01"}},"billing_source":{},"koku_uuid":null,"source_uuid":"b7555865-055d-475e-9a42-4330c543d599"}
```

PATCH https://ci.foo.redhat.com:1337/api/cost-management/v1/sources/1261/
request
```
{"authentication":{"credentials":{"subscription_id":"boaz01"}},"billing_source":{"data_source":{"resource_group":"boaz01","storage_account":"boaz01"}}}
```
response
```
{"source_id":1261,"name":"boaz01","source_type":"AZURE","authentication":{"credentials":{"client_id":"boaz01","tenant_id":"boaz01","client_secret":"boaz01","subscription_id":"boaz01"}},"billing_source":{"data_source":{"resource_group":"boaz01","storage_account":"boaz01"}},"koku_uuid":null,"source_uuid":"b7555865-055d-475e-9a42-4330c543d599"}
```

**Comment by boaz0** [comment]
OK, after speaking with @rvsia 

We thought about moving the PATCH request to the end but there is no way we can relay that by the time we update the source on the cost management side "credentials" will be in the source.

We believe that either the assertion of `credentials exists` should be removed or the instance will be initialized with credentials as empty object - in order to fix this problem. 

What do you think?

//cc @dccurtis @maskarb 

Thanks.

**Comment by lcouzens** [comment]
Verified
Commit: 558ce56cb6a82cfd22bd8a51965e788b47427eb9
