### ISSUE TITLE
Cost per service for current month vs. last month

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#158]
## User Story
As a user, I want to be able to see my Cost by Service for the current month in comparison to the last month so that I can understand my service cost breakdown month-to-month.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- The user can only view cost data for accounts that are visible to them via the AWS organization.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/costs/ |
 | **Query Params** | ?filter[time_scope_value]=-1&group_by[service]=*&filter[time_scope_units]=month&filter[resolution]=monthly |
 **Response**:
```
{
    "group_by": {
        "service": [
            "*"
        ]
    },
    "filter": {
        "resolution": "monthly",
        "time_scope_value": "-1",
        "time_scope_units": "month"
    },
    "data": [
        {
            "2018-06": [
                {
                    "Storage Snapshot": [
                        {
                            "date": "2018-06",
                            "units": "USD",
                            "service": "Storage Snapshot",
                            "total": 73524.680680838
                        }
                    ]
                },
                {
                    "Storage": [
                        {
                            "date": "2018-06",
                            "units": "USD",
                            "service": "Storage",
                            "total": 8446.981846119
                        }
                    ]
                },
                {
                    "Compute Instance": [
                        {
                            "date": "2018-06",
                            "units": "USD",
                            "service": "Compute Instance",
                            "total": 7255.689
                        }
                    ]
                },
                {
                    "Data Transfer": [
                        {
                            "date": "2018-06",
                            "units": "USD",
                            "service": "Data Transfer",
                            "total": 2.174076039
                        }
                    ]
                }
            ]
        }
    ],
    "total": {
        "value": 89229.525602996,
        "units": "USD"
    }
}
```

## UI Details
UI will provide a chart/table with the costs broken down by Service for the current month in comparison to the last month.

## Acceptance Criteria

- [ ] The user is able to see the costs for Service but only for the accounts visible via AWS organization for the current month in comparison to the last month
- [ ] The API and UI work gracefully for cases when has there is no usage data
- [ ] For multiple accounts it should aggregate across across accounts and then separate by service.

**Comment by LandoCalrizzian** [comment]
Verified that koku is reporting service charges correctly by month
