### ISSUE TITLE
group_by tag will not match no-environment (others)

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1596]
**Describe the bug**
Users want the ability to filter tag keys by value. In the UI details page; for example, I may want to group_by tag key "environment", but show only the "others" row (i.e., represented by the "no-environment" tag name).

It turns out that `group_by[and:tag:environment]=dev` works, but `group_by[and:tag:environment]=no-environment` will not match any data.

**To Reproduce**

1. Go to: `/api/cost-management/v1/reports/openshift/infrastructures/all/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[and:tag:environment]=*&order_by[cost]=desc`

2. See "dev" and "no-environment" in the available data

3. Go to: `/api/cost-management/v1/reports/openshift/infrastructures/all/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[and:tag:environment]=no-environment&order_by[cost]=desc`

3. See empty data

**Expected behavior**
Expecting `group_by[and:tag:environment]=no-environment` and `group_by[or:tag:environment]=no-environment` to return matching data.

Likewise, `group_by[and:tag:environment]=no` should return a partial value match.

**Screenshots**
Want to filter this table
![Screen Shot 2020-01-08 at 8 18 35 PM](https://user-images.githubusercontent.com/17481322/72029494-18076180-3254-11ea-8fa5-6171eaa12696.png)

No match 
![Screen Shot 2020-01-08 at 8 20 45 PM](https://user-images.githubusercontent.com/17481322/72029607-76344480-3254-11ea-8478-0e6cd5457631.png)

**Comment by chambridge** [comment]
So I agree we could support the capability for a user to filter down to items that don't have the tag key (i.e. the other group), but I disagree in supporting `no` should lead to partial matching the other group.

**Comment by blentz** [comment]
I'd like to suggest an alternative syntax for this. I have two ideas to suggest:

1. We add a `not:` keyword that does what you'd expect. So, getting all entries without an environment tag would be: `&group_by[not:environment]=*`

2. We could use the keyword `others` for this kind of query. So, it would be: `&group_by[environment]=others`.

I personally prefer option 1, but I think option 2 is workable.

**Comment by chambridge** [comment]
I agree with @blentz around the concept of supporting `not:`. This mirrors some of my previous passing comments. I had suggested `null` vs. `others` as the alternative.

The only problem is the complexity involved with supporting `not` at this point. Currently we support a comma separated list as an input `group_by[environment]=dev,qa` and it implicitly is an `or`. Then we support explicit `group_by[and:environment]=dev,qa` and `group_by[or:environment]=dev,qa`. Is `group_by[not:environment]=dev,qa` an implicit `or`, are we going to start handling `group_by[not:and:environment]=dev,qa` and `group_by[not:or:environment]=dev,qa`? Then the complexity of mixed groupings like `?group_by[not:environment]=dev,qa&group_by[or:environment]=prod` (not that this is a good query, but we'd need to handle it).  I'm not suggesting that eventually we don't want to support complex logic like this, but I feel like it might be a bit much for enabling this feature.

**Comment by dlabrecq** [comment]
We want "others" to always be included in the data displayed in the details table. Would using `not:` require two separate API calls to achieve what we have in the UI today?

If we use a special keyword, I would prefer to see the API look for the "no-" prefix that was provided to the UI. Otherwise, the UI would need to hard code that. The UI would need to determine when to ask for "others" Vs "no", "no-env", "no-environment", etc.

**Comment by adberglund** [comment]
Okay I'm applying the needs discussion label so we can talk through this more.

**Comment by blentz** [comment]
We held a design discussion. 

Here's the working doc from that meeting: https://docs.google.com/document/d/1qE3BgZF7-3XhykFtcwwPXJJnQoOpRmEF5vpm4GsRt8Y/edit?usp=sharing

The general consensus is that this is an important enough feature that we prefer to tackle implementing the `NOT:` syntax. However, the priority on when this feature needs to land is low enough that it can wait to be prioritized during the next Roadmap Planning session.
