### ISSUE TITLE
Instance trend for the current month vs. the last month

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#160]
## User Story
As user, I want to see my current number of instances and a trend of instances for the current month in comparison to the last month so that understand my instance usage month to month.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- The user can only view instance data for accounts that are visible to them via the AWS organization.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## UI Details
UI will a value for the current number of instances and provide a chart/table with the trend of instances for the current month vs. the last month.

## Acceptance Criteria

- [ ] The user is able to see the instances data but only for the accounts visible via AWS organization for the current month vs. the last month.
- [ ] The API and UI work gracefully for cases when has there is no usage data
- [ ] For multiple accounts it should aggregate across across accounts

**Comment by blentz** [comment]
Has this been done already?  What's left to do?

**Comment by LandoCalrizzian** [comment]
VERIFIED
