### ISSUE TITLE
Intermittent test failure: test_prefixed_logical_and

### ISSUE THREAD

**Issue by maskarb** [project-koku/koku#1607]
The following test has been failing intermittently. I had thought I found a fix for it in PR #1591, but apparently my changes weren't sufficient.

```
======================================================================
FAIL: test_prefixed_logical_and (api.report.test.aws.tests_queries.AWSReportQueryTest)
Test prefixed logical AND.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/project-koku/koku/koku/api/report/test/aws/tests_queries.py", line 1296, in test_prefixed_logical_and
    self.assertEqual(query_1_total, query_2_total)
AssertionError: Decimal('6286.727549599') != Decimal('2057.636139521')
----------------------------------------------------------------------
```

**Comment by adberglund** [comment]
One thing to investigate here is that the setUp method in this test class also generates some test data. It's possible that data is sometimes matching a filter in our queries. To do a direct comparison between the two data sets in the test, we should probably remove that data first.

**Comment by nbon12** [comment]
I think if we namespace the accounts that this test adds, and queries, it may help reduce data that is queried by accident.
