### ISSUE TITLE
Storage trend for the last N days (daily)

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#161]
## User Story
As user, I want to see my current storage use and a trend of storage use for the last N days so that understand my storage usage over time.

Time frames will be specific values (last 10 days, last 30 days, last month, last 3 months)

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- The user can only view storage data for accounts that are visible to them via the AWS organization.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## UI Details
UI will  provide a chart/table with the trend of storage used for the last N days (daily).

## Acceptance Criteria

- [ ] The user is able to see the storage data but only for the accounts visible via AWS organization for the last N days.
- [ ] The API and UI work gracefully for cases when has there is no usage data
- [ ] For multiple accounts it should aggregate across across accounts

**Comment by LandoCalrizzian** [comment]
VERIFIED that this returning correct values where each storage line item == report total for all query parameter permutations
