### ISSUE TITLE
group_by tag only outputs "others" with :and :or prefix

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1615]
**Describe the bug**
Users want the ability to filter tag keys by value, but also see an "others" category in the returned data. In the UI details page; for example, I may want to group_by tag key "environment", but also expect an "others" row in the details table (i.e., represented by the "no-environment" tag name).

It turns out that `group_by[and:tag:environment]=*` and `group_by[or:tag:environment]=*` work, but `group_by[tag:environment]=*` does not return a "no-environment" category. That is, "no-environment" is only returned while using a prefix; `:and` or `:or`.

**To Reproduce**

1. Go to: `/api/cost-management/v1/reports/openshift/infrastructures/all/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[and:tag:environment]=*&order_by[cost]=desc`

2. See "dev" and "no-environment" in the available data

3. Go to: `/api/cost-management/v1/reports/openshift/infrastructures/all/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[tag:environment]=*&order_by[cost]=desc`

3. See that "no-environment" is not in the returned data

**Expected behavior**
Expecting `group_by[and:tag:environment]=*`, `group_by[or:tag:environment]=*`, and `group_by[tag:environment]=*` to return "no-environment".

**Screenshots**
<img width="1216" alt="Screen Shot 2020-01-11 at 12 12 19 AM" src="https://user-images.githubusercontent.com/17481322/72199212-116d1b80-3407-11ea-8065-5b1d7f3d67a4.png">

<img width="868" alt="Screen Shot 2020-01-11 at 12 09 17 AM" src="https://user-images.githubusercontent.com/17481322/72199192-a3c0ef80-3406-11ea-9899-765915326f7a.png">

**Comment by nbon12** [comment]
Sprint planning notes: 
UI Dan: This only happens for Azure because azure has tag key cost. The tags per cost is not matching the tag, the only tag for cost is management. It is actually the cost value that is being returned as the tag name. This probably happens for other APIs. 

Andrew: An annotation returns value cost. A tag name gets overridden because "oh that's cost I know what to do with it." it's unfortunate that we would have a tag key name that is actually one of our reserved words but we can fix this.
UI Dan: This is not a blocker.

**Comment by chambridge** [comment]
The cause appears to be this condition which adds a `has_key` filter if wildcard is present:
https://github.com/project-koku/koku/blob/master/koku/api/report/queries.py#L188-L195

The affected request works if this code is removed.

**Comment by lcouzens** [comment]
Verified
Commit: 7f641fa8ec42be6045713530e83f21f40bf79697
