### ISSUE TITLE
AWS Compute API Cost Is Not Right

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1617]
**Describe the bug**
The new materialized view for AWS instance types uses a lateral join right now that is causing some cost double counting. The view needs to be rewritten. 

**Expected behavior**
We should give the accurate cost for EC2 instances.

**Additional Context**
The materialized views in question:  https://github.com/project-koku/koku/pull/1495/files#diff-e2a73832a69ada76bfae37b05cc8873aR360-R476

**Comment by nbon12** [comment]
Notes taken during sprint planning: 
Andrew: ["First issue is a bug that Andrew caused, if you look at dashboard the computer card cost is not quite right. The new materialized view for AWS Instanced types uses Lateral Join that Andrew was doing to accomodate Instance Count feature which we are not using in the UI so it's an optional feature but I did it wrong so we need to re-write that view and we can do it in such a way we still get count information but don't repeat costs."]
Brett: "Which materialized view? What is it doing now and what should it be doing?"
Andrew: "We can "
Kevan: "point to the PR of the other materialized view"

- [ ] TODO: Andrew to put a github link in this issue that points to a similar PR

Brett: "Who are you expecting to do the work? If you're expecting someone else to do the work, that's where my concern for more detail is."
Andrew: "If someone wants to pick this up and tackle it, it's welcome for anyone, but it's SQL so whoever wants to do that, if no one takes it, I know exactly what's wrong and I caused this problem so I know what would fix it."
Andrew: "it is high priority in our backlog"

**Comment by lcouzens** [comment]
The only comment I want to add to this is im surprised the IQE automation didnt catch this issue as a regression the first time. Perhaps there is a gap in our tests, just a side not for QE to review the tests and make sure its covered going forward.

**Comment by Red-HAP** [comment]
Went through several permutations to get the best performance that I could since now I am requiring the query to crawl over the same table twice to get two different aggregations based on the data storage.

Will be testing the changes with unit tests now.

**Comment by lcouzens** [comment]
Verified
Commit: 27a32e82d6c94dc5807df72996d532ec34d40f98
Updated raw calc test should catch this in future
