### ISSUE TITLE
Storage trend for the current month vs. the last month

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#162]
## User Story
As user, I want to see my current storage use and a trend of storage use for the current month in comparison to last month so that understand my storage usage month to month.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- The user can only view storage data for accounts that are visible to them via the AWS organization.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## UI Details
UI will a value for the current storage usage and provide a chart/table with the trend of storage used for the current month in comparison to last month.

## Acceptance Criteria

- [ ] The user is able to see the storage data but only for the accounts visible via AWS organization for the current month in comparison to last month.
- [ ] The API and UI work gracefully for cases when has there is no usage data
- [ ] For multiple accounts it should aggregate across across accounts

**Comment by LandoCalrizzian** [comment]
VERIFIED that this returning correct values where each storage line item == report total for all query parameter permutations
