### ISSUE TITLE
Review circular dependency in database

### ISSUE THREAD

**Issue by Red-HAP** [project-koku/koku#1620]
There is a circular foreign key dependency in the database between tables api_provider.infrastructure_id -> api_providerinfrastructuremap.id 
and 
api_providerinfrastructuremap.infrastructure_provider_id -> api_provider.uuid

api_providerinfrastructuremap.infrastructure_provider_id has a not null constraint
api_provider.infrastructure_id is allowed to be null

The fact that the not-null constraint is one-way keeps this from being a problem. The question I have is: Should this relationship be retooled or is it correct as-is?

## Acceptance Criteria
- [ ] Determine if there is a better database relationship to use here.

## Time Box
- 4 hours

**Comment by nbon12** [comment]
Sprint Planning Conversation minutes:
Andrew: "A little history: we added that infrastructure map in semi-recently. Previously everytime we ran summarization we did a check to see which infrastructure in OpenShift the cluster was running on, so we created a side table to hold that information, the potential problem here is that the Providers table now has a foreign key to the infrastructure table, and the and the infrastructure key has a foreign key to the providers table.

In practice the only providers that should have a key to the infra table is OpenShift providers. If it were on a Cloud Provider than something went wrong, that would be a bug, The Django model limits this to make sure the entries, to limit this to only be one of the cloud providers, effectively an OpenShift provider just needs to get matched to which Cloud it's on, I think the code now keeps this from ever being a problem. The question here is should it be re-tooled? I'm totally open to that If there's a better way."
