### ISSUE TITLE
Clean up manifest and report tables when expiring data

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1623]
## Summary
We have two tables in the public schema that track the manifest and files for a report for a source: `reporting_common_costusagereportmanifest` and `reporting_common_costusagereportstatus`. Those tables grow indefinitely right now and we don't really need a record for a report or manifest that has been deleted from our system. We can remove manifests and file records from a billing period when we remove the data for that billing period.

## Assumptions
- This can be done in the `ExpiredDataRemover` 

## Additional Information
- The Manifest model: https://github.com/project-koku/koku/blob/46b5c98364cf27b19e0530cc9a50cc79753b6900/koku/reporting_common/models.py#L24
- The report status model: https://github.com/project-koku/koku/blob/46b5c98364cf27b19e0530cc9a50cc79753b6900/koku/reporting_common/models.py#L44
- Expired Data Remover: https://github.com/project-koku/koku/blob/46b5c98364cf27b19e0530cc9a50cc79753b6900/koku/masu/processor/expired_data_remover.py#L45
- Just deleting the `CostUsageReportManifest` should cascade deletes to the `CostUsageReportStatus` table.

## Acceptance Criteria

- [ ] Report file records are deleted when you delete data for a billing period. 
- [ ] Manifest records are deleted when you delete data for a billing period.

**Comment by nbon12** [comment]
Andrew: "One thing we're not doing is cleaning up the manifest and report status tables."

**Comment by nbon12** [comment]
https://github.com/project-koku/koku/blob/46b5c98364cf27b19e0530cc9a50cc79753b6900/koku/masu/processor/aws/aws_report_db_cleaner.py#L46

**Comment by lcouzens** [comment]
Verified!!
