### ISSUE TITLE
Customer facing issue reporting & triage process is defined & documented for GA

### ISSUE THREAD

**Issue by spookysushi** [project-koku/koku#1628]
Make sure that customers understand how to report issues or make requests of Cost Management once we're GA.

## Acceptance Criteria
- [x] Document exists in mojo with this process defined
- - [x] Cost Management Priority Workflow for CEE and Engineering
- [x] Our cost management docs have information on how to open a bug (Bugzilla)

**Comment by jlalbertson** [comment]
https://mojo.redhat.com/docs/DOC-1214544

**Comment by jlalbertson** [comment]
Published docs have link to our cost management bugzilla: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/getting_started_with_cost_management/assembly_introduction_cost_management
