### ISSUE TITLE
Cost management requires OpenShift entitlement with Tech Preview

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1634]
## User Story
As a customer, I must have an OpenShift entitlement so that I can use the cost management feature (application).

## Impacts
API

## Role
Customer

## Assumptions
- The platform will provide the users entitlements in the x-rh-identity header passed on an API call
- The entitlement header will include `openshift` and whether it is entitled

## API Details

Alter the current entitlement check in the Koku middleware to check for `openshift`.

Identity header should look like the following containing the entitlements object.
```
{
	'identity': {
...
	'entitlements': {
		'openshift': {
			'is_entitled': True
		}
	}
}
```

You can test a users entitlement  by logging in and performing a GET request on [https://cloud.redhat.com/api/entitlements/v1/services](https://cloud.redhat.com/api/entitlements/v1/services)

## Acceptance Criteria

- [ ] If a user is not entitled to openshift based on the response of the entitlement service then they will receive a 403 from the API
- [ ] If the user is entitled to openshift based on the response of the entitlement service then the request will proceed

**Comment by lcouzens** [comment]
Verified
Commit: 6b73e765bef0ff34e6ac3c632c2ced4c75f5a3c3
Automation: test_api_entitlements

**Comment by chambridge** [comment]
Platform team didn't move use to `openshift` need to use `cost_management` instead.

**Comment by lcouzens** [comment]
Verified
Commit: 6b162121636a591f1826abbe1367242281629856
