### ISSUE TITLE
Upgrade the local dev oc version to 3.11 to match osd

### ISSUE THREAD

**Issue by myersCody** [project-koku/koku#1636]
## User Story
As a developer I want to be able to develop with openshift locally using the same version as osd. However currently our make commands are using deprecated flags from 3.9

**Example of deprecated flags being used:**
List of changes coming on the way for oc cluster up (3.10.x) [here](https://github.com/minishift/minishift/issues/2248)

Our current makefile: https://github.com/project-koku/koku/blob/master/Makefile#L423
```
oc-up:
	oc cluster up \
		--image=$(OC_SOURCE) \
		--version=$(OC_VERSION) \
		--host-data-dir=$(OC_DATA_DIR) \
		--use-existing-config=true
	sleep 60
```
The `--host-data-dir` flag is no longer an option past 3.10.x. 

Additional justification for why the change is needed. We are trying to deploy e2e locally using a script created by Brandon; however, the script is returning 3.11.x oc syntax because that is what osd is on which can't be used on 3.9. For more information on this we can loop @abaiken into the conversation.

## Acceptance Criteria 
- [ ] change the make targets to function for oc 3.11

**Comment by nbon12** [comment]
Andrew:  "I feel like we have a pretty strong reason to do this, is this blocking us now? It seems like a relatively small change"
Ashley: "It's not blocking"
Kevan: "The makefile only works with 3.9 and e2e requires 3.11 and they're incompatible. You have to remember to upgrade your client because the makefile will not work. "

**Comment by blentz** [comment]
Comments from PR #1666 :  The decision we reached is to eventually deprecate the use of `oc cluster up` in favor of directing contributors to Minishift and Code-Ready Containers. 

So, this request is mostly about updating the docs and then removing the relevant references from the `Makefile`

**Comment by nbon12** [comment]
Sprint Planning:
Andrew: "Closed due to PR merged."
