### ISSUE TITLE
Clean Up Volumes on Listener and Worker and Alert on High Volume Usage

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1639]
**Describe the bug**
Our production listener pod stopped working because the volume filled up and we couldn't download any more files.

**To Reproduce**
1. Make a listener with very small volume
2. Load lots of data into the mounted volume
3. Try to process using the listener (assumes you have a local ingress service / kafka) ((ping @abaiken  or use e2e) 

**Expected behavior**
We should clean up report files such that we never run out of room. 

**Proposed Solution** 
- Look at using an existing volume Prometheus metric, or if necessary create a Prometheus metric to alert on so that we can alert on hitting a certain threshold on our volume ( i.e. 80% usage of capacity). 
- We should also consider creating a scheduled celery task that crawls the `/var/tmp/masu/` in the workers and clears out files for any manifest that is not the most recently seen manifest. 

**Additional context**
- Today, if a file is properly processed successfully we delete it, so the "green path" is working.

**Comment by nbon12** [comment]
Andrew: I don’t know if we’ll have to create our own metric. This might be researching the proper prometheus query that we can put into the alert manager and we could do it on a per-stateful set. Let’s say we hit 80% of the threshold we should get an alert to fix it before it crashes.

**Comment by abaiken** [comment]
Corresponding e2e-deploy PR for adding scheduling environment variables: https://github.com/RedHatInsights/e2e-deploy/pull/1116

**Comment by lcouzens** [comment]
Looks good to me, my only question would be what happens to files that get uploaded for ingest just before the clean up job runs. They will get deleted. Had a quick discussion with @abaiken about having some timing check to ignore files that have just been uploaded, just need to decide on the degradation time frame.

Pushing it back so this can be worked on.

**Comment by kholdaway** [comment]
@lcouzens Take a look again.  We added a 24-hour delay before files are removed.

**Comment by lcouzens** [comment]
Verified!
