### ISSUE TITLE
Update local docker postgresql.conf for statement statistics

### ISSUE THREAD

**Issue by Red-HAP** [project-koku/koku#1652]
## User Story
As a developer I want the PostgreSQL engine to track statement statistics for performance tuning and testing.

The objective here is to enable the `pg_stat_statements` preload shared library in the local docker environment and initially log statements that run slower 2 seconds. (2 seconds is the current SLO that our report for latency uses, so align there.)

This ticket is intended to help support performance testing and tuning along with [Large Data Volume Generation for Performance Testing](https://app.zenhub.com/workspaces/project-koku-5ab50f63d0f4ea53b00232c8/issues/project-koku/nise/187). 

Also, many performance analysis tools for PostgreSQL require that this library is loaded.

## Impacts
Database, Local-development environment

## Role
Developer

## Assumptions

- [x] Local docker postgresql.conf can be modified without having to build a hosted image

## Acceptance Criteria

- [ ] Docker postgres container has configuration changes applied
- [ ] Connecting to the local koku db; executing `show shared_preload_libraries;` should return `pg_stat_statements`
- [ ] Connecting to the local koku db; executing `select * from pg_stat_statements;` should return data with no errors.

**Comment by nbon12** [comment]
HAP: It's a low priority thing but I think it'll be useful, to leverage pgAdmin to identify longer running statements.
Andrew: 2 seconds is the current SLO for API requests in general.
HAP: [Resolving this ticket] It is fairly quick, after that it is utilizing the metrics and starting to look at them.

**Comment by Red-HAP** [comment]
This will work with localdev using docker-compose, but will not work (as yet) with OpenShift locally. 
I'd like to punt that to another ticket and get some help as I think it may require that an image be built.
