### ISSUE TITLE
GroupBy Azure tag returns cost instead of tag name

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1658]
**Describe the bug**
The results produced by the `/v1/reports/azure/costs/` API look off when group_by `tag:cost` is applied. It does not match the tags provided by the `/v1/tags/azure` API.

I'm expecting "management" and "no-cost" to be returned when `group_by[and:tag:cost]=*` is applied. Instead, I get the actual cost as the tag names. 

**To Reproduce**

`/v1/reports/azure/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[and:tag:cost]=*&order_by[cost]=desc`

**Expected behavior**
I'm expecting to see the same tag values for both APIs. I also expect to see the "no-cost" (i.e., others) category.

**Screenshots**
`/v1/reports/azure/costs` and `group_by[and:tag:cost]=*`

![Screen Shot 2020-01-28 at 2 50 06 PM](https://user-images.githubusercontent.com/17481322/73299616-86996880-41dd-11ea-983b-2e911dc35868.png)

`/v1/tags/azure`

![Screen Shot 2020-01-28 at 2 44 47 PM](https://user-images.githubusercontent.com/17481322/73299206-c0b63a80-41dc-11ea-8b22-b22211941419.png)

**Comment by lcouzens** [comment]
Verified
Commit: 7f641fa8ec42be6045713530e83f21f40bf79697
