### ISSUE TITLE
searching with filter  fails if filter field is empty.

### ISSUE THREAD

**Issue by ddonahue007** [project-koku/koku#1659]
1. from main page select all projects
2. hit the search button without adding anything to the search field

![Screen Shot 2020-01-28 at 3.09.53 PM.png](https://images.zenhubusercontent.com/5dc5dcfe586229000122b6e7/379491c2-52bc-49c8-991d-15d5b03009a8)

Search URL from browser:
https://ci.foo.redhat.com:1337/beta/cost-management/ocp-cloud?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&filter_by[project]=&group_by[project]=*&order_by[cost]=desc

**Comment by dlabrecq** [comment]
Issue moved to [project-koku/koku-ui #1282](https://github.com/project-koku/koku-ui/issues/1282) via [**ZenHub**](https://www.zenhub.com/)
