### ISSUE TITLE
Docker postgres container fails to start on Fedora due to "cannot create directory '/var/lib/pgsql/data/userdata': Permission denied"

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/koku#166]
Running "make start-db" on Fedora shows success but the postgres container isn't running. The output of "docker logs koku_db_1" is "cannot create directory '/var/lib/pgsql/data/userdata': Permission denied"

Issue is due to host volume ./pg_data not having ownership assigned to postgres (uid 26)

**To Reproduce**
1. Run "make start-db"
Command returns success but the container isn't running

**Expected behavior**
"make start-db" success guarantees that the koku_db_1 container is running

**Context (please complete the following information):**
 - OS: Fedora 27
 - Commit Hash from status endpoint: 6dbde8d6639a524ecd7f54b83a5ded20293cf49e

**Additional context**
Assigning ownership of pg_data to postgres (uid 26 / gid 26), setting the selinux context container_file_t and restarting the container allows it to run successfully.

**Comment by chambridge** [comment]
This is a known issue with Docker on Linux the suggested development path is to utilize Openshift.

You should use:
`make oc-up-db`

These are the useful command in the Makefile.
```
	@echo "  oc-up-db                 to run Postgres in an openshift cluster"
	@echo "  oc-create-db             to create a Postgres DB in an initialized openshift cluster"
	@echo "  oc-forward-ports         to port forward the DB to localhost"
	@echo "  oc-stop-forwarding-ports to stop port forwarding the DB to localhost"
	@echo "  oc-run-migrations  	  to run Django migrations in the Openshift DB"
	@echo "  oc-serve 			 	  to run Django server locally against an Openshift DB"
```

If you feel necessary we can update the README docs to note this for Linux.

**Comment by LandoCalrizzian** [comment]
Understood. Deploying to Openshift worked w/o any issues and since it is the suggested method this is probably a docs issue.  

The readme starts off with instructions for deploying using docker so it would be helpful to state that Openshift is the suggested method from the start and include those Openshift deployment commands instead while moving the docker deployment Makefile commands to a "Deploying koku using Docker" section

The docs mention that there might be a selinux issue with deploying postgres in a container. Until there is a permanent fix, a quick note detailing that postgres container deployment may fail with permission denied can be resolved by granting ./pg_data ownership permissions to uid:26 (postgres user in centos/postgresql-96-centos7)
