### ISSUE TITLE
Filter by tag generates 500 internal error

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1663]
**Describe the bug**
In the UI's details pages, we have the ability to show a data table grouped by project, cluster, etc. When grouped by projects; for example, the table shows a list of project names. When expanding the table to show more details, we also apply a filter to show the top services, accounts, and regions. 

If we expand project "analytics"; for example, the top services would be obtained by applying `filter[project]=analytics` and `group_by[service]=*`.

Unfortunately, this does not work when filtering by tags. The UI currently has nothing to display because the API returns a 500 error when `filter[tag:app]=analytics` is applied.

**To Reproduce**

`/v1/reports/openshift/infrastructures/all/costs/?filter[limit]=3&filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&filter[tag:app]=analytics&group_by[project]=*`

**Expected behavior**
I want to filter results by tag. The API should not generate a 500 error.

**Screenshots**
![Screen Shot 2020-01-28 at 5 20 30 PM](https://user-images.githubusercontent.com/17481322/73310563-848dd480-41f2-11ea-8282-fc798b9ba7c7.png)

**Comment by nbon12** [comment]
Sprint Planning Meeting Minutes:
Andrew: "I think this is a duplicate issue, after I merged the PR for the group by tag stuff yesterday and I tried this API call and I think it works now in CI. So I'm inclined to move this to QA so that can be verified by Luke."

**Comment by dchorvat1** [comment]
verified, c65a123af8cf3729abe5751bd66a1c1e03108c82
