### ISSUE TITLE
Delete provider intermittently misses latency targets

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1672]
**Describe the bug**
In production the deletion of providers can take over 5 seconds. Impacting our latency target of requests less then 2 seconds.

**To Reproduce**
1. Perform a delete of a Provider
2. See slow processing (this does not happen with every execution)

**Expected behavior**
Deleting a provider request should take less than 2 seconds.

**Comment by lcouzens** [comment]
Verified
