### ISSUE TITLE
Remove deprecated cluster_alias from data return

### ISSUE THREAD

**Issue by myersCody** [project-koku/koku#1696]
## User Story
With the addition of the `clusters` [array](https://github.com/project-koku/koku/pull/1675), has been deprecated and will be removed as soon as the UI no longer references it. 

Remove the `cluster_alias` annotation from the `group_by[cluster]` data return: https://github.com/project-koku/koku/pull/1675/commits/9f25b5ed8a97d60dd4f89d211023c98ef361d9ce

## Acceptance Criteria
- `cluster_alias` is no longer returned when doing a group by cluster

**Comment by lcouzens** [comment]
Verified
Commit: 30208f4ccfd80db2270d6e523b0343d5d6139b19
