### ISSUE TITLE
Utilize materialized views for OCP report queries

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1698]
## User Story
As a customer running a large OCP footprint on premises I would like OCP reporting queries to return quickly at scale, so that when viewing the dashboard the experience does not suffer from long request load times.

## Impacts
API

## Assumptions
- The current AWS materialized views can be used as a template
-

## Implementation Details
Changes should be modeled on the following PRs that added materialized views for AWS queries:
- https://github.com/project-koku/koku/pull/1495
- https://github.com/project-koku/koku/pull/1554
- https://github.com/project-koku/koku/pull/1645

## Acceptance Criteria

- [ ] Verify that existing test cases (unit and QE) still pass
- [ ] Views exist for cost, cost by project, cost by cluster
- [ ] Views exist for compute API
- [ ] Views exist for memory API
- [ ] Views exist for storage API

**Comment by nbon12** [comment]
Sprint planning meeting minutes:

Andrew: This is an API thing and database thing. This is changing the underlying structure of where the data is coming from, no actual changes to the data that should be coming out of it.

**Comment by nbon12** [comment]
Sprint Planning Meeting Conversation: 
Andrew: "Blocked because it changes the underlying models. "

**Comment by lcouzens** [comment]
Verified
