### ISSUE TITLE
Utilize materialized views for Azure report queries

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1701]
## User Story
As a customer running a large Azure footprint, I would like Azure reporting queries to return quickly at scale, so that when viewing the dashboard the experience does not suffer from long request load times.

## Impacts
API

## Assumptions
- We will need to select the right model for the query handler based on the query: https://github.com/project-koku/koku/blob/2879d253f1bc8daee5f67bddc8709f3120408f26/koku/api/report/aws/query_handler.py#L120

## Implementation Details
Changes should be modeled on the following PRs that added materialized views for AWS queries:
https://github.com/project-koku/koku/pull/1495
https://github.com/project-koku/koku/pull/1554
https://github.com/project-koku/koku/pull/1645

## Acceptance Criteria

- [ ] Verify that existing test cases (unit and QE) still pass
- [ ] Views exist for cost, 
   - reports/openshift/infrastructures/all/costs/
   - reports/openshift/infrastructures/all/costs/?group_by[service] 
   - reports/openshift/infrastructures/all/costs/?group_by[account]
   - reports/openshift/infrastructures/all/costs/?group_by[region]
- [ ] Views exist for compute API
   - reports/azure/instance-types/
- [ ] Views exist for storage API
   - reports/azure/storage
- [ ] Views exist for database API
   - reports/openshift/infrastructures/all/costs/?filter[service_name]=Database,Cosmos%20DB,Cache%20for%20Redis
- [ ] Views exist for network API
   - reports/openshift/infrastructures/all/costs/?filter[service_name]=Virtual%20Network,VPN,DNS,Traffic%20Manager,ExpressRoute,Load%20Balancer,Application%20Gateway

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:

Andrew: "Take the cookie cutter of what we made there and apply it to the other reports. We're swapping out the back-end. [We may not not need additional testing]"

HAP: "I could use a primer on what we're doing for tagging and how it's intended to work. "

**Comment by lcouzens** [comment]
Verified
