### ISSUE TITLE
Utilize materialized views for OCP on Azure report queries

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1704]
## User Story
As a customer running a large OCP footprint on Azure I would like OCP on Azure reporting queries to return quickly at scale, so that when viewing the dashboard the experience does not suffer from long request load times.

## Impacts
API

## Assumptions
- We will need to select the right model for the query handler based on the query: https://github.com/project-koku/koku/blob/2879d253f1bc8daee5f67bddc8709f3120408f26/koku/api/report/aws/query_handler.py#L120

## Implementation Details
Changes should be modeled on the following PRs that added materialized views for AWS queries:
https://github.com/project-koku/koku/pull/1495
https://github.com/project-koku/koku/pull/1554
https://github.com/project-koku/koku/pull/1645

## Acceptance Criteria

- [ ] Verify that existing test cases (unit and QE) still pass
- [ ] Views exist for cost, 
   - reports/openshift/infrastructures/azure/costs/
   - reports/openshift/infrastructures/azure/costs/?group_by[project] 
   - reports/openshift/infrastructures/azure/costs/?group_by[cluster]
- [ ] Views exist for compute API
   - reports/openshift/infrastructures/azure/instance-types/
- [ ] Views exist for storage API
   - reports/openshift/infrastructures/azure/storage
- [ ] Views exist for database API
   - reports/openshift/infrastructures/azure/costs/?filter[service]='AmazonRDS','AmazonDynamoDB','AmazonElastiCache','AmazonNeptune','AmazonRedshift','AmazonDocumentDB'
- [ ] Views exist for network API
   - reports/openshift/infrastructures/azure/costs/?filter[service]='AmazonVPC','AmazonCloudFront','AmazonRoute53','AmazonAPIGateway'

**Comment by lcouzens** [comment]
Verified
