### ISSUE TITLE
Specify the Cost Impact for Price List rates in cost model

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1709]
## User Story
As a customer, I want to define how markup impacts the total cost, so that I choose to define the cost as either infrastructure or supplementary.

## Impacts
- API
- UI
- Docs

## Assumptions
- Node and cluster / cost / month rates default to infrastructure
- All other rates default to supplementary

## Implementation Details
The cost model object needs to support the option to define a rate as infrastructure or supplementary cost.

The worker cost summarization needs to account for the defined cost impact (infrastructure or supplementary cost) when performing the cost calculation.

## Acceptance Criteria

- [ ] Verify that the cost model object supports price list cost types to be defined
- [ ] Verify that the rate is attributed to infrastructure if the Cost Model defines it as such
- [ ] Verify that the rate is attributed to supplementary costs if the Cost Model defines it as such
- [ ] Verify that a 400 is provided to the user if the cost type is specified as something other than infrastructure or supplementary
- [ ] Verify that the Open API spec has been updated appropriately

**Comment by nbon12** [comment]
Sprint Planning Meeting Minutes:

Andrew: Similar to the last story with cost models, this is for markup instead. 

Chris: We return infrastructure, derived cost, and monthly cost, so what are we actually returning and what are they named, we'll need to re-visit this with the actual names.

**Comment by lcouzens** [comment]
Verified

**Comment by lcouzens** [comment]
Verified
