### ISSUE TITLE
Defined Monthly Costs can be Classified

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1710]
## User Story
As a customer, I want the node per month cost to be reflected as infrastructure cost, so that it reflects my definition that this is a monthly infrastructure cost.

## Impacts
- API
- UI
- Docs

## Assumptions
-
-

## Implementation Details
When defining monthly costs for a node in the cost model, the cost model object should allow the user to specify either infrastructure or supplementary cost type.

The default cost type for monthly per node (and per cluster) cost should be infrastructure.

The worker cost summarization needs to account for the defined cost impact (infrastructure or supplementary cost) when performing the monthly per node cost calculation.

## Acceptance Criteria
- [ ] Verify that the cost model object supports cost types to be defined for the monthly node cost
- [ ] Verify that the monthly per node cost is attributed to infrastructure if the Cost Model defines it as such
- [ ] Verify that the monthly per node cost is attributed to supplementary costs if the Cost Model defines it as such
- [ ] Verify that a 400 is provided to the user if the cost type is specified as something other than infrastructure or supplementary
- [ ] Verify that the Open API spec has been updated appropriately

**Comment by nbon12** [comment]
Sprint Planning meeting minutes:

Andrew: Impacts across the board, back end needs to address this, also the UI, and docs. I like that it's a choice, the small departure from what Sergio initially requested, for him if you had a node cost it's just infra cost, but this allows the user to make a decision on how they want to call that.

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:

Andrew: "Cody brought this up [that the] columns that exist in the database now don't allow for this so part of the re-work, potentially in a new issue, is syncing up database columns to have a place for that information to go. I'm not going to move this over yet because getting the database columns in is a dependency to this and that issue isn't created yet"

**Comment by lcouzens** [comment]
Verified
