### ISSUE TITLE
Verify OpenAPI Servers section for autogenerated client

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1724]
## User Story
As a user of our OpenAPI spec I want to known that our variable enum in the servers section will workin in a generated client so that I can call the APIs on the correct server. 

## Impacts
API

## Assumptions
- Our enum is okay
- Worst case we get less fancy and just copy how another team is doing this

## Acceptance Criteria

- [ ] The servers section works in a generated client

**Comment by adberglund** [comment]
@lcouzens Just moving to QA for completeness sake, but my understanding from our conversation with Pete the other day is that our spec is acceptable today.

**Comment by lcouzens** [comment]
I believe so!
