### ISSUE TITLE
Assess current implementation of Tags APIs

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1734]
## User Story
As a customer, I want tags to return quickly so that I can filter and group by at ease.

## Impacts
API, UI

## Assumptions
- Currently the tags APIs get tags from the line item daily summary table instead of the much smaller tag summary tables. https://github.com/project-koku/koku/blob/master/koku/api/tags/aws/queries.py#L27
- If it is easy to switch over to using the tag summary table, then we should go ahead and do that. 
- The date filters on the tags APIs will likely be the thing that causes trouble with using the tag summary tables. We can either
  1) rework the filters in the tag query handler to look at the bill's start and end dates. 
  2) add in usage_start and usage_end columns to the tag summary tables and populate them using the bill start/end dates so the filters work (potentially) as-is.
 

## Acceptance Criteria

- [x] We determine if we should be using the tag summary tables
- [x] Tag queries work against the tag summary tables
- [x] No regressions

**Comment by lcouzens** [comment]
Verified
