### ISSUE TITLE
Support Monthly Cluster Cost for OCP

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1758]
## User Story
As a customer, I want to be able to apply a monthly cost for the cluster, so that I can associate generic monthly costs like operations with the cluster.

## Impacts
- API, 
- UI,
- Docs

## Assumptions
Update needed to Cost Model object and supported Metrics

## Implementation Details
Update the code similar to monthly node cost PR (https://github.com/project-koku/koku/pull/1438) but for a cluster. This needs to be expanded so that the model also allows the user to specify the cost type as infrastructure or calculated.

## Acceptance Criteria
- [x] Verify that the cost model allows the creation of a rate with monthly cluster cost that can be specified as infrastructure or supplementary
- [x] Verify that the monthly per cluster cost is attributed to infrastructure if the Cost Model defines it as such
- [x] Verify that the monthly per cluster cost is attributed to supplementary costs if the Cost Model defines it as such
- [x] Verify that a 400 is provided to the user if the cost type is specified as something other than infrastructure or supplementary
- [x] Verify that the Open API spec has been updated appropriately

**Comment by nbon12** [comment]
Sprint Planning Meeting notes:

Andrew: For our cost models version 2 epic. This is a back-end issue.

**Comment by nbon12** [comment]
Sprint Planning meeting notes:

Andrew: "This is to support monthly cost, today we have node cost and node monthly; this is one layer up for clusters. This is a cost model change to add whatever we did for node, add it for cluster. We have something that calculates monthly cost, maybe we should put a dependency on this to work out node-monthly bug. This is a new monthly cost type."

**Comment by adberglund** [comment]
@adberglund Go update code pointers for how to add this work in masu + the cost model metrics.

**Comment by lcouzens** [comment]
So this is working mostly as expected. Although seeing costs doubled when summary happens. Might need your eyes on this @adberglund pushing it back to review for now.

**Comment by lcouzens** [comment]
Cluster per month metric no longer available from a recent regression. Pushing back to backlog.

**Comment by lcouzens** [comment]
Verified!
