### ISSUE TITLE
Optimize Pricelist Calculation Code

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1760]
## User Story
As a developer, I want to optimize the price list calculation code to utilize the database as much as possible, so that calculations are as quick as possible and less calls are made against the database.

## Impacts
- Worker

## Assumptions
- We need the ability to get the memory or cpu or volume or node specific values for a particular cost type, but we probably don't want to explode out the number of columns in this table to handle each new cost type.
- Will explore using a JSON dictionary for costs that have sub values to split by resource contributing the cost. 
- We can leverage the Python code in existence to grab the rates for each resource type, but instead of calculating in Python then loading the data into the DB, we can template some SQL to do the math in the DB and populate the new columns. 

## Implementation Details
- OpenShift DailySummary model will need to be altered to have the following columns
  - infrastructure_raw_cost
  - infrastructure_project_raw_cost
  - infrastructure_usage_cost
  - infrastructure_markup_cost
  - infrastructure_monthly_cost
  - supplementary_raw_cost
  - supplementary_project_raw_cost
  - supplementary_usage_cost
  - supplementary_markup_cost
  - supplementary_monthly_cost
- OpenShift DailySummary model will need to be altered to remove the following columns
  - pod_charge_cpu_core_hours
  - pod_charge_memory_gigabyte_hours
  - persistentvolumeclaim_charge_gb_month
  - infra_cost
  - project_infra_cost
  - markup_cost
  - project_markup_cost
  - monthly_cost

## Acceptance Criteria
- [ ] Verify that existing test cases (unit and QE) still pass

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:

@adberglund to populate this issue with more detail
Andrew: "Right now there's a lot of stuff done in code that might be able to move over."

**Comment by lcouzens** [comment]
Verified
