### ISSUE TITLE
Validate and improve performance of queries against OCP Daily Summary tables

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1761]
## User Story
As a user I want to make more complex queries (multiple group bys and filters) not covered by our materialized views and have them not time out, so that I can gain value from the data.

## Impacts
API, Database

## Assumptions
- This will require assessment of the queries being performed on a large customer to determine how Postgres's query planner is really running the query
- Model changes and/or index changes may be required to bring query time down
- OCP daily summary model: https://github.com/project-koku/koku/blob/7acb90eb68c69268ea8ca9c616e5ff2bc9efe04f/koku/reporting/provider/ocp/models.py#L188

## Acceptance Criteria

- [ ] Verify that existing test cases (unit and QE) still pass
- [ ] Queries against the daily_summary tables do not time out (30 seconds)

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes: 

Andrew: "A version of this story exists for AWS Summary Tables, this is the OCP version. We don't have openshift materialized views yet but this story was copy and pasted."
