### ISSUE TITLE
Cannot group_by tag

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1773]
**Describe the bug**
Cannot group by tag in the UI. Looking at the console, I see "Unsupported parameter or invalid value" errors

**To Reproduce**
1. Go to

/v1/reports/openshift/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[or:tag:app]=*&order_by[cost]=desc

2. Go to

/v1/reports/openshift/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[or:project]=*&group_by[tag:version]=beta&order_by[cost]=desc

**Expected behavior**
Being able to group by tag is a key feature fo the UI details page.

**Screenshots**
Step 1:
![Screen Shot 2020-02-18 at 11 34 53 AM](https://user-images.githubusercontent.com/17481322/74756545-b8cd4180-5242-11ea-932f-e180636b6358.png)

Step 2:
![Screen Shot 2020-02-18 at 11 35 01 AM](https://user-images.githubusercontent.com/17481322/74756554-bbc83200-5242-11ea-834c-cc09433949a8.png)

**Additional context**
Note that it doesn't seem to matter if the `or:` prefix is used.

**Comment by chambridge** [comment]
So interestingly these queries work with the `cost-demo` user in *CI*:
<img width="928" alt="Screen Shot 2020-02-18 at 1 51 35 PM" src="https://user-images.githubusercontent.com/29379759/74768526-bd035a00-5256-11ea-9e02-ebd02c40c10e.png">
<img width="905" alt="Screen Shot 2020-02-18 at 1 52 08 PM" src="https://user-images.githubusercontent.com/29379759/74768533-c096e100-5256-11ea-8aab-4b1244573038.png">

But if I use our old user setup I do hit the above issues.

Below are the associated tags showing that these should be valid tag keys:
```
GET /api/cost-management/v1/tags/openshift/?filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: HTTP_X_RH_IDENTITY, Accept

{
    "meta": {
        "count": 4,
        "filter": {
            "resolution": "monthly",
            "time_scope_value": "-1",
            "time_scope_units": "month"
        },
        "key_only": false,
        "group_by": {},
        "order_by": {}
    },
    "links": {
        "first": "/api/cost-management/v1/tags/openshift/?filter%5Bresolution%5D=monthly&filter%5Btime_scope_units%5D=month&filter%5Btime_scope_value%5D=-1&limit=100&offset=0",
        "next": null,
        "previous": null,
        "last": "/api/cost-management/v1/tags/openshift/?filter%5Bresolution%5D=monthly&filter%5Btime_scope_units%5D=month&filter%5Btime_scope_value%5D=-1&limit=100&offset=0"
    },
    "data": [
        {
            "key": "version",
            "values": [
                "beta",
                "gamma",
                "prod"
            ],
            "type": "storage"
        },
        {
            "key": "storageclass",
            "values": [
                "bravo",
                "charlie",
                "delta",
                "epsilon"
            ],
            "type": "storage"
        },
        {
            "key": "environment",
            "values": [
                "dev",
                "prod",
                "qe"
            ],
            "type": "storage"
        },
        {
            "key": "app",
            "values": [
                "analytics",
                "catalog",
                "cost"
            ],
            "type": "storage"
        }
    ]
}
```

**Comment by dlabrecq** [comment]
What should we be using in the CI beta environment? I'm using jalberts, but thought cost-demo is prod only?

**Comment by chambridge** [comment]
@dlabrecq `cost-demo` is now available in CI beta. Its on org_admin user, so we will be using it moving forward in terms of recurring data, but this was something that was going to be highlighted during tomorrow's demo. Your issue with `jalberts` is a real one and talking to @adberglund he thinks the problem is due to a manual summarization task that needs to be run given the current generated data in that account.

**Comment by adberglund** [comment]
@dlabrecq @chambridge The re-summarization has been triggered so this should be okay on the jalberts account as well now. Let me know if not.

**Comment by adberglund** [comment]
@dlabrecq Mind if I close this as resolved?

**Comment by dlabrecq** [comment]
Sure
