### ISSUE TITLE
Refine IAM Policy for service needs

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#179]
We will be providing users with an IAM Policy (in JSON form) that we will use to access their cost usage data, organizational setup, and get SNS updates when new cost usage data is available.

Our JSON policy should have the minimal set of permissions needed.

____
Associated with #99

**Comment by blentz** [comment]
This is cloudhealth's IAM policy:
https://github.com/openshift/openshift-tools/blob/prod/scripts/cloudhealth/cloudhealth_policy_template.json

It's basically every Get*, List*, or Describe* permission across all services. (i.e. read-only, but view everything.)

We don't have to start with this, but I'd be surprised if we didn't end up with something very similar by the time we hit the Walk/Fly phases.
