### ISSUE TITLE
Duplicate tags

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1797]
## Proposed Solution
By default we roll up tags from the different sources (storage, pod, node for OpenShift) into a single resultset with a new query param that will provider the ability to break tags out by where they came from.

--------------------------------------------------------------------------
**Describe the bug**
Seeing duplicate tags in the UI details pages. Not clear if this is intentional -- only the `type` prop appears to be different?

**To Reproduce**
/v1/tags/openshift/?filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1

**Expected behavior**
Expecting tag keys to be unique. If expected, then the UI needs to handle this appropriately.

**Screenshots**
<img width="307" alt="Screen Shot 2020-02-20 at 2 48 40 PM" src="https://user-images.githubusercontent.com/17481322/74972655-1bb00b80-53f0-11ea-8058-e916f2dbb838.png">

**Additional context**
This is with CI beta using the cost-demo user

**Comment by chambridge** [comment]
So I think this is intentional as we are trying to provide information on where the tags came from, but I can definitely understand the UI usecase where you don't care.

We should implement some merge type flag that only gives back the union without type info.

**Comment by dlabrecq** [comment]
It's causing some confusion with the UI. In the example below, the two "environment" options are equal because they share the same option value.

![Screen Shot 2020-02-20 at 2 59 26 PM](https://user-images.githubusercontent.com/17481322/74973643-ca088080-53f1-11ea-88af-707c4d454141.png)

**Comment by chambridge** [comment]
yep, makes sense

**Comment by adberglund** [comment]
@blentz Proposed structure: 

```
{ “key”: “environment, “tags”: [ {“name”: foo, “type”: [pod, storage] } ]
```

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:

Andrew: "It's pulling all the keys, and showing that we have two environment keys. How do people feel on [how to handle this. My feeling is to add parameter that can break it up by type."

Chris: "We could add something in future to determine where tags came from for example: `product family`."

Brett: "I think if we rearrange the response we could provide the same detail and reduce the duplication."

Michael: "What if you have different values between those two values, for example pod and storage."
Andrew: "It would be the union between the two sets."
Brett: "If we make `values` it's own objects we could match that particular value as part of the whole things and reduce duplication at the value level."

**Comment by lcouzens** [comment]
Verfied
