### ISSUE TITLE
[Spike] To Accessor or not to accessor.

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#1808]
## User Story
As Koku developer, I want to follow accepted development patterns, so that I can take advantage of best practices within the project and its upstream communities.

## Background
Koku and Masu used to be separate projects with separate repositories. Second, Masu used to be a Flask app while Koku was a Django app. This meant that Masu didn't have access to the same model objects that Koku did. Our solution was to introspect the model information, which required the creation of the DBAccessor layer.

Now that Koku and Masu have merged and are both Django apps, the accessor layer is somewhat extraneous. It works and it provides some value, but it is only used by half of our project while the other half uses Django's ORM more directly.

The main reason to do this is just so that we reduce the overall project complexity by going from 2 design patterns down to 1, which makes future changes easier.

## Expected outcome

This is a research spike. The desire is to have someone walk through the Koku and Masu code and assess whether it would be better to A) make everything use the accessors or for us to B) deprecate and eventually remove the accessors to allow Masu to use the Django ORM.

Once an assessment has been made and some pros & cons of each approach have been compiled, the findings should be presented to the team so we can make a group decision on what pattern the team prefers to align around. After the decision is made, new issues should be created and placed into the New Issues column to prioritize the work. 

## Impacts
Backend only

## Role
- Koku dev

## Assumptions
- There will be no impact to the UI or API
- The future work being scoped should not have a negative performance impact
- This research should take about 1 day and not more than 2 days.

## Acceptance Criteria

- [ ] An analysis of the Accessor use cases versus the Django ORM uses has been done.
- [ ] A list of pros & cons is drafted for keeping versus discarding the accessors.
- [ ] A team discussion with relevant stakeholders has been held. (Everyone should get an invite as an optional participant.)
- [ ] A "keep" or "deprecate" decision is made on what to do with the Accessors
- [ ] New issues are created to either expand the use of Accessors to the rest of the code, or to refactor Masu to remove the deprecated accessors.

**Comment by nbon12** [comment]
Would this line of code be considered an Anti-pattern because it requires internal knowledge of the Django ORM, even though the DB Accessor is supposed to encapsulate and hide that information? https://github.com/project-koku/koku/blob/master/koku/masu/processor/ocp/ocp_report_db_cleaner.py#L78

**Comment by blentz** [comment]
Moved: https://issues.redhat.com/browse/COST-108
