### ISSUE TITLE
Remove Preferences API as this is becoming a platform feature

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1811]
**Describe the bug**
Instead of cost management having preferences, this will be handled at the platform level.
We should remove our API endpoint and align with the platform team as this rolls out.

**To Reproduce**
1. Go to 'api/cost-management/v1/preferences/'
2. See valid API which needs to be removed

**Expected behavior**
We should not support the preferences API, but utilize the platform version.

**Comment by lcouzens** [comment]
Verified! I just need to remove the IQE preference tests we have.
