### ISSUE TITLE
Fix iqe makefile targets to be more fedora-friendly

### ISSUE THREAD

**Issue by Red-HAP** [project-koku/koku#1819]
**Describe the bug**

On Fedora (or any non-mac system) the mount directories should have their filemodes changed for `o+rwx` so that when mounted in the containers, they can be accessed proverly. 

There is also an issue with the `docker-reinitdb` targets in that they currently fail when containers are running. This is because they do not detect when koku-server is running and try to run a server directly with `manage.py runserver` then attempt to kill any command executing `manage.py runserver` which, with escalated permissions, will kill containers. 

The `reinitdb` targets should detect when koku-server is not running and start it. Else, they should both use the `--bypass-api` argument.

**To Reproduce**

1. make docker-up
2. make docker-reinitdb (fails on Fedora)
3. make docker-iqe-smokes-tests (fails on Fedora at the reinitdb step)

**Expected behavior**

For reinitdb, it should execute without failure.
For the iqe tests, the directories under ./testing should be set to `o+rwx` before the tests are run

**Screenshots**

**Context (please complete the following information):**

 - Fedora

**Additional context**

**Comment by adberglund** [comment]
This was tackled alongside other work
