### ISSUE TITLE
List of OpenShift Tag Keys Returns All or Enabled

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1834]
## User Story
As a customer, I want to be able to query only on enabled OpenShift tags, but also be able to see all OpenShift tags when enabling tags, so that I am only presented with relevant tags when performing queries.

## Impacts
- API

## Assumptions:
None

## Implementation Details:
On the OpenShift tag API support an “enabled_only” query parameter. Default behavior for “enabled_only” is true, the user can provide false and will see all available tags (paginated). Each tag key object will have an “enabled” field that will be set to true or false. Tag keys are defaulted to “enabled=false” until enabled using the settings.

##Acceptance Criteria:
- [ ] Verify that the OpenShift tag API returns only enabled tags by default
- [ ] Verify that passing enabled_only=false will return all the OpenShift tags
- [ ] Verify that tag key objects have a field that indicates whether the tag is enabled or not
- [ ] Verify that providing not true or false to enabled_only results in a 400

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:

Chris: We could have them all enabled by default at first, then when you get to the Enabling Settings flow, we could flip a switch to everything is disabled by default until we mark it as enabled. This story is a nicer way to view for testing and when the UI needs to show a drop down of tag keys.

**Comment by lcouzens** [comment]
Verified
