### ISSUE TITLE
OpenShift Cost should Summarize based only on Enabled Tags

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1835]
## User Story
As a customer, I want OpenShift cost data to summarize only on enabled tags, so that less data is stored and queries run as fast as possible.

## Impacts:
- Worker
- API

## Assumptions:
- A table exists that defines the enabled tags for an account

## Implementation Details:
- Update the existing cost summarization logic to drop tag keys that are associated with tags that are not enabled.
- When returning data via the report API only data from enabled tags are returned

## Acceptance Criteria:
- [ ] Verify that existing test cases (unit and QE) still pass
- [ ] Verify that tags that aren't enabled are not used for summarization in our task
- [ ] Verify that tags that aren't enabled don't show up in reports APIs

**Comment by adberglund** [comment]
@adberglund to look at specific worker flow requirements.

**Comment by nbon12** [comment]
Sprint Planning Discussion:
Andrew: Are we talking about all data or just Openshift on cloud? At what level do we want to filter this?
Chris: If I was in openshift view for details show a list of keys, then that is only the summarized data from those enabled tags. 
Andrew: I think this is more an API thing than worker, if they're just grouping by account or Node, we want all data available not just if they're tagged.
Chris: This is the cost pieces.
HAP: The enabled/disabled feature is tag-key level or tag-key-value level? 
Chris: Tag-key
Andrew: I'm trying to think of where in the worker flow we need to change. I'll look into this.

**Comment by chambridge** [comment]
@adberglund Should the following files be updated to join on tag_keys present in `reporting_ocpenabledtagkeys`?
- reporting_ocpusagelineitem_daily_summary.sql
- reporting_ocpawscostlineitem_daily_summary.sql
- reporting_ocpazurecostlineitem_daily_summary.sql

For example:
- [OCP - create temp table of reduced tags](https://github.com/project-koku/koku/blob/master/koku/masu/database/sql/reporting_ocpusagelineitem_daily_summary.sql#L12)
- [OCP on AWS](https://github.com/project-koku/koku/blob/master/koku/masu/database/sql/reporting_ocpawscostlineitem_daily_summary.sql#L31-L76)
- [OCP on Azure](https://github.com/project-koku/koku/blob/master/koku/masu/database/sql/reporting_ocpazurecostlineitem_daily_summary.sql#L26-L71)

Or do you think there is more to it than that?

**Comment by lcouzens** [comment]
Verified
