### ISSUE TITLE
Grafana dev monitor should be RHEL/CentOS based

### ISSUE THREAD

**Issue by Red-HAP** [project-koku/koku#1839]
A community container was used for the dev monitor (grafana) which was based on alpine. This should be replace with one that is based on RHEL or CentOS.

**Expected behavior**
Grafana container should be based on RHEL or CentOS instead of alpine.

**Context (please complete the following information):**
 - RHEL Openshift

**Additional context**
The current container will cause issues with RHEL Openshift depoyment. 

**Question**
Is this an issue since this iwas desinged to be a localdev tool?

**Comment by kholdaway** [comment]
Here's a potential image --> https://access.redhat.com/containers/?tab=images#/registry.access.redhat.com/openshift3/grafana
