### ISSUE TITLE
Sources serializer should not display client_secret

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1856]
**Describe the bug**

The list/get for sources shows the client_secret. 

**To Reproduce**
1. Populate an Azure source
2. Go to `/api/cost-management/v1/sources/`
3. See error

**Expected behavior**
We should not return the client_secret in the response data.

**Comment by lcouzens** [comment]
I am still seeing the secret show up locally and on CI, this maybe need further investigation.

**Comment by lcouzens** [comment]
Verified!
