### ISSUE TITLE
Clean up providers in databases

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1869]
## User Story
As a developer I want our provider table to only reflect what exists in platform sources so that no errant providers cause issues.

## Impacts
- Database

## Assumptions
- We need to either 
  a) remove a provider if there is no source
  b) create a source if we need the provider

## Acceptance Criteria

- [ ] CI Database has a 1:1 relationship between providers:sources
- [ ] Prod Database has a 1:1 relationship between providers:sources

**Comment by Red-HAP** [comment]
@adberglund 
Is any action needed if there is a source with a null koku_uuid column?

**Comment by Red-HAP** [comment]
Research can be found at this link:
https://drive.google.com/file/d/1VAVACjGT6uunJOxBzoiZIVPZvJE595eM/view?usp=sharing

**Comment by Red-HAP** [comment]
@adberglund 
I just re-ran my check sql against production. There were no rows returned. I think the issue of the unlinked or missing providers and sources has been resolved.

**Comment by adberglund** [comment]
@Red-HAP Let's close this up then. I'm comfortable moving directly to close as there's no functionality for QE to test.
