### ISSUE TITLE
Gather AWS Organizational Unit Data

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1894]
## User Story
As a user viewing AWS data I want to be able to view costs by organizational unit so I can understand the cost associated with each unit (e.g. a cost center or app team, et cetera).

## Impacts
- API
- Docs

## Assumptions
- Organizational units are a tree structure and we want to crawl the AWS APIs to get each level and the accounts associated with that org unit
- There are a few ways to store tree structures in a relational DB (see https://bitworks.software/en/2017-10-20-storing-trees-in-rdbms.html), but I'm inclined to pick the materialized path in that link (possibly using the ltree extension for fast lookups) 
    - This would allow for searches against the org_unit_name column to get only the accounts in a specific org unit or partial string search against the path to the org unit column to rollup all costs in accounts under a parent org unit 
    - Interested in this approach as I believe it would be achievable without writing raw recursive SQL in Django
    - This would lead to a database with columns

| id | org_unit_name | path.to.org_unit_name | account | created_timestamp |
 | --- | --- | --- | --- | --- |
| 1 | root | root | account_1 | 2020.03.01T00:00:00Z |
| 2 | big_org_unit | root.big_org_unit | account_2 | 2020.03.01T00:00:00Z |
| 3 | big_org_unit | root.big_org_unit | account_3 | 2020.03.01T00:00:00Z |
| 4 | sub_org_unit | root.big_org_unit.sub_org_unit | account_4 | 2020.03.01T00:00:00Z |
| 5 | sub_org_unit | root.big_org_unit.sub_org_unit | account_3 | 2020.03.05T00:00:00Z |

### AWS Organizational Units Notes
- list-roots (https://docs.aws.amazon.com/cli/latest/reference/organizations/list-roots.html)
  - boto3 doc: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations.html#Organizations.Client.list_roots
- list-organizational-units-for-parent (https://docs.aws.amazon.com/cli/latest/reference/organizations/list-organizational-units-for-parent.html)
  - boto3 doc: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations.html#Organizations.Client.list_organizational_units_for_parent
- list-accounts-for-parent (https://docs.aws.amazon.com/cli/latest/reference/organizations/list-accounts-for-parent.html)
  - boto3 doc: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations.html#Organizations.Client.list_accounts_for_parent

- Currently we get account aliases for AWS here: https://github.com/project-koku/koku/blob/master/koku/masu/processor/orchestrator.py#L147

## Acceptance Criteria

- [ ] We can successfully populate a database table with all of the organizational units and associated accounts from an AWS parent account
- [ ] Any IAM permissions updates have been documented

**Comment by myersCody** [comment]
**Update:**
Since we are currently in a hardening state, this pr has been approved, but merged into the feature branch: `final_aws_org_unit_featuer`
- https://github.com/project-koku/koku/tree/final_aws_org_unit_feature

@lcouzens we went ahead and moved the issue to QA since it was merged into the feature branch. However, it may be easier to wait to review the organizational unit feature as a whole which will be ready when the feature branch is merged into master.

**Comment by lcouzens** [comment]
Closing this in favour of the issues in Jira
