### ISSUE TITLE
Currency conversions

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#19]
## User Story
As a user, I want to see my costs in the payment currency so that they are the same ones used in the AWS bills. I will be able to see costs in both USD and the chosen currency.

## Assumptions

- It is possible to gather the currency conversion rate from Amazon Service LLC.
- The system will be using a disclaimer whenever there is a rate that can change

## Implementation details

Amazon converts the bill to a preferred currency after your bill is finalized. Until then, all of the preferred currency amounts shown in the console are estimated in USD. AWS guarantees your exchange rate, so that refunds use the same exchange rate as your original transaction.

## Acceptance Criteria

- [ ] Verify that the rate used to show costs is available in both a specified currency and USD (default is only USD if no alternative currency preference was specified).

**Comment by blentz** [comment]
https://currencylayer.com/ is probably the best web API for exchange rates. It returns JSON, which is easy to interact with using `requests`.

There's also the `CurrencyConverter` library, which defaults to using data from the European Central Bank. (See: https://pypi.org/project/CurrencyConverter/ )

In general, I think this should be implemented in two parts.

1. We should cache exchange rates for performance and resiliency reasons. So, we'll need a scheduled async task to fetch and store rates on some regular interval.
2. We'll need to query our rate cache and do internal conversions in order to return data using the customer's preferred currency.

**Comment by chargio** [comment]
many companies (most), have specific currency conversion rates. 
Red Hat does it, Oracle too. They set up a conversion rate every 6m or 12m and stick to it.
It would be good to replicate that:
- Use company currency conversion rate. The customer can set it up for a period of months.
- Use provider (AWS, Azure, etc), conversion rate.
- Use online conversion rate.

This can be split in several use cases.

**Comment by blentz** [comment]
Cloud providers do not provide an API or any public information on what exchange rates they use, or how often and when they are updated.

So, that's not an option.

**Comment by blentz** [comment]
Also, see my comments in #264. We need to define the expected behavior before we begin implementation.

**Comment by chargio** [comment]
We need to provide both customer based currency conversions based on online services (that will vary every time the customer connects) and customer defined currency conversion.
I would go with two use cases for non finished invoices:
- Default, the customer does not define currency conversion, we use an online service to provide the conversion. Every time we calculate the values, we use the new currency conversion table (that will be updated x times per day). There can be slight differences in the converted currency values, so we will show the original currency, the exchange rate applied, and the currency in the customer selected currency.
- If the customer has defined a currency exchange rate, that will be used. The result will be always the same because the rate is the same, but we need to define the workflows to define the currency exchange rate and use it.

Once the bill is finalised, AWS provides the data in the final currency with their own currency exchange. We will use that data instead of the USD data.

Opening several use cases to reflect this.
For the short
