### ISSUE TITLE
Update API documentation

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#190]
---
name: API documentation needs to be updated

---

**Describe the bug**
openapi.yml and the openAPI view documentation needs to be verified and updated as needed.  I'm seeing a lot of error cases (401 and 403) responses are not documented.

As a stretch goal for this user story an automated verification system should be implemented to verify that OpenAPI documentation is updated as part of the regular automated test process.

**Comment by chambridge** [comment]
@LandoCalrizzian Was going to try and provide information on QE mechanisms for automated testing of API via swagger and generated client.
