### ISSUE TITLE
App Settings wording update needed

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1906]
**Describe the bug**
Update Text:
"Enable your OpenShift label names to be used as tag keys **for** report grouping and filtering."

**To Reproduce**
1. Go to `/beta/settings/applications/cost-management`
2. See error

**Expected behavior**
Text should read:
"Enable your OpenShift label names to be used as tag keys **for** report grouping and filtering."

**Screenshots**
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/29379759/76782415-a2090480-6786-11ea-803d-1c9f11585da6.png">

**Additional context**
https://github.com/project-koku/koku/pull/1897#issuecomment-599640087

**Comment by chambridge** [comment]
@dayleparker FYI ^

**Comment by dchorvat1** [comment]
verified
