### ISSUE TITLE
Enable pg_stat_statements in prodution RDS database

### ISSUE THREAD

**Issue by Red-HAP** [project-koku/koku#1921]
## User Story

As a developer, I want to be able to examine query performance in production.

----

This will require the addition of the `pg_stat_statements` shared library added to the PostgreSQL config as well as the requisite settings for that library that will be tuned for practical production usage.

Also, a script providing access to the `pg_stat_statements` view with superuser privileges without superuser credentials. Access to this function **must** be explicitly be granted to a known database user or role.

Another function should be created wrapping the `pg_stat_statements_reset()` function should be created to allow for the reset of the statistics data collection.

Coordination and explicit instructions for the SRE team (assuming that they will be the ones to implement) must be provided along with any SQL scripts that should be run as the superuser.

This work **must** be completed before other query monitoring work can be accomplished in production.

## Impacts

Database

## Role

Developer, SRE

## Assumptions

- [X] ~Certain superuser access will be granted to a known non-superuser database role or user~ (not necessary, insights user has sufficient priveleges)
- [ ] SRE will be implementing these changes

## Caution

Since the database was initially used without `pg_stat_statements`, its inclusion now **will require a database restart**. If the production database is currently set for Multi-AZ, then there should be very minimal impact to users. If not, then there will be a down time for however long it takes for RDS to restart the database and for it to be available for connections.

## Acceptance Criteria

- [X] Role or user to which certain admin-level functionality is granted **must** be identified (insights)
- [X] ~This role and the functionality must have the proper communication and any required sign-offs acquired~ (not necessary, existing user has sufficient privs)
- [X] ~SQL script deliverable for pg_stat_statements wrapper functionality must be written in an idempotent design.~ (not necessary, the extension can be created by the user to which we have access)
- [x] **Clear and explicit** instructions must be written for implementation

**Comment by blentz** [comment]
From here:  https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html

```
Performance metrics – The pg_stat_statements module is included in shared_preload_libraries by default. This avoids having to reboot the instance immediately after creation. However, this functionality still requires you to run the statement CREATE EXTENSION pg_stat_statements;. Also, track_io_timing is enabled by default to add more granular data to pg_stat_statements. 
```

**Comment by Red-HAP** [comment]
This is my confusion:
```
koku=> show shared_preload_libraries;
 shared_preload_libraries 
--------------------------
 rdsutils
(1 row)
```

If pg_stat_statements was loaded, then the library should show up here.

**Comment by Red-HAP** [comment]
Local dev DB shows this:
```
postgres=# show shared_preload_libraries;
 shared_preload_libraries 
--------------------------
 pg_stat_statements
(1 row)
```

**Comment by Red-HAP** [comment]
But if we can just try to create the extension, then so much the better.

**Comment by blentz** [comment]
@Red-HAP - Are you able to run `CREATE EXTENSION pg_stat_statements;` like the docs say we need to, first?

**Comment by blentz** [comment]
update:  we tried the `CREATE EXTENSION` command suggested by the AWS docs during a video conference. It appears that the extension needs to be created and then the RDS instances needs to be rebooted. So, we'll need to coordinate a scheduled reboot through the platform SREs.

**Comment by Red-HAP** [comment]
With Andrew, Brett, and myself in attendance in a live session, we attempted to created the pg_stat_statememts extension in production. The extension could be created, but it was not able to be used as my analysis was correct and the shared library was not loaded.

The insights user was also listed as a rds_superuser and we will try to get the extension up and running with that user without having to write funcation wrappers around everything.

**Comment by Red-HAP** [comment]
![RDS_console_PostgreSQL_parameter_changes](https://user-images.githubusercontent.com/59652772/78918727-d5c20c00-7a5e-11ea-88cc-c00e7862cac4.png)

Saving preliminary RDS console parameter group change recommendations

**Comment by Red-HAP** [comment]
@adberglund @chambridge 
Link to document detailing [RDS parameter changes](https://docs.google.com/document/d/1xthcX8yRGcV7MPTcWSg3M59KoBfSGIkagnP3mONP3g0/edit?usp=sharing) for the production database.

**Comment by adberglund** [comment]
@Red-HAP parameters seem fine to me! Have we created a ticket and/or are we doing this ourselves?

**Comment by Red-HAP** [comment]
@adberglund 
If we have access to the RDS console, we can do this ourselves. The assumption I had made was that only SRE will have access to those controls.

**Comment by Red-HAP** [comment]
Post-configration and reboot instructions can be found [here](https://docs.google.com/document/d/1WlsNirqf4wj_2VLw6M_SotmdXk1RbM3AVJbiJvIrPcA/edit?usp=sharing)

**Comment by Red-HAP** [comment]
Ops ticket for parameter changes is here: https://projects.engineering.redhat.com/browse/RHIOPS-717
