### ISSUE TITLE
OpenAPI spec missing entries for OpenShift on All infrastructures

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#1935]
**Describe the bug**
There is no information in the OpenAPI spec for the OpenShift on All infrastructures endpoints

**To Reproduce**
1. Go to https://github.com/project-koku/koku/blob/master/docs/source/specs/openapi.json
2. Copy the contents of the file
3. Point browser to http://editor.swagger.io/
4. Paste content of spec
5. See error

**Expected behavior**
OpenAPI spec should contain information for the OpenShift on All endpoints

**Comment by lcouzens** [comment]
Verified
