### ISSUE TITLE
Provider create: Organization should be optional

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#194]
---
name: AWS organization should be optional when creating a provider.

---

**Describe the bug**
When attempting to create a provider in Koku and the AWS account user is not a member of *any* organization provider creation will fail.

**To Reproduce**
1. Follow [Koku Provider Documentation](https://koku.readthedocs.io/en/178-on-boarding-docs/providers.html)
2. Attempt to create a provider and you will be blocked due to AWSOrganizationsNotInUseException 

**Expected behavior**
The documentation does not state that organizations are optional.  Once Koku is updated to in fact optionally accept organizations the documentation should be updated.

**Screenshots**
```

ERROR An error occurred (AWSOrganizationsNotInUseException) when calling the DescribeOrganization operation: Your account is not a member of an organization.
Traceback (most recent call last):
  File "/Users/curtisd/projects/repos/provider_create_sa/koku/api/provider/serializers.py", line 128, in _check_org_access
    org_client.describe_organization()
  File "/Users/curtisd/py_env/koku/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/curtisd/py_env/koku/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AWSOrganizationsNotInUseException: An error occurred (AWSOrganizationsNotInUseException) when calling the DescribeOrganization operation: Your account is not a member of an organization.
WARNING "POST /api/v1/providers/ HTTP/1.1" 400 14997
```

**Comment by dccurtis** [comment]
@chargio 
For now we are going to lift the restriction for an organization when a provider is created.  I'll make a log of the fact that a provider was created without an organization and there will be no restrictions placed on the report views in this case.

I'm going to open a separate story for us to research organizations more generally and figure out how they should be incorporated into our product.

**Comment by chargio** [comment]
@dccurtis Thinks that come out of my mind:
- Is it possible for the user to be migrated into an organization in AWS. (https://aws.amazon.com/organizations/faqs/) If that is the case, what happens with the account in Koku? Are we capable of realizing that the account is now part of an organization?  (AWS CloudWatch events needed?)
- Question: There a way of getting out of an organization. (https://docs.aws.amazon.com/organizations/latest/APIReference/API_LeaveOrganization.html) What happens with accounts that are associated to that account then?
- One customer in Koku can map to different organizations, so we need to follow the full list of actions:
 * New user without organization creates an organization as master
 * New user without an organization is invited to one
 * Old user leaves an organization
 * Old user joins a new organization

All of them with and without accounts associated. If a user adds an organization and then leaves, it can happen that there is another user that is part of that organization in that user. Should we keep the organization?

**Comment by dccurtis** [comment]
Great points.  I'll paste these over to the research story #200 so we don't forget.
