### ISSUE TITLE
All tags/tag_keys are returned to /tags/openshift endpoint rather than just the enabled ones

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#1944]
**Describe the bug**
All tags/tag_keys are returned to /tags/openshift endpoint rather than just the enabled ones

**To Reproduce**
1. Add ocp source
2.  Enable a tag_key with Post `{"api": {"settings": {"openshift": {"tag-management": {"enabled": [tag]}}}}}` to v1/settings/
3. See /tags/openshift/ endpoint

**Expected behavior**
Should only see enabled tags/tag_keys returned

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: 2ca923c3a707f78c8145916218aca1268566187b

**Additional context**
Testing against CI

**Comment by chambridge** [comment]
So I figured out why it works fine in CI. The enable default of true only happens if the filter object is part of the query param: https://github.com/project-koku/koku/blob/master/koku/api/tags/serializers.py#L87

At least I get it now … and the UI will work, but shouldn’t be horrible to resolve otherwise.

```
{
    "meta": {
        "count": 3,
        "filter": {
            "resolution": "monthly",
            "time_scope_value": "-1",
            "time_scope_units": "month",
            "enabled": true
        },
        "key_only": true,
        "group_by": {},
        "order_by": {}
    },
    "links": {
        "first": "/api/cost-management/v1/tags/openshift/?filter%5Bresolution%5D=monthly&filter%5Btime_scope_units%5D=month&filter%5Btime_scope_value%5D=-1&key_only=true&limit=100&offset=0",
        "next": null,
        "previous": null,
        "last": "/api/cost-management/v1/tags/openshift/?filter%5Bresolution%5D=monthly&filter%5Btime_scope_units%5D=month&filter%5Btime_scope_value%5D=-1&key_only=true&limit=100&offset=0"
    },
    "data": [
        "storageclass",
        "environment",
        "app"
    ]
}
```

**Comment by lcouzens** [comment]
Verified!
