### ISSUE TITLE
Spike: Programmatically get list of products for cloud providers

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1963]
## User Story
As a user I want my filtered datasets in the UI to always reflect the whole array of services in a cloud provider so that none of my cost data is missing. 

## Impacts 
- API
- UI

## Spikessumptions
- Let's see if this part of the AWS billing API will give us a full list of products and product types: https://docs.aws.amazon.com/cli/latest/reference/pricing/get-products.html
- Let's see if this Azure API gives us the product data we need https://docs.microsoft.com/en-us/partner-center/develop/get-a-list-of-products

## Acceptance Criteria

- [ ] Yay or nay on AWS API
- [ ] Yay or nay on Azure API
- [ ] Open a new issue to load this data into our database for better service filtering in our data/APIs

**Comment by blentz** [comment]
I can speak to the AWS API's behavior.

The AWS billing API will only show you services that you have consumed. It's not an exhaustive list of all services that are available.

If we want the exhaustive list of all available services, we can pull from the Pricing API. The main index file has a list of all AWS services, with pointers to each service's Price List: https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/index.json

**Comment by jlalbertson** [comment]
Converted to JIRA issue: https://issues.redhat.com/browse/COST-104, closing this issue.
