### ISSUE TITLE
Support Currency

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#20]
## User Story
As an service, I want to support a set of available currencies. For each currency, it should be supported currency name, symbol, and number of decimal digits. The list should be compliant with ISO 4217 (https://en.wikipedia.org/wiki/ISO_4217)

## Assumptions
- As AWS presents charges in USD until the end of the period, it is possible that the same bill has to be calculated both in USD and in EUR.
- Currency is stored in a format that does not have redundancy errors. Number of decimal digits on the information stored it is not mandated by the number of digital digits of the currency. For instance, it is possible to store information with 12 decimal digits for a USD (that shows 2 decimal digits)

## Acceptance Criteria

- [ ] Verify that the currencies are available and properly identified by ISO numbers
- [ ] Verify that the customer can see reports and dashboards in the proper currency.
- [ ] Verify that the numbers calculated are identified with the proper currency.

**Comment by blentz** [comment]
See my comments in #264. This needs more specific expected behavior to be defined before we can implement it.

**Comment by chargio** [comment]
The requirements are here. This is a prerequisite for other use cases but it should be almost transparent to the user.

- For any calculation on costs, the number of decimal digits needs to be high enough. Using a library that provides that calculation is a need, or using our own system. Using 2 digits does not work because of redundancy errors.
- We need to use some decimal numbers, not float, as currency errors are not acceptable.
- The list of supported currencies is that of the ISO 4217. A customer should not have to open an RFE to support a new currency.

I would prefer the currencies to be available, but the user being able to select which ones are shown in the interface, so when they are defining rates they don't need to choose between a high list of currencies. This can also be achieved with a list of recently used currencies.
