### ISSUE TITLE
Research AWS Organizations

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#200]
Issue #194 and creating a provider in general is Koku's the first interaction with AWS Organizations.  We need to have a better understanding of what an organization is, how they are generally used in the industry, and what we should support in Koku.

## Acceptance Criteria

- [ ] Research and document AWS Organizations so that we know their capabilities and limitations.
- [ ] Research and document how AWS Organizations are used throughout the industry.
- [ ] Provide some proposals as to how Koku should handle AWS Organizations.

**Comment by dccurtis** [comment]
@chargio If you have any thoughts or requirements please document them here.

**Comment by dccurtis** [comment]
Comments from @chargio from #194 that are relevant here:

* Is it possible for the user to be migrated into an organization in AWS. (https://aws.amazon.com/organizations/faqs/) If that is the case, what happens with the account in Koku? Are we capable of realizing that the account is now part of an organization?  (AWS CloudWatch events needed?)
* Question: There a way of getting out of an organization. (https://docs.aws.amazon.com/organizations/latest/APIReference/API_LeaveOrganization.html) What happens with accounts that are associated to that account then?
* One customer in Koku can map to different organizations, so we need to follow the full list of actions:
* New user without organization creates an organization as master
* New user without an organization is invited to one
* Old user leaves an organization
* Old user joins a new organization
All of them with and without accounts associated. If a user adds an organization and then leaves, it can happen that there is another user that is part of that organization in that user. Should we keep the organization?

**Comment by dccurtis** [comment]
Updating acceptance criteria since how AWS orgs are used throughout the industry isn't directly relevant to how koku will use them.  We only need to know what they are and how cost usage reporting works with them.

**Comment by dccurtis** [comment]
## Acceptance Criteria
**Research and document AWS Organizations so that we know their capabilities and limitations.**
AWS Organizations gives AWS customers greater convenience and flexibility when working with multiple accounts.  The flexibility comes in the form of having consolidated service control policies and billing across all of the accounts in the organization.  Members of an organization can also create accounts without supplying any billing information since it’s wrapped up into the consolidated bill.  This enables a multi-tenant environment to have different organizational units such as development, test, production, or sandbox without having the burden of managing the financial aspects of creating the accounts.  In addition to the technical flexibility gains from Organizations; the consolidated bill enables organizations to more easily take advantage of volume discounts in the service rates.

Only the Master Account has access to the consolidated billing information with the cost and usage breakdown.


**Provide some proposals as to how Koku should handle AWS Organizations.**
* We should have a general understanding of what problems AWS Organizations is solving for the customer.  This will help influence our design decisions and allow us to ask relevant questions during customer interviews.
* Member accounts can not be added to koku since only the master account has access to the cost and usage reports.
* The master account is responsible for the bill; this is most likely the account that would be used while setting up HCCM (Sergio, what do you think?).  This user would want to have access to all of the organization’s accounts and most likely a way to view/group by Organizational Unit (see next item).  After setting up a sample AWS Organization, I was able to successfully download and process a consolidated bill from a master account S3 bucket.
* An Organizational Unit is a key aspect of AWS Organizations that I can imagine customers would want to surface in HCCM.  First thought is maybe this could be supported when we do tagging.
* If a member account leaves the organization and the master account is configured in koku then the data will still be available.
* I have verified that a master account's consolidated bill cost usage S3 bucket includes member accounts as `bill/UsageAccountId` and the master account number is in the `bill/PayerAccountId`.  I had no problems setting up the account in koku and downloading and processing the data in masu for this test organization setup.

**Comment by chargio** [comment]
Two comments:
- Organizations for us is a concept that we need to acknowledge but 
- Organizational Units should be mapped to our similar concept. Any kind of organisation that the customer is already done, should be mapped and reused.
- It is possible to get access to member accounts to the bills, but then you get access to everything. Using a visibility filter of our own, we can provide a better service than the out of the box experience given by AWS.

**Comment by dccurtis** [comment]
Agree with that Sergio.

So if the user is not using AWS Organizations they should be able to use our own similar concept to manually set it up.  If AWS Orgs are detected it would be nice to have those same labels/tags/groups populated automatically?

**Comment by chambridge** [comment]
Closing this as we've moved cost visibility to Q3 priority.
