### ISSUE TITLE
Return results in a single unit

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#203]
## User Story
When returning information to the UI for graphs, it is necessary in some moment to standardize the unit used (i.e. MB vs b)

The API will return the measures in a single unit (by group).

I.e. If memory and storage are reported together, the result will use one single measure, converting all results to that measure), If they are reported as separate groups, they will be reported in a single unit per group

## Impacts
API

## Role
Service

## Assumptions
- It is possible to identify one unit to report to (i.e. TB)
- It is possible to use one unit for all elements of the group (it can be that we need to report on one unit, but add the unit in each element of the response: 5 TB, not 5 and suppose TB is the standard)

## API Details

Data consumption must standardize on a unit of measure for each of the different data types. 

- Instance Usage: hrs
- Storage Usage: Gib - mo

## Acceptance Criteria

- [ ] Verify that consumed data is standardized to a single unit of measure as described above.

**Comment by chambridge** [comment]
Can you give an example report where this is going to happen?

It seems like AWS reports Storage/Memory in one consistent format, so I'm not clear on where this is needed, unless its to deal with beyond *Release 1*.

This story needs to be flushed out more for it to be testable.

**Comment by chargio** [comment]
For Release 1 it should be covered (although I am still working on details to make sure that there is no use case for that). The only consideration right now is to return the unit with the measure, not suppose that the measure is always the same.

For beyond, we will need this.  There can be huge differences in the way that measures are done in different platforms. CloudForms in fact, uses different untis for different providers, even for the same metrics

**Comment by chargio** [comment]
However, flvaour characteristics (i.e. TB of Memory) are not using a single measure, depending on the flavour you will have TB, TiB, MB, MiB.

```json
    "42UQFUQC2AD4Y6VV" : {
      "sku" : "42UQFUQC2AD4Y6VV",
      "productFamily" : "Compute Instance",
      "attributes" : {
        "servicecode" : "AmazonEC2",
        "location" : "Asia Pacific (Seoul)",
        "locationType" : "AWS Region",
        "instanceType" : "m3.xlarge",
        "currentGeneration" : "No",
        "instanceFamily" : "General purpose",
        "vcpu" : "4",
        "physicalProcessor" : "Intel Xeon E5-2670 v2 (Ivy Bridge/Sandy Bridge)",
        "clockSpeed" : "2.5 GHz",
        "memory" : "15 GiB",
        "storage" : "2 x 40 SSD",
        "networkPerformance" : "High",
        "processorArchitecture" : "64-bit",
        "tenancy" : "Dedicated",
        "operatingSystem" : "RHEL",
        "licenseModel" : "No License required",
        "usagetype" : "APN2-DedicatedUsage:m3.xlarge",
        "operation" : "RunInstances:0010",
        "capacitystatus" : "Used",
        "ecu" : "13",
        "normalizationSizeFactor" : "8",
        "preInstalledSw" : "NA",
        "processorFeatures" : "Intel AVX; Intel Turbo",
        "servicename" : "Amazon Elastic Compute Cloud"
      }
```


On tyhe other hand: youy can see that the storage is 2x40 DSDF (what unit?)

```
    "RNAPPKDKJ3TJXGN3" : {
      "sku" : "RNAPPKDKJ3TJXGN3",
      "productFamily" : "Compute Instance",
      "attributes" : {
        "servicecode" : "AmazonEC2",
        "location" : "Asia Pacific (Singapore)",
        "locationType" : "AWS Region",
        "instanceType" : "m4.10xlarge",
        "currentGeneration" : "Yes",
        "instanceFamily" : "General purpose",
        "vcpu" : "40",
        "physicalProcessor" : "Intel Xeon E5-2676 v3 (Haswell)",
        "clockSpeed" : "2.4 GHz",
        "memory" : "160 GiB",
        "storage" : "EBS only",
        "networkPerformance" : "10 Gigabit",
        "processorArchitecture" : "64-bit",
        "tenancy" : "Dedicated",
        "operatingSystem" : "Linux",
        "licenseModel" : "No License required",
        "usagetype" : "APS1-DedicatedUsage:m4.10xlarge",
        "operation" : "RunInstances:0200",
        "capacitystatus" : "Used",
        "dedicatedEbsThroughput" : "4000 Mbps",
        "ecu" : "124.5",
        "enhancedNetworkingSupported" : "Yes",
        "normalizationSizeFactor" : "80",
        "preInstalledSw" : "SQL Web",
        "processorFeatures" : "Intel AVX; Intel AVX2; Intel Turbo",
        "servicename" : "Amazon Elastic Compute Cloud"
      }
```

The requirement was done because it simplifies the UX

**Comment by LandoCalrizzian** [comment]
@adberglund I'm getting 500 errors when specifying units on a report with no instance data.

**Comment by LandoCalrizzian** [comment]
VERIFIED.
