### ISSUE TITLE
Incorrect copyright notice in DCO file

### ISSUE THREAD

**Issue by richardfontana** [project-koku/koku#2061]
**Describe the bug**
The DCO file has been modified from its original form by replacing the Linux Foundation copyright notice with a Red Hat copyright notice, and deleting the LF address. 

**To Reproduce**
View https://github.com/project-koku/koku/blob/master/DCO

**Expected behavior**
Should see a file completely identical to https://developercertificate.org

**Comment by blentz** [comment]
https://github.com/project-koku/koku/pull/2084
https://github.com/project-koku/koku-ui/pull/1521
https://github.com/project-koku/koku-doc/pull/51
https://github.com/project-koku/nise/pull/221
https://github.com/project-koku/korekuta-operator/pull/41
https://github.com/project-koku/korekuta/pull/154
https://github.com/project-koku/koku-daily/pull/3
