### ISSUE TITLE
Source status unavailable error messages should be actionable by a user to make their source available.

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#2075]
## User Story
As user, I want to have useful, actionable error messages displayed in the UI so I understand why my source is not available.

## Impacts
API, UI, Docs

## API Details

Source Status is pushed to the platform in the following situations:
* The Sources client provides a `source-status` endpoint which the platform calls periodically to get source status.
* Source create and edits

`SourcesHTTPClient().set_source_status()` is used to push the status to the platform

## UI Details
No changes needed to the UI.  Ensuring that we are pushing appropriate user facing strings to the platform is all that's required.

## Acceptance Criteria

- [ ] All possible source status strings are known and have been reviewed by a Docs engineer 
- [ ] Functional tests have been run to demonstrate that all status strings are populated in the platform sources database for source create, update, and source-status API call

**Comment by adberglund** [comment]
@dccurtis Do you want to add a link to the message spreadsheet here?

**Comment by dccurtis** [comment]
Sheet used to review messages with docs: https://docs.google.com/spreadsheets/d/1BgweFAhU3RAU30Bj1rzYQcVxwOBWS1WUBYyjlvD-bFY/edit?usp=sharing

**Comment by lcouzens** [comment]
Verified
