### ISSUE TITLE
Node labels dont seem to be getting ingested in CI/QA but do locally

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#2081]
**Describe the bug**
Node labels dont seem to be getting ingested in CI/QA but do locally

**To Reproduce**
1. Add ocp source with Node labels/tags
2. Ingest data
3. Go to 'api/cost-management/v1/tags/openshift/?filter[enabled]=false'
4. See no tags set at node level

**Expected behavior**
Should see tags set at the node level

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: 7472b8e64e3b2dd1026555fd9dbc256bc69d6457

**Additional context**
Automation test failing in vortex 'test_api_ocp_tag_node_to_pod_level'

Tried running this against CI and QA manually and I see the same issue, however if I run it locally it passes. Perhaps there is something different locally because of using dev=True?

Also as a side note I assume this prevents the UI 'Tag key enablement' working for node tags too since we dont ingest them.

Heres my tags endpoint locally:

```
    "data": [
        {
            "key": "volume",
            "values": [
                "stor_echo"
            ],
            "enabled": true
        },
        {
            "key": "volqe",
            "values": [
                "stor_qe",
                "rock"
            ],
            "enabled": false
        },
        {
            "key": "node",
            "values": [
                "asuna"
            ],
            "enabled": true
        },
        {
            "key": "app",
            "values": [
                "echo"
            ],
            "enabled": true
        }
    ]
}
```

Vs CI/QA From this you can see the ` "key": "node",` and value is missing from the output

```
 },
    "data": [
        {
            "key": "volume",
            "values": [
                "stor_tiers",
                "stor_echo"
            ],
            "enabled": true
        },
        {
            "key": "volqe",
            "values": [
                "stor_qe",
                "rock"
            ],
            "enabled": false
        },
        {
            "key": "app",
            "values": [
                "teirs",
                "echo"
            ],
            "enabled": true
        }
    ]
}
```

**Comment by adberglund** [comment]
Try running ingestion of data with DEVELOPMENT=True and DEVELOPMENT=False and both ways check the node DB tables and OCP tag summary tables to see where the data is falling out.

**Comment by nbon12** [comment]
Sprint Planning Meeting Notes:
Andrew: My suspicion is that they are getting ingested it's just probably the tag summary SQL isn't happening."
Chris: Is this when you run it against CI / QA yourself or via smoke test?
Luke: This was failing on vortex, I tried it locally and it did the same thing. I tried it locally again and it worked correctly so I'm not entirely sure.
Andrew: A good first step is running locally with development=TRUE and development=FALSE and see if you get the same result.
Brett: Looking at the data structures in the post, what are the outputs supposed to be?
Doug: In this case it's missing data
Luke: I have tag labels on a specific node, and I'm expecting to see that in the output.

**Comment by adberglund** [comment]
This was caused by two missing rows in the `reporting_common_reportcolumnmap` table. We had a PR out to switch from using that table to a static Python data structure, so we should no longer have a problem with keeping that table updated.

**Comment by lcouzens** [comment]
Verified!
