### ISSUE TITLE
Manifests Still Being Double Processed

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#2094]
**Describe the bug**
A particularly large manifest was processed 3 times on April 22. It should have only been processed 1 time. 

**To Reproduce**
1. Need to figure out how

**Expected behavior**
We should correctly identify that we finished processing the manifest or that we still have a running task. 

**Additional context**
- Logs: https://kibana-kibana.1b13.insights.openshiftapps.com/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2020-04-22T00:00:00.000Z',mode:absolute,to:'2020-04-22T23:59:59.000Z'))&_a=(columns:!(_source),filters:!(),index:'0a2575c0-65f9-11e9-ba88-097c6c9f6850',interval:auto,query:(language:kuery,query:'@log_stream:+%22koku-worker%22+AND+%22e096fb21-cff3-4223-bc2c-783c949cfbb6-chance-50.csv.gz%22'),sort:!('@timestamp',desc))

**Comment by lcouzens** [comment]
Verified
