### ISSUE TITLE
Consolidate refresh materialized view calls

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#2098]
## User Story
As a developer I want one block of code refreshing my materialized views so that we keep overall complexity lower. 

## Impacts
- Worker

## Assumptions
- First, check that it is okay to remove https://github.com/project-koku/koku/blob/163b0a80a0400dd0ca5fdc53dfb1d9d62775c395/koku/masu/processor/ocp/ocp_cloud_summary_updater.py#L171
- If that is okay, add OCP_ON_AWS_MATERIALIZED_VIEWS,  OCP_ON_AZURE_MATERIALIZED_VIEWS, OCP_ON_INFRASTRUCTURE_MATERIALIZED_VIEWS be called in https://github.com/project-koku/koku/blob/163b0a80a0400dd0ca5fdc53dfb1d9d62775c395/koku/masu/processor/tasks.py#L331

## Acceptance Criteria

- [ ] All materialized views are updated after summary data updates
- [ ] API data is gone once relevant sources have been removed (OpenShift + AWS/Azure)

**Comment by adberglund** [comment]
Also worth looking at PLPGSQL function to update views.

**Comment by jlalbertson** [comment]
Converted to Jira issue: https://issues.redhat.com/browse/COST-103, closing this issue.
