### ISSUE TITLE
Support VM resizing

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#21]
As an admin, I want to be able to charge for VM that are resized, so I can accurately present costs of physical infrastructure in a virtual and cloud environments.

## Acceptance Criteria

- [ ] Verify that the costs are accurate when no change is done in a period
- [ ] Verify that the costs are accurate when there are changes in the VM (or storage) for the period.  
- [ ] Charges will be related to each other, and will be visually different than two different VM

## Assumptions and Questions

- There is a source that specifies the size and/or flavours of the VM at each time.
- It is possible to identify the moment when the charge is done

**Comment by chambridge** [comment]
Closing this issue. It has been capture in another tool for future breakdown.
