### ISSUE TITLE
API Support for "Other" categorization

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#224]
## User Story
As an API consumer, I want a way to aggregate the "long tail" costs so that my pie charts don't suck.

## Impacts
UI, API

## Role
User

## Assumptions
- For use by authenticated user

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/(costs | inventory) |
 | **Query Param** |  filter[top]=5 |

## UI Details
For a pie/donut chart, we want to only display 4-5 elements (10 elements, worst case). For a "total cost" pie chart, we need to aggregate anything into an "Other" category that is too small to fit into a top or top set of results.

## Acceptance Criteria

- [ ] API query for data can flag to return "top" X results with a boolean that selects whether we include an "other" category.
- [ ] API will fail gracefully when no data is present.

**Comment by LandoCalrizzian** [comment]
VERIFIED. Including filter[limit]=X correctly separated the data into X named items and 1 "Other" item
