### ISSUE TITLE
User specification for Cost Usage Report

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#232]
## User Story
As an API consumer, I want to designate which Cost Usage Report I want to monitor in my S3 bucket.

Background: There can be multiple Cost Usage Reports in a single S3 bucket.  We need the customer to tell us which report they want to monitor with Koku.

Some things to keep in mind:
* We may need some clarification from PM clarify the requirements with respect to processing a single or multiple CUR that a customer may have.
* The on-boarding experience needs to be thought out to incorporate CUR selection.
* This setting will have to be accessible through the shared database for Masu to know what report to fetch.

## Impacts
UI, UX, API

## Role
User

## Assumptions
- For use by a regular user or customer owner (Same permissions as adding a Provider)

## API Details
TBD: Probably would get included in the add Provider workflow

## UI Details
Some way for a user to specify which Cost Usage Report in the S3 bucket they want to monitor.  Getting a list of available reports to select would be the most user friendly.

## Acceptance Criteria

- [ ] During on-boarding (or Provider add) the user must specify which CUR they would like Koku to monitor.

For Koku the acceptance criteria can be validated with unit test to ensure that the setting is saved in the database.  During integration testing with Masu we can verify that the correct CUR is downloaded.

**Comment by chambridge** [comment]
User should provide `report_prefix` to specify the CUR report to process when creating a Provider.

**Comment by dccurtis** [comment]
Opened June 2018...
