### ISSUE TITLE
Create a DCO

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#235]
Best practices in the BU are to include a Developer Certificate of Origin, signing the commits to verify that the code is free to use.

The code so far has been developed by RH engineers, and that we can easily change the license, but we should update it to reflect best practices.

Text:

 https://github.com/ansible/awx/blob/devel/DCO_1_1.md

  In CONTRIBUTING.md (can also be in README.md):

 https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md#things-to-know-prior-to-submitting-code

**Comment by blentz** [comment]
https://github.com/project-koku/koku-doc/pull/45
https://github.com/project-koku/koku-ui/pull/1455
https://github.com/project-koku/korekuta-operator/pull/25
https://github.com/project-koku/korekuta/pull/147
https://github.com/project-koku/nise/pull/218
https://github.com/project-koku/koku/pull/2009
