### ISSUE TITLE
Cost reporting query params are validated but not implemented

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/koku#242]
**Describe the bug**
Cost reporting query params are validated but don't appear to actually work when specified. Including a custom query for:
Descending order "?order_by[cost]=desc" doesn't affect the order of the cost data returned
Last 10 days "?filter[resolution]=daily&filter[time_scope_value]=-30&filter[time_scope_units]=day" returns costs for the last 30 days

Query params will be validated to make sure that daily time_scope_value is -10 or -30 and monthly time_scope_value is -1 or -2

**To Reproduce**
1. Nise: Create csv data
2. Koku: Create db
3. Koku: Run "make oc-create-test-db-file" and start koku
4. Load the data into masu and start masu
5. Run report queries 

**Expected behavior**
Query params affect the data returned via the api

**Context (please complete the following information):**
 - OS: Fedora 27
 - Browser: Chrome
 - Commit Hash from status endpoint: d3848b1

**Comment by chambridge** [comment]
This is true, but the fact is just isn't implemented yet.

Current query support only focused on adding support the described following:
https://github.com/project-koku/koku/pull/233

Will leave this open so that it can be tested when added. But wasn't a requirement for for the total cost trend story.

**Comment by blentz** [comment]
@LandoCalrizzian says this is done. Moving to review/qa.

**Comment by nachandr** [comment]
Verified that the cost reporting query parameters are working like they should.

1)http://localhost:9000/api/v1/reports/costs/?filter[resolution]=daily&filter[time_scope_value]=-10
The above  query returns daily data for the last 10 days.

Similarly,the following query returns data for the last 30 days.
http://localhost:9000/api/v1/reports/costs/?filter[resolution]=daily&filter[time_scope_value]=-30

2)http://localhost:9000/api/v1/reports/costs/?filter[resolution]=monthly&filter[time_scope_value]=-1
The above query returns monthly data for the current month.

Similarly, the following query returns data for the last month.
http://localhost:9000/api/v1/reports/costs/?filter[resolution]=monthly&filter[time_scope_value]=-2
