### ISSUE TITLE
region parameter missing when creating boto client

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#246]
**Describe the bug**
I was working on configuring a test provider. During new provider setup, when koku was checking access to the CUR service, it complained about a NoRegionError. 

A simple workaround is to specify `AWS_DEFAULT_REGION` in the openshift template as an environment variable. But, this only masks the real issue, which is that we need to specify a region when creating a boto CUR client.

**Comment by adberglund** [comment]
Yes to this! Since billing is "global" does it matter which region we specify? If so, we'll need to know a region per customer. If not, then a default sounds good. Likewise with S3. It's a "global" thing, but also has buckets in specific regions. Will we need to assign a region there too?

**Comment by blentz** [comment]
Correction: This isn't the client, it's the session. We need to specify `region_name` as a parameter when creating new `Session` objects.

(See: https://boto3.readthedocs.io/en/latest/reference/core/session.html )

To @adberglund 's question - the region requirement is service-specific. Some services require it (ec2), some don't (s3).

I know that S3 is geo-replicated, but it's "eventually consistent", so there can be delays in replication. You can access buckets and objects from any endpoint, but like @dccurtis mentions, things get "opinionated" when you mix-in other services.

**Comment by adberglund** [comment]
Yep, it is service specific. I was just trying to point specifically to that weirdness. If a service is "global" but boto3 still requires a region to be specified for it, we should figure out how specific we need to be with the region for that service. If it varies by customer then we'll need to collect that information from customers. I like having a default region specified, but I think we need to be careful with the boundary between our account and the assumed role into others' accounts. We can know our default region, but not a customer's, so we should explicitly set region where we can/need to when accessing a service as the assumed role into the customer's account.

**Comment by LandoCalrizzian** [comment]
VERIFIED. The AWS_DEFAULT_REGION environmental variable is no longer required when deploying the app
