### ISSUE TITLE
Default cost report total value doesn't equal the sum of the numbers listed in the data

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/koku#249]
**Describe the bug**
When running the default cost report for nise data uploaded to masu, the sum of the daily costs listed in the report isn't equal to the cost listed in the total

**To Reproduce**
1. Use nise to generate custom data
2. In koku, create a customer (make oc-create-test-db-file)
3. Start masu and upload data generated by nise
4. Login to koku as the test customer and hit /api/v1/reports/costs/

**Expected behavior**
The response[total][value] == sum (response data items[date][0][total])

**Screenshots**
![koku_cost_report_default](https://user-images.githubusercontent.com/2432396/42225452-957b0388-7eaa-11e8-848d-a11e6d65af3c.png)

**Context (please complete the following information):**
 - OS: Fedora 27
 - Browser: Chrome
 - Commit Hash from status endpoint: e64bbbf

**Comment by chambridge** [comment]
May have already fixed a bug for this in my latest PR as I don't see the same issue:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/29379759/42226808-e3ca57f2-7ead-11e8-94e2-48dad305beae.png">

**Comment by chambridge** [comment]
I'm closing this as fixed by:
https://github.com/project-koku/koku/pull/250


This branch is now in master can you still reproduce? If so please reopen and attach the mock data from Nise or S3 if possible.

**Comment by LandoCalrizzian** [comment]
I'm still hitting this issue but I have seen instances where it is calculated correctly. After some investigation, I found that the issue is that the response data doesn't include a cost item for the current day but the total appears to include it in the calculation.

Every day I generate new nise data using the command: nise --start-date <<START_DATE>> --output-file test_<<START_DATE>>-<<CURRENT_DATE>>.csv

**Comment by LandoCalrizzian** [comment]
VERIFIED. Daily and monthly cost reports are reporting the correct total when comparing the report total to the sum of each reported data line item
