### ISSUE TITLE
Group/filter cost data by region or availability zone

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#253]
## User Story
As user, I want to view my cost data grouped by region or availability zone so that I can understand my cost breakdown by location.

## Impacts
API, UI, Docs

## Role
User

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/costs/ |
 | **Query Parameters** | group_by[region]=<wildcard or region> ; group_by[avail_zone]=<wildcard or avail_zone>  |
**Response:**
```
{
  "group_by": {
    "region": [
      "*"
    ]
  },
  "order_by": {
    "cost": "asc"
  },
  "filter": {
    "resolution": "daily",
    "time_scope_value": -10,
    "time_scope_units": "day",
    "resource_scope": []
  },
  "data": [
    [
      [
        {
          "date": "2018-05-28",
          "regions": [
            {
              "region": "us-east-1",
              "values": [
                {
                  "date": "2018-05-28",
                  "units": "USD",
                  "region": "us-east-1",
                  "total": 1498.92962634
                }
              ]
            },
            {
              "region": "us-west-1",
              "values": [
                {
                  "date": "2018-05-28",
                  "units": "USD",
                  "region": "us-west-1",
                  "total": 1065.845524241
                }
              ]
            }
          ]
        }
      ]
    ]
  ]
}
```

Model fields:
region = `cost_entry_product__region`
avail_zone = `availability_zone`

## UI Details

Cost details page allows breakdown region/availability zone via combo box

## Acceptance Criteria

- [ ] Cost data is grouped by region/availability zone (dependent on group by parameter). Wildcard presents breakdown for all regions/availability zones with cost usage data.
- [ ] Cost data is grouped by region/availability zone for filtered set. Data returned only applies to the values matching the filtered set (i.e. group_by[avail_zone]=us-east-2c). Invalid regions or availability zones don't cause errors, data will just not match.
- [ ] If no data is present for the time period an empty date place holder without values will be provided.

___
Associated with: https://github.com/project-koku/masu/issues/85

**Comment by chambridge** [comment]
Another acceptance criteria for testing both region & az at the same time.

**Comment by LandoCalrizzian** [comment]
VERIFIED works with daily and monthly resolution
