### ISSUE TITLE
Order cost data by cost (ascending/descending)

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#254]
## User Story
As a user, I want order the cost data I'm viewing in ascending or descending order so that I can understand what is costing me the most or look at the minor expenses.

## Impacts
API, UI, Docs

## Role
User

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/costs/ |
 | **Query Parameter** |  order_by[cost]=asc, order_by[cost]=desc |

By default if not provide cost will be ordered in descending order with largest cost first.

## UI Details
UI provides controls to order by cost (ascending/descending)

## Acceptance Criteria

- [ ] Cost data is ordered by cost in ascending or descending order.
- [ ] Cost data is ordered by cost in descending order by default.

**Comment by LandoCalrizzian** [comment]
VERIFIED. Cost is ordered accordingly when order_by is included as a query param
