### ISSUE TITLE
 Group/filter cost data by account 

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#255]
## User Story
As user, I want to view my cost data grouped by account so that I can understand my cost breakdown by account.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- 

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/costs/ |
 | **Query Parameters** | group_by[account]=<wildcard or account>  |
**Response:**
```
{
  "group_by": {
    "account": [
      "*"
    ]
  },
  "order_by": {
    "cost": "asc"
  },
  "filter": {
    "resolution": "daily",
    "time_scope_value": -10,
    "time_scope_units": "day",
    "resource_scope": []
  },
  "data": [
    [
      [
        {
          "date": "2018-05-28",
          "accounts": [
            {
              "account": "8577742690384",
              "values": [
                {
                  "date": "2018-05-28",
                  "units": "USD",
                  "account": "8577742690384",
                  "total": 1498.92962634
                }
              ]
            },
            {
              "account": "9420673783214",
              "values": [
                {
                  "date": "2018-05-28",
                  "units": "USD",
                  "account": "9420673783214",
                  "total": 1065.845524241
                }
              ]
            }
          ]
        }
      ]
    ]
  ]
}
```
Model fields:
account = `usage_account_id`

## UI Details

Cost details page allows breakdown account via combo box

## Acceptance Criteria

- [ ] Cost data is grouped by account. Wildcard presents breakdown for all accounts with cost usage data.
- [ ] Cost data is grouped by account for filtered set. Data returned only applies to the values matching the filtered set (i.e. group_by[account]=accountA). Invalid accounts don't cause errors, data will just not match.
- [ ] If no data is present for the time period an empty date place holder without values will be provided.

**Comment by LandoCalrizzian** [comment]
VERIFIED
