### ISSUE TITLE
Group/filter cost data by service

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#256]
## User Story
As user, I want to view my cost data grouped by service so that I can understand my cost breakdown by service.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- 

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/costs/ |
 | **Query Parameters** | group_by[service]=<wildcard or service>  |
**Response:**
```
{
  "group_by": {
    "service": [
      "*"
    ]
  },
  "order_by": {
    "cost": "asc"
  },
  "filter": {
    "resolution": "daily",
    "time_scope_value": -10,
    "time_scope_units": "day",
    "resource_scope": []
  },
  "data": [
    [
      [
        {
          "date": "2018-05-28",
          "services": [
            {
              "service": "Storage",
              "values": [
                {
                  "date": "2018-05-28",
                  "units": "USD",
                  "service": "Storage",
                  "total": 1498.92962634
                }
              ]
            },
            {
              "service": "Compute",
              "values": [
                {
                  "date": "2018-05-28",
                  "units": "USD",
                  "service": "Compute",
                  "total": 1065.845524241
                }
              ]
            }
          ]
        }
      ]
    ]
  ]
}
```
Model fields:
service = `cost_entry_product__product_family`

## UI Details

Cost details page allows breakdown service via combo box

## Acceptance Criteria

- [ ] Cost data is grouped by service. Wildcard presents breakdown for all services with cost usage data.
- [ ] Cost data is grouped by service for filtered set. Data returned only applies to the values matching the filtered set (i.e. group_by[service]=Storage). Invalid services don't cause errors, data will just not match.
- [ ] If no data is present for the time period an empty date place holder without values will be provided.

**Comment by LandoCalrizzian** [comment]
VERIFIED
