### ISSUE TITLE
Filter cost data by account list without grouping

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#257]
## User Story
As a user, I want filter my cost data by a set of accounts so that I can see what a subset of my costs are.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/costs/ |
 | **Query Parameters** | ?filter[account]=accountA&filter[account]=accountC |

## UI Details

UI provides ability to filter data by account

## Acceptance Criteria

- [ ] Cost data is filtered by accounts for filtered set. Invalid accounts don't cause errors, data will just not match.
- [ ] If no data is present for the time period an empty date place holder without values will be provided.

**Comment by chambridge** [comment]
Assume input values are the Account ID

**Comment by LandoCalrizzian** [comment]
VERIFIED. I was able to filter on account without grouping
