### ISSUE TITLE
Filter cost data by service list without grouping

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#258]
## User Story
As a user, I want filter my cost data by a set of services so that I can see what a subset of my costs are.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/costs/ |
 | **Query Parameters** | ?filter[service]=Compute&filter[service]=Storage |

## UI Details

UI provides ability to filter data by service

## Acceptance Criteria

- [ ] Cost data is filtered by service for filtered set. Invalid services don't cause errors, data will just not match.
- [ ] If no data is present for the time period an empty date place holder without values will be provided.

**Comment by LandoCalrizzian** [comment]
VERIFIED. I was able filter by service without grouping
