### ISSUE TITLE
Export line item cost data (with context)

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#260]
## User Story
As a user, I want export the line item data so that can view the data with other reporting engines.

All current queries have been focused on providing aggregated by cost grouped by date, account, services, etc; however, there are views of the data not available in our current UI that if the user has access to the subset of data the can create those charts/reports.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- The user will only have access to the fields from the Cost Usage Report that we are storing in the database.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/costs/ |
 | **Query Parameter** |  ?operation=none; by default operation=sum to create an aggregation |

## UI Details

UI provides an export button. The export API call applies the query parameters that lead to the current UI context.
## Acceptance Criteria

- [ ] When an export occurs all line item values are returned matching the filter and grouping, but not group_by transformation will occur. Data is just returned in the group_by order.
- [ ] If no data is present for the time period an empty date place holder without values will be provided.

**Comment by LandoCalrizzian** [comment]
if operation and group_by[account]=AcctID is specified what is the expected outcome? Will AcctID just be ignored or is an error returned?

**Comment by chambridge** [comment]
@LandoCalrizzian I tried to cover this in the first acceptance criteria. The data returned will be filtered to `AcctID` and it will be grouped by account in the more traditional SQL mechanism.

Meaning you would expect to see:
```
"data": [
   { "account": "AcctID",  ... rest of line item data}
]
```

If you had done a group_by with `*` then all the data for each account would be clustered together in the data list.

**Comment by LandoCalrizzian** [comment]
After re-reading the description and my comment, everything makes sense now.

**Comment by LandoCalrizzian** [comment]
VERIFIED. It will export the data but further will need additional protections to prevent issues when data returned is sufficiently large
