### ISSUE TITLE
Provide grouped item delta (current month vs. last month)

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#261]
## User Story
As user, I want to view the delta between what I'm spending this month vs. last month so that I can understand if any of my spend is abnormal.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- API provides mechanism to specify what delta is relative to (i.e. last months total cost, last years total cost for same month)

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/costs/ |
 | **Query Parameters** |  |
 | **Body** |  |
 | **Response** | |

Need to develop a mechanism to do this via the API^.
Would return to new "columns" delta_total and delta_percentage

## UI Details
UI provides a list view of grouped items for the current month with a delta that shows the cost change compared to the previous month in currency units and percentage.

## Acceptance Criteria

- [ ] Data returns delta information relative to delta time scope
- [ ] delta_total and delta_percentage are null if the compared time scope didn't have a value for that item.

**Comment by LandoCalrizzian** [comment]
@chambridge Will delta_total and delta_percentage be included by default on all monthly reports w/ group_by or only when a specific delta query param is specified?

For the assumptions, are you going to have support for same month from last year if we are currently only supported 3month retention?

**Comment by chambridge** [comment]
@LandoCalrizzian The delta output will be controlled by a query parameter to minimize trying to produce this information on every query. We will work through this query parameter as we implement and update the issue.


We are only tackling current month compared to previous month. Anything else will create a 400 bad input response for now.

**Comment by LandoCalrizzian** [comment]
@chambridge Gotcha. Thx for the clarification

**Comment by LandoCalrizzian** [comment]
VERIFIED. I was able to generate delta's for month's with an increase & decrease(partial current month) in price
