### ISSUE TITLE
Locale support

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#264]
## User Story
As koku user, I want koku to be locale-aware so that I can see location-dependent details (currency, time zone, etc.) in my locale.

Note: This is a pre-requisite for #19 and #20

## Impacts
API, UI

## Role
HCCM Consumer

## Assumptions
- Units data is stored in a consistent manner
- 

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/PATCH/DELETE |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## UI Details
- User should be able to set Locale preferences - currency, time zone

## Acceptance Criteria

- [x] Currency preference can be set 
- [x] Time zone preference can be set
- [ ] API queries return data in the user's preferred Currency or Time Zone

**Comment by blentz** [comment]
After doing some investigation, I'm flagging this as needing additional discussion on what exactly we're looking to do and what the use cases for it are.

Requirements:
1. At a bare minimum, we can *not* display costs that are different than what's on the customer's invoice. If we tell somebody they should expect to spend $25k and their invoice says they owe $22k or $28k, that's going to make it very difficult to trust our tool's analysis.

Timezones:

Right now, AWS uses UTC for all datetimes. Everything we get from them is UTC.

1. Converting timezones during ingestion is a non-starter. It will cause too many problems for cost-calculations.

2. Converting timezones during reporting could cause confusion when Amazon says "Start date: 1-Sept-2018 00:00:00+0" and we tell the customer "Start date: 31-Aug-2018 22:00:00-2".   

This problem only gets worse when factoring in DST and the fact that for regions that observe DST, there are two distinct hours that are both 01:00:00-02:00:00.

Currencies:

Currency conversions are time-sensitive, as currency rates fluctuate over time. This means that if we include currency conversions in our estimates, that introduces variance and increases our margins of error. 

Just like with time zones, this can be seen as a negative by the customer and may reduce the trust they have in our application.


So, for both of these, I think we need to clarify the use cases and define the expected behaviors more precisely.

**Comment by chargio** [comment]
Timezones can get complicated when more than one provider is added. As soon as we add some provider that is not aligned with UTC (inc. on-premises), we will be needing to work this out.

https://aws.amazon.com/premiumsupport/knowledge-center/non-us-currency/

In Amazon, exchange rates are calculated when the invoice is generated, so any currency conversion will vary until the final moment of the invoice.

I see two ways to do this:
- Use both currencies. Show the invoice in the original currency (USD or Rupees), and show the result of the currency conversion. That gives accurate information, aligned with what they can see in their invoices until the end of the month, but with additional information about the rates that are being applied. Once the invoice is final (has an invoice number), we can calculate the currency conversion used.
- Keep non final invoices in USD or the original currency, until the moment where the invoice is final, and then we show both, or provide them in the final currency. Azure used to  provide pricing in the final currency (https://docs.microsoft.com/en-us/previous-versions/azure/reference/mt219004%28v%3dazure.100%29) 

I prefer number 1 as it is more clear what is going on. It also allows the customer to specify their currency rate when they have an internal currency conversion rate.

**Comment by blentz** [comment]
Moved: https://issues.redhat.com/browse/COST-117
