### ISSUE TITLE
Report inventory instance type: Total count different that sum of report line time count

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/koku#275]
**Describe the bug**
The inventory instance report total count is different than the sum of the count field from each returned line item.

**To Reproduce**
1. Generate and add nise data
2. call the instance trend endpoint /api/v1/reports/inventory/instance-type/

**Expected behavior**
The count property in the report total is the same number as the sum of the count from each line item

**Context (please complete the following information):**
 - OS: Fedora w/ local minishift instance
 - Commit Hash: e178aff

**Additional context**
I haven't tested this actual AWS data yet

**Comment by adberglund** [comment]
@LandoCalrizzian I think that's actually an acceptable state. We're using the SQL `DISTINCT` on counts so when we're breaking the counts down by day we might see 20 t2.smalls on one date, and 20 t2.smalls on the other day, they could be the exact same 20 so the total distinct count seen in the API time frame would be 20. 

Likewise you could see 20 on either day, and for some reason they shut down 10 machines on the first day, and started up 10 completely new instances the next day. So the count each day would be 20, but the total distinct count for the time period would be 30.

Here's an example with some real data I loaded where it's the same set of instances on either day.

```
koku=> SELECT count(DISTINCT resource_id), date(usage_start) FROM reporting_awscostentrylineitem li JOIN reporting_awscostentryproduct p on li.cost_entry_product_id = p.id WHERE p.service_code='AmazonEC2' AND p.instance_type IS NOT NULL GROUP BY date(li.usage_start);
 count |    date
-------+------------
   779 | 2018-06-22
   779 | 2018-06-23
(2 rows)

koku=> SELECT count(DISTINCT resource_id) FROM reporting_awscostentrylineitem li JOIN reporting_awscostentryproduct p on li.cost_entry_product_id = p.id WHERE p.service_code='AmazonEC2' AND p.instance_type IS NOT NULL;
 count
-------
   779
(1 row)
```

**Comment by LandoCalrizzian** [comment]
@adberglund This makes perfect sense now. This is just a docs issue to reflect that it's a distinct count of the instances for each line item and total

**Comment by chambridge** [comment]
@LandoCalrizzian  Would updates to swagger/apidoc make sense to you or are you thinking something in readthedocs?

**Comment by LandoCalrizzian** [comment]
@chambridge An update to the apidoc would be best. Just need a small comment to state the count is the distinct number of instances for the respective time period

**Comment by chambridge** [comment]
@LandoCalrizzian PR opened: https://github.com/project-koku/koku/pull/305
