### ISSUE TITLE
Units are not always available in report API results

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#298]
**Describe the bug**
We are relying on the pricing table's unit column to display the units for usage in our API. In our AWS account, we have a t2.micro instance that is covered under the free tier right now, and so the `unit` is coming through blank in the report. This means some results have units, while others do not.

**To Reproduce**
1. Load data from July in our AWS account
2. Run `api/v1/reports/inventory/instance-type/?filter[time_scope_value]=-2&filter[resolution]=daily`
3. View results

**Expected behavior**
All results returned should have units

**Screenshots**
<img width="462" alt="screen shot 2018-08-06 at 3 34 54 pm" src="https://user-images.githubusercontent.com/3845021/43737473-58b5bef2-998f-11e8-96f3-1f739d72f61d.png">

**Comment by adberglund** [comment]
This might just be an issue with free tier accounts, and maybe we aren't targeting supporting them. I see the same issue cropping up with counts and `resourceId` not being available.

**Comment by LandoCalrizzian** [comment]
Also, including "?units=hours" will return a 500 server error

**Comment by LandoCalrizzian** [comment]
VERIFIED. All line items are displaying units
