### ISSUE TITLE
Invalid values are allowed when updating default user preferences via API

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/koku#308]
The API allows a user to set invalid values for any of the default user preferences: currency, locale, timezone

1. Create any user 
2. Update a user preference for any of the default preferences with an invalid value:
    currency -> Hugs
    locale -> en_FOO.LOL-EIGHT
    timezone -> LOL
3. Update successful

**Expected behavior**
The update should fail since the new value is not valid

Context:
  - Commit Hash from status endpoint: 6ed68c

Additional Info:
Should the default user preference be locked down to white listed values?  You can even rename the default user preference name, preference name and description

**Comment by lcouzens** [comment]
Can this even be tested? Preferences has been removed currently right? Perhaps this needs to go to the backlog for now.

**Comment by blentz** [comment]
Please add some detail about what isn't working or what test cases failed.

**Comment by blentz** [comment]
I've been able to reproduce the issue locally:

PUT /api/v1/preferences/b3c9f135-2978-441d-9973-a9f135f011be/
HTTP_X_RH_IDENTITY: ImlkZW50aXR5Ijp7Im9yZ19pZCI6IjIwMDAxIiwiYWNjb3VudF9udW1iZXIiOiIxMDAwMSIsInVzZXJuYW1lIjoidGVzdF9jdXN0b21lciIsImVtYWlsIjoiYmxlbnR6K2tva3UtZGV2QHJlZGhhdC5jb20ifQo=
Content-Type: application/json
cache-control: no-cache
Postman-Token: 573270fb-d031-40a8-aaea-fa0dd6725924
User-Agent: PostmanRuntime/7.4.0
Accept: */*
Host: koku-myproject.127.0.0.1.nip.io
cookie: d02bf7bff81a220d14ef9d513c8d6521=d9683f59ff67188ee1cd2a7f994e39ac
accept-encoding: gzip, deflate
content-length: 53
{"name":"currency","preference":{"currency":"LLAMA"}}
HTTP/1.1 200
status: 200
Server: gunicorn/19.9.0
Date: Wed, 28 Nov 2018 17:48:45 GMT
Content-Type: application/json
Vary: Accept, Origin
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
X-Frame-Options: SAMEORIGIN
Content-Length: 238
{"uuid":"b3c9f135-2978-441d-9973-a9f135f011be","name":"currency","description":"default preference","preference":{"currency":"LLAMA"},"user":{"uuid":"3cf477cd-371c-48ab-87ee-abbc1817adcc","username":"user_dev","email":"user_dev@foo.com"}}

----

DEBUG (0.000) SELECT "api_tenant"."id", "api_tenant"."schema_name" FROM "api_tenant" WHERE "api_tenant"."schema_name" = 'acct10001org20001'; args=('acct10001org20001',)
DEBUG (0.000) SET search_path = acct10001org20001,public; args=None
DEBUG (0.001) SELECT "api_userpreference"."id", "api_userpreference"."uuid", "api_userpreference"."user_id", "api_userpreference"."preference", "api_userpreference"."name", "api_userpreference"."description" FROM "api_userpreference" WHERE ("api_userpreference"."user_id" = 1 AND "api_userpreference"."uuid" = 'b3c9f135-2978-441d-9973-a9f135f011be'::uuid); args=(1, UUID('b3c9f135-2978-441d-9973-a9f135f011be'))
DEBUG (0.000) SET search_path = acct10001org20001,public; args=None
DEBUG (0.000) SELECT "api_user"."id", "api_user"."uuid", "api_user"."username", "api_user"."email", "api_user"."date_created", "api_user"."is_active", "api_user"."customer_id" FROM "api_user" WHERE "api_user"."id" = 1; args=(1,)
DEBUG (0.000) SET search_path = acct10001org20001,public; args=None
DEBUG (0.000) SELECT "api_user"."id", "api_user"."uuid", "api_user"."username", "api_user"."email", "api_user"."date_created", "api_user"."is_active", "api_user"."customer_id" FROM "api_user" WHERE "api_user"."username" = 'user_dev'; args=('user_dev',)
DEBUG (0.000) SET search_path = acct10001org20001,public; args=None
DEBUG (0.000) UPDATE "api_userpreference" SET "uuid" = 'b3c9f135-2978-441d-9973-a9f135f011be'::uuid, "user_id" = 1, "preference" = '{"currency": "AABBCCDD"}', "name" = 'currency', "description" = 'default preference' WHERE "api_userpreference"."id" = 1; args=(UUID('b3c9f135-2978-441d-9973-a9f135f011be'), 1, <django.contrib.postgres.fields.jsonb.JsonAdapter object at 0x7fb3dbe18198>, 'currency', 'default preference', 1)
172.17.0.1 - - [28/Nov/2018:17:40:45 +0000] "PUT /api/v1/preferences/b3c9f135-2978-441d-9973-a9f135f011be/ HTTP/1.1" 200 241 "-" "PostmanRuntime/7.4.0"
DEBUG (0.000) SET search_path = public; args=None

**Comment by lcouzens** [comment]
Verified
"commit": "0f89e4171013f7ed716d59cb53785606e9b30ae8"
