### ISSUE TITLE
Alter services to use lineItem/ProductCode

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#310]
Current queries against the database use the product/ProductFamily column from the cost and usage report for grouping and filtering of services.

The Product Family field doesn't match the content that the dashboard and cost details are looking for and it also can be empty for some products.

This bug will switch to the lineItem/ProductCode value from the CUR as it appears to always be populated and provides more of the billable item level.

**Comment by LandoCalrizzian** [comment]
VERIFIED.
