### ISSUE TITLE
Setup RDS for Performance testing and Staginging environment

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#312]
## User Story
As service, I want to utilize the AWS RDS service for the remote database instead of an Openshift volume so that performance is more realistic when compared to a production environment.

## Impacts
Ex. Backend

## Role
None

## Assumptions
- RDS systems will be setup in our HCCM AWS account
- Changes to utilize RDS will be made within Openshift and not placed in GitHub

## Implementation
https://aws.amazon.com/rds/

https://gitlab.com/cloudigrade/cloudigrade/blob/master/docs/dev-sysop-aws-rds-setup.rst

## Acceptance Criteria

- [ ] Performance testing and Staging environment are connected to AWS RDS

**Comment by dccurtis** [comment]
koku-dev staging environment is connected to RDS database.  We can scale up the database size now to run performance testing.  Setup instructions sent out on slack
