### ISSUE TITLE
Line Item Daily Aggregate Table

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#328]
## User Story
As a user of koku, I want the dashboard to load data quickly so that I have a positive experience. As a koku developer, I'd like to create a daily aggregate table so that report APIs can hit it instead of the hourly data, so that they return data faster.

## Impacts
Backend, API

## Acceptance Criteria

- [ ] Dashboard Reporting APIs pull data from the daily aggregate table instead of the hourly data

**Comment by lcouzens** [comment]
How exactly would I go about testing this?

**Comment by lcouzens** [comment]
Verified
commit: "95005674814c755e1b1865a3b2b751c9b97f10ca"
