### ISSUE TITLE
Map Account names to other names

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#344]
## User Story
As an admin, I want to be able to define a mapping between an account number/id and an identifier and description, so I can identify that account easily when I am looking at reports

## Impacts
All

## Assumptions
- ID do not change with time
- The customer can manually 
- If anything is found in the provider it can be reused

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/PATCH/DELETE |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## UI Details
When looking at the UI and showing things by account, the account is identified only with a number, and thus is complicated to understand.
With this enhancement, it will be possible to define a name for the account and a description, and show the name along the number, and be able to show the description in pop-overs and detail pages.

## Acceptance Criteria

- [ ]
- [ ]

**Comment by chambridge** [comment]
This issue is already covered by https://github.com/project-koku/koku/issues/329
