### ISSUE TITLE
Install/Configuration Docs for Insights Client to upload OCP usage reports

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#354]
## User Story
As an OCP administrator, I want install/configuration documentation to enable the Insights Client to upload usage reports from OCP Operator Metering.

## Impacts
Docs

## Role
OCP Admin

## Assumptions
- User will have documentation to install OCP with Operator Meter
- User will have documentation to install Insights Client

## Doc Details

- Document should cover any installable component (cron + script) if necessary
- Document should cover any configuration (Operator meter credentials + endpoint)

## Acceptance Criteria

- [ ] Verify that a customer can follow the install and configuration documentation to successfully collect Operator Metering reports via the Insights Client.

**Comment by lcouzens** [comment]
Verified!
