### ISSUE TITLE
Integrate API with Insights API Gateway

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#359]
## User Story
As a user, I want to be able to access the cost management API via the Insights Platform API Gateway.

## Impacts
API

## Role
Service Developer / Quality Engineer

## Assumptions
- API Gateway will provide a Principal and Account information
- If our endpoints are reached we assume the Principal has been authenticated

## Implementation Details

- We will be removing the AuthN & AuthZ from our APIs, if our API is call if we don’t have a schema for the given Account one should be generated on the fly
- On-boarding data [Web API Gateway](https://docs.google.com/document/d/1eSmZ2sswtf7gi5kB1EbSMtG8y--mL2Kc80u_I978KvQ/edit#heading=h.mu4c21mbxif1)
- Provide documentation for how to run without Insights API Gateway (3scale) gateway for local development

## Acceptance Criteria

- [ ] Verify that API endpoints can be called via the Insights API Gateway

**Comment by lcouzens** [comment]
Verified
automation test: Test_api_login
