### ISSUE TITLE
Allow API creation of an OCP provider

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#360]
## User Story
As a user, I want to be able to add (configure) an OCP provider with Cost Management so I can obtain its usage information

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- User has setup OCP installation with Insights Client configured

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | POST |
 | **Path** | /api/v1/providers/ |
 | **Response** | 201 |
**Body:**
```
{
"name": "RH-OCP-Test",
"type": "OCP",
            "authentication": {
                "provider_resource_name": "my-ocp-cluster-1"
            }
}
```

## UI Details

A button and wizard or modal to add an OCP provide

## Acceptance Criteria

- [ ] Verify that a user can add an OCP provider with a “OCP cluster id”

**Comment by dccurtis** [comment]
Went in with PR https://github.com/project-koku/koku/pull/370

**Comment by lcouzens** [comment]
Verified in "commit": "332008b5f7960302b6defd5fde55dd78f58fdd47"
Test: Test_api_ocp_provider_crud
