### ISSUE TITLE
View OCP total charge data for current month vs. last month

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#362]
## User Story
As a user, I want to be able to view my total charge for my OCP providers in the overview for the current month vs. the last month.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- User has setup at least one OCP provider

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/charges/ocp/ |
 | **Response** | Charge data for only OCP providers|

## UI Details
A total charge for and breakdown (by day/month) with trendline.

## Acceptance Criteria

- [ ] Verify that a user can view a Total Charge card with trendline current month by day vs. last month by day.

**Comment by lcouzens** [comment]
Verified
"commit": "79267e27f71d8818fcc3b6ff584137a33f1e058c"
Automation: test_api_ocp_charge_validate_total
