### ISSUE TITLE
Filter by Account alias

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#369]
## User Story
As a user, I want to be able to filter using account aliases.

## Impacts
API, UI

## Role
User

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/costs/ |

## UI Details
The UI currently shows the "redhat-hccm" alias, instead of the ID "589173575009", in the cost details page. However, the report API does not allow a filter to be applied using this alias, only by account ID.

![screen shot 2018-09-18 at 9 11 00 am](https://user-images.githubusercontent.com/17481322/45724514-9aae6e00-bb84-11e8-92b2-874958d91948.png)

As a workaround, I added code to search for the account ID, based on the alias in report obtained for the cost details page. This allows the user to apply a filter using "redhat-hccm". However, if the user filters using "389787642310" first, then filter by "redhat-hccm", the logic fails.

This is because the report has been filtered and no longer has any data associated with the "redhat-hccm" account. At this point, the report only contains information for account "389787642310". 

Ideally, the report API would support filtering by alias, in addition to account IDs. That is, considering the UI won't always have all data available client-side. For example, when pagination is introduced, "redhat-hccm" may be on another page and not visible.

## Acceptance Criteria

- [ ] Calling the report API using group_by[account]=redhat-hccm is equivalent to group_by[account]=589173575009

**Comment by chambridge** [comment]
Delivered with https://github.com/project-koku/koku/pull/392
