### ISSUE TITLE
During provider creation, AWS Organization required error: "botocore.errorfactory.AWSOrganizationsNotInUseException: An error occurred (AWSOrganizationsNotInUseException) when calling the DescribeOrganization operation: Your account is not a member of an organization."

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/koku#373]
**Describe the bug**
Creating an AWS provider that is not associated with an AWS organization fails with the error

`ERROR An error occurred (500) when calling the DescribeReportDefinitions operation (reached max retries: 4): Internal Server Error
Traceback (most recent call last):
  File "/opt/app-root/src/koku/providers/aws/aws_provider.py", line 139, in _check_cost_report_access
    cur_client.describe_report_definitions()
  File "/opt/app-root/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (500) when calling the DescribeReportDefinitions operation (reached max retries: 4): Internal Server Error
`

**Expected behavior**
Provider is created successfully b/c the documentation for "Adding an AWS Account" states "AWS organization setup in order to control cost visibility (optional)"

**Context:**
 - Koku Commit: 968ce4c417d32be2f9f1b3c17ee51b791af37535

**Comment by chambridge** [comment]
Need to remove requirement from AWS organization. Docs need to be removed as well.

**Comment by chambridge** [comment]
https://github.com/project-koku/koku/pull/397

**Comment by LandoCalrizzian** [comment]
VERIFIED. This is no longer occurring when adding a provider w/ no AWS organization defined
