### ISSUE TITLE
Filter by partial string, using AND operator

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#374]
## User Story
As a user, I want to filter (lowercase) partial strings, using the boolean AND operator per the PatternFly [filter pattern](https://www.patternfly.org/pattern-library/forms-and-controls/filter/#design).

## Impacts
API, UI

## Role
User

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/costs/ |

## UI Details
The UI currently filters by matching exact strings. For example, I can match the service "AmazonEC2", but cannot match accounts with "EC2" in the name. 

In addition, filters are currently applied using the boolean OR operator. That is, the API will match either "AmazonEC2" or "awskms". In this scenario, I don't expect the API to return any matches.

I do expect the filter to match service names containing partial (lowercase) strings; "ec2" and "amazon".

Please refer to the issue below for greater detail.
https://github.com/project-koku/koku-ui/issues/128

## Acceptance Criteria

- [ ] Calling the report API using group_by[service]=amazon and group_by[service]=ec2 is equivalent to group_by[service]=AmazonEC2

**Comment by chambridge** [comment]
Need more acceptance criteria to make sure we cover the various permutations for ORs/ANDs

**Comment by lcouzens** [comment]
Verified
"commit": "79267e27f71d8818fcc3b6ff584137a33f1e058c"
Items in the same category are ORed together and items in different categories are AND-ed together.
api/v1/reports/costs/aws/?group_by[region]=east&group_by[region]=west&group_by[service]=Amazon
{
    "group_by": {
        "region": [
            "east",
            "west"
        ],
        "service": [
            "Amazon"
        ]
    },
    "data": [
        {
            "date": "2018-11-23",
            "regions": [
                {
                    "region": "us-east-1",
                    "services": [
                        {
                            "service": "AmazonEC2",
                            "values": [
                                {
                                    "region": "us-east-1",
                                    "date": "2018-11-23",
                                    "units": "USD",
                                    "service": "AmazonEC2",
                                    "total": 97.097
                                }
                            ]
                        }
                    ]
                },
                {
                    "region": "us-west-2",
                    "services": [
                        {
                            "service": "AmazonEC2",
                            "values": [
                                {
                                    "region": "us-west-2",
                                    "date": "2018-11-23",
                                    "units": "USD",
                                    "service": "AmazonEC2",
                                    "total": 92.84
