### ISSUE TITLE
Order by total does not work

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#375]
**Describe the bug**
A change was made so that `order_by[cost]=asc` would become `order_by[total]=asc`, but the serializer code and swagger documentation still are using *cost*.

**To Reproduce**
1. GET request with `/api/v1/reports/costs/?filter[time_scope_units]=month&filter[resolution]=monthly&filter[time_scope_value]=-1&group_by[account]=*&order_by[total]=asc`
```

{
    "order_by": {
        "total": [
            "Unsupported parameter"
        ]
    }
}
```

**Expected behavior**
This order by value should succeed and return data in the correct order.

**Comment by dlabrecq** [comment]
Using `order_by[account]=asc` also returns the same error

**Comment by dlabrecq** [comment]
Should I be able to order by service as well? I see account, region, & total, but I don't see service in the choices below.

`Choices are: account, availability_zone, blended_cost, blended_rate, currency_code, date, id, instance_type, normalization_factor, normalized_usage_amount, product_code, product_family, public_on_demand_cost, public_on_demand_rate, region, resource_count, tax_type, total, unblended_cost, unblended_rate, unit, units, usage_account_id, usage_amount, usage_start`
