### ISSUE TITLE
Use RST code documentation in APIs to produce API documentation

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#39]
As a developer, I want to produce hostable API documentation so that users understand how to exercise the API.

Insights as a Service uses [apidocjs](http://apidocjs.com/) to produce their API docs, we should be consistent with this look and feel.

## Acceptance Criteria

- [ ] Verify API documentation can be generated for use by customers.

**Comment by blentz** [comment]
Is this already covered by our readthedocs setup, or is there more to do?

**Comment by adberglund** [comment]
I believe there's a specific docstring formatting we want to add for each API so this can be generated. DRF has some docstring markup that will produce API documentation, but without knowing, I'm guessing it is *not* consistent with what Insights is doing.

**Comment by chambridge** [comment]
There is more to do. I was going to look at this and the required setup after the status endpoint goes in and have that be the first item documented.

From what I've seen it creates an interactive api doc.
