### ISSUE TITLE
Unable to create two providers that use the same RoleARN

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#395]
Currently, the ProviderAuthentication serializer has a `unique=True` constraint that prevents us from creating multiple providers that use the same Role.

We should remove the uniqueness constraint in the serializer because Roles can have access to multiple S3 buckets containing cost usage data. So, the relationship is 1-to-Many, not 1-to-1.

**Comment by lcouzens** [comment]
Verified in "commit": "332008b5f7960302b6defd5fde55dd78f58fdd47"
