### ISSUE TITLE
Order by group does not work

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#398]
**Describe the bug**
group_by[account]=asc, group_by[region]=asc, & group_by[service]=asc do not work. The Koku UI also needs the ability to sort by account aliases.

To Reproduce

    GET request http://koku-hccm-staging.1b13.insights.openshiftapps.com/api/v1/reports/costs/?filter[time_scope_units]=month&filter[resolution]=monthly&filter[time_scope_value]=-1&group_by[account]=*&order_by[account]=asc

GET request http://koku-hccm-staging.1b13.insights.openshiftapps.com/api/v1/reports/costs/?filter[time_scope_units]=month&filter[resolution]=monthly&filter[time_scope_value]=-1&group_by[region]=*&order_by[region]=asc

GET request http://koku-hccm-staging.1b13.insights.openshiftapps.com/api/v1/reports/costs/?filter[time_scope_units]=month&filter[resolution]=monthly&filter[time_scope_value]=-1&group_by[service]=*&order_by[service]=asc

See error
```

{
    "order_by": {
        "total": [
            "Unsupported parameter"
        ]
    }
}
```

**Expected behavior**
This order by value should succeed and return data in the correct order.

**Comment by chambridge** [comment]
Resolved by these PRs:
order_by[account_alias]
https://github.com/project-koku/koku/pull/392
order_by[service], order_by[region]
https://github.com/project-koku/koku/pull/399
