### ISSUE TITLE
Create report for user automatically

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#4]
## User story
As a user, I want to configure reports that are updated automatically.
As an admin, I want to configure reports that are updated automatically for a group of users. The list of users and groups will be dynamic (i.e. a new user added to a group will automatically get a report generated). Reports can be configured to be created at the group or user level.

## Acceptance criteria
- [ ] When the user logs in, a set of reports are available
- [ ] The information on the report is up to date, with refresh every x hours / days. 
- [ ] The report specifies when the last refresh was done, and the user can manually trigger a refresh
- [ ] The report is visualized and/or generated in less than 5 seconds
- [ ] Admin can choose criteria for report generation (i.e. for each user in a group, for an specific group, for all groups except x, for all tenants)
- [ ] Admins can see all the reports generated
- [ ] Users can see all reports generated by them
- [ ] Other users can not see reports generated by user x
- [ ] Admins can set visibility of the reports generated automatically to: all tenant, user, group, group admin

## Assumptions and questions
- [ ] There is in place RBAC for reports
- [ ] group definition, group admin

**Comment by blentz** [comment]
Please add a description that includes:

1. User story
2. Acceptance criteria
3. Assumptions / Dependencies.

**Comment by chargio** [comment]
## User story
As a user, I want to configure reports that are updated automatically.
As an admin, I want to configure reports that are updated automatically for a group of users. The list of users and groups will be dynamic (i.e. a new user added to a group will automatically get a report generated). Reports can be configured to be created at the group or user level.

## Acceptance criteria
- [ ] When the user logs in, a set of reports are available
- [ ] The information on the report is up to date, with refresh every x hours / days. 
- [ ] The report specifies when the last refresh was done, and the user can manually trigger a refresh
- [ ] The report is visualized and/or generated in less than 5 seconds
- [ ] Admin can choose criteria for report generation (i.e. for each user in a group, for an specific group, for all groups except x, for all tenants)
- [ ] Admins can see all the reports generated
- [ ] Users can see all reports generated by them
- [ ] Other users can not see reports generated by user x
- [ ] Admins can set visibility of the reports generated automatically to: all tenant, user, group, group admin

## Dependencies

**Comment by blentz** [comment]
This is an epic unto itself with multiple dependencies. 

For example - pulling data from a single data source, having a pluggable data retrieval mechanism that supports multiple data sources, making data retrieval a scheduled task are three distinct pieces of work.

We'll need to break this up further before there are actionable tasks.

**Comment by chargio** [comment]
I've split this into two elements:
a) Generate the report
b) Automatically schedule and update the report.

This is b) only. If we need to create an epic for that, then we should discuss it and do that.

**Comment by chambridge** [comment]
Closing this issue for now. It was not part of our milestone 1 breakdown of stories. Hopefully the appropriate information can be captured in Aha! and made ready for the appropriate milestone to be broken down.
