### ISSUE TITLE
API: User can authenticate using an identity header w/ invalid email address format

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/koku#407]
**Describe the bug**
Using an identity header that includes an invalid email format is allowed for authentication

{ 
  identity: {
    username: 'llasmith',
    email: 'user_AWDSES.com',
    account_number: 1337,
    org_id: 123456
  }
}

**To Reproduce**
1. Issue an api call to /api/v1/preferences using an identity header w/ invalid email (or email different from user email) 
2. API call returns successful with an invalid header

**Expected behavior**
Functionality should probably return an error due to the invalid email that doesn't matched the insights user. 
**Context (please complete the following information):**
 - Commit Hash from status endpoint: 013957acb

**Additional context**
API calls with an identity header that has a NULL value for email fails w/ a 401 error.

**Comment by chambridge** [comment]
We will be getting valid content from 3scale. A bug fix went in yesterday for the NULL value issue. But there is not need to check valid email format.

https://github.com/project-koku/koku/pull/402/files#diff-917f0d4ca5aa0a4ed3169c9f0ec4ad36R151
