### ISSUE TITLE
View OCP CPU usage & request data for current month vs. last month

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#418]
## User Story
As a user, I want to be able to view my CPU limit, request and usage for my OCP providers in the overview for the current month vs. the last month.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- User has setup at least one OCP provider

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/inventory/compute/ |
 | **Query Parameter** | provider_type=OCP |
 | **Response** | usage, request, limit data for only OCP providers|

## UI Details
CPU limit, usage and request breakdown (by day/month) with trendline.

## Acceptance Criteria

- [ ] Verify that a user can view a CPU Limit, Usage & Request card with trendline current month by day vs. last month by day.
- [ ] Verify that if a request is made without the provider_type or an invalid provider type the user will get a 400 with an informative message.

**Comment by lcouzens** [comment]
Verified
"commit": "79267e27f71d8818fcc3b6ff584137a33f1e058c"
Automation: test_api_ocp_cpu_validate_totals
