### ISSUE TITLE
View OCP Memory usage & request data for current month vs. last month

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#419]
## User Story
As a user, I want to be able to view my Memory limit, request, and usage for my OCP providers in the overview for the current month vs. the last month.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- User has setup at least one OCP provider

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/inventory/memory/ |
 | **Query Parameter** | provider_type=OCP |
 | **Response** | usage, request, limit data for only OCP providers|

## UI Details
Memory usage, request, limit breakdown (by day/month) with trendline.

## Acceptance Criteria

- [ ] Verify that a user can view a Memory Usage, Request and Limit card with trendline current month by day vs. last month by day.
- [ ] Verify that if a request is made without the provider_type or an invalid provider type the user will get a 400 with an informative message.

**Comment by chambridge** [comment]
Great question. I'll update the acceptance criteria above, but `provider_type` will be required. You will get a 400 that will tell you its required if you don't supply it.

**Comment by chambridge** [comment]
`group_by[project]` & `group_by[cluster]` follow on story.

**Comment by chambridge** [comment]
Document differences in AWS API capabilities vs OCP API capabilities. Open separate story.

**Comment by lcouzens** [comment]
Verified
Commit: "79267e27f71d8818fcc3b6ff584137a33f1e058c"
Automation: test_api_ocp_memory_validate_totals
