### ISSUE TITLE
[API Change] Update time scope parameters to a general purpose implementation.

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#421]
## User Story
As a Koku API consumer, I want `time_scope_value` to not be treated specially so that `time_scope_units` can define the units for the requested data.

For example:
`time_scope_value=3&time_scope_units=days` should return 3 days of data.
`time_scope_value=3&time_scope_units=months` should return up to 3 months of data.

## Impacts
API, UI, docs

## Assumptions
- There will be limits created to avoid resource-intensive queries (e.g. `time_scope_value=99` shouldn't DOS the app.

## UI Details
- The UI should be updated to provide a `time_scope_units` when it uses `time_scope_value`

## Acceptance Criteria

- [ ] `time_scope_value` depends on `time_scope_units` to define the units returned.
- [ ] `time_scope_units` will be defaulted to 'days' if `time_scope_units` is not defined.
- [ ] The maximum amount of data returned by the API should be 32 days or 3 months, depending on `time_scope_units`.

**Comment by blentz** [comment]
The `FilterSerializer` should still control the acceptable options. So, for the purposes of this work, no change should be made to the `FilterSerializer`.

The change described in this issue is intended to be scoped to the `ReportQueryHandler` side, which adds additional special-case processing for these values.

So, really, we're talking about going from 4 discrete options to 8 possible options because the constraints of the serializer will still apply after this work is complete.

**Comment by chambridge** [comment]
Just as a comment. We are removing the complexity of the code in the query handler around checking that matches the values (-1, -2, -10,-30) to they types (month, day). These checks will only be performed in the serializers. For the current timeframe we will only support  the same summarized data points of current month (-1), previous month (-2), last 10 days (-10), and last 30 days (-30)

**Comment by lcouzens** [comment]
Verified
Commit: 4bc63891ac27ffa0365680bd83230bdc987d1cae
