### ISSUE TITLE
View paginated data

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#431]
## User Story
As a user, I want to paginate through data on the AWS and OCP details pages. 

## Impacts
API, UI

## Role
User

## Assumptions
- User has setup at least one AWS and/or OCP provider

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/cost/ |

## UI Details
Currently, all data is displayed client-side, forcing the user to scroll. The number of accounts is small for now, but services and regions is potentially lengthy.

See AWS mocks https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/323822462
See OCP mocks https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/323822484

## Acceptance Criteria

- [ ] Verify that a user can view cost details with page and page_limit parameters
- [ ] Verify that if a request is made without the page_limit parameter, that the default number (e.g., 20) of items is returned
- [] Verify that filter and sort work as expected with paginated data

**Comment by chambridge** [comment]
Use "data" for where the data lives. (change the out-of-the-box key for django).

**Comment by lcouzens** [comment]
Verified
Commit: 4bc63891ac27ffa0365680bd83230bdc987d1cae
