### ISSUE TITLE
Define rate model for OCP data

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#433]
## User Story
As koku developer, I want a rate model so that I can store rate information.

## Impacts
DB, API

## Role
Dev

## Assumptions
- 
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/PATCH/DELETE |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ] Must support storing flat rates
- [ ] Must define a currency per rate
- [ ] Must define a metric to measure against (e.g. per-CPU, per-GiB-network-io)
- [ ] Must define a time unit to measure against (e.g. per-hour, per-minute)
- [ ] Should include a name and description of the rate.
- [ ] (Optional) Should have a plan for supporting tiered rates or other formula-defined rates
- [ ] (Optional) Should have a plan for supporting discounts
- [ ] (Optional) Should determine whether to integrate support for AWS Pricing API

**Comment by blentz** [comment]
https://docs.google.com/document/d/1NZb8d36IYn1Ex2O7sMoVrV_CYlcEhuF5189PNHtPcNc/edit?usp=sharing

**Comment by blentz** [comment]
This is merged in PR #444

**Comment by lcouzens** [comment]
Verified
"commit": "79267e27f71d8818fcc3b6ff584137a33f1e058c"
Automation: test_api_ocp_charge_provider_rates_crud
