### ISSUE TITLE
Add fixed rate CRUD to API

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#434]
## User Story
As a Koku developer, I want rate CRUD added to the API so that I can create, read, update, and delete rates.

## Impacts
API, Docs

## Role
Dev

## Assumptions
- Rate model has been defined
- Fixed rates are the current target. More advanced use cases will be addressed in future work.
- Rate models will use the existing Tenant schemas, so Rates are specific to each customer.
- Rates will only apply to OCP providers for now.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/rate/ |
 | **Body** | ?filter[name]=myRate&filter[metric]=cpu_ticks&filter[time_unit]=hour&filter[currency]=EUR |
 | **Response** | uuid, name, description, price, metric, time_unit, currency |

| API  | Detail|
 | --- | --- |
 | **Method** | POST |
 | **Path** | /api/v1/rate/ |
 | **Body** | name, description, price, metric, time_unit, currency |
 | **Response** | uuid, name, description, price, metric, time_unit, currency |
 | **Error Response** | Invalid Rate, Duplicate name, Invalid type, Invalid currency, Unknown metric, Invalid time_unit |

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/rate/{uuid}/ |
 | **Body** |  |
 | **Response** | uuid, name, description, price, metric, time_unit, currency |
 | **Error Response** | Invalid/Unknown Rate |

| API  | Detail|
 | --- | --- |
 | **Method** | PUT |
 | **Path** | /api/v1/rate/{uuid}/ |
 | **Body** | name, description, price, metric, time_unit, currency |
 | **Response** | uuid, name, description, price, metric, time_unit, currency |
 | **Error Response** | Invalid Rate, Duplicate name, Invalid type, Invalid currency, Unknown metric, Invalid time_unit |

| API  | Detail|
 | --- | --- |
 | **Method** | DELETE |
 | **Path** | /api/v1/rate/{uuid}/ |
 | **Body** |  |
 | **Response** | uuid, name, description, price, metric, time_unit, currency |
 | **Error Response** | Invalid/Unknown Rate, Server Error |

## Acceptance Criteria

- [ ] A rate can be created
- [ ] An existing rate can be read
- [ ] An existing rate can be updated
- [ ] An existing rate can be deleted
- [ ] apidoc is updated to include rate operations
- [ ] RTD docs are updated to discuss rates

**Comment by lcouzens** [comment]
Verified
"commit": "79267e27f71d8818fcc3b6ff584137a33f1e058c"
Automation: test_api_ocp_charge_provider_rates_crud
