### ISSUE TITLE
Provide cost associated with AWS Compute Instance Hours

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#455]
## User Story
As user, I want understand the cost associated with my AWS Compute Instance Hours so that make clearer connections about may infrastructure spending.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- Builds on existing `/api/v1/reports/inventory/instance-type/` API

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/inventory/instance-type/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&filter[limit]=5&group_by[instance_type]=* |
 **Response**:
```
{
    "group_by": {
        "instance_type": [
            "*"
        ]
    },
    "filter": {
        "resolution": "monthly",
        "time_scope_value": "-1",
        "time_scope_units": "month",
        "limit": 5
    },
    "data": [
        {
            "date": "2018-11",
            "instance_types": [
                {
                    "instance_type": "t2.small",
                    "values": [
                        {
                            "instance_type": "t2.small",
                            "date": "2018-11",
                            "units": "Hrs",
                            "total": 199.0,
                            "count": 11,
                            "cost": 15490.00,
                            "currency": "USD"
                        }
                    ]
                },
                {
                    "instance_type": "t2.micro",
                    "values": [
                        {
                            "instance_type": "t2.micro",
                            "date": "2018-11",
                            "units": "Hrs",
                            "total": 150.0,
                            "count": 0,
                            "cost": 23766.00,
                            "currency": "USD"
                        }
                    ]
                }
            ]
        }
    ],
    "total": {
        "value": 349.0,
        "count": 1,
        "units": "Hrs",
        "cost": 39256.00,
        "currency": "USD"
    }
}
```

## UI Details
UI will show cost associated with total and each breakdown.

## Acceptance Criteria

- [ ] Sum of group by cost matches cost in total section
- [ ] Cost is present in all queries

**Comment by lcouzens** [comment]
Verified
"commit": "193b17823b88acfc8a0bb7f0b03c1008742b02a7"
Automation: 
test_api_aws_cost_validate_total
test_api_aws_instance_validate_total
test_api_aws_storage_validate_total
