### ISSUE TITLE
Associate rates with a provider instance and limit choices and types (metrics, etc) via serializers

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#463]
## User Story
As user, I want to be able to create a rate for a metric associated with a provider instance so that proper usage can be applied.

## Impacts
API, UI, Docs

## Role
User

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/DELETE |
 | **Path** | /api/v1/rates/ |

 **Body:**
```
{
    "provider_uuid": <uuid>,
    "metric": "cpu_core_per_hour" | "memory_byte_per_hour"
    "fixed_rate": {
         "value": 0.02,
         "unit": "USD"
    }
}
```
 **Response:**
```
{
    "uuid": <uuid>,
    "provider_uuid": <provider_uuid>,
    "metric": "cpu_core_per_hour" | "memory_byte_per_hour"
    "fixed_rate": {
         "value": 0.02,
         "unit": "USD"
    }
}
```
## Acceptance Criteria

- [ ] Creation of rate fails (400) if given a bad provider uuid
- [ ] Creation of rate fails (400) if given a bad metric value
- [ ] Rate created with valid inputs and provider
- [ ] Deleting provider will remove the associated rate

**Comment by chambridge** [comment]
https://github.com/project-koku/koku/pull/465

**Comment by lcouzens** [comment]
Verified
"commit": "79267e27f71d8818fcc3b6ff584137a33f1e058c"
Automation: test_api_ocp_charge_provider_rates_crud
