### ISSUE TITLE
Allow delta calculations for OCP data

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#469]
## User Story
As a Koku user, I want to see my OCP usage deltas grouped by cluster, project, node, and total so that I can spot changes month-over-month when looking at report details

## Impacts
API

## Assumptions
- The reuse portions of existing delta calculation

## Acceptance Criteria

- [ ] Deltas are returned for each grouped element in the month view along with total for OCP
- [ ] Deltas are returned for each grouped element in the daily view along with total for OCP

**Comment by lcouzens** [comment]
Verified
"commit": "193b17823b88acfc8a0bb7f0b03c1008742b02a7"
Adding automation (To be done) Hccm-plugin Issue #50
