### ISSUE TITLE
Support current month deltas (e.g. usage__request)

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#478]
## User Story
As a user, I want to be able to view different delta values related to metrics within the current month so that can evaluate there impacts on my charge.

Deltas:
 - usage vs request (by group_by; project, node, cluster)
 - usage vs cluster capacity  (by group_by)
 - request vs cluster capacity  (by group_by)

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- Will expand the supported strings utilized by `delta=<delta_value>` for the OCP related reports

## API Details
Support the following new values for `delta`:
- `usage__request`
- `usage__capacity`
- `request__capacity`

If the `filter[resolution]` is `monthly`  the difference is between the values for the month.  If the `filter[resolution]` is `daily`  the difference is between the values for each day.

## UI Details
The OCP tab on the overview will display different delta views.

## Acceptance Criteria

- [ ] If an invalid delta string is provided then an error will be returned (400)
- [ ] If a valid delta string is provided then both the resolution (month/day) and/or group values will have the delta value along with a overall delta for the time period in the `total`.

**Comment by chambridge** [comment]
@adberglund Can you clean up the implementation info for Luke for testing?

When done add a `ready to test` tag and move to the **QA** Pipeline.

Thanks :bow:

**Comment by lcouzens** [comment]
Verified
"commit": "cd1fd6b8d56fe0cc15f33a0d6393701e0dba75b4"
