### ISSUE TITLE
Inconsistent URL naming conventions

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#487]
Currently, there is no convention being applied to our API URLs. So, we have a mix of singular and plural terms with no coherent strategy for when the singular form is used instead of the plural.

We also don't really have a defined scheme for deciding where URI elements should be placed or why.

Please do two things:

1. Define naming conventions for the whole development team to follow.
2. Fix the URLs based on the defined naming convention.

Our current URLs:
```
/providers     (plural)
/preferences   (plural)
/status        (singular)
/reports/costs/aws      (plural, plural, singular)
/reports/charges/ocp    (plural, plural, singular)
/reports/inventory/aws/instance-type  (plural, singular, singular, singular)
/reports/inventory/aws/storage        (plural, singular, singular, singular)
/reports/inventory/ocp/memory         (plural, singular, singular, singular)
/reports/inventory/ocp/cpu            (plural, singular, singular, singular)
```

**Comment by chambridge** [comment]
ocp --> openshift

**Comment by chambridge** [comment]
We are going to collapse the `costs` and `charges` endpoints into a single `costs` endpoint.

Openshift responses will contain `infrastructure_cost` and `derived cost`.

AWS responses will contain only
`infrastructure_cost` (until we allow specifying rates for AWS (like a markup) then we will have a `derived cost`).

*Derived cost* is the cost based on the users defined price list
*Infrastructure cost* is the cost based on the underlying infrastructure like the AWS cost and usage report.

These will be objects that provide back the value and unit:
```
"infrastructure_cost": { "value": 100.00, "unit": "USD" }
"derived_cost": { "value": 150.00, "unit": "USD" }
```

**Comment by dayleparker** [comment]
Nice differentiation ^^ So IIUC, is _derived cost_ = cost + markup? And is that what you would use in a chargeback?

**Comment by chargio** [comment]
Ok.

So 

metrics --- (rate) --------- infra costs ----- markup (rate) --- derived cost
                                                                                |
metrics (AWS)  - infra costs (AWS provided)---

**Comment by chambridge** [comment]
@dayleparker Yes, an example of _derived cost_ would be `infrastructure_cost + markup`. However, in some cases like on premise where there isn't any infrastructure providing a underlying cost it would be  based on things like `CPU usage * rate` etc.

**Comment by dayleparker** [comment]
Thanks @chambridge. I've added _derived cost_ and _infrastructure cost_ to our lexicon so it's recorded.

**Comment by chambridge** [comment]
Going to brake merging cost + charge APIs into single API into another issue. This one will just cover general path changes for consistency.

**Comment by lcouzens** [comment]
Verified
Commit: 9e21cbb23de1645b26188c6c4079d04131ddf98e
