### ISSUE TITLE
Fix API parameter naming: avail_zone should be availability_zone

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#488]
Currently, our API uses a non-standard shortening of the term "availability zone". This is likely to cause confusion with users, as this is not a standard way to shorten that term.

Please update the API parameter to be `availability_zone` or `az` instead of `avail_zone`

**Comment by chambridge** [comment]
Let's do it!

**Comment by lcouzens** [comment]
Verified
commit: ecd015eb1013a08049061cb87cf8f36829d0c8e1
Automation: test_api_aws_filtered_total_match_group_by_total_available_zones
