### ISSUE TITLE
Reconcile report output, maximize consistency across reports.

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#490]
As part of reviewing PR#485, a concern was raised about the data structure being returned by the API across providers. For example, OCP uses the term `charge` where AWS uses the terms `cost`, `value`, and `total`.

We should reconcile our outputs with the lexicon that @chargio has put together and with the terms that the upstream providers use. 

It's important to ensure that each API endpoint is returning as close to the same data structure as possible. For example, cost reports and instance-type reports should use the same names for keys with the same type of data.

The label `total` appears to be contextual, which may or may not be desirable. We should make a decision on that, so that we use `total` consistently throughout the application, if we use it at all.

**Comment by lcouzens** [comment]
Verified
Commit: 77cee8faafbb53b349bdb51f83062eb94c07db5d
Automation: API smoke tests.
