### ISSUE TITLE
List of regions includes regions that are not used

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#494]
**Describe the bug**
The list of regions in AWS total costs includes many regions that are present in AWS but not present in the account. You can see that they are not present in the other regions views

**To Reproduce**
It happens always

**Expected behavior**
Only those that have data should be present

**Screenshots**

![image](https://user-images.githubusercontent.com/7500590/49286659-23a62780-f49b-11e8-929b-664796a86688.png)

**Context (please complete the following information):**
 - OS: max OS X
 - Browser: Chrome
 - Commit Hash from status endpoint:

**Additional context**

**Comment by adberglund** [comment]
@chargio I have not investigated this bug specifically, but as I looked through a lot of the data we ingest, I have seen lots of line items in these regions, and lots of line items that are zero cost. If you look at the details page by region, I wonder if you'll see these zero cost items? We could filter out results that have zero cost, but then we wouldn't display them in the details page and I don't know if there's value in seeing those items there?

**Comment by chambridge** [comment]
@chargio Your assumption is bad. Sure we have zero cost items, but the other two views are only a narrow view of either instance type or storage. All it means is that these line items were encountered from another kind of service that isn't instance type or storage related. We don't magically add region info so we encountered real data.

**Comment by chargio** [comment]
Good to know that there were zero cost items.

I was confused by the list of regions with 0%

Thanks
