### ISSUE TITLE
API item and total key:values in different order

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#499]
**Describe the bug**
When running various api reports the line items and the running total have key/values in different order

**To Reproduce**
1. Add provider
2. Head to /api/v1/reports/inventory/ocp/cpu
3. Scroll down to totals
4. compare last item keys with total keys

Ordering is different
Items key order:
usage
request
limit
charge
units

Totals key order:
usage
request
charge
limit
unit

**Expected behavior**
It would be useful for these to have the same ordering to make the data easier to understand and for quick reading of the lines

**Context (please complete the following information):**
 - OS: fedora
 - Browser: firefox
 - Commit Hash from status endpoint: "79267e27f71d8818fcc3b6ff584137a33f1e058c"

**Additional context**

                    "date": "2018-11-30",
                    "usage": 257.035908,
                    "request": 483.199129,
                    "limit": 721.68592,
                    "charge": 48.319922,
                    "units": "Core-Hours"
                }
            ]
        }
    ],
    "total": {
        "usage": 3249.490773,
        "request": 6231.465721,
        "charge": 623.146736,
        "limit": 9321.913913,
        "units": "Core-Hours"

**Comment by lcouzens** [comment]
Looks like this still fails for me using api/v1/reports/inventory/ocp/cpu/ (capacity/charge are in the wrong order)
```"date": "2018-12-11",
                    "usage": 2.752515,
                    "request": 25.389,
                    "limit": 33.579,
                    "capacity": 28.0,
                    "charge": 5.097067,
                    "units": "Core-Hours"
                }
            ]
        }
    ],
    "total": {
        "usage": 1028.339547,
        "request": 10149.0714,
        "limit": 13426.803,
        "charge": 2037.012643,
        "capacity": 728.0,
        "units": "Core-Hours"```

Also I should of mentioned before, the same behavior is seen at api/v1/reports/inventory/ocp/memory/
```          "date": "2018-12-11",
                    "usage": 35.039966,
                    "request": 43.475011,
                    "capacity": 116.604035,
                    "limit": 45.970619,
                    "charge": 2.489111,
                    "units": "GB-Hours"
                }
            ]
        }
    ],
    "total": {
        "usage": 14218.080758,
        "request": 17378.824507,
        "limit": 18376.427147,
        "charge": 996.903967,
        "capacity": 3030.872025,
        "units": "GB-Hours"```

While we are at it I just checked and similar can be seen for aws/storage/ and aws/instance-type/

``` "units": "GB-Mo",
                    "cost": 0.118279568,
                    "total": 1.794185144
                }
            ]
        },
        {
            "date": "2018-12-11",
            "values": []
        }
    ],
    "total": {
        "value": 15.671461941,
        "cost": 0.118279568,
        "units": null```
```      "instance_type": "db.t2.small",
                            "date": "2018-12-10",
                            "units": "Hrs",
                            "cost": 0.288,
                            "count": 1,
                            "total": 8.0
                        }
                    ]
                }
            ]
        },
        {
            "date": "2018-12-11",
            "instance_types": []
        }
    ],
    "total": {
        "cost": 30.0778,
        "count": 3,
        "value": 509.0,
        "units": null```

commit: "34f5553e0b65889fc7d162b4f4b9d0abefa769ec"

**Comment by chambridge** [comment]
I was focused on the original reported issue which was `limit` and `charge` being swapped. I will take a look at capacity ordering and AWS.

**Comment by lcouzens** [comment]
@chambridge I am still seeing AWS key/values in different orders, the OCP stuff all looks good now though.
api/v1/reports/inventory/aws/storage/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly

commit: f663f1901b8ad60af55eebcb7897d93372007240

```                    "date": "2018-12",
                    "units": "GB-Mo",
                    "cost": 0.494911034,
                    "total": 7.123981786
                }
            ]
        }
    ],
    "total": {
        "cost": 0.494911034,
        "units": "GB-Mo",
        "value": 7.123981786```

**Comment by chambridge** [comment]
Fix of order here:
https://github.com/project-koku/koku/pull/526

**Comment by lcouzens** [comment]
Verified
commit: "9085b19af615fd8fbe687b5deda369c3b1647f1d"
