### ISSUE TITLE
[BUG] When adding a new AWS service I get 0.00 with an up arrow and red 

### ISSUE THREAD

**Issue by vestival** [project-koku/koku#504]
**Describe the bug**
When I add a new service in AWS (in this case is RDS) I get this new service but when it goes into comparing the cost to the previous month I get 0.00% 

**To Reproduce**
1. Go to All Services
2. See error

**Expected behavior**
I am expecting either: no data to compare or a 100% than last month 

**Screenshots**

![image](https://user-images.githubusercontent.com/6848398/49391139-1901c180-f72b-11e8-9862-680a7fd77888.png)

![image](https://user-images.githubusercontent.com/6848398/49391172-346ccc80-f72b-11e8-9e36-095423d3d0d9.png)

**Context (please complete the following information):**
 - OS: MAC OS
 - Browser: Chrome

**Comment by vestival** [comment]
@chambridge this is what told you about, not sure if it's a bug
@chargio

**Comment by chambridge** [comment]
API returns:
```
{
	"delta": {
		"value": -28.525199829,
		"percent": -82.25212071917441
	},
	"group_by": {
		"service": ["*"]
	},
	"order_by": {
		"total": "desc"
	},
	"filter": {
		"resolution": "monthly",
		"time_scope_value": "-1",
		"time_scope_units": "month"
	},
	"data": [{
		"date": "2018-12",
		"services": [{
			"service": "AmazonEC2",
			"values": [{
				"date": "2018-12",
				"units": "USD",
				"service": "AmazonEC2",
				"total": 5.615,
				"delta_value": -29.065199829,
				"delta_percent": -83.80920517273182
			}]
		}, {
			"service": "AmazonRDS",
			"values": [{
				"date": "2018-12",
				"units": "USD",
				"service": "AmazonRDS",
				"total": 0.54,
				"delta_value": 0.54,
				"delta_percent": 0.0
			}]
		}, {
			"service": "AmazonCloudWatch",
			"values": [{
				"date": "2018-12",
				"units": "USD",
				"service": "AmazonCloudWatch",
				"total": 0.0,
				"delta_value": 0.0,
				"delta_percent": 0.0
			}]
		}, {
			"service": "AmazonS3",
			"values": [{
				"date": "2018-12",
				"units": "USD",
				"service": "AmazonS3",
				"total": 0.0,
				"delta_value": 0.0,
				"delta_percent": 0.0
			}]
		}, {
			"service": "AmazonSNS",
			"values": [{
				"date": "2018-12",
				"units": "USD",
				"service": "AmazonSNS",
				"total": 0.0,
				"delta_value": 0.0,
				"delta_percent": 0.0
			}]
		}]
	}],
	"total": {
		"value": 6.155,
		"cost": 6.155,
		"units": "USD"
	}
}
```

@adberglund Any thoughts why delta_percent is handing back `0.0`? in this case? Or is this just a corner case we need to account for because we didn't have any data from the previous month?

**Comment by adberglund** [comment]
I agree with @chargio here. We should show situations where there is no data for last month as their own case. @chambridge That is what's happening here. Delta percent is calculated as `((current - previous) / previous) * 100` So the division by zero gets handled currently just by returning `0`. We can easily return `None` instead and have that be expressed in the UI however we design.

**Comment by chambridge** [comment]
@adberglund going with `None` sounds like a plan.

FYI @nlcwong @dlabrecq @boaz1337, we will be making an update to the API for this case, the UI should be able to handle the`None` case and show some clarifying text.

**Comment by chargio** [comment]
Could we also add a minus sign when the number is decreasing? It confuses me that is green and down
