### ISSUE TITLE
Provide an API to view available OCP tag keys

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#509]
## User Story
As a user, I want to be able to get a list of the associated tag keys for the given time scope so that I can know how to perform associated group_bys for OCP API requests.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- Utilize the same time scope capabilities as reports API

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/tags/ocp/ |
 | **Query Params** | filter[resolution]={monthly}&filter[time_scope_value]={-1 or -2}&filter[time_scope_units]={month}
 | **Response** | {"data": [list of tag keys]} |

## UI Details
Group by dropdown will contain the list of tag keys

## Acceptance Criteria

- [ ] API provides 400 and usable error when filter params are invalid
- [ ] API provides a list of tag keys for OCP for the given time frame

**Comment by adberglund** [comment]
```
koku=> select jsonb_object_keys(pod_labels) from reporting_ocpusagelineitem group by jsonb_object_keys(pod_labels);
         jsonb_object_keys
------------------------------------
 presto
 statefulset_kubernetes_io_pod_name
 controller_revision_hash
 pod_template_hash
 app
 prometheus
 hive
 alertmanager
 k8s_app
(9 rows)
```

**Comment by lcouzens** [comment]
Verified
commit: 0ce1865c4ed6dc95b87e1d74c02eebb836fb570b
