### ISSUE TITLE
Enable report OCP API grouping by tag key

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#510]
## User Story
As a user, I want to be able to group my OCP charge data by tag key so that I can view the charge breakdown by that tag key.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- We will need to dynamically obtain the tags for the given time scope to validate the query parameter for the group by.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/charges/ocp/ |
 | **Query Parameters** | group_by[{tag key}]=* or {tag_value_list} |
 | **Response** | charges response grouped by tag key |

## UI Details

The **OpenShift Charge** page will display the breakdown of charges grouped by tag key

## Acceptance Criteria

- [ ] The API will return a 400 if the provided tag key is not valid for the given time scope
- [ ] The API will return charge data grouped by the given tag key and filtered tag value list.

**Comment by adberglund** [comment]
If group_by[app]=* were the param, this might translate in Postgres to something like... 

```
koku=> select pod_labels->'app' from reporting_ocpusagelineitem group by pod_labels->'app';
       ?column?
----------------------

 "presto"
 "hdfs-datanode"
 "grafana"
 "kube-state-metrics"
 "hdfs-namenode"
 "prometheus"
 "reporting-operator"
 "hive"
 "metering-operator"
 "alertmanager"
(11 rows)
```

**Comment by lcouzens** [comment]
Verified
commit: 0ce1865c4ed6dc95b87e1d74c02eebb836fb570b
