### ISSUE TITLE
Enable report OCP API filter by tag value for a tag key

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#511]
## User Story
As a user, I want to be able to filter my OCP charge data by tag value for a tag key so that I can view the charge breakdown by matching tags.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- We will need to dynamically obtain the tags for the given time scope to validate the query parameter for the filter.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/charges/ocp/ |
 | **Query Parameters** | filter[{tag key}]=* or {tag_value_list} |
 | **Response** | charges response filtered by tag values for the tag key |

## UI Details

The **OpenShift Charge** page will display the breakdown of charges filtered by tag value for the given key

## Acceptance Criteria

- [ ] The API will return a 400 if the provided tag key is not valid for the given time scope
- [ ] The API will return charge data filtered by the given tag value for the tag key.

**Comment by lcouzens** [comment]
Verified
commit: 0ce1865c4ed6dc95b87e1d74c02eebb836fb570b
