### ISSUE TITLE
Enable report AWS API grouping by tag key

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#514]
## User Story
As a user, I want to be able to group my AWS cost data by tag key so that I can view the cost breakdown by that tag key.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- We will need to dynamically obtain the tags for the given time scope to validate the query parameter for the group by.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/costs/aws/ |
 | **Query Parameters** | group_by[{tag key}]=* or {tag_value_list} |
 | **Response** | cost response grouped by tag key |

## UI Details

The **Cloud Cost** page will display the breakdown of cost grouped by tag key

## Acceptance Criteria

- [ ] The API will return a 400 if the provided tag key is not valid for the given time scope
- [ ] The API will return cost data grouped by the given tag key and filtered tag value list.

**Comment by lcouzens** [comment]
Verified
Commit: b7bca99add93d0bef63ad849a29de3da1b95d96e
Automation: test_api_aws_tagging_limit_order_by
