### ISSUE TITLE
API spec does not return uuid

### ISSUE THREAD

**Issue by psav** [project-koku/koku#517]
**Describe the bug**
The API spec does not define uuid as a required parameter, as such and call using a swagger generated client, yields just `name` and `type` which is not enough to identify the provider for other REST calls.

**To Reproduce**
1. Generate a swagger client (python tested)
2. Add a provider

**Expected behavior**
uuid should be a required field for the Provider definition

**Comment by chambridge** [comment]
I don’t ge what you mean by:
> *Expected behavior*
> uuid should be a required field for the Provider definition

To create a Provider you don’t need a UUID. The resulting object back is modeled by `ProviderOut` and it does contain a uuid as required.

```
ProviderOut:
    allOf:
      - $ref: '#/definitions/Provider'
    required:
      - uuid
      - authentication
      - billing_source
      - customer
      - created_by
    properties:
      uuid:
        type: string
        format: uuid
        example: 57e60f90-8c0c-4bd1-87a0-2143759aae1c
      authentication:
        $ref: '#/definitions/ProviderAuthenticationOut'
      billing_source:
        $ref: '#/definitions/ProviderBillingSourceOut'
      customer:
        $ref: '#/definitions/CustomerOut'
      created_by:
        $ref: '#/definitions/UserOut'
```

**Comment by chambridge** [comment]
per psav:
> we can close off that bug
