### ISSUE TITLE
API pagination showing incorrect internal endpoint

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#538]
**Describe the bug**
API pagination showing incorrect internal endpoint

**To Reproduce**
1. Add over 10 providers so we have multiple pages
2. see pagination link

**Expected behavior**
Link should direct you to the correct page

**Context (please complete the following information):**
 - OS: Fedora 28
 - Browser: chrome 66
 - Commit Hash from status endpoint: f9f39be3da286221dadc9833c7bcfa0afc41b57c

Additional info:
Seeing internal endpoints on CI and QA
    "count": 45,
    "next": "http:****.local/r/insights/platform/cost-management/api/v1/providers/?page=3",
    "previous": "http:****.local/r/insights/platform/cost-management/api/v1/providers/",
    "results": [
        {

**Comment by lcouzens** [comment]
The link looks better in the fact is not showing internal now but its still navigating to the wrong page, it seems to have api and page in the link twice.

redhat.com/r/insights/platform/cost-management/api/v1/providers/?page=2api/v1/providers/?page=2",

Clicking it goes to
/api/v1/providers/?page=2api%2Fv1%2Fproviders%2F%3Fpage%3D2

```HTTP 404 Not Found
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "Invalid page."
}```

**Comment by chambridge** [comment]
Are you seeing that from the hover over the link?

I’m personally ok with how it’s working as the Browsable API is a nice feature, and the important things to me is the JSON response is good and the buttons function with the partial url. 

I think we need Tim Gerla to finish updating the REST API IPP, as that will likely have bigger impacts.

**Comment by chambridge** [comment]
@lcouzens I think if you want to something to track at this point there should be a new issue as the endpoint info is no longer incorrect. The page number links on the Browseable API do have an issue, however, that is not the API itself and the page forward and back arrows work, so to me its a low priority issue for now. Not the high priority that the original issue presented.
