### ISSUE TITLE
[RFE] As an Admin, I want to be able to add the same AWS account to different Insights User Accounts

### ISSUE THREAD

**Issue by vestival** [project-koku/koku#573]
Right now, one AWS can only exist within one single Insights user (RH Account) and we would need to have the same AWS on several RH Accounts. This is relevant for demo and enablement purposes

@chargio

**Comment by lcouzens** [comment]
@vestival 
Whats the exact use case around this?
Is it multiple demos running simultaneously or something? in which case they can all login as the same user and see the same data, or if multiple users are in the same organization then they would also have access to the same AWS source/data. Similar to the current setup we have on CI most users share Jens data.

Or is it just that you want to be able to demo adding a source? 
In which case you can add the same source over and over on any user as long as you delete it through the api afterwards each time.

**Comment by chambridge** [comment]
So you can definitely add another provider by just creating a new role and reusing the same policy, so if you were doing a training you could create a bunch. Could even script that, but would want it cleaned up after.

On the back end we do encounter an error where we assume the assemble id of the report to be unique. We could probably change this to a unique_together with the provider_id.
```
[2019-01-24 19:28:47,089: INFO/ForkPoolWorker-2] No manifest entry found.  Adding for bill period start: 2018-12-01 00:00:00
--
  | [2019-01-24 19:28:47,101: ERROR/ForkPoolWorker-2] masu.processor.tasks.get_report_files[c77cb905-4d7d-4920-97a8-113dda1bb5e9]: (psycopg2.IntegrityError) duplicate key value violates unique constraint "reporting_common_costusagereportmanifest_assembly_id_key"
  | DETAIL:  Key (assembly_id)=(fa740530-8128-4536-9fad-d76cc6ad8d7d) already exists.
```

Thoughts @project-koku/development ?

**Comment by chambridge** [comment]
Double check that we are getting last months data too. That we fix our Update bug.

**Comment by lcouzens** [comment]
Verified
Commit: 54550d21cbb71211122fbfb7bb7a483bef727e38
