### ISSUE TITLE
Estimate the operational cost of the data we will be storing over time in RDS

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#580]
## User Story
As service developer, I want to provide a rough forecast of potentially how much the operation RDS cost will be in production for N customers.

Roughly providing X amount of $ per customer.

Data needed for 10 customers with 1 year of summary data
Data needed for 50 customers with 1 year of summary data

**Comment by chargio** [comment]
Thanks @chambridge This is what we need to know for storage and it will be a good starting point.
I understand that RDS will be the majority of the costs, once we are analyzing our own data we will be able to know about the rest of services being used (EC2 specifically)

**Comment by chargio** [comment]
Ideally, the outcome would be to have our own system point out to our deployment, identify the resources used by cost management, and provide a report on costs and resources. Then we can use the number of customers to calculate an average.

**Comment by blentz** [comment]
I'm not sure that a forecast is really the right thing to focus on just yet.

The first step, IMO, ought to be reporting our per-tenant disk consumption (e.g. https://wiki.postgresql.org/wiki/Disk_Usage ) via either the status or another administrative API endpoint.

Once we have that information, we can track that consumption over time through Prometheus or some other tool.

At the end of all of that work, _then_ we can discuss whether to build out a way to forecast future storage needs.

**Comment by chargio** [comment]
This is going to be an ongoing request. If we have some data to extrapolate now and then when we have additional data we refine the forecast as we know more I am fine with that

**Comment by blentz** [comment]
Step 1: Surfacing storage consumption data

https://github.com/project-koku/koku/pull/589

**Comment by chambridge** [comment]
Shared Google Document  with team for project management to understand what our current spend is and how it can shift over time related to RDS usage. Definitive information depends on predicted customer types.

Brett added Prometheus metrics to show current customer data usage on RDS (broken down by schema).

Closing this item for now, until further requirement requests are in place and more definitive customer projections are in place.
