### ISSUE TITLE
View OCP Storage Usage and Request data in dashboard

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#596]
## User Story
As user, I want to understand my storage usage and request on OCP month over month so that I can compare and understand the drivers of my storage usage.

## Impacts
API, UI, Docs

## Role
User

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | api/v1/reports/inventory/ocp/volume/ |
 | **QueryParams** | ?filter[time_scope_units]={month or day}&filter[time_scope_value]={-1 or -2 or -10 or -30}&filter[resolution]={monthly or daily}&filter[limit]=5&group_by[{project or cluster or node or tag:value}]={* or value} |
 
**Response:**
```
{
	"group_by": {
		"project": ["*"]
	},
	"filter": {
		"resolution": "monthly",
		"time_scope_value": "-1",
		"time_scope_units": "month",
		"limit": 5
	},
	"data": [{
		"date": "2019-01",
		"projects": [{
			"project": "worker_proj",
			"values": [{
				"date": "2019-01",
				"project": "worker_proj",
				"usage": 489.777497,
				"request": 652.66972,
				"charge": 22.848948,
				"units": "GB-Month"
			}]
		}, {
			"project": "white_staging",
			"values": [{
				"date": "2019-01",
				"project": "white_staging",
				"usage": 668.714775,
				"request": 915.419569,
				"charge": 31.68269,
				"units": "GB-Month"
			}]
		}, {
			"project": "trial_prod",
			"values": [{
				"date": "2019-01",
				"project": "trial_prod",
				"usage": 426.486764,
				"request": 599.492358,
				"charge": 20.519583,
				"units": "GB-Month"
			}]
		}, {
			"project": "top_staging",
			"values": [{
				"date": "2019-01",
				"project": "top_staging",
				"usage": 97.679715,
				"request": 129.833436,
				"charge": 4.550266,
				"units": "GB-Month"
			}]
		}, {
			"project": "through_dev",
			"values": [{
				"date": "2019-01",
				"project": "through_dev",
				"usage": 543.538152,
				"request": 730.752343,
				"charge": 25.485822,
				"units": "GB-Month"
			}]
		}, {
			"project": "36 Others",
			"values": [{
				"date": "2019-01",
				"project": "36 Others",
				"usage": 14412.825285,
				"request": 19470.554558,
				"charge": 677.667648,
				"units": "GB-Month"
			}]
		}]
	}],
	"total": {
		"usage": 16639.022188,
		"request": 22498.721984,
		"charge": 782.754957,
		"units": "GB-Month"
	}
}
```
## Acceptance Criteria

- [ ] OCP Storage API returns usage and request of GiB per month data broken down by project, cluster, node, and tag key; also includes charge data and aggregated result.
- [ ] OCP Storage API provides meaning full error if given an invalid parameter or tag key.
- [ ] OCP Storage API provides a result of 0 if no matches are found based on the group_by or filter entries.

_____
Associated with: https://github.com/project-koku/masu/issues/347

**Comment by chambridge** [comment]
Don't think we can do by node, need to verify.
Would need an extra check in API for this case to return a 400 if node was used for group_by or filter.

**Comment by lcouzens** [comment]
Verified
Commit: 0daaf8012966f31e9fa15a20282716743197e915
Automation: test_api_ocp_volume_has_item_values, test_api_ocp_volume_endpoint
