### ISSUE TITLE
View OCP on AWS Total Monthly Cost

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#597]
## User Story
As a user, I want to be able to see the cost of running OCP on AWS so that I can understand my cost breakdown as a subset of overall AWS cost.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- Same as current view of AWS data providing daily/monthly breakdowns with the following groupings (account, services, regions, cluster, project, node, tag)

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | api/v1/reports/costs/ocp/ |
 | **Query Params** |  filter[time_scope_units]={month or day}&filter[time_scope_value]={-1 or -2 or -10 or -30}&filter[resolution]={daily or monthly}&filter[limit]=5&group_by[{service or account or region or tag:key or cluster or node or project }]={* or value}|
 **Response**:
```
{
	"group_by": {
		"service": ["*"]
	},
	"filter": {
		"resolution": "monthly",
		"time_scope_value": "-1",
		"time_scope_units": "month",
		"limit": 5
	},
	"data": [{
		"date": "2019-01",
		"services": [{
			"service": "AmazonEC2",
			"values": [{
				"date": "2019-01",
				"units": "USD",
				"service": "AmazonEC2",
				"total": 247.035683715
			}]
		}, {
			"service": "AmazonRDS",
			"values": [{
				"date": "2019-01",
				"units": "USD",
				"service": "AmazonRDS",
				"total": 24.361099056
			}]
		}, {
			"service": "AmazonGlacier",
			"values": [{
				"date": "2019-01",
				"units": "USD",
				"service": "AmazonGlacier",
				"total": 0.002097676
			}]
		}, {
			"service": "AmazonS3",
			"values": [{
				"date": "2019-01",
				"units": "USD",
				"service": "AmazonS3",
				"total": 0.000106328
			}]
		}, {
			"service": "AmazonSNS",
			"values": [{
				"date": "2019-01",
				"units": "USD",
				"service": "AmazonSNS",
				"total": 0.0
			}]
		}, {
			"service": "3 Others",
			"values": [{
				"date": "2019-01",
				"units": "USD",
				"service": "3 Others",
				"total": 0
			}]
		}]
	}],
	"total": {
		"units": "USD",
		"value": 271.398986775
	}
}
```

## UI Details
The UI will show the OCP on AWS cost month over month daily data in the dashboard.
The UI will provide top 5 cost drivers for (cluster, project, service, account, region)

## Acceptance Criteria

- [ ] A request containing a bad query parameter will result in a 400 and error message
- [ ] A request containing a filter that results in no matches will result in 0 total cost
- [ ] A request for an improper time scope will result in a 400 and error message
- [ ] A request for data with valid parameters matching OCP on AWS data will result in total cost broken down by day or month with associated groupings or filtering of data.

____
Associated with: https://github.com/project-koku/masu/issues/349

**Comment by lcouzens** [comment]
Verified
Commit: dd866691f654b4b4ffe91ad751b3db980946303c
