### ISSUE TITLE
View OCP on AWS Monthly Compute Instance Hours

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#598]
## User Story
As a user, I want to see my usage of EC2 instances for running OCP on AWS so that I can correlate the usage and cost drivers of the deployment broken down by instance type, account, region, cluster and project.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- Same as current view of AWS data providing daily/monthly breakdowns with the following groupings (account, services, regions, cluster, project, node, tag)

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | api/v1/reports/inventory/ocp/instance-type/ |
 | **Query Param** | filter[time_scope_units]={month or day}&filter[time_scope_value]={-1 or -2 or -10 or -30}&filter[resolution]={monthly or daily}&filter[limit]=5&group_by[{instance_type or account or region or cluster or project}]={* or value} |
 **Response:**
```
{
	"group_by": {
		"instance_type": ["*"]
	},
	"filter": {
		"resolution": "monthly",
		"time_scope_value": "-1",
		"time_scope_units": "month",
		"limit": 5
	},
	"data": [{
		"date": "2019-01",
		"instance_types": [{
			"instance_type": "t2.micro",
			"values": [{
				"instance_type": "t2.micro",
				"date": "2019-01",
				"units": "Hrs",
				"cost": 3.77,
				"count": 0,
				"total": 1365.0
			}]
		}, {
			"instance_type": "t2.small",
			"values": [{
				"instance_type": "t2.small",
				"date": "2019-01",
				"units": "Hrs",
				"cost": 71.287,
				"count": 28,
				"total": 1349.0
			}]
		}, {
			"instance_type": "db.t2.small",
			"values": [{
				"instance_type": "db.t2.small",
				"date": "2019-01",
				"units": "Hrs",
				"cost": 24.192,
				"count": 28,
				"total": 672.0
			}]
		}, {
			"instance_type": "t2.xlarge",
			"values": [{
				"instance_type": "t2.xlarge",
				"date": "2019-01",
				"units": "Hrs",
				"cost": 165.0432,
				"count": 28,
				"total": 672.0
			}]
		}]
	}],
	"total": {
		"units": "Hrs",
		"cost": 264.2922,
		"count": 3,
		"value": 4058.0
	}
}
``` 

## UI Details
The UI will show the OCP on AWS instance hour month over month daily data in the dashboard.
The UI will provide top 5 for (instance hours, cluster, project, account, region)

## Acceptance Criteria

- [ ] A request containing a bad query parameter will result in a 400 and error message
- [ ] A request containing a filter that results in no matches will result in 0 total usage data
- [ ] A request for an improper time scope will result in a 400 and error message
- [ ] A request for data with valid parameters matching OCP on AWS data will result in instance hour usage and cost broken down by day or month with associated groupings or filtering of data.

____
Associated with: https://github.com/project-koku/masu/issues/349

**Comment by adberglund** [comment]
Testing will require using nise to generate data for both OCP and AWS that share a resource_id

**Comment by lcouzens** [comment]
Verified
Commit: 6fb2ef11bb48542ce26b5011d30a29bac526e5be
