### ISSUE TITLE
View OCP on AWS Monthly Storage Allocation

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#599]
## User Story
As a user, I want to see my usage of Storage for running OCP on AWS so that I can correlate the usage and cost drivers of the deployment broken down by account, region, cluster and project.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- Same as current view of AWS data providing daily/monthly breakdowns with the following groupings (account, services, regions, cluster, project, node, tag)

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/inventory/ocp/storage/ |
 | **Query Param** | ?filter[time_scope_units]={month or day}&filter[time_scope_value]={-1 or -2 or -10 or -30}&filter[resolution]={monthly or daily}&filter[limit]=5&group_by[{account or region or cluster or project}]={* or value} |
 **Response:**
```
{
	"group_by": {
		"account": ["*"]
	},
	"filter": {
		"resolution": "monthly",
		"time_scope_value": "-1",
		"time_scope_units": "month",
		"limit": 5
	},
	"data": [{
		"date": "2019-01",
		"accounts": [{
			"account": "256293412812",
			"values": [{
				"date": "2019-01",
				"units": "GB-Mo",
				"account": "256293412812",
				"cost": 6.935483715,
				"total": 117.457744935,
				"account_alias": "256293412812"
			}]
		}, {
			"account": "589173575009",
			"values": [{
				"date": "2019-01",
				"units": "GB-Mo",
				"account": "589173575009",
				"cost": 0.171196732,
				"total": 26.262278963,
				"account_alias": "hccm-alias"
			}]
		}]
	}],
	"total": {
		"units": "GB-Mo",
		"cost": 7.106680447,
		"value": 143.720023898
	}
}
```
## UI Details
The UI will show the OCP on AWS storage usage month over month daily data in the dashboard.
The UI will provide top 5 for (cluster, project, account, region)

## Acceptance Criteria

- [ ] A request containing a bad query parameter will result in a 400 and error message
- [ ] A request containing a filter that results in no matches will result in 0 total usage data
- [ ] A request for an improper time scope will result in a 400 and error message
- [ ] A request for data with valid parameters matching OCP on AWS data will result in storage usage and cost broken down by day or month with associated groupings or filtering of data.

____
Associated with: https://github.com/project-koku/masu/issues/349

**Comment by chambridge** [comment]
We may not be able to do node. Need to to verify

**Comment by adberglund** [comment]
There is a small nise change required before this can easily be tested. I can detail how to manually test, but will work on the nise change.

**Comment by adberglund** [comment]
@lcouzens This should now be testable with nise static data and the work done in https://github.com/project-koku/masu/issues/352. In fact testing this, to me, tests https://github.com/project-koku/masu/issues/352. Basically if you generate AWS data with an EBS tag that matches a volume or volume claim label then we should have data visible in this API. The example files in nise have the tag `resourceTags/user:storageclass: bravo` already on EBS matching a volume with `label_storageclass:bravo`

**Comment by lcouzens** [comment]
Verified
Commit: 480d5fddb3d5a0c164f186a4f2034122afbb008b
Automation: test_ocp_on_aws_storage
