### ISSUE TITLE
Document how users can map tags between OCP and AWS for cost distribution

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#602]
## User Story
As a user, I want documentation that helps me understand how I can add tags to AWS and OCP so that cost in AWS can be properly correlated to OCP objects and tags.

## Impacts
Docs

## Role
User

## Details
- We will use the resolution from the tag mapping investigation: https://github.com/project-koku/masu/issues/338
To assume special AWS tag keys, `openshift_cluster`, `openshift_node`, and `openshift_project`, to correspond to the OCP objects cluster, node and project. All other tags will use an case-insensitive match.
- The user is required to add tags for correlation to both OCP resources (except for cluster, node, project) and AWS billing line items.
- If an AWS line item has multiple `openshift_project` tags (or other OCP objects with the special tag keys) the cost of the line item will be evenly distributed across those items (e.g. RDS service line item with 4 `openshift_project` tags will be split evenly 4 ways (naively assuming equal usage)

## Acceptance Criteria

- [ ] Documentation describes how tags are mapped and correlated
- [ ] Documentation provides links to AWS billing tag directions

____
Associated with: https://github.com/project-koku/masu/issues/352

**Comment by dayleparker** [comment]
@adberglund 
Hi Andrew,

I had a couple of questions as I'm adding this as a topic to the downstream user documentation.

1. Am I understanding correctly that tags and labels are automatically pulled into Koku after the source (OCP or AWS) is added to Koku? Does the user need to refresh anything/do anything else to show newly created tags from the sources?

2. Are there any additional steps needed by the user to map the AWS <=> OCP tags, or are they mapped automatically if the tags are identical?

3. I'm not sure I understand the point about "special AWS tag keys like openshift_cluster". Is _openshift_cluster_ a prefix for an AWS tag that would match an OCP tag? For example, if "development" was an OCP cluster, would this be how you'd name these resources to be mapped? :

AWS tag                                         | OCP label
openshift_cluster-development  |  development

Thanks for your help,
Dayle

**Comment by lcouzens** [comment]
Verified
Commit: dd866691f654b4b4ffe91ad751b3db980946303c
