### ISSUE TITLE
API for determining whether OCP clusters are running on AWS

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#607]
## User Story
As a user, if I have OCP clusters running on AWS, I want to see the cost of my clusters that are running on AWS so that I can understand cost of running these OCP clusters broken down by AWS cost line items; however, if I do not have any clusters running on AWS I should not have an option to view this information.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- This is special case provider information for OCP

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/providers/ |
 **Response:**
```
{
	"count": 1,
	"next": null,
	"previous": null,
	"results": [{
		"uuid": "e5206320-9286-4b0b-ac3c-7150102a21d2",
		"name": "ocp-hccm",
		"type": "OCP",
		"authentication": {
			"uuid": "fc15ebd5-8c1e-4306-b8ff-8fcc1347e0f2",
			"provider_resource_name": "9b6fc2fe-427b-4457-9f85-3211dd564158"
		},,
		"customer": {
			"uuid": "5065621e-5a39-495f-98b9-341b5d6b782f",
			"account_id": "6193296",
			"date_created": "2019-02-04T19:41:50.386195Z"
		},
		"created_by": {
			"uuid": "212a19fe-77c2-4395-aebb-5251f9d26fe6",
			"username": "cost-demo",
			"email": "chambrid@redhat.com"
		},
	       "infrastructure": "AWS",
		"stats": {
			"2019-01-01": [{
				"assembly_id": "f23124d1-cdb0-468d-a84a-a0adaa783280",
				"billing_period_start": "2019-01-01",
				"files_processed": "0/1",
				"last_process_start_date": "2019-02-04 19:55:15",
				"last_process_complete_date": null,
				"summary_data_creation_datetime": "2019-02-04 19:55:22",
				"summary_data_updated_datetime": "2019-02-04 20:06:02"
			}]
		}
	}]
}
```

## UI Details
UI can determine whether an OCP cluster/provider is running on AWS by looking at the information found in the providers endpoint. OCP clusters/providers will have a read-only `infrastructure` field that could be `AWS` or `Unknown`.

## Acceptance Criteria

- [x] OCP providers have "infrastructure" field that provides either "AWS" or "Unknown" correctly

**Comment by chambridge** [comment]
Maybe filter by infrastructure type too?

**Comment by dchorvat1** [comment]
Verified
commit: 178d2ea
