### ISSUE TITLE
Verify that resource_id is selected when Cost Usage Report is configured

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#610]
## User Story
As a user of koku I need AWS resource_id to be included in the cost usage report so that my data can be reflected accurately and will be guaranteed to be unique. 

## Impacts
Koku backend

## Assumptions
- Given our ARN permissions we can verify the CUR's settings

## Acceptance Criteria

- [ ] When we verify our ARN access during koku AWS provider onboarding, we succeed only if resource id is selected, otherwise an appropriate error is generated

**Comment by lcouzens** [comment]
Verified
