### ISSUE TITLE
Delta percent being returned as null

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#617]
**Describe the bug**
Delta percent being returned as null

**To Reproduce**
1. Add OCP provider with only a few days data
2. Head to api/v1/reports/charges/ocp/?delta=charge&filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&group_by[project]=*&order_by[charge]=desc
3. Scroll down to percent values
```{
    "group_by": {
        "project": [
            "*"
        ]
    },
    "delta": {
        "value": 0.0,
        "percent": null
    },
    "order_by": {
        "charge": "desc"
    },
    "filter": {
        "resolution": "monthly",
        "time_scope_value": "-1",
        "time_scope_units": "month"
    },
    "data": [
        {
            "date": "2019-02",
            "projects": [
                {
                    "project": "namespace_ci",
                    "values": [
                        {
                            "date": "2019-02",
                            "project": "namespace_ci",
                            "charge": 0.0,
                            "units": "USD",
                            "delta_value": 0.0,
                            "delta_percent": null
                        }
                    ]
                }
            ]
        }
    ],
    "total": {
        "charge": 0.0,
        "units": "USD"
    }
}
```
**Expected behavior**
We should always return the percentage as a number.

**Screenshots**
![screenshot from 2019-02-08 21-07-50](https://user-images.githubusercontent.com/18352403/52506989-297d5f00-2be8-11e9-883f-e3d1a1d44f5a.png)

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Chrome
 - Commit Hash from status endpoint: 3a71f65270828b5409a5038795a9cd24d8764dd4

**Additional context**
This is actually causing an issue in the UI on the OpenShift details page, as the API is not returning a number the UI shows it as NaN% of charge. See screenshot

**Comment by chambridge** [comment]
@lcouzens what do you expect the response here to be?

`1.00`?
or 
`0.00`?

Neither are quite true as we don't really know the delta based on the information we have. I almost feel that `null` is a good response as long as the UI is tolerating it and presenting a good message (which I believe it does now).

**Comment by lcouzens** [comment]
Yeah I think I agree, I was mainly raising it for clarification and to help fix the UI bug, but like you say I think it handles it now so we can probably just close this?
