### ISSUE TITLE
Align REST API with Platform Guidelines

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#629]
## User Story
As insights application owner, I want our app to follow the platform RESTAPI guidelines so that the user has a consistent experience when utilizing the REST API.

## Impacts
API, UI, Docs

## Role
Application Owner

## Assumptions
- We will make multiple PRs to minimize breaks with the UI and Automation

## API Details
https://docs.google.com/document/d/1sEgro5-lXYJGsxOdxFOcyz7EHilrnpBVkHT_m2IXogk/edit

## UI Details
UI updates will need to match the changes to the API

## Acceptance Criteria

- [ ] REST API returns the same data content in the refactored format
- [ ] REST API conforms to the Platform REST API Guidlines

____
Associated issues:
https://github.com/project-koku/koku/issues/487
https://github.com/project-koku/koku/issues/421
https://github.com/project-koku/koku/issues/431
https://github.com/project-koku/koku/issues/483
https://github.com/project-koku/koku/issues/490

**Comment by chambridge** [comment]
All items completed, with time scope refactor defered.

**Comment by lcouzens** [comment]
Verified
Commit: dd866691f654b4b4ffe91ad751b3db980946303c
