### ISSUE TITLE
OCP on AWS Storage allocation API does not support tags

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#635]
**Describe the bug**
Looks like OCP on AWS serializer doesn't support tags.

**To Reproduce**
*GET* `/r/insights/platform/cost-management/api/v1/reports/inventory/ocp/storage/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&group_by[tag:environment]=*`

```
{
    "group_by": {
        "tag:environment": [
            "Unsupported parameter"
        ]
    }
}
```

**Comment by adberglund** [comment]
AWS tags are currently what the filtering happens on. If we also want OCP labels then we definitely need to rework our tag system a little bit.

**Comment by chambridge** [comment]
Gotcha dumb issue on my part.  It’s an invalid tag for the given data set.  Makes sense I was just following PR examples.
