### ISSUE TITLE
reports/costs/aws API cannot groupBy tag

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#644]
**Describe the bug**
Noticed that reports/costs/aws API isn't quite working as expected (regarding tags) this morning. This had been working last week (i.e., last tested on Feb 13).

**To Reproduce**
GET /r/insights/platform/cost-management/api/v1/reports/costs/aws/?delta=total&filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&group_by[tag:5dc_key]=*&group_by[account]=*&order_by[total]=desc

**Expected behavior**
I expect data to be returned, matching the given tag parameter: group_by[tag:5dc_key]=*.

**Screenshots**
<img width="734" alt="screen shot 2019-02-18 at 2 26 41 pm" src="https://user-images.githubusercontent.com/17481322/52972618-7223dd80-3389-11e9-8397-c355ca6a4bcb.png">

**Additional context**
This still works:

GET /r/insights/platform/cost-management/api/v1/reports/charges/ocp/?delta=charge&filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&group_by[tag:hive]=*&group_by[project]=*&order_by[charge]=desc

**Comment by lcouzens** [comment]
Verified
Commit: 0daaf8012966f31e9fa15a20282716743197e915
