### ISSUE TITLE
Convert Swagger to OpenAPI v3 and host JSON definition

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#646]
## User Story
As an API user, I want to be able to consume the Cost Management API so that can understand and potentially utilize a client to interact with it.

## Impacts
API

## Role
API User

## Assumptions
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/openapi.json |
 | **Response** | JSON data for OpenAPI definition|

## Acceptance Criteria

- [ ] Able to download Open API definition for provided path
- [ ] Able to view Open API definition using [Swagger Editor](http://editor.swagger.io/)

____
Associated with: 
https://github.com/project-koku/koku/issues/629

**Comment by dchorvat1** [comment]
Verified
commit: 'a00d92b353e8387a2c140f30652318f74de5d419'
