### ISSUE TITLE
Align existing pagination with the new platform guidelines

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#654]
Rework the existing pagination items (providers, rates, preferences).
```
{
"count": 2,
"next": null,
"previous": null,
"results": [ ... ]
}
```
converted to:

```
{
"meta": { "count": 2},
"links": {
"first": null,
"next": null,
"previous": null,
"last": null,
},
"data": [ ... ]
}
```
___ 
Associated with: 
https://github.com/project-koku/koku/issues/629

**Comment by lcouzens** [comment]
Verified
Commit: 3da7031fae2cf0eb8e422a352e18870fe64a0aa9
