### ISSUE TITLE
AWS and OCP provider counts

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#658]
## User Story
As a user, I want to see an empty state when providers do not exist under the following scenarios.

- On the AWS Details page, when there are no AWS providers
- On the OCP Details page, when there are no OCP providers
- On the Overview page, when there are neither AWS or OCP providers

## Impacts
Ex. API, UI, Docs

## Role
UI

## Assumptions
- The existing count represents the total number of AWS/OCP providers
- The existing count returns zero if no providers exist
- The data is an empty array if no providers exist

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/providers/ |
 | **Body** |  |
 | **Response** |  |

## UI Details
Currently, the UI uses the providers API to see if there is at least one AWS or OCP provider. However, this API is paginated and we cannot always determine if there is an AWS provider; for example, when 10+ providers exist. The only way we could do this today is to make multiple API calls and search each page of data.

It was suggested we could add a filter to return just the AWS or OCP providers. That would allow the UI to make one API call for the AWS / OCP Details pages.

See: https://github.com/project-koku/koku-ui/issues/453

## Acceptance Criteria

- [ ] The API provides a separate count of AWS providers
- [ ] The API provides a separate count of OCP providers

**Comment by lcouzens** [comment]
Verified
Commit: 3da7031fae2cf0eb8e422a352e18870fe64a0aa9
