### ISSUE TITLE
Missing parameters in providers API docs

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#660]
**Describe the bug**
The providers API docs are missing the `page_size` parameter.

**To Reproduce**
1. Go to 'https://raw.githubusercontent.com/project-koku/koku/master/docs/source/specs/openapi.json'
2. Cut/paste that into a swagger editor
3. Scroll down to 'providers'

**Expected behavior**
All parameters should be documented.

**Screenshots**
![screen shot 2019-02-21 at 11 02 48 am](https://user-images.githubusercontent.com/17481322/53182844-480c2e80-35c8-11e9-81b6-a42f2802ed0a.png)

**Comment by chambridge** [comment]
https://github.com/project-koku/koku/pull/667

**Comment by lcouzens** [comment]
Verified
Commit: 3da7031fae2cf0eb8e422a352e18870fe64a0aa9
