### ISSUE TITLE
Collapse the charge and cost APIs into a single API

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#668]
## User Story
As user, I don't want confusion between cost and charge concepts therefore my cost API should provide both the cost from infrastructure and the derived cost from rates so that I have a single API to see all my costs.

## Impacts
API, UI, Docs

## Role
User

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/{provider_type}/costs/ |
 **Response**: 
Alter to contain the following for the cost information instead of `total`, `cost` or `charge`
```
"infrastructure_cost": { "value": 100.00, "unit": "USD" }
"derived_cost": { "value": 50.00, "unit": "USD" }
"cost": { "value": 150.00, "unit": "USD" }
```
`cost` = `infrastructure_cost` + `derived_cost`

`aws` would currently have `infrastructure_cost`; `derived_cost` == `0` (until we have markup) 

`openshift` will have `infrastructure_cost` only if running on AWS otherwise the value will be `0.00`
`openshift` will have `derived_cost` only if rates are defined otherwise the value will be `0.00`

## UI Details
UI will call costs endpoint for each provider and consume the new values.

____
Associated with: https://github.com/project-koku/koku/issues/629
Discussion here: https://github.com/project-koku/koku/issues/487#issuecomment-464875359

**Comment by chambridge** [comment]
FYI @chargio @dayleparker @lcouzens 

After an extensive development conversation we are making the above update.

**Comment by lcouzens** [comment]
Verified
Commit: dd866691f654b4b4ffe91ad751b3db980946303c
Automation: test_ocp_cost_reports
