### ISSUE TITLE
Support group by and filter for product family with AWS cost data

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#684]
## User Story
As user, I want to breakdown my AWS cost using the product families supply by AWS so that I can understand my month over month costs in the high-level areas and then breakdown the data further by additionally grouping by associated service/accounts/ regions etc.

## Impacts
API, UI

## Role
User

## Assumptions
- UI will be showing month over month data for specific product families to provide an enhanced view of AWS cost.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /v1/reports/aws/cost |
 | **Query Parameter** | group_by[product_family]=* or group_by[product_family]=Compute or filter[product_family]=Compute |

## Acceptance Criteria

- [x] Support cost output with group by of product family data with wild card or filtered group by
- [x] Support cost output filtered by product family (one or more)
- [x] If filter or filtered group by used and no items match then returned response will be 0, not an error

**Comment by dchorvat1** [comment]
verified
commit: 'fc853c716d68d810d03be91c1c767655a4a85e67'
