### ISSUE TITLE
Document Openshift Object and AWS account visibility control

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#688]
## User Story
As a user, I want documentation that describes the feature around how visibility to a subset of data either OpenShift or AWS or so that I under stand that the feature exists and how to leverage it additionally how it is dependent on the defined Groups, Roles, and Policies.

## Impacts
Docs

## Role
Account Admin, User

## Assumptions
- A more complete description of RBAC management will be done when implemented in the UI, for now we want to describe the existence of the feature.

# Associated with:
#686 
#687

**Comment by lcouzens** [comment]
Verified
