### ISSUE TITLE
All api response's should show you current default filter values

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#696]
**Describe the bug**
All api response's should show you current default filter values

**To Reproduce**
1. Go to any endpoint such as 'r/insights/platform/cost-management/v1/reports/aws/costs/'
2. See json response, no default filters shown
```
HTTP 200 OK
Allow: OPTIONS, GET
Content-Type: application/json
Vary: Accept

{
    "data": [
        {
            "date": "2019-02-21",
            "values": [
                {
                    "date": "2019-02-21",
```
**Expected behavior**
We should show the current default values that are being used with each call. Such as resolution, time_scope_units, time_scope_value.

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Chrome
 - Commit Hash from status endpoint: 4d67ef8cbc2f2a3c5dd0ff2505551903631d8620

**Additional context**
We show the values when they are manually used.
aws/costs/?filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1
```
HTTP 200 OK
Allow: OPTIONS, GET
Content-Type: application/json
Vary: Accept

{
    "filter": {
        "resolution": "monthly",
        "time_scope_value": "-1",
        "time_scope_units": "month"
    },
    "data": [
        {
            "date": "2019-03",
            "values": [
```

**Comment by chambridge** [comment]
kinda a feature, but I'm okay with doing this. Not sure what makes it a medium priority bug, but I'm with you on "nice to have".

**Comment by lcouzens** [comment]
Yeah so it came out of the unit/value discussions I was having with Pete on Friday. Happy to lower priority, tbh I thought I clicked low.. :)

**Comment by lcouzens** [comment]
Verified
Commit: 7d70418c6ff42c67635c13da7bcc651078efed4b
