### ISSUE TITLE
OpenShift project/node name collisions possible

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#711]
**Describe the bug**
If Openshift  project or node with the same name exist on multiple clusters the resulting report APIs to not provide an accurate view of the data (either dropping or combining values)

**To Reproduce**
1. Generate nise report with the same project and/or node names for two different clusters
2. Upload information for providers with associated rates
3. See error

**Expected behavior**
Should see each individual data point from different clusters.

On any group_by for node or project we should add annotations for the cluster and cluster_alias to create the distinct rows.

**Comment by lcouzens** [comment]
Verified
Commit: d63dfd02ff0063d8de9f18f8c8f6b6421a694905
