### ISSUE TITLE
Group by logical AND

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#713]
**Describe the bug**
During testing, I noticed that partial group_by strings are no longer applied using logical AND. This happens for both AWS and OpenShift detail pages.

**To Reproduce**
1. Go to 'AWS Details'
2. Click on 'Filter by Project'
3. Enter 'jonny'
4. Enter 'hccm'
5. See error

**Expected behavior**
When I enter 'jonny' and 'hccm', in the AWS details filter, two items are returned; 'jonnyfive' and 'hccm-alias'. I expect to see only items that match both.

When the UI applies each group_by parameter, the PatternFly pattern is expected to be applied using logical AND, not OR.

**Screenshots**

AWS Details:
![screen shot 2019-03-06 at 5 04 49 pm](https://user-images.githubusercontent.com/17481322/53919017-adcfd000-4036-11e9-9d6e-75c940f6efc5.png)

OpenShift Details:
![screen shot 2019-03-06 at 5 03 32 pm](https://user-images.githubusercontent.com/17481322/53919043-bc1dec00-4036-11e9-9b3d-dcaa9823bd92.png)

**Additional context**
OCP Details
* Request URL: https://ci.foo.redhat.com:1337/r/insights/platform/cost-management/v1/reports/openshift/charges/?delta=cost&filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&group_by[tag:pod_template_hash]=332952236&group_by[tag:pod_template_hash]=1057594167&order_by[cost]=desc
* Request Method: GET

AWS Details
* Request URL: https://ci.foo.redhat.com:1337/r/insights/platform/cost-management/v1/reports/aws/costs/?delta=cost&filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&group_by[account]=jonnyfive&group_by[account]=hccm&order_by[cost]=desc
* Request Method: GET

**Comment by dchorvat1** [comment]
Verified
commit b7b53fac8b29c96de7dbea2ada1cb023219741bc
