### ISSUE TITLE
Sort by tag name

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#714]
## User Story
As a user, I want to sort tags in the AWS and OCP detail pages.

## Impacts
Ex. API, UI, Docs

## Role
User

## Assumptions
-
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/PATCH/DELETE |
 | **Path** | /api/v1/reports/aws/costs/ |
 | **Body** |  |
 | **Response** | |

## UI Details
Currently, sorting by tags does not appear to be supported? Thus, the sort feature must be disabled in the UI.

The parameter `order_by[cost]=asc` seems to work with `group_by[tag:environment]=*`. However, `order_by[tag:environment]=asc` does not work.

/r/insights/platform/cost-management/v1/reports/aws/costs/?delta=cost&filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&group_by[tag:environment]=*&order_by[name]=asc

## Acceptance Criteria

- [ ] Able to sort while applying group_by tag keys
- [ ] Support params like `group_by[tag:environment]=asc` or `order_by[name]=asc`

**Comment by chambridge** [comment]
Some kind of sort by tag value
