### ISSUE TITLE
Tech Debt: Delta calculations with monthly resolution could be misleading.

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#719]
Calculating deltas when `resolution=month` is currently doing a naive delta.

The code doesn't consider total number of days or number of data points between the two querysets being compared. In this way, a delta of Jan to Feb is comparing 31 days of data to 28/29 days. In many cases, this comparison isn't very meaningful or could be misleading.

We should discuss which data sets can provide meaningful deltas and drop support for those we exclude.

**Comment by adberglund** [comment]
To be talked about with the larger time scope discussion.

**Comment by blentz** [comment]
Moved: https://issues.redhat.com/browse/COST-120
