### ISSUE TITLE
Group By / Filter By Openshift Tags returns "Unsupported parameter" for valid tag key

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#720]
**Describe the bug**
Group by tag is failing with valid tag key.

<img width="331" alt="image" src="https://user-images.githubusercontent.com/29379759/54071840-50a76a80-4240-11e9-8933-a207480f8514.png">

**To Reproduce**
1. Go to *GET* `/r/insights/platform/cost-management/v1/tags/openshift/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly`
2. Select a valid tag key to pass to the openshift cost API
3. Request *GET* `/r/insights/platform/cost-management/v1/reports/openshift/costs/?delta=cost&filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&group_by[tag:app]=*&order_by[cost]=desc`

**Expected behavior**
Should group by the valid tag key

**Comment by chambridge** [comment]
This should work now with the latest updates. Please try an reopen if not working.

**Comment by dlabrecq** [comment]
Unfortunately, I'm seeing a different 500 error now.

![Screen Shot 2019-03-14 at 11 26 26 AM](https://user-images.githubusercontent.com/17481322/54369304-15e07080-464c-11e9-9c60-406b838af6e3.png)

**Comment by chambridge** [comment]
Thanks for trying it out we'll take a look.

**Comment by dchorvat1** [comment]
Verified
Commit: 178d2ea
