### ISSUE TITLE
Add 'page' property for pagination

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#733]
## User Story
As a user, I want a 'page' parameter for pagination APIs.

## Impacts
Ex. API, UI, Docs

## Role
User

## Assumptions
- The page property would be an optional parameter
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/openshift/costs/ |
 | **Body** |  |
 | **Response** | |

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/aws/costs/ |
 | **Body** |  |
 | **Response** | |

## UI Details
We have pagination working with sort and filtering. However, it's painful to calculate the offset. That is, considering the PatternFly pagination component works with properties like page, limit, and count.

When we need to fetch new data from the API; for example, the offset must be calculated like so:

`const offset = (pageNumber * limit) - limit;`

Upon updating the UI with the response, we then need to calculate the page for the PatternFly pagination component, like this:

`const page = (report.meta.filter.offset / report.meta.filter.limit) + 1;`

It would be ideal to provide the API with a limit and page number. Then, we could let the API calculate what its own offset should be.

Note that we must implement this in multiple places in the UI. Calculating the offset and page like this feels error prone.

## Acceptance Criteria

- [ ] API accepts page and limit properties
- [ ] The offset property is not required

**Comment by dlabrecq** [comment]
FYI @adberglund

**Comment by chambridge** [comment]
This is not in alignment with the IPP-12
https://docs.google.com/document/d/1sEgro5-lXYJGsxOdxFOcyz7EHilrnpBVkHT_m2IXogk/edit

You can use the links meta data to get the previous and next values instead of calculating yourself.

**Comment by dlabrecq** [comment]
Unfortunately, we only obtain the page number from the PF4 pagination component. We cannot tell if the user has clicked on the first, last, next, or previous page. So, we cannot just use the first or last links; for example, without yet more logic to track. Will keep the calculations we currently have, but perhaps try filing an issue with PatternFly?
