### ISSUE TITLE
Capture total/free space remaining for DB metrics

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#737]
## User Story
As service operator, I want to report the remaining free space for the database so that I can create an alert when the DB is 90% utilized in order to increase the db size.

## Impacts
Backend

## Role
Service operator

## Implementation Details
Extend the current DB metrics gathering capabilities to capture core total, used, free space metrics.

## Acceptance Criteria

- [ ] See new DB metrics in Grafana chart

**Comment by blentz** [comment]
A few months ago, I was working on a port of an existing prometheus exporter for postgresql metrics. There was some technical reason for doing the port - dead upstream, I think.

I've got my work-in-progress code in a branch: https://github.com/project-koku/koku/compare/master...blentz:postgresql-exporter

Original code: https://github.com/wrouesnel/postgres_exporter

So, one approach to this issue would be to finish off my port. This will enable us to send all of postgresql's metrics to prometheus.

**Comment by blentz** [comment]
Update:

1. PostgreSQL doesn't have an internal mechanism for showing filesystem usage stats for where it is deployed. My previous comment about the postgresql-exporter isn't a solution this issue.

2. OpenShift already exposes all filesystem stats to Prometheus. So, for databases deployed inside of OpenShift, this is already complete.

3. The use case for databases deployed externally (e.g. AWS), that needs to be handled.
