### ISSUE TITLE
Create Alerts for cost management operations

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#738]
## User Story
As service operator, I want alerts that notify me of important system issues so that I can respond and fix potential customer issues.

Important system issues:
- Low DB space
- X number of 5xx response codes within a 5 minute period
- X number of provider processing errors within the last hour
- Provider ingestion has not happened in the last 36 hours

## Role
Service Operator

## Assumptions
- Utilizing OpenShift Alert manager from prometheus data

## Implementation Details
Docs on how to add Slack integration and write rules based on prometheus data:
https://platform-docs.cloud.paas.upshift.redhat.com/sre/alerts.html

## Acceptance Criteria

- [x] See active alerts in Alert Manager setup

**Comment by blentz** [comment]
Remaining alerts created in insights-mnm-deploy#58
