### ISSUE TITLE
Openshift costs API blows up when using group_by tag

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#748]
**Describe the bug**
Openshift costs API blows up when using group_by tag

**To Reproduce**
1. Add OCP provider
2. Go to `v1/reports/openshift/costs/?group_by[tag:app]=*`
3. See error

**Expected behavior**
API should return costs grouped by tags

**Screenshots**
![Screenshot from 2019-03-18 11-17-07](https://user-images.githubusercontent.com/18352403/54526679-64a14980-496f-11e9-9fb8-3ab3ce0030db.png)

![Screenshot from 2019-03-18 11-22-04](https://user-images.githubusercontent.com/18352403/54526912-2b1d0e00-4970-11e9-99a3-cbdf006555e7.png)

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: cb23d119a77210211dd0bcb428df302d149fbedc

**Additional context**
This can be seen currently on CI
This issue is also causing the UI OpenShift details to break
API Compute/Memory group bys are working as expected.

**Comment by lcouzens** [comment]
This also blows up when doing a filter on the tag too.

**Comment by chambridge** [comment]
Looks like this is now where #720 is at and it should fix both of these.

Closing this as a dup @lcouzens
