### ISSUE TITLE
Filter Openshift Usage endpoints by infrastructure

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#749]
## User Story
As user, I want only see the usage data for OpenShift clusters running on AWS when I'm in the OpenShift on AWS view so that I can differentiate that information from on-prem/unknown infrastructure types.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- Will determine the clusters running on AWS and filter the usage data to just those.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /v1/reports/openshift/{compute or memory or volumes}/?infrastructures=aws |
 | **Response** | Usage data for only openshift running on AWS|

## UI Details
Will need to pass the query parameter

## Acceptance Criteria

- [ ] Should only seed data for AWS openshift
- [ ] passing an infrastructure that isn't "aws" causes a 400

**Comment by dchorvat1** [comment]
Verified
commit: 71ea39a7d29eff584d5763c2c48106ac1007da14
