### ISSUE TITLE
Upgrade to newer version of PostgreSQL

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#759]
Looking at the PostgreSQL feature matrix, there are several performance-related enhancements in psql 10 and 11.  See: https://www.postgresql.org/about/featurematrix/

We should upgrade to at least Postgres 10.x, if not 11.x sometime soon. Investigate the timing and develop a migration plan for doing the upgrade.

There already is a Centos 7 container image with PostgreSQL 10: https://hub.docker.com/r/centos/postgresql-10-centos7

**Comment by adberglund** [comment]
We should stay consistent with RDS as our production database.

**Comment by adberglund** [comment]
RDS is currently running Postgres 10.0. If we upgrade our image to 10.0 It would also be a great time to separate the Postgres deployment from Koku since we don't really want a postgres pod in production.

**Comment by blentz** [comment]
RDS supports postgres 11: https://aws.amazon.com/rds/postgresql/why-postgresql-11/
