### ISSUE TITLE
Clean up AWS and OCP test data generators

### ISSUE THREAD

**Issue by dccurtis** [project-koku/koku#762]
There are three test generators that the Koku unit tests use: `OCPReportDataGenerator`, `OCPAWSReportDataGenerator`, and `FakeAWSCostData`.

A couple of areas could be cleaned up:
1. `FakeAWSCostData` should be decoupled from `ReportQueryTest` and put into it's own file, `add_data_to_tenant` should be part of this class like it is in the other report generators.  Might as well change the name to `AWSReportDataGenerator` too
2. `OCPAWSReportDataGenerator` has a method to add corresponding AWS data to align with the OCP data, `add_aws_data_to_tenant`.  Once #1 is done, this method could be used as the basis for `AWSReportDataGenerator(). add_data_to_tenant()` and that generator should be used here.
3. `OCPAWSReportDataGenerator` has the capability to create OCP and AWS line items and daily summary to simulate OCP-on-AWS clusters.  `_populate_ocp_aws_cost_line_item_daily_summary()` should be replaced with a proper summary implementation based on the `OCPAWSUsageLineItemDaily` view.
4.  Once #3 is done test case `test_ocp_infrastructure_type` can become:
```
    def test_ocp_infrastructure_type(self):
        """Test that the provider infrastructure returns Unknown when running stand alone."""
        data_generator = OCPAWSReportDataGenerator(self.tenant, current_month_only=True)
        data_generator.add_data_to_tenant()
        data_generator.create_ocp_provider(data_generator.cluster_id, data_generator.cluster_alias)

        provider_uuid = data_generator.provider_uuid
        manager = ProviderManager(provider_uuid)
        infrastructure_name = manager.get_infrastructure_name(self.tenant)
        self.assertEqual(infrastructure_name, 'Unknown')

        data_generator.remove_data_from_tenant()
```

**Comment by blentz** [comment]
We should probably complete #1085 before working on this issue.

**Comment by adberglund** [comment]
@lcouzens Nothing to actually QA here, as this impacts dev unit tests only. Just following protocol by putting it in QA.
