### ISSUE TITLE
Limit query parameter groups project names from different clusters

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#774]
**Describe the bug**
Limit query parameter for OCP cost reports makes the api display different results 

**To Reproduce**
1. Go to api
2. Get OCP cost reports [1] without filter[limit] 
3. Get OCP cost reports [2] with filter[limit]
4. See that the results differ

**Expected behavior**
There should be two projects if they are in different clusters 

**Screenshots**
![Screenshot from 2019-03-29 10-11-33](https://user-images.githubusercontent.com/46324552/55223471-8d96c980-520e-11e9-87b6-b918d44f9400.png)
![Screenshot from 2019-03-29 10-11-45](https://user-images.githubusercontent.com/46324552/55223482-8ff92380-520e-11e9-9bbb-f0442f9246de.png)

**Context (please complete the following information):**
 - OS: RHEL
 - Browser: chrome
 - Commit Hash from status endpoint: 562bcaa9a04b01f5dc02b0566a15764a3514283d

**Additional context**
tested on lcouzens account
[1]: ?delta=cost&filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&group_by[project]=*&order_by[cost]=desc
[2]:  ?delta=cost&filter[limit]=10&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[project]=*&order_by[cost]=desc

cc: @lcouzens feel free to correct me if I misunderstood anything in our discussion, or if you want to provide any additional information

**Comment by lcouzens** [comment]
@adberglund So I think this is related to the cluster_alias changes, I wonder whether there is some corner case when specifying limit. Weird things seem to happen with limit anyway, also I noticed that we are adding cluster_alias to `others` ```  {
                    "project": "22 Others",
                    "values": [
                        {
                            "cluster_alias": "test0-ocp-alpha",
                            "date": "2019-03",
                            "cluster": "test0-ocp-alpha",
                            "project": "22 Others",
                            "infrastructure_cost": {
                                "value": 336.0,
                                "units": "USD"
                            },
                            "derived_cost": {
                                "value": 4038.894987,
                                "units": "USD"
                            },
                            "cost": {
                                "value": 10220.682039,
                                "units": "USD"
                            }```

**Comment by blentz** [comment]
I could not reproduce the original bug. It seems like it's already been fixed.

I've created PR#787 to fix the secondary issue of improper labels in the "other" category.

**Comment by dlabrecq** [comment]
The UI flattens out the list by project, cluster, or node. As long as those values are unique, there won't be an issue, considering the data structure is an array. However, the projects in the example above use the same name. I suspect one project could override the other in our flattened list. One way to fix that would be to provide a unique ID for each item in the report.
