### ISSUE TITLE
Review API performance using grafana chart results

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#776]
We currently have grafana charts that provide response time stats for our various REST APIs
https://metrics-mnm-ci.5a9f.insights-dev.openshiftapps.com/d/2qQzKA_mk/cost-management-ci-environment?orgId=1

Some of these responses are on the slow between 4-14 seconds. We need to determine if any performance improvements can be made.

Seems to be the `reports-openshift-cpu` and `reports-openshift-memory` views. I'd guess that volume likely has the same issue, but isn't being seen as it is not present on the Cost Management overview.

**Comment by adberglund** [comment]
For now the biggest change for CI was just bumping up memory limits for koku and the koku-pgsql deployments. This has brought the slowest calls back down to the 1-2 second range. There are a few more improvements we can potentially make to speed those calls up now, but I suspect our biggest issue was resource strain on the DB pod.

**Comment by adberglund** [comment]
Opened https://github.com/project-koku/masu/issues/411,  #804, #805, #806 as specific performance improements.
