### ISSUE TITLE
Cache RBAC response into Redis/MemCache with 30s TTL

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#777]
Currently, every request to our API calls the RBAC service. We take the data from the RBAC service and convert it to a dictionary of access items (aws accounts, openshift clusters etc).

We could make less calls to the RBAC service and skip data transformation if we stored the data in Redis or Memcache with a short time to live window.

We could check whether use of Redis/MemCache was enable (so we can run with or without it).
If it is we check for a hit, if not we call the RBAC Service and construct the access object. When done constructing the access object we store that object for the given user in Redis/Memcache (if enabled) so the next request can reuse that data.

Would be nice to also have the time to live be configurable (default 30s) so we can toggle that value if need be.

**Comment by lcouzens** [comment]
Verified
Commit: 54550d21cbb71211122fbfb7bb7a483bef727e38
