### ISSUE TITLE
Create production users for demo with non administrator roles

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#779]
Our current `cost-demo` user in production is an administrator. We need users setup that are using less visibility. One should use the globally seeded role Cost Cloud Viewer to see AWS data. Another should use the globally seeded role Cost OpenShift Viewer to see all OpenShift data.

**Comment by chambridge** [comment]
Non-admin users have been created and setup with access.

**Comment by lcouzens** [comment]
Hey @chambridge could you send me the creds for these on slack so I can verify this issue.

**Comment by dchorvat1** [comment]
In the "viewer" demo users, we can still click "add sources" from the overview page, which takes us to sources page, where we can see all cost management sources and add/delete them. I assume this is not correct, according to demo requirements, viewer role should only see their data and not be able to add/remove anything

**Comment by chambridge** [comment]
No we decided to not add any RBAC around sources, since these APIs will go away once we integrate with the platform sources. The point of these users is really about visibility controls.

**Comment by lcouzens** [comment]
@dchorvat1 I think you can verify this one now then based on everything else you told me.

**Comment by dchorvat1** [comment]
Verified
