### ISSUE TITLE
Add globally seeded roles for Cost to RBAC service

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#780]
RBAC service is supporting globally seeded uneditable roles.

We need to define our roles for cost:
Cost Administrator - all access
Cost Price List Administrator - Write access for all rates
Cost Cloud Viewer - Read access for all AWS accounts
Cost OpenShift Viewer - Read access for all OpenShift clusters

**Comment by lcouzens** [comment]
Verified
Commit: 290f970787c32058e868da103075b01fb728cc36
