### ISSUE TITLE
OCP on AWS: Filter by product family yields same cost

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#789]
**Describe the bug**
We're adding AWS database and network cards to the UI's OpenShift on AWS overview page. However, unlike the AWS overview page, filtering by product family shows no difference in the cost.

Similar to the AWS overview page, I expected to apply a product family filter to the `/reports/openshift/infrastructures/aws/cost` API. Is there something the UI needs to do differently?

**To Reproduce**
1. Go to 'Overview'
2. Click on 'OpenShift on cloud'
3. Scroll down to 'AWS network services''
3. Scroll down to 'AWS database services'

**Expected behavior**

**Screenshots**
No product family:
![Screen Shot 2019-04-04 at 1 44 36 PM](https://user-images.githubusercontent.com/17481322/55576665-d1db0b80-56df-11e9-83e7-9c06a9f0654f.png)
`/reports/openshift/infrastructures/aws/costs/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&filter[limit]=5`

'Load Balancer-Network':
![Screen Shot 2019-04-04 at 1 45 36 PM](https://user-images.githubusercontent.com/17481322/55576719-f20aca80-56df-11e9-8a54-ce2e9654472e.png)
`/reports/openshift/infrastructures/aws/costs/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=daily&filter[limit]=5&filter[product_family]=Load%20Balancer-Network`

'Database Instances':
![Screen Shot 2019-04-04 at 1 46 50 PM](https://user-images.githubusercontent.com/17481322/55576828-2e3e2b00-56e0-11e9-87a0-4beaecccded7.png)
`/reports/openshift/infrastructures/aws/costs/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=daily&filter[limit]=5&filter[product_family]=Database%20Instance`

**Comment by lcouzens** [comment]
Verified
Commit: 3d29fc6466fc14fc8372aef1995b6be498235d74
