### ISSUE TITLE
Get a list of services that are part of Storage and Databases

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#791]
## User Story
As the user, we want to be able to select all services that are related to databases and networking so they can be part of the cards for networking and databases.

## Impacts
Details and dashboard.

## Assumptions
- The list will be automatically created by AI in the future, we are doing this exercise once and it won't be recurring until AI provides it.
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/PATCH/DELETE |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ] 
- [ ]

**Comment by adberglund** [comment]
@chargio Let's talk about this so we can get a clearer picture of what we need before we tackle this

**Comment by chargio** [comment]
Sent you an invite @adberglund

**Comment by adberglund** [comment]
For the time being, to avoid maintaining a mapping and special column on our side we can make use of the `filter[service]` filter to return data for the specific services we care about 

That would mean that database and network cards go from using a `product_family` filter to a `service` filter.

To start we can do the following 

For network: `filter[product_family]=Load Balancer-Network` :arrow_right:  `filter[service]=AmazonVPC,AmazonCloudFront,AmazonRoute53,AmazonAPIGateway`

For database: `filter[product_family]=Database Instance` :arrow_right:  `filter[service]=AmazonRDS,AmazonDynamoDB,AmazonElastiCache,AmazonNeptune,AmazonRedshift,AmazonDocumentDB`

**Comment by blentz** [comment]
[Bug Triage]

Needs acceptance criteria.

We need to define what the desired behavior is when there are conflicts between how the API groups things with how the website groups things. Sergio would like an example of this to help show the concern.

This may be something that needs to be an RFE for Sources or Topology, rather than something we implement ourselves.

**Comment by chargio** [comment]
Acceptance criteria:
- We have a taxonomy of services and the main groups they belong to (specifically compute, network, storage and database, but if the process is automatic any other possible group)
- There is no overlap between components (i.e. if the storage part of EC2 is included in the group compute, it won't be included in the group Storage)
- New services can be included in one of the groups.
- The taxonomy is documented.
- It is possible to ask for a group (i.e. cost of network), in the same way we would ask for EC2 costs

**Comment by infinitewarp** [comment]
An effective solution is already in place for this, per discussion with @adberglund. So, the team has decided to close this issue. We may reopen or create a new issue if we want to revisit this topic.
