### ISSUE TITLE
OCP order_by derived and infrastructure costs

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#796]
## User Story
As a user, I want to sort the OCP details page by derived and  infrastructure cost.

It appears that `order_by[derived_cost]=asc`  and `order_by[infrastructure_cost]=asc` are not supported parameters of the reports/openshift/costs API.

## Impacts
Ex. API, UI, Docs

## Role
User

## Assumptions
- 
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/openshift/costs/ |
 | **Body** |  &order_by[derived_cost]=asc |
 | **Response** | |

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/openshift/costs/ |
 | **Body** |  &order_by[infrastructure_cost]=asc |
 | **Response** | |

<img width="1177" alt="Screen Shot 2019-04-07 at 10 57 55 AM" src="https://user-images.githubusercontent.com/17481322/55685481-d93f2680-5924-11e9-8a8c-79e6ff6d7ead.png">

<img width="1193" alt="Screen Shot 2019-04-07 at 10 57 22 AM" src="https://user-images.githubusercontent.com/17481322/55685483-dd6b4400-5924-11e9-970e-6c1a15b37ef3.png">

## UI Details
We want to update the Cost details page with derived and infrastructure columns, like so:
<img width="1262" alt="Screen Shot 2019-04-07 at 11 00 03 AM" src="https://user-images.githubusercontent.com/17481322/55685463-92513100-5924-11e9-9548-a975046177be.png">

## Acceptance Criteria

- [ ] Sort by derived cost
- [ ] Sort by infrastructure cost

**Comment by dchorvat1** [comment]
Verified
commit b7b53fac8b29c96de7dbea2ada1cb023219741bc
