### ISSUE TITLE
Migrate production RDS and utilize TLS certifiacte

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#797]
The platform team has provisioned us an RDS database that has proper encryption enabled. The production environment already contains the secret to connect to the database along with a certificate to use for TLS connection.

We need to migrate the data (if possible) from our existing RDS database to the platform provisioned DB and enable the TLS certificate based connection.

**Comment by chambridge** [comment]
https://stackoverflow.com/a/50132395
Looks like we need to add an options stanza for this:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'DATABASE_NAME',
        'USER': 'DB_USER_NAME',
        'PASSWORD': 'DB_USER_PASS',
        # https://console.cloud.google.com/sql/instances
        'HOST': '<ip of your google instance>',
        'PORT': '5432', #at the moment of this writing google cloud postgresql is using the default postgresql port 5432
        'OPTIONS': {
            'sslmode': 'verify-ca', #leave this line intact
            'sslrootcert': '/your/path/to/server-ca.pem',
            "sslcert": "/your/path/to/client-cert.pem",
            "sslkey": "/your/path/to/client-key.pem",
        }
    }
}
```

production project has a secret `rds-client-ca`

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.SSL

From the above^ looks like we just need to supply the `sslrootcert` and `verify-full`.

**Comment by lcouzens** [comment]
@chambridge can you give me some details on the best way to verify this one? Thanks

**Comment by chambridge** [comment]
@lcouzens Can't think of anything beyond we are getting data in production and you can see that the environment variable`DATABASE_SERVICE_CERT` for the Deployment Config has been set which triggers the extra options to be added in the code flow.

If you go to a running pod and execute the following:
```
(app-root) sh-4.2$ python koku/manage.py dbshell
psql (9.2.24, server 10.6)
WARNING: psql version 9.2, server version 10.0.
         Some psql features might not work.
SSL connection (cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256)
```
You see the SSL connection ^

**Comment by lcouzens** [comment]
Verified
Commit: a97addc51f93ddc1810cf1453fcdc6dc2c4096a2
