### ISSUE TITLE
Calculate costs

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#8]
# Use case
As a user, I want to see the costs associated with my objects.
As a service, I want the calculations to be accessible via API

### Rate
A rate defines monetary value calculations for a single measure in the data. 

A rate consists on an input value (value) and a fixed and variable rate:

    Cost = fixed_rate + f(variable_rate, value)

Fixed rate is applied in full, independently of the input, while variable rates are applied depending on the input value. When applying fixed rate, that can be prorated by time or not, depending on the calculation (see below)

#### Calculation:

There are three types of calculations that can applied to the rate. Calculation is a parameter of the rate itself, and not of the input. You can add as many rates (different or similar) to a price plan.

- **Occurrence**: the rate is applied if it is present. For instance, $ 10 per month if the account is present. Fixed cost are always added fully, variable costs will only be added if the object is present. In that way, you can add a fixed rate to the price plan, or a fixed rate if an specific event is present in the system.
- **Duration**: the rate is applied depending on the duration of the event. Fixed rate will be prorated, variable rate will be calculated using the duration of the event as a modifier, using both the duration and the quantity of the input for variable rating. (i.e. A VM is rated based on the number of CPU that has been used while the VM was running 4€/hour/CPU)
- **Quantity**: the rate is applied depending on the quantity of the value per cycle, independently of the duration. For instance, MB downloaded. That is independent on the time that is needed to download those Mb.

#### Rate modifiers:
- **Per time**: It is possible to define a rate per time (i.e. 5 $ per hour). It will be applied as many times as needed on the cycle
- **Per unit**: You can define the same rate as 1$/Mbps or 1000$/Kbps, to make this easier to understand. 

We differentiate between *SI* units (Mb = 1000 b), and *BINARY* units (Mib = 1024b)

Defining per unit or per time won't modify the rates, 24$/day and 1$/hour are exactly the same rate (if you don't take into account 28, 29, 30, 31 days in month).

- **Minimum step**: it defines the minimum amount considered. For instance, 1 b with a minimum step of 1MB will be considered as 1MB. Example: Red Hat rates are defined as x$ /year / par of sockets. Using 1 CPU per one month in a single socket 8 core CPU will be charged as 2 sockets one full year.

#### Tiers:
Many times, rates depend on an input parameter (i.e. you get a different price if you buy 1 candy that if you buy 1.000 of them). In IT, many times you get a free tier and a paid tier.
Example 1:
The price of the CPU is different depending on the number of CPU
0-4 CPU -> 4$/month/CPU variable, 0 fixed
5- CPU --> 5$/month/CPU. 16$ fixed

A VM with 3 CPU will be charged 0 + 4 * 3 = 12$/month
A VM with 6 CPU will have to options:
 1. Apply the tier in full (like the candy example):                 16$ + 6 * 5$         = 46 $
 2. Apply the tier only with the metrics within the tier:         16$ + (6-4) * 5$  = 26$
 3. Apply all tiers with the metrics within the tier:  4 * 4$ + 16$ + 2 * 5$         = 42$

AWS normally uses schema 1 for VM sizing, while using 3 for volume discounts. 
Depending on the circumstances, the three strategies can be used.

In addition, tiers can depend on other parameters in the context:
0 - 100 users in the system -->  5$ /user /month
101+ - users in the system  -->  4$ / user /month

In this case, the number of users in the system needs to be part of the context of the calculation, and be used to determine the tier to be used.

# Success Criteria
- [ ] You can call a rating API with a object description and get a rating
- [ ] Tier rating works
- [ ] Discounts can be applied

# Assumptions
- The costs are calculated with enough precision, and showed in different currencies. 8 or 12 digits are used.

**Comment by blentz** [comment]
Please add a description that includes:

1. User story
2. Acceptance criteria
3. Assumptions / Dependencies.

**Comment by blentz** [comment]
My comments from #7 apply here, too - How we approach this depends heavily on what external data sources we're using, and whether there will be local changes input directly into our data store that will modify those calculations.

For example - If we pull the AWS CUR, the final value is calculated for us, which we can just pass-through to the user unmodified. But we'll need to understand how it's calculated in order to do more interesting things with it, like forecasting or "what-if" analyses.

However, external pricing info also requires us to answer the question of how we handle updates if the pricing model changes. For example, if the tiered pricing changes from 3-tiers to 5-tiers.

**Comment by chambridge** [comment]
For milestone 1 we are just focused on using the AWS CUR and the associated final values it provides.

I'm closing this issue for now. It as cost analysis like forcasting and "what-if" scenarios were not part of our milestone 1 breakdown of stories. Hopefully the appropriate information can be captured in Aha! and made ready for the appropriate milestone to be broken down.
