### ISSUE TITLE
Incorrect units returned by rates API

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#807]
After backlog refinement on April 11, 2019, we decided that a few additions are needed to the rates API to satisfy the front end mocks. 

- [ ] A UI/user friendly display name should be included for a metric
- [ ] A metric should have a unit associated with it
- [ ] A usage tier should have a unit associated with it 

See @blentz comment below for suggested implementation

**Describe the bug**
The /api/cost-management/v1/rates/ API returns 'USD' as units for all rates. Even when the metric is `cpu_core_request_per_hour` or `storage_gb_request_per_month`, for example. 

![Screen Shot 2019-04-11 at 11 07 07 AM](https://user-images.githubusercontent.com/17481322/55968929-f0df1d80-5c4a-11e9-91e6-b08eba46f642.png)

**Expected behavior**
Want to see units such as 'GB-hours', 'GB-mo', etc. in addition to 'USD'.

**Screenshots**
The UI needs to localize units, but currently hard codes them for the price list.

![Screen Shot 2019-04-11 at 11 11 41 AM](https://user-images.githubusercontent.com/17481322/55968786-abbaeb80-5c4a-11e9-98f1-7e519f3459ce.png)

**Comment by blentz** [comment]
Proposed new data structure:

```
{
    "uuid": <uuid>
    "provider": <provider_uuid>
    "metric": {
        "name": "cpu_core_usage_per_hour",
        "unit": "core-HRs"
    },
    "rate": [
        {
            "value": "0.25",
            "unit": "USD",
            "usage": {
                "usage_start": "10000",
                "usage_end": "50000"
            }
        },
        {
            "value": "0.10",
            "unit": "USD",
            "usage": {
                "usage_start": "50001",
                "usage_end": "250000"
            }
        }
    ]
}
```

**Comment by adberglund** [comment]
Probably going to need a pretty display name of the metric and also the usage unit of the metric.

**Comment by boaz0** [comment]
By the way, there are two more things that I don't understand:

In the mocks [here](https://user-images.githubusercontent.com/17481322/54701276-1032d100-4b0b-11e9-8de2-381e32c4ee98.png) I see `Storage usage tier X` but I don't see such (only cpu/memory/storage_core/gb_usage/request_per_hour).

In addition, how can I calculate `Applied usage range` and `Applied usage date range` from `usage_start` and `usage_end`?

Moreover, can we filter the rates by cluster name or provider uuid?

Thanks.

**Comment by adberglund** [comment]
@boaz0 Part of this issue that we discussed on Thursday was to add in a display name as seen in the mock. Right now, as you see from the API, we return metrics with the following set of strings:

https://github.com/project-koku/koku/blob/master/koku/rates/models.py#L31-L36

The API will be updated to also return a display name that matches the mocks. So for instance the metric `storage_gb_usage_per_month` would get a new `display_name` of `Storage usage tier`.

Right now our rates are not time based, so for the current implementation there's no way to calculate a date range. That may change in a future iteration, but for now everything follows a monthly billing cycle.

Filtering is a great request. Yes, I think we should add the ability to filter to the list API for rates.

**Comment by dchorvat1** [comment]
Verified
commit b7b53fac8b29c96de7dbea2ada1cb023219741bc
