### ISSUE TITLE
OpenShift on Cloud infrastructure cost should not be higher than Cloud cost

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#811]
**Describe the bug**
Currently the infrastructure cost reported for OpenShift on Cloud is a higher dollar amount then the total cost on the cloud tab. 

**Expected behavior**
OpenShift on Cloud infrastructure cost should reflect accurately

**Screenshots**
From OpenShift on Cloud

![image (4)](https://user-images.githubusercontent.com/3845021/56061830-97edb300-5d38-11e9-8672-4cac30dfa99a.png)

From Cloud

![image (5)](https://user-images.githubusercontent.com/3845021/56061840-9d4afd80-5d38-11e9-9997-99c4fc2d48c7.png)

**Comment by adberglund** [comment]
There's a series of fixes here to make sure OCP on AWS infrastructure costs aren't higher than AWS costs, and that the infrastructure costs on the OCP tab are the same as those on the OCP on AWS tab.

**Comment by lcouzens** [comment]
Verified
Commit 1ffb96a8942d7c338de85eb1ecdd3c8689abf4c7
