### ISSUE TITLE
Potentially double counting EC2 cost in OpenShift on cloud cost

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#816]
**Describe the bug**
OpenShift tag + AWS resource ID == double count

We apply cost distribution in two paths. 
- We associate operator metering data using the  resourceID for and EC2 node.
- We associate items tagged with `openshift_cluster`, etc. 

If an EC2 instance is a node being used to run OpenShift and it is also tagged we may calculate cost in both paths.

**To Reproduce**
1. Generate nise data for OCP on AWS but apply a openshift tag to the EC2 instance line item
2. "Upload" and process both datasets through masu
3. See double counting

**Expected behavior**
If we can establish the EC2 instance relationship we should ignore the tag cost distribution

**Comment by adberglund** [comment]
This has been taken care of while working #811. The examples here: https://github.com/project-koku/koku/pull/821 are both tag matches and resource_id matched, and EC2 cost is not double counted.

**Comment by lcouzens** [comment]
@adberglund did you happen to take a look at the openshift costs endpoint when checking this? Though we don't get double counts it seems like we are not storing any infrastructure costs on the openshift costs endpoint.

```
{
    "meta": {
        "count": 10,
        "group_by": {
            "cluster": [
                "*"
            ]
        },
        "filter": {
            "time_scope_value": "-10",
            "time_scope_units": "day",
            "resolution": "daily"
        },
        "total": {
            "infrastructure_cost": {
                "value": 0.0,
                "units": "USD"
            },
            "derived_cost": {
                "value": 13.8875,
                "units": "USD"
            },
            "cost": {
                "value": 13.8875,
                "units": "USD"
            }
        }
    },
```

**Comment by lcouzens** [comment]
Verified
Commit: 3d29fc6466fc14fc8372aef1995b6be498235d74
