### ISSUE TITLE
Add a "fields" parameter to API

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#820]
## User Story
As an API user, I want to be able to specify report fields in my API queries, so that my reports have all the fields I require.

## Impacts
API

## Role
API user

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET|
 | **Path** | /api/v1/reports/* |
 | **Query Parameters** |  fields=cost,derived_cost, ... etc |

## Acceptance Criteria

- [ ] API allows a `fields` parameter that accepts a list of field names
- [ ] API queries that use `fields` returns a report with the specified fields.
- [ ] API queries that don't include `fields` should have a sensible default that is similar to the current API responses
- [ ] When `order_by` is present, that named field should be included in the `fields` list, regardless of whether it was explicitly specified in `fields` or not.
- [ ] When `group_by` is present, that named field should be included in the `fields` list, regardless of whether it was explicitly specified in `fields` or not.

**Comment by chambridge** [comment]
Need to capture the sensible defaults for the various reports.

**Comment by blentz** [comment]
[Bug Triage]

This might be a good candidate for APIv2.

**Comment by chambridge** [comment]
Maybe of use or interest: https://github.com/dbrgn/drf-dynamic-fields

**Comment by blentz** [comment]
Moved: https://issues.redhat.com/browse/COST-119
