### ISSUE TITLE
Use Rolling Update Strategy for Koku Deployment

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#836]
## User Story
As a user of koku I want zero downtime so that I can always access the site.

## Acceptance Criteria

- [ ] The koku deployment config uses the rolling update strategy https://docs.okd.io/3.11/dev_guide/deployments/deployment_strategies.html#rolling-strategy

**Comment by dccurtis** [comment]
Addressed by https://github.com/project-koku/koku/pull/878.  Moving to QA

**Comment by lcouzens** [comment]
Verified
