### ISSUE TITLE
Openshift volume missing comparison unit

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#838]
**Describe the bug**
Openshift volume is missing its comparison unit.

**To Reproduce**
1. Go to 'Overview'
2. Click on 'Openshift'
3. Scroll down to 'Volume' card
4. See comparison '()' missing GB-Month

**Expected behavior**
Should provide unit

**Screenshots**
![Screenshot from 2019-04-29 12-05-53](https://user-images.githubusercontent.com/18352403/56892420-7bab7f00-6a77-11e9-80cc-fff7e56b85cc.png)

**Additional context**
Testing against PROD with demo user

Note that the UI is functioning as expected. The UI doesn't hard code defaults because we don't know if the units should be in each card; GB-mo, GB-hours, core-hours, etc.

**Comment by chambridge** [comment]
@dlabrecq Can you clarify where you are expecting data from the API and not getting a value?
I'm not clear on how the legend header is mapping data from the API into the UI

**Comment by dlabrecq** [comment]
Sorry, this turns out to be a localization issue in the UI.
