### ISSUE TITLE
filter_by with specific set of values should override group_by with wildcard

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#848]
**Describe the bug**
When using the koku reporting APIs, group by with wildcard overrides a filter with specific values. 
E.g. filter[service]=AmazonEC2&group_by[service]=* returns data for all services, despite a specific filter being set. 

**Expected behavior**
The filter should be respected

**Comment by adberglund** [comment]
See https://github.com/project-koku/koku-ui/pull/847 for some examples

**Comment by blentz** [comment]
Essentially, this means that `filter[service]=S3&group_by[service]=*` should be equivalent to `group_by[service]=S3`. 

So, those two queries should return the same report or one of those should raise an error that instructs the user to use the equivalent form.

**Comment by dccurtis** [comment]
@nbon12 Here's the issue we were discussing

**Comment by nbon12** [comment]
The endpoint is 
api/cost-management/v1/reports/aws/storage/

**Comment by nbon12** [comment]
Regarding: "So, those two queries should return the same report or one of those should raise an error that instructs the user to use the equivalent form."
should it return the same report, or raise an error? @blentz  @adberglund @dccurtis 

Option1: filter[service]=AmazonS3&group_by[service]=*  is equivalent to group_by[service]=AmazonS3
Option2: filter[service]=AmazonS3&group_by[service]=* is an error with a message "Please use group_by[service]=AmazonS3"

**Comment by nbon12** [comment]
@adberglund which APIs are affected by this bug? 
I notice it affects /api/cost-management/v1/reports/aws/storage/

**Comment by nbon12** [comment]
blocked due to IQE pipeline failure: https://gitlab.cee.redhat.com/insights-qe/hccm-plugin/-/jobs/1163812

**Comment by lcouzens** [comment]
Verified
Commit: 712a742a78b0c0593169c8a8266f4392603477be
Automation: test_api_ocp/azure/aws_cost_filter_respecting
