### ISSUE TITLE
Enable CloudWatch Logging

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#856]
## User Story
As dev/ops I want to adhere to the platform's logging requirements so I can view logs in a timely manner when debugging issues.

## Assumptions
- A ticket has been submitted to RHIOPS for AWS access for logging
- We need to update logging in our Django settings to send to CloudWatch

See https://github.com/RedHatInsights/cloudwatch-test for example 

## Acceptance Criteria

- [x] Dev projects log to the new dev kibana cluster
- [ ] Prod projects log to the new prod kibana cluster

**Comment by chambridge** [comment]
Available in DEV cluster.
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/29379759/57809631-d8738e80-7733-11e9-8d95-f83bcd567195.png">
