### ISSUE TITLE
Improve docs for managing DB changes across Koku & Masu

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#858]
## User Story
As developer, I want better documentation about working with DB changes across Koku and Masu so that I know what pieces need to be managed when making changes to Koku and Masu.

## Impacts
Docs

## Assumptions
-
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/PATCH/DELETE |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ] Provides detailed information about how Koku manages database models
- [ ] Provides detailed information about how Masu introspects database models
- [ ] Provides detailed information about how to test in-development model changes
- [ ] Provides detailed information about managing a local openshift/minishift deployment for development of DB changes

**Comment by blentz** [comment]
[Bug triage]

:+1:

**Comment by adberglund** [comment]
Closing this as the koku/masu merge makes a shared database setup much easier.
