### ISSUE TITLE
OCP tag query for storage tag returns 400

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#868]
**Describe the bug**
Query for OCP reports grouping by tag that has `'type': 'storage'` returns 400 error

**To Reproduce**
1. Go to `https://ci.cloud.paas.upshift.redhat.com/api/cost-management/v1/reports/openshift/costs/?delta=cost&filter[limit]=10&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1&group_by[tag:storageclass]=*`
2. See error

**Expected behavior**
We should get cost reports grouping by the tag in the query

**Context (please complete the following information):**
 - OS: RHEL
 - Browser: Chrome 73
 - Commit Hash from status endpoint: b472e6db1e90216b1834e3aa01384265f70fff3a

**Additional context**
Tested on jalberts account, we can see that for any of the "pod" tags in
`https://ci.cloud.paas.upshift.redhat.com/api/cost-management/v1/tags/openshift/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly`
we get correct reports, for both "storage" tags we get a 400

**Comment by dccurtis** [comment]
Started triaging this issue.

Problem is in here:
```
def handle_invalid_fields(this, data):
    """Validate incoming data.

    The primary validation being done is ensuring the incoming data only
    contains known fields.

    Args:
        this    (Object): Serializer object
        data    (Dict): data to be validated
    Returns:
        (Dict): Validated data
    Raises:
        (ValidationError): if field inputs are invalid
    """
    unknown_keys = None
    if hasattr(this, 'initial_data'):
        import pdb; pdb.set_trace()
        unknown_keys = set(this.initial_data.keys()) - set(this.fields.keys())

    if unknown_keys:
        error = {}
        for unknown_key in unknown_keys:
            error[unknown_key] = _('Unsupported parameter or invalid value')
        raise serializers.ValidationError(error)
    return data
```

`unknown_keys = set(this.initial_data.keys()) - set(this.fields.keys())`
When a group_by `tag:storage*` is used the tag key is not showing up in `this.fields`

```
(Pdb) this.initial_data.keys()
dict_keys(['tag:storageclass'])
(Pdb) this.fields.keys()
KeysView({'cluster': StringOrListField(child=CharField(), required=False), 'project': StringOrListField(child=CharField(), required=False), 'node': StringOrListField(child=CharField(), required=False), 'and:project': StringOrListField(child=CharField(), required=False), 'and:cluster': StringOrListField(child=CharField(), required=False), 'and:node': StringOrListField(child=CharField(), required=False), 'or:project': StringOrListField(child=CharField(), required=False), 'or:cluster': StringOrListField(child=CharField(), required=False), 'or:node': StringOrListField(child=CharField(), required=False)})
(Pdb)
```

**Comment by dccurtis** [comment]
Looks like the storage tags are not showing up in the summary table

```
postgres=# select * from reporting_ocpusagepodlabel_summary;
 key  |     values
------+----------------
 key1 | {label_value1}
 key2 | {label_value2}
(2 rows)

postgres=#
```

**Comment by dchorvat1** [comment]
verified, commit 4ce8120e0b8bf945fcb97c72656cc51465264104
