### ISSUE TITLE
Price LIst CRUD API

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#872]
## User Story
As a user I want to perform CRUD operations on a price list to calculate derived cost on my data sources. 

This work effectively converts the current `/rates/` APIs to `/pricelists/`. We can leverage all our existing rate validation but move the validation under the context of a price list. The price list can effectively be a JSON list that holds multiple rates. Since we no longer have the 1 to many problem of providers <-> rates, we can also optionally remove the rate map in favor of foreign key relationship on the provider/source table to the price list entry. 

## Impacts
API

## Assumptions
- All of the rate validation exists and should be directly usable here
- We will remove the rate object and instead collect rates inside a price list object

## Acceptance Criteria

- [ ] All operations required in https://marvelapp.com/73ii7a7 are covered. (More detailed acceptance criteria to come)

**Comment by blentz** [comment]
[Bug triage]

Description and Acceptance Criteria need to be fleshed out more.

Implementation needs to consider how things like mark-ups and discounts will work. (e.g. 10% off all pricing during Black Friday)

If more discussion is needed or if we need a research spike to explore an implementation before committing to it, let's do that (and create distinct issues for the research and implementation).

Sergio should be involved for nailing down naming.

**Comment by lcouzens** [comment]
First thing to mention is the endpoint is at /costmodels/ not /pricelists/ that was confusing :D

**Comment by dchorvat1** [comment]
Currently can't use tiered rates due to this:
https://github.com/project-koku/masu/issues/489

**Comment by nlcwong** [comment]
I just updated the link to show where the latest cost model mocks are located in the marvel app, not the invision app: https://marvelapp.com/73ii7a7
