### ISSUE TITLE
User defined alias for cloud children accounts

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#873]
## User Story
As a user, I want to be able to define alias in AWS for member accounts of a parent account in koku, and see them in the interface. It should be possible to define alias if they are not defined in AWS.

Priorities:
1. Koku set aliases (local database)
2. AWS aliases (received)
3. Account ID

## Impacts
Data ingestion

## Role
Admin

## Assumptions
- The customer can update those aliases in koku.
In consolidated billling, we get the AWS alias and we can define aliases for the parent account, but we don't support the same for children accounts. However, the customer that is using children account will want to see that reflected in the interface, and use a user friendly name for it (including when the alias is not defined in the cloud)

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/PATCH/DELETE |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ] Account alias can be set as part of provider creation.
- [ ] Account alias can be updated on an existing provider.
- [ ] When an account alias is set or changed on the aws account, that change should propagate to the provider config

**Comment by adberglund** [comment]
@chargio To research and open new issues around researching API to get child account alias and UI/API to create our own alias.

**Comment by chambridge** [comment]
Looks like we should be able to get all AWS account names with the following:
<script src="https://gist.github.com/chambridge/5dfd76fd76c62067afb8112097aa41ab.js"></script>

This would require the following update to the `CostUsage` Policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::bucket_name",
                "arn:aws:s3:::bucket_name/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "iam:ListAccountAliases",
                "s3:HeadBucket",
                "cur:DescribeReportDefinitions",
                "organizations:List*",
                "organizations:Describe*"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by chambridge** [comment]
Enabled check for orgs API with this PR: https://github.com/project-koku/koku/pull/951

**Comment by infinitewarp** [comment]
The team discussed this issue during backlog refinement and agreed that the recent work done to handle names from the organization should be sufficient, and we no longer need this customer-customizable feature.
