### ISSUE TITLE
Automate openapi generation

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#884]
## User Story
As developer, I want to automate openapi schema generation so that I don't have to manually update the openapi schema.

See: https://www.django-rest-framework.org/community/3.9-announcement/#built-in-openapi-schema-support

## Impacts
APIs

## Assumptions
- DRF generates an OpenAPI 3.0 compliant spec
- If we need to fork or run a custom bleeding-edge version of DRF or other supporting libraries, that's okay.

## Acceptance Criteria

- [ ] OpenApi schema is served as JSON from `/v1/openapi.json`
- [ ] The generated schema is defined sufficiently such that `openapi-generator` will process it to generate clients with no errors.
- [ ] The generated schema provides definitions including at least:
  - all currently known API paths
  - all APIs have appropriate verbs (GET, POST, etc.)
  - all APIs have appropriate required and optional parameters
  - all parameters that should have defaults do have defaults
  - pagination
- [ ] The schema defines paths assuming the client makes requests _through 3scale_ and not against the backing service directly. This means the base URL should be `"/api/cost-management/v1"` instead of `"/r/insights/platform/cost-management/v1"`.
- [ ] The legacy static `openapi.json` file has been deleted, and any commands that handle it have been deleted.
- [ ] Documentation has been updated to direct users and/or developers to access the schema from the URL only.

**Comment by infinitewarp** [comment]
See also:
- https://github.com/project-koku/koku/issues/974
- https://github.com/project-koku/koku/issues/973
- https://github.com/project-koku/koku/issues/933

**Comment by lcouzens** [comment]
Just a heads up on this one. We should probably check IPP-12 if its changed but last I saw it said we shouldn't be auto generating this. ```All OpenAPI specifications SHOULD maintain this specification file in its VCS repository alongside the code that it describes. The specification file SHOULD NOT be auto-generated in response to code changes. ```

**Comment by werwty** [comment]
`SHOULD` in IPP-12 expresses more of a recommendation and not a `MUST` do. 

Personally, I think manually writing the specification just adds a lot of additional work, and increases the chances of the spec and code becoming divergent.

**Comment by infinitewarp** [comment]
I'll second what @werwty said above.

Furthermore, there is also discussion (although it is months-old and never resolved) in the comments of that part of IPP-12 that also puts into questions whether this `SHOULD` should be specified this way.

**Comment by werwty** [comment]
There is a PR open against IPP-12 to change it (apologies in advance for the company internal url): https://gitlab.cee.redhat.com/insights-platform/platform-docs/merge_requests/12/diffs

**Comment by infinitewarp** [comment]
After further discussion elsewhere, we are closing this issue and will not implement it. Team members prefer manually writing and maintaining the openapi.json file as well as maintaining the independent server API independently of that file; implementing this feature would remove manual control of the openapi.json file.
