### ISSUE TITLE
Add Masu Database Accessors to Koku and Integrate Django ORM

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#887]
## Objective
We want to move the database accessor layer over to Koku in preparation for moving the rest of the masu code base.

## Assumptions
- The functionality of the accessors will remain unchanged
- The database accessors will use Django ORM instead of SQLAlchemy

## Acceptance Criteria

- [ ] Database accessor unit tests pass in koku

**Comment by blentz** [comment]
Note: The openshift templates are still pointing at the masu git repo. The git URL in the templates needs to be updated in tandem with this work.

**Comment by adberglund** [comment]
@lcouzens This is just part of the general "make sure everything passes" testing for koku/masu merge.

**Comment by lcouzens** [comment]
Verified
