### ISSUE TITLE
Move masu code to Django app within koku

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#888]
## Objective
Once the database access layer is in place in koku, we should move the rest of the masu code base over to a Django "app" inside the koku application. 

## Assumptions
- With a functioning database access layer, this should "just work"

## Acceptance Criteria

- [ ] All masu unit tests work
- [ ] All celery tasks function 
- [ ] The normal flow for data processing proceeds without error

**Comment by adberglund** [comment]
We want to keep our masu git history as well if possible. Reference https://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/ if this is possbile?

**Comment by blentz** [comment]
Note: The openshift templates are still pointing at the masu git repo. The git URL in the templates needs to be updated in tandem with this work.

**Comment by werwty** [comment]
Branch here with most of the processor tests fixed: https://github.com/werwty/koku/tree/888-masu-mv

I'm putting this back onto the backlog since I will be PTO until 8/2.

**Comment by lcouzens** [comment]
Verified
