### ISSUE TITLE
Create a database model for what we store for sources

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#892]
## Objective
We want a database table where we can store cost-management specific information about a source

## Assumptions
- We will get username information from sources, but will want to continue storing ARNs for our use. This means we will need a new flow to create the ARN using a source username/pass
- We need a place to store "bucket" (or whatever we want to call it) as this is not part of the source definition.
-  Sources client service exists
-  Sources information can trickle in over a series of kafka messages and HTTP calls.  The work for this issue must provide a persistent storage location to store this information as it comes in.
- The persistence storage would be resilient to service restarts such that a particular sources account could handle getting separate pieces of information about the account over different life cycles of the sources client service.

## Acceptance Criteria

- [ ] A database table exists that can be tied back to an entry in the sources database, but contains our additional required information

**Comment by dccurtis** [comment]
Completed with PR: https://github.com/project-koku/koku/pull/1111

**Comment by lcouzens** [comment]
Verified
Commit: "6bac6962d08f693740f8147c966bfdb5ce39a7c3"
