### ISSUE TITLE
Handle case where we have not received/processed sources kafka message, but an API call is made for bucket

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#896]
## Objective
We want to not crash when sources calls our API to add a bucket before we have finished processing their messages from kakfa. 

## Assumptions
- Because of the asyncronous nature of handling kafka messages it is entirely possible that sources would call our API before we have finished processing a message
- We can make use of Django's https://docs.djangoproject.com/en/2.1/ref/models/querysets/#get-or-create (assuming we use Django for sources client service)
-  The sources client service should not have any requirements/assumptions on what piece of data comes in to create the initial sources database entry.  The creation of the sources database entry could be from a kafka even tor from a bucket API call.  All subsequent information would be an update to that row.

## Acceptance Criteria

- [ ] We gracefully handle/require enough information in our API to create a record before we have processed a kafka sources message.
- [ ] We gracefully handle/require enough information in our API to create a record after we have processed a kafka sources message.

**Comment by dccurtis** [comment]
Completed with PR: https://github.com/project-koku/koku/pull/1111

**Comment by lcouzens** [comment]
Verified
Commit: 5f65d324af3f801b7f2ee6f20f7a6da5ba6162d7
