### ISSUE TITLE
Decouple Koku from providers and replace with sources logic

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#897]
## Objective
Because we will no longer be storing providers, we need to change all references and work flows in koku from using providers to our source model. 

## Assumptions
- This is the last step of integrating with sources 
- When done with this we "flip the switch" over to using sources

## Acceptance Criteria

- [ ] All koku/masu workflows function without a provider (instead use a source)

**Comment by dccurtis** [comment]
Since we will be creating an Insight-Sources integration service on issue #891 which will issue `/provider` HTTP calls; there should be no changes required for changing koku/masu database objects and related code.
