### ISSUE TITLE
Data is not being summarized after ingestion

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#918]
**Describe the bug**
We appear to be downloading and processing data fine, but summarization is not always happening.

**Expected behavior**
Summarization should always occur after processing.

**Additional context**

The `reporting_common_costusagereportmanifest` table tracks the number of number of files in a manifest and how many have been processed. We defer summarization until all files have been processed. There are many entries in that table with more files processed than the total in the manifest. There is likely a bug in incrementing the number of files processed.

**Comment by lcouzens** [comment]
Verified
Commit: b1d944786767c151ef80f23a259f6f09a9861be5
