### ISSUE TITLE
Hitting 502's when performance testing the API with a single user

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#923]
**Describe the bug**
Hitting 502's when performance testing the API with a single user

**To Reproduce**
1. Go to Overview
2. Click around the UI
3. Notice 502's showing in the console network tab

**Expected behavior**
Data should load correctly without getting 502's

**Screenshots**
![Screenshot from 2019-07-02 11-01-14](https://user-images.githubusercontent.com/18352403/60504796-3a735d80-9cba-11e9-8c3e-5d43cadca717.png)

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: "61349f806eb1394a34d46c017a4b119dc26057cf"

**Additional context**
Only seem to be able to reproduce this against PROD

**Comment by adberglund** [comment]
We don't have anything logged for 502s on our end so although this warrants additional investigation we suspect that this is a platform issue.

**Comment by adberglund** [comment]
Going to attempt to run with 2 pods for koku by default to see if that helps things.

**Comment by dchorvat1** [comment]
I started seeing random 502's on CI in recent time, some test runs have failed due to that

**Comment by lcouzens** [comment]
So I was running some performance testing on PROD with 5 users and didn't see any 502's (after we scaled to 2 pods)
That said I was previously seeing the 502's with a single user with basically no load on the pod so I think its safe to assume that issue has been resolved.

That said I would like to understand exactly what you are seeing on CI @dchorvat1 have you got any additional info? Is it happening on a single test or totally random?

My guess is that the pod request/cpu is low on CI which is hindering the tests but thats a guess.

**Comment by lcouzens** [comment]
I spoke to Dan about this WRT CI and ran some testing myself confirming that its based on usage/request. 

If we hammer the pods enough pushing it over the cpu request we expect scaling to happen but before we scale we end up killing the current pod(s) or forcing them to restart. At this point we get 502's as a single or no pods can't handle the requests. If a pod restarts I feel like we should automatically scale up to compensate assuming thats possible?

Another note is the default usage request is sat at 80%, I lowered this to 60% on QA but still see at least one pod restart and no scaling happen when running with around 5 users. Running with anything over 5 users will just bring both pods down and we never scale up.

**Comment by adberglund** [comment]
Trying out a thread worker on the QA cluster's koku right now to see if it helps.

**Comment by lcouzens** [comment]
PROD seems stable so closing this issue. Can re-raise if this issue comes up again.
