### ISSUE TITLE
Providers endpoint accepts any query parameter

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#926]
**Describe the bug**
Accessing `/api/cost-management/v1/providers/` with any invalid query parameter results in a 200 response

**To Reproduce**
1. Go to `/api/cost-management/v1/providers/?invalid_parameter=random_value`
2. See error

**Expected behavior**
We should get a 400 response, similar to the other endpoints

**Screenshots**
![Screenshot from 2019-07-12 14-44-43](https://user-images.githubusercontent.com/46324552/61129162-12eb7480-a4b4-11e9-8b48-49d365c1bcc6.png)

**Context (please complete the following information):**
 - OS: RHEL
 - Browser: Chrome 75
 - Commit Hash from status endpoint: 61ed898f486cfb91c654ac83cce2d71bb2393b60

**Additional context**
Tested both on CI/prod

**Comment by adberglund** [comment]
We're going to leave this as-is as the view does nothing with the invalid param so it doesn't influence behavior. The reporting API is a special case where we do a lot of parameter validation, but the rest of our APIs don't require that.
