### ISSUE TITLE
API: reports/openshift/infrastructures/aws/costs returns empty values

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#928]
**Describe the bug**
Encountering an empty state with the Ocp on AWS Details page because the `reports/openshift/infrastructures/aws/costs` API currently returns no values. The APIs for the Ocp and AWS Details pages appear to be returning values.

**To Reproduce**
/api/cost-management/v1/reports/openshift/infrastructures/aws/costs/?delta=cost&filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly

**Expected behavior**
Expecting values not to be empty.

**Screenshots**
<img width="939" alt="Screen Shot 2019-07-14 at 11 25 12 PM" src="https://user-images.githubusercontent.com/17481322/61194402-2999f300-a68f-11e9-96ca-c5aed67ffb28.png">

**Additional context**

**Comment by lcouzens** [comment]
@dlabrecq Which environment and user where you seeing this on?

**Comment by dlabrecq** [comment]
My local CI

**Comment by lcouzens** [comment]
Oh right, I was wondering if it was a tag/label correlated data issue. Were you adding providers we normally use or generating Nise data? Difficult to diagnose without the data anyway :D

**Comment by dlabrecq** [comment]
I didn't create any new providers, just using Jen's existing account on CI.

**Comment by adberglund** [comment]
Action here is to get OCP on AWS data in CI

**Comment by adberglund** [comment]
@dlabrecq There should be data now in CI. Still working on the duplication issue there, but values should at least return now.

**Comment by dlabrecq** [comment]
There are still some empty cards for the Ocp on AWS page. @adberglund, you stated that's just due to a lack of tags, correct?

For example:
/reports/openshift/infrastructures/aws/costs/?filter[time_scope_units]=month&filter[time_scope_value]=-2&filter[resolution]=daily&filter[service]=AmazonRDS,AmazonDynamoDB,AmazonElastiCache,AmazonNeptune,AmazonRedshift,AmazonDocumentDB

**Comment by adberglund** [comment]
Yes, this is due to not tag matching AWS resources with our OpenShift cluster. It will be difficult to tag resources in the AWS account as we do not own it and have no access. Can consider using nise generated data for CI in particular so we can make sure data is in all cards while working on the UI.
