### ISSUE TITLE
API: reports/openshift/compute returns duplicate projects

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#929]
**Describe the bug**
Encountering duplicate projects with the Ocp Details page.

**To Reproduce**
/api/cost-management/v1/reports/openshift/compute/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&filter[limit]=3&group_by[project]=rydetest

**Expected behavior**
Expecting unique projects

**Screenshots**
<img width="441" alt="Screen Shot 2019-07-14 at 11 31 01 PM" src="https://user-images.githubusercontent.com/17481322/61194495-c361a000-a68f-11e9-94b0-618b66e399fd.png">

**Additional context**

**Comment by lcouzens** [comment]
@dlabrecq was this one also local or can I see it on CI?

**Comment by dlabrecq** [comment]
Local CI using Jen's account

**Comment by dlabrecq** [comment]
Wondering if something changed recently with Jen's account? I see a completely different projects now and no duplications.

![Screen Shot 2019-07-18 at 11 52 07 AM](https://user-images.githubusercontent.com/17481322/61472865-4cf4c480-a953-11e9-8712-7984886b97cc.png)

**Comment by adberglund** [comment]
@dlabrecq Yes, there was a fix that went in for derived cost calculation, so we have some derived cost calculated now. I paged through and found some duplication still, so it's still an issue.

**Comment by adberglund** [comment]
I believe this is a CI data related issue. I will wait and monitor our production data as it now has the same two OpenShift clusters with the same code running. If no duplication happens there, I'm inclined to delete CI data and re-make the sources.

**Comment by adberglund** [comment]
I removed and re-added the OpenShift providers for CI. Hopefully the duplication is fixed by this.

**Comment by adberglund** [comment]
@lcouzens @dchorvat1 This was a korekuta issue where a config file was being used by multiple OpenShift clusters. I fixed that, and reloaded OpenShift providers in CI. The project duplication issue seen there is no more.

**Comment by dchorvat1** [comment]
verified
