### ISSUE TITLE
Customer On-boarding

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#93]
## User Story
As a service administrator, I want to be able to create a new customer so that users associated with that customer can join the service and see their associated data.

## Impacts
API, UI, Docs

## Role
Service Admin

## Assumptions
- Customers will have associated unique IDs and a descriptive name and also associated with an “owning” user.
- A user id (email) can only be a member of a single customer.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | POST | 
 | **Path** | /api/v1/customers/ | 
 | **Body** | name, owner (name, email) | 
 | **Response** | uuid, name, owner (uuid, name, email) | 

## UI Details
A view for signup exists alongside of login.

## Acceptance Criteria

- [ ] Verify that a customer can be created and the response provides the UUID of the customer and the owning user (uuid, name, email).
- [ ] Verify that a customer cannot be created with a user (email) that exist in another customer.

**Comment by chambridge** [comment]
@blentz @adberglund 
Didn't discuss the authentication flow for this. Two choices we create a super user and utilize the same token flow or we use an API key.

At app startup we would check for the presence of the user or apikey and if it doesn't exist then create it.

**Comment by adberglund** [comment]
I'm not sure I follow 100%. Are you saying we potentially want to automatically create a Django super user (or generate the api key) when we start our Django app process? (In the startup method called in wsgi.py)?

**Comment by chambridge** [comment]
Yes, we need a way of having control (authentication) around the Customer on-boarding APIs. Unless you have an alternative suggestion.

**Comment by adberglund** [comment]
Nope, not at all. I like using the same token flow as a regular user would. That way we are users, we just have another level of permissions up from a customer owner.

**Comment by chambridge** [comment]
@blentz Is there a feasible way for us to do this based on the environment we deploy into vs. baking it into the template? I don't want to expose the info in Github. Does the OSD Github webhook give us any control?

**Comment by blentz** [comment]
@chambridge  - I'm not sure I understand the question, re: OSD. I don't have a good handle on how Django does auth, so I may need you to talk me through that side of it so that I understand what y'all are seeing.

What I know about the Template file is basically this:

Inside the template, we can define an environment var (as a template parameter) to pass in, and we can even auto-generate a value for that parameter, if one isn't supplied by the user.

If that allows us to put some magic into the Makefile for generating & passing an auth token, then great.

**Comment by chambridge** [comment]
We need to create a super user (if it doesn't exist) at application startup. Django users require usernames and passwords. We will use this super user to get an authentication token (requires that we know the username and password). We can then use this token to add customers with a POST to the customer API.

In the development we can have an environment variable just use an in code default that defines the password. I guess we can just use a secret in the template similar to what we use for database-password, database-user, and django-secret-key. We just may need to help QE with the code (when they test the environment) to get the new secret key for the password to properly do integration testing.
