### ISSUE TITLE
Data ingestion on CI too slow

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#930]
**Describe the bug**
There's a significant data processing speed difference between CI and QA environments, data ingestion for one provider on CI takes more than 10 minutes, whereas on QA the same process takes around one minute.

**To Reproduce**
1. Add a provider
2. Upload data and hit ingest
3. Wait until data processes and shows up in UI/API

**Expected behavior**
Faster data processing on CI

**Context (please complete the following information):**
 - OS: RHEL
 - Browser: Chrome 75
 - Commit Hash from status endpoint: f6bb69d588502a8bcf183564b24871ec8a8881fa

**Comment by adberglund** [comment]
Going to bump memory on the Postgres pod in CI to see if timing improves on slower queries. If not then we'll raise priority and troubleshoot the SQL immediately.

**Comment by adberglund** [comment]
@lcouzens @dchorvat1 No functional change here, but this was to get your tests to not take 10 mintues to run each one.

**Comment by lcouzens** [comment]
Yeh we can close this one I think. That said I need to look into QA now though as that seems to not be ingesting ocp data correctly.
