### ISSUE TITLE
Filter cost models by name or source type

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#932]
## User Story
As a user I'd like to filter cost models by name or source type so that I can quickly and efficiently find what I'm looking for.

## Assumptions
- This will add some filter params to the GET List APIs to return a subset of data

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/costmodels/ |

## Acceptance Criteria

- [ ] Filtering on source type returns cost models for the specific type.
- [ ] Filtering on name does case insensitive partial string matching to return matching cost models

**Comment by boaz0** [comment]
If you don't mind I will take this.
