### ISSUE TITLE
API client generated from spec does not require or return expected data

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#933]
**Describe the bug**
API client generated from spec does not require or return expected data
**To Reproduce**
1. Generate client from openapi spec file
2. Use generated client to add provider

Required fields by spec are Name and Type however we also require provider_resource_name and also bucket for aws sources

Also when filling out the fields correctly the returned data is not consistent with what the user expects. We only return Name and Type. Certainly at the very least we should also be returning the uuid.

Working from the browsable api we return the following:
```
{
    "uuid": "00103454-6f71-4508-8565-8b05ed1403e9",
    "name": "test",
    "type": "OCP",
    "authentication": {
        "uuid": "23748885-10d3-48ba-b0fa-7350b02ca6bb",
        "provider_resource_name": "cluster_1"
    },
    "billing_source": {
        "uuid": "c5b55032-f5c9-4c81-ac31-4f03f2b233a6",
        "bucket": ""
    },
    "customer": {
        "uuid": "f24b1571-9785-4035-bc10-50d092341b65",
        "account_id": "10001",
        "date_created": "2019-07-19T14:11:16.348431Z"
    },
    "created_by": {
        "uuid": "f162fe10-c8f0-4736-b94c-f62aa681547e",
        "username": "user_dev",
        "email": "user_dev@foo.com"
    }
}
```

**Comment by dchorvat1** [comment]
The client also returns only `meta` and `links` fields of the request response and the `data` part is missing, when we want to list all of the providers/preferences
```
{'links': {'first': '/api/cost-management/v1/providers/?limit=10&name=unique_9384857684014394&offset=0',
           'last': '/api/cost-management/v1/providers/?limit=10&name=unique_9384857684014394&offset=0',
           'next': None,
           'previous': None},
 'meta': {'count': 2}}
```

**Comment by dchorvat1** [comment]
Verified, commit d5d24666043e6e6bdb6964ac7e093f523f9a6b86
