### ISSUE TITLE
Add Users to a Customer

### ISSUE THREAD

**Issue by chambridge** [project-koku/koku#94]
## User Story
As a customer owner, I want to be able to add additional users associated with the customer so they can join the service and see their associated data.

## Impacts
API, UI, Docs

## Role
Customer Owner

## Assumptions

- A user (email) can only be a member of a single customer.
- A user will get an email/link to join and set up their password.

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | POST | 
 | **Path** | /api/v1/users/ | 
 | **Body** | name, email | 
 | **Response** | uuid, name, email | 

## UI Details

- A view exists in order to add additional users to a customer.
- A view exists to setup the user’s password.

## Acceptance Criteria

- [ ] Verify that a user can be added by a customer owner to a customer and the response provides the user (uuid, name, email).
- [ ] Verify that a user cannot be added by a non-customer owner.
- [ ] Verify that a user cannot be created and added to a customer with a user (email) that exist in another customer.

**Comment by chambridge** [comment]
@blentz @adberglund 
I didn't go into authentication flow for protecting customer creation. Do you think we create a super user with a "development" password that can be overridden in the production environment? Or something similar with an API key?

The app starts up, checks the db for the presence of the user or apikey and creates it if it doesn't exist?

**Comment by chambridge** [comment]
Possible tool for the user registration logic and email:
https://github.com/sunscrapers/djoser

**Comment by chambridge** [comment]
@blentz @adberglund Thoughts on the below:

Since we are separating the API and UI I can't really utilize the Django built-in capabilities for templates that handle this:
https://simpleisbetterthancomplex.com/tutorial/2016/09/19/how-to-create-password-reset-view.html

I'm going to alter this story to open a story in the UI project for a password reset page and add an API for setting the user password. The emails generated by creating a user will currently have a "Dummy link" to the password reset URL.

| API  | Detail|
 | --- | --- |
 | **Method** | POST | 
 | **Path** | /api/v1/users/(user_id)/reset-password/ | 
 | **Body** | password, token | 
 | **Response** | 200 - uuid, name, email | 

Additionally having a new model for **User Reset Token**:
- token (UUIDField; auto-generated)
- expiration_date (set based on `settings.PASSWORD_RESET_TIMEOUT_DAYS` [default is 7 days])
- user (ForeignKey)
- used (BooleanField: default False; set to True after call to `reset-password` endpoint).

**Comment by blentz** [comment]
I like it. I have no objections.

Minor nitpick - I would probably timeout the reset tokens after 24 hours. They shouldn't be active very long.
