### ISSUE TITLE
Onboard an Azure Source

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#956]
## Objective
An Azure provider/source can be created and stored in the database.

## Impacts
Ex. API, UI, Docs

## Assumptions
- Maybe update provider auth table to handle user/pass required for Azure
- Using our local concept of a provider/source right now. 

## Acceptance Criteria

- [ ] An Azure provider is successfully created
- [ ] An credential checks we require pass

**Comment by dchorvat1** [comment]
verified, commit a7671ac3766c1b2818a351f8ba2ab32e3c92d471
