### ISSUE TITLE
Download Azure Cost Export (cost and usage report)

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#957]
## Objective
We want to successfully download an Azure report.

## Impacts
Ex. API, UI, Docs

## Assumptions
-We will need to generate a concept of a manifest for Azure.
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/PATCH/DELETE |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ]
- [ ]

**Comment by lcouzens** [comment]
Verified
