### ISSUE TITLE
Summarize Azure data 

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#959]
## Objective
We want summarized Azure data for presentation to the UI and API.

## Impacts
Ex. API, UI, Docs

## Assumptions
- Mirror what we do for AWS in terms of what the summarization does (GROUP BY statement)
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/PATCH/DELETE |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ]
- [ ]

**Comment by lcouzens** [comment]
Verified
Commit: 3b449b7efba245e00d85c7dc1fb96461d86985e6
