### ISSUE TITLE
Azure Costs API

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#962]
## Objective
We want an Azure Query Handler, Config Map, and Serializer to handle the Azure costs API.

## Impacts
API

## Assumptions
- We want to honor all of the same query params as AWS
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/azure/costs/ |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ]
- [ ]

**Comment by msager27** [comment]
Verified
Commit: a8a00c585888596881fc7f4e9d18c4c8042ec764
Automation: test_api_azure_cost_validate_total
