### ISSUE TITLE
Azure compute API

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#963]
## Objective
We want an "instance_types" API for Azure.

## Impacts
Ex. API, UI, Docs

## Assumptions
-
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/azure/instance_types/ |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ]
- [ ]

**Comment by msager27** [comment]
Verified
Commit: a8a00c585888596881fc7f4e9d18c4c8042ec764
Automation: test_api_azure_instance_validate_total
