### ISSUE TITLE
Azure storage API

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#964]
## Objective
As X, I want Y so that Z.

## Impacts
Ex. API, UI, Docs

## Assumptions
-
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/azure/storage/ |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ]
- [ ]

**Comment by msager27** [comment]
Verified
Commit: a8a00c585888596881fc7f4e9d18c4c8042ec764
Automation: test_api_azure_storage_validate_total
