### ISSUE TITLE
AWS report downloader misses last update of the month

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#968]
**Describe the bug**
Once we switch over to a new month we only look for a manifest for the current month's report. On the first of the month we miss a potential final update for the last month that is written on the 1st of the month. We also need to keep checking the previous month's manifest for a change so that we download and process the finalized report.

So on August 1, the downloader only looks in
 `Will attempt to download manifest: /koku/20190801-20190901/koku-Manifest.json`

and needs to check the previous month as well.

**Expected behavior**
We should always be looking for the most up to date manifest's data for the date ranges we care about.

**Comment by maskarb** [comment]
closed in #1007

**Comment by maskarb** [comment]
reopen for QA

**Comment by lcouzens** [comment]
Verified
