### ISSUE TITLE
CI/QA koku pods not scaling up when hitting request threshold

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#970]
**Describe the bug**
CI/QA koku pods not scaling up when hitting request threshold

**To Reproduce**
1. Hit api endpoints to push koku usage over scale threshold
2. See if pods scale up

**Expected behavior**
If we hit request usage we should scale pods up to handle requests.

Commit: "afc618f654ae481af10e77e88f70164c0e9e042e"

**Additional context**
I can easily reproduce this with the performance tool which can hit api endpoints with concurrent users.

Also another thing to mention is this is only an isuee on CI/QA prod seems to be scaling fine.

**Comment by adberglund** [comment]
We will also need to readjust the readiness probe timing with migrations now out of the regular pod startup.

**Comment by lcouzens** [comment]
Pushing this one back as I think it needs more investigation.

The fix that was put in I would say can only help. However the issue I am actually seeing though is CI and QA just don't scale at all. Regardless of usage, openshift just says `no` I thought it might be quotas or something but everything looks fine.

Reach out to me if you want to play with the pods while I run our performance tests. Currently I am seeing random restarts of pods seemingly regardless of usage too.

**Comment by adberglund** [comment]
I temporarily altered our autoscaler's CPU target to 2% and was able to scale from 2 to 4 pods by hitting a few API endpoints. I suspect we may have previously had a resource quota issue blocking scaling. Manual testing reveals that this *should* work.

**Comment by lcouzens** [comment]
Verified
