### ISSUE TITLE
Openapi spec file missing "required" fields

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#973]
**Describe the bug**
Openapi specification is missing `"required": "true"` or `"required": "false"` field for the query parameters for /reports/ and /tags/ endpoints, which makes the api client generated from the spec require using all of the query parameters when making requests

**To Reproduce**
1. Go to /api/cost-management/v1/openapi.json
2. See error

**Expected behavior**
"required" field in the query parameter specification

**Example**
Query parameters of `/reports/aws/costs/` in the spec file:
```
"parameters": [
        {
          "name": "delta",
          "in": "query",
          "description": "Toggle to include delta values in report.",
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "filter",
          "in": "query",
          "description": "The filter to apply to the report as a URL encoded dictionary.",
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "group_by",
          "in": "query",
          "description": "The grouping to apply to the report as a URL encoded dictionary.",
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "order_by",
          "in": "query",
          "description": "The ordering to apply to the report as a URL encoded dictionary.",
          "schema": {
            "type": "string"
          }
        },
        {
          "$ref": "#/components/parameters/QueryOffset"
        },
        {
          "$ref": "#/components/parameters/ReportQueryLimit"
        }
      ]
```

**Additional context**
Commit afc618f654ae481af10e77e88f70164c0e9e042e

**Comment by chambridge** [comment]
@dchorvat1 @lcouzens  Can you add more info here about how you are encountering the issue, what tooling you are using and procedure steps?

If I plug the spec into http://editor.swagger.io/ and generate a python client no error or warning is generated, so I want to be sure that we fix all the problems like this and not just the listed query params above.

**Comment by dchorvat1** [comment]
The doc about generating the client is [here](https://gitlab.cee.redhat.com/insights-qe/iqe-tests/blob/master/docs/rest_client.md).

We couldn't make any requests to /tags/ or /reports/ endpoints because the client would raise exceptions about parameters missing when making requests with none or some of the parameters.
The client would also raise exceptions on the parameters being wrong type (filter, group_by, order_by) when we tried to include all of the query params in the request

**Comment by dchorvat1** [comment]
I re-generated the api client and noticed that the fields are marked as required here, so it overrides the former parameters and makes the requests fail:
```
"ReportPaginationMeta": {
                "required": [
                    "delta",
                    "group_by",
                    "order_by",
                    "filter"
                ],
                "properties": {
                    "count": {
                        "type": "integer",
                        "format": "int64",
                        "example": 30
                    },
                    "delta": {
                        "$ref": "#/components/schemas/ReportDelta"
                    },
                    "group_by": {
                        "$ref": "#/components/schemas/ReportGrouping"
                    },
                    "order_by": {
                        "$ref": "#/components/schemas/ReportOrdering"
                    },
                    "filter": {
                        "$ref": "#/components/schemas/ReportFilter"
                    },
                    "units": {
                        "description": "The units for the output data.",
                        "type": "string",
                        "example": ""
                    }
                }
            }
``` 
also we could make use of the pointers to the query parameters in other than cost reports (storage, compute...) 
@chambridge if you're ok with it, I could look into the remaining issues and try to fix them, it shouldn't be difficult and it might be easier to find any more issues like this if I generate the client and test it on the fly

**Comment by lcouzens** [comment]
@dchorvat1 Go for it, we had a brief discussion about this the other week. If you have the time to put in fixes and test it on the fly please do. We really want to get this re-factor work completed so we can focus on new Azure features/tests.
