### ISSUE TITLE
Openapi spec file missing some of the endpoints

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#974]
**Describe the bug**
openapi.json is missing `/metrics/` and `/costmodels/` (there's still `/rates/`) endpoints, so we can't reach them using the auto generated api client

**To Reproduce**
1. Go to /api/cost-management/v1/openapi.json
2. See error

**Expected behavior**
All endpoints specification

**Additional context**
commit afc618f654ae481af10e77e88f70164c0e9e042e

**Comment by adberglund** [comment]
Might be a good idea to rename the cost models metrics endpoint name to not be confused with Prometheus metrics.

**Comment by dchorvat1** [comment]
@werwty In the current spec, there is no `/metrics/` endpoint, could we also get that one?

**Comment by werwty** [comment]
@dchorvat1 +1 on it

**Comment by werwty** [comment]
https://github.com/project-koku/koku/pull/1107 has been merged.

**Comment by dchorvat1** [comment]
Thanks @werwty, the only thing that the generated client was complaining about was a missing slash in `/metrics/`. I put out a PR for that (https://github.com/project-koku/koku/pull/1123), can you review so it can be merged?
