### ISSUE TITLE
openapi-generator build image

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#979]
## User Story
As a Koku developer, I want a build image that publishes a generated Bash CLI by running openapi-generator against the currently available openapi.json.

## Assumptions and Questions
- Depends on https://github.com/project-koku/koku/issues/884
- What deployed environment of koku should be used for fetching the openapi.json? production, qa, or ci?
  - https://cloud.redhat.com/api/cost-management/v1/openapi.json
  - https://qa.cloud.paas.psi.redhat.com/api/cost-management/v1/openapi.json
  - https://ci.cloud.paas.psi.redhat.com/api/cost-management/v1/openapi.json
- Generated output will be committed and pushed to a new repo. Location TBD.
- Do we want to automatically tag releases? Or should that be a manual process?

## Acceptance Criteria

- [x] Docker image exists that generates updated Bash CLI when run.
- [x] Generated Bash CLI code is committed and pushed to a remote git repo.
- [x] Location of openapi.json is configurable.
- [x] Credentials for reaching the openapi.json URL are configurable.
- [x] Location of remote git repo is configurable.
- [x] Credentials for remote git repo are configurable.

**Comment by werwty** [comment]
LGTM.
