### ISSUE TITLE
API to create and check status of data dump requests

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#981]
## User Story
As a Koku API user, I want an API where I can request a data dump and check on the status of my previous data dump requests.

## Assumptions and Questions
- User can create and view requests but not delete or update them.
- API is a standard DRF create-list-read endpoint.
- User can specify start and end dates for limiting the data.
  - Is start date inclusive and end date exclusive? TBD in a later story.
- Gathering and sending of the data to S3 will be implemented in a future story. For now, this is just the initial infrastructure for accepting and tracking the request.
- Check with other Koku devs and APIs to ensure consistency with all attribute names and behaviors.
- Should a superuser be able to get all dump requests? What happens if a superuser creates a dump request?
  - Not today. For now, only limit the API to the logged-in requesting user.

## Acceptance Criteria

- [ ] API is served at `/v1/dataexportrequests/`
  - [ ] post to create, get to list, get with uuid to fetch individual request
  - [ ] list uses standard pagination
  - [ ] user limited
- [ ] required post params are:
  - `start_date` with ISO-8601 formatted date string
  - `end_date` with ISO-8601 formatted date string
    - must be greater than `start_date` (if `end_date` is exclusive)
- [ ] returned responses include attributes:
  - `uuid`  (automatically set upon creation)
  - `start_date`
  - `end_date`
  - `status`
  - `created_timestamp` (automatically set upon creation)
  - `updated_timestamp` (automatically set upon creation or update)
- [ ] The requesting user ID is automatically stored internally with the request so the future data collection can filter appropriately based on that user's access (RBAC).
- [ ] The datetime at which the request was created is also stored in the model.
- [ ] The `status` attribute can be one of the following strings, although only `pending` is normally visible right now:
  - `pending` (the initial state upon creation)
  - `complete`
- [ ] API returns 400 error upon post/creation:
  - [ ] if `start_date` and `end_date` are not both defined.
  - [ ] if `start_date` and `end_date` are not both ISO-8601 formatted date strings.
  - [ ] if `end_date` is not greater than `start_date`.
  - [ ] with details in response explaining _all_ problematic inputs (e.g. if both `start_date` and `end_date` are malformed, the response indicates both of them).

**Comment by infinitewarp** [comment]
Future possible enhancement not in this issue: add the customer's target S3 bucket name to the model and API.

**Comment by dchorvat1** [comment]
verified
