### ISSUE TITLE
Dump data from secondary database

### ISSUE THREAD

**Issue by infinitewarp** [project-koku/koku#986]
## User Story
As a Koku sysop, I want production database performance not to be impacted when data dump processes are running.

We suggest creating a read-only replica of the database in RDS. See also: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PostgreSQL.Replication.ReadReplicas.html

## Assumptions and Questions
- This requires working with the Insights operations team or whoever maintains the AWS account(s) for Koku.
- This will require updating configuration for each environment so Koku will know about the two different databases.
- Local environments may use the same configuration for both databases.

## Acceptance Criteria

- [ ] The heavy queries from https://github.com/project-koku/koku/issues/983 exclusively use the configured replica/standby database.
- [ ] Any write operations from https://github.com/project-koku/koku/issues/983 (such as to update the dump-request status) use the primary/master database.

**Comment by adberglund** [comment]
Let's get together and discuss this, and rope in @chambridge when we do, as we definitely want input from our architect on this.

**Comment by infinitewarp** [comment]
Closing because we're taking a different approach to solve this problem.
